force-app/main/default/objects/Campaign/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>Termin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Is_public__c.field-meta.xml
<CustomField>
    <fullName>Is_public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ist öffentlich</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Speaker</relationshipLabel>
    <relationshipName>Speaker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <inlineHelpText>Beispielsweise bei Webinaren der Link zum Webinar</inlineHelpText>
    <label>Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <inlineHelpText>Wichtig: Dies ist das Datum der ursprünglichen Vertragsunterzeichnung seitens des Kunden.</inlineHelpText>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <label>Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provisionssumme__c.field-meta.xml
<CustomField>
    <fullName>Provisionssumme__c</fullName>
    <label>Provisionssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Collection_Id__c.field-meta.xml
<CustomField>
    <fullName>Collection_Id__c</fullName>
    <label>Collection Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aktiv</fullName>
                <default>true</default>
                <label>Aktiv</label>
            </value>
            <value>
                <fullName>Komplettverkauft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <formula>Verkaufschance__r.Notartermin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Provisionssumme__c.field-meta.xml
<CustomField>
    <fullName>Provisionssumme__c</fullName>
    <formula>Wert_Verk_ufer_Beratungsprovision_o_R__c +  Wert_Verk_ufer_Beratungsprovision_m_R__c +  Wert_Sonstige_2__c +  Wert_Sonstige_1__c +  Wert_Referentenverg_tung__c +  Wert_Differenzprovision__c +  Wert_Beteiligung_SMB_an_JMB__c +  TA_Beteiligung__c +  JMB_Beteiligung__c +  Erfolgsabh_ngige_Provision_direkt__c +  Erfolgsabh_ngige_Provision_indirekt__c +  Direktverkauf_Provision__c +  Wert_Tippprovision__c +  Wert_Overhead__c +  Wert_Maklerprovision__c +  WertMarketingzuschuss__c + AdditionalBrokerCommission__c +  BeratungsprovisionMitPVInEuro__c +  ClosingBonusInEuro__c + ProvisionVertriebskoordination__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provisionssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Rechnungsvorlage_verschickt_am__c.field-meta.xml
<CustomField>
    <fullName>Rechnungsvorlage_verschickt_am__c</fullName>
    <label>Rechnungsvorlage verschickt am</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/Realty_User__c.object-meta.xml
<CustomObject>
    <label>Immo Benutzer</label>
    <nameField>
        <label>Immo Benutzer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immo Benutzer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realty_User__c/fields/Collection_Id__c.field-meta.xml
<CustomField>
    <fullName>Collection_Id__c</fullName>
    <label>Collection Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Realty_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestDashboard.cls
@RestResource(urlMapping='/Dashboard')
global with sharing class RestDashboard  {

    @HttpPost
    global static DashboardData show(Id userId) {

        DashboardData dashboardData = new DashboardData(userId);

        return dashboardData;

    }

    global class DashboardData {
        List<Campaign> myCampaigns = new List<Campaign>();
        List<Campaign> webinars = new List<Campaign>();
        List<Campaign> otherCampaigns = new List<Campaign>();
        List<Property__c> properties = new List<Property__c>();
        List<Opportunity> oppsThisYear = new List<Opportunity>();
        List<Provision__c> provsThisYear = new List<Provision__c>();


        public DashboardData(Id userId) {
            // Get the User from which the request is being sent
            Realty_User__c user = [SELECT Contact__c FROM Realty_User__c WHERE Id = :userId];
            // Get the Contact related to the user
            Contact con = [SELECT Id, AccountId FROM Contact WHERE Id =: user.Contact__c];

            // Get all campaigns and then filter them in a for loop to add to the right list
            List<Campaign> allCampaigns = [SELECT Name, Id, Type, Speaker__c, Url__c, DateTime__c, Is_Public__c, Description FROM Campaign WHERE DateTime__c > TODAY AND Status != 'Abgeschlossen' AND Status != 'Abgebrochen'];
            for(Campaign camp:allCampaigns) {
                if(camp.Speaker__c == con.Id){
                    myCampaigns.add(camp);
                } else if(camp.Type == 'Online-Seminar') {
                    webinars.add(camp);
                } else {
                    otherCampaigns.add(camp);
                }
            }

            // Get highlight properties
            // Right now it's just the for most recent
            properties = [SELECT Name, Collection_Id__c FROM Property__c WHERE Is_Public__c = true AND Status_Reason__c = 'Aktiv' ORDER BY CreatedDate DESC LIMIT 4];

            // Get Data Statistics
            oppsThisYear = [SELECT StageName FROM Opportunity WHERE (Notartermin__c = THIS_YEAR OR CreatedDate = THIS_YEAR) AND Makler__c = :con.Id];
            provsThisYear = [SELECT Provisionssumme__c, Rechnungsvorlage_verschickt_am__c FROM Provision__c WHERE Makler__c = :con.Id AND (Rechnungsvorlage_verschickt_am__c = LAST_N_MONTHS:11 OR Rechnungsvorlage_verschickt_am__c = THIS_MONTH)];


        }

    }

}