force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <summarizedField>Zahlung__c.Zahldatum__c</summarizedField>
    <summaryForeignKey>Zahlung__c.MaBVRechnung__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VKCZahlung__c/VKCZahlung__c.object-meta.xml
<CustomObject>
    <label>VKC Zahlung</label>
    <nameField>
        <displayFormat>EZ-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>VKC Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VKC Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VkcZahlung__c/fields/BusinessPartner__c.field-meta.xml
<CustomField>
    <fullName>BusinessPartner__c</fullName>
    <label>Geschäftspartner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VKC Zahlungen</relationshipLabel>
    <relationshipName>VKCZahlungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/Zahlung__c.object-meta.xml
<CustomObject>
    <label>Zahlung</label>
    <nameField>
        <displayFormat>Z-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zahlung__c/fields/AccountingText__c.field-meta.xml
<CustomField>
    <fullName>AccountingText__c</fullName>
    <label>Buchungstext</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Betrag__c.field-meta.xml
<CustomField>
    <fullName>Betrag__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/BusinessPartner__c.field-meta.xml
<CustomField>
    <fullName>BusinessPartner__c</fullName>
    <label>Geschäftspartner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/MaBVRechnung__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnung__c</fullName>
    <label>MaBV Rechnung</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MaBVRechnung__c.MaBVRechnungMaster__r.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MaBVRechnung__c</referenceTo>
    <relationshipLabel>Zahlungen</relationshipLabel>
    <relationshipName>ZahlungenMaBVRechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity which this Payment belongs to via MaBV records.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Zahlungen</relationshipLabel>
    <relationshipName>MabvPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/KaufpreisEingangBestaetigungExtension.cls
public class KaufpreisEingangBestaetigungExtension {
    private final Opportunity opp;
    
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public KaufpreisEingangBestaetigungExtension(ApexPages.StandardController stdController) {
        this.opp = (Opportunity)stdController.getRecord();
    }

    public List<Zahlung__c> getZahlungen() {
        List<Zahlung__c> zahlungen = [SELECT Id, Name, Betrag__c, Zahldatum__c, BusinessPartner__c, IBAN__c, AccountingText__c FROM Zahlung__c WHERE MaBVRechnung__r.MaBVRechnungMaster__r.Opportunity__c = :this.opp.Id Order By Zahldatum__c ASC];
        return zahlungen;
    }
    
    public List<VKCZahlung__c> getVKCZahlungen() {
        List<VKCZahlung__c> zahlungen = [SELECT Id, Name, Betrag__c, Zahldatum__c, BusinessPartner__c, IBAN__c, AccountingText__c FROM VKCZahlung__c WHERE Verkaufschance__c = :this.opp.Id Order By Zahldatum__c ASC];
        return zahlungen;
    }
}