force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
            <value>
                <fullName>Storno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Gutschriften.recordType-meta.xml
<RecordType>
    <fullName>Gutschriften</fullName>
    <active>true</active>
    <label>Gutschriften</label>
</RecordType>

force-app/main/default/objects/Gutschrift__c/Gutschrift__c.object-meta.xml
<CustomObject>
    <label>Gutschrift</label>
    <nameField>
        <label>Gutschrift-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gutschrift__c/fields/Empfaenger__c.field-meta.xml
<CustomField>
    <fullName>Empfaenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Gutschriften</relationshipLabel>
    <relationshipName>Gutschriften</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/StornoLaufnummer__c.field-meta.xml
<CustomField>
    <fullName>StornoLaufnummer__c</fullName>
    <formula>&apos;SB&apos; + TEXT(YEAR( DatumGutschriftStorniert__c )) + LPAD(TEXT( StornoLaufnummerZahl__c ), 4 , &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Storno Laufnummer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GutschriftStorno.cls
/**
 * Created by frederikwitte on 03.08.20.
 */

public with sharing class GutschriftStorno {

    @Future(callout=true)
    public static void sendGutschriftStornoAsPdf(Id id) {
        List<Gutschrift__c> gutschriften = [SELECT Id, StornoLaufnummer__c, Empfaenger__c FROM Gutschrift__c WHERE Id = :id];
        Gutschrift__c gutschrift = gutschriften.get(0);
        PageReference pdf = Page.GutschriftStorno;
        pdf.getParameters().put('id', gutschrift.Id);

        // Blob und E-Mail Anhang aus dem String generieren
        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
        attach.ContentType = 'application/pdf';
        Blob body;
        try {
            body = pdf.getContentAsPDF();
        } catch (Exception e) {
            body = blob.valueOf('Ein Fehler ist aufgetreten');
        }
        // Dateiname der CSV
        String fileName = 'Stornobeleg ' + gutschrift.StornoLaufnummer__c + '.pdf';
        attach.setFileName(fileName);
        attach.setInline(false);
        attach.Body = body;

        Id templateId = [SELECT id, name FROM EmailTemplate WHERE developername = 'GutschriftStorno'].id;
        List<OrgWideEmailAddress> oweas = new List<OrgWideEmailAddress>([SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE Address = 'maklerbetreuung@wirtschaftshaus.de']);
        Messaging.Email[] messages = new Messaging.Email[0];
        // SingleEmailMessage erstellen
        Messaging.SingleEmailMessage emailToBroker = new Messaging.SingleEmailMessage();
        emailToBroker.setTemplateId(templateId);
        emailToBroker.setTargetObjectId(gutschrift.Empfaenger__c);
        emailToBroker.setWhatId(gutschrift.Id);
        if (oweas.size() > 0) {
            emailToBroker.setOrgWideEmailAddressId(oweas.get(0).Id);
        }
        emailToBroker.setFileAttachments(new Messaging.EmailFileAttachment[]{
                attach
        });
        // Sends the email
        messages.add(emailToBroker);
        Messaging.SendEmailResult [] r = Messaging.sendEmail(messages, false);
        System.debug(r);

        //Send Email to Fibu
        Messaging.SingleEmailMessage emailToFibu = new Messaging.SingleEmailMessage();

        String[] toMails = new List < String > ();
        toMails.add('fibu@carestone.com');
        //toMails.add('f.witte@carestone.com');
        emailToFibu.setToAddresses(toMails);
        if (oweas.size() > 0) {
            emailToFibu.setOrgWideEmailAddressId(oweas.get(0).Id);
        }
        if(r[0].isSuccess()) {
            emailToFibu.setHtmlBody(emailToBroker.getHtmlBody());

            emailToFibu.setPlainTextBody(emailToBroker.getPlainTextBody());

            emailToFibu.setSubject(emailToBroker.getSubject());

            emailToFibu.setFileAttachments(emailToBroker.getFileAttachments());
        } else {
            emailToFibu.setPlainTextBody('Für die Gutschrift wurde ein Storno Beleg generiert und konnte nicht per Mail an den Makler zugestellt werden.');

            emailToFibu.setSubject('Gutschrift Storno ' + gutschrift.StornoLaufnummer__c);

            emailToFibu.setFileAttachments(new Messaging.EmailFileAttachment[]{
            attach
            });
        }
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {
                emailToFibu
        });

        ContentVersion file = new ContentVersion();
        file.VersionData = body;
        file.Title = fileName; 
        file.ContentLocation= 's';
        file.PathOnClient=fileName;
        gutschrift.StornoWurdeGeneriert__c = true;
        Id gutschriftenRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Gutschriften').getRecordTypeId();
        file.Typ__c = 'Storno';
        file.RecordTypeId = gutschriftenRecordTypeId;
        insert file;
        
        List<ContentVersion> files = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :file.Id];

        if(files.size() > 0) {
            file = files[0];
            ContentDocumentLink cde = new ContentDocumentLink();
            cde.ContentDocumentId = file.ContentDocumentId;
            cde.LinkedEntityId = gutschrift.Id;
            insert cde;
            update gutschrift;
        }
    }

}