force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
            <value>
                <fullName>Mahnung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/MaBV.recordType-meta.xml
<RecordType>
    <fullName>MaBV</fullName>
    <active>true</active>
    <label>MaBV</label>
</RecordType>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/IDKunde__c.field-meta.xml
<CustomField>
    <fullName>IDKunde__c</fullName>
    <label>ID Käufer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/MahnungVersendetAm__c.field-meta.xml
<CustomField>
    <fullName>MahnungVersendetAm__c</fullName>
    <label>Mahnung versendet am</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MaBVMahnungPdf.cls
/**
 * Created by frederikwitte on 06.05.2022
 */

public without sharing class MaBVMahnungPdf {
    
    //@Future(callout=true)
    public static void sendMahnungenAsPdf(List<Id> maBVRechnungenIds) {
        String reminderFileName = 'Zahlungserinnerung ';
        String emailTemplateName = 'MaBVMahnungPDF';

        List<MaBVRechnung__c> maBVRechnungen = [SELECT Id, Name, IDKunde__c FROM MaBVRechnung__c WHERE Id IN :maBVRechnungenIds];
        Id templateId = [SELECT Id, Name FROM EmailTemplate WHERE developername = :emailTemplateName].id;
        List<OrgWideEmailAddress> oweas = new List<OrgWideEmailAddress>([SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE Address = 'support@carestone.com']);
        Messaging.Email[] messages = new Messaging.Email[0];
        Map<Id, ContentVersion> maBVRechnungIdToFile = new Map<Id, ContentVersion>();
        List<ContentDocumentLink> fileLinks = new List<ContentDocumentLink>();

        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            PageReference pdf = Page.MaBVMahnung;
            pdf.getParameters().put('id', maBVRechnung.Id);
            // Blob und E-Mail Anhang aus dem String generieren
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            attach.ContentType = 'application/pdf';
            Blob body;
            try {
                body = pdf.getContentAsPDF();
            } catch (Exception e) {
                body = blob.valueOf('Ein Fehler ist aufgetreten');
            }
            // Dateiname der CSV
            String fileName = reminderFileName + maBVRechnung.Name + '.pdf';
            attach.setFileName(fileName);
            attach.setInline(false);
            attach.Body = body;
            // SingleEmailMessage erstellen
            Messaging.SingleEmailMessage Emailwithattch = new Messaging.SingleEmailMessage();
            Emailwithattch.setTemplateId(templateId);
            Emailwithattch.setTargetObjectId(maBVRechnung.IDKunde__c);
            Emailwithattch.setWhatId(maBVRechnung.Id);
            Emailwithattch.treatTargetObjectAsRecipient = false;
            // Email to broker "Couldn't create"
            String[] toMails = new List < String > ();
            toMails.add('MaBV-Rechnungen@carestone.com');
            //toMails.add('frederik.witte93@gmail.com');
            Emailwithattch.setToAddresses(toMails);
            if (oweas.size() > 0) {
                Emailwithattch.setOrgWideEmailAddressId(oweas.get(0).Id);
            }
            Emailwithattch.setFileAttachments(new Messaging.EmailFileAttachment[]{
                    attach
            });
            messages.add(Emailwithattch);

            ContentVersion file = new ContentVersion();
            file.VersionData = body;
            file.Title = fileName; 
            file.ContentLocation= 's';
            file.PathOnClient=fileName;
            Id mabvRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('MaBV').getRecordTypeId();
            file.Typ__c = 'Mahnung';
            file.RecordTypeId = mabvRecordTypeId;
            maBVRechnungIdToFile.put(maBVRechnung.Id, file);
            maBVRechnung.MahnungVersendetAm__c = Date.today();
        }
        // Sends the email
        Messaging.SendEmailResult [] r = Messaging.sendEmail(messages, false);
        System.debug(r);

        insert maBVRechnungIdToFile.values();

        List<Id> fileIds = new List<Id>();
        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            ContentVersion file = maBVRechnungIdToFile.get(maBVRechnung.Id);
            fileIds.add(file.Id);
        }

        Map<Id, ContentVersion> files = new Map<Id, ContentVersion>([SELECT ContentDocumentId FROM ContentVersion WHERE Id IN :fileIds]);

        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            Id fileId = maBVRechnungIdToFile.get(maBVRechnung.Id).Id;
            ContentVersion file = files.get(fileId);
            ContentDocumentLink cde = new ContentDocumentLink();
            cde.ContentDocumentId = file.ContentDocumentId;
            cde.LinkedEntityId = mabvRechnung.Id;
            fileLinks.add(cde);
        }
        insert fileLinks;
        update maBVRechnungen;
    }
}