force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DigitaleVsa__c/DigitaleVsa__c.object-meta.xml
<CustomObject>
    <label>Digitale VSA</label>
    <nameField>
        <displayFormat>DVSA-{yyyy}-{0000}</displayFormat>
        <label>Digitale VSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digitale VSAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateAndSavePdfTest.cls
@isTest
public with sharing class CreateAndSavePdfTest {

    @TestVisible private static Boolean isSuccess;

        @testSetup
        static void makeData() {
                     
            DigitaleVsa__c digitaleVsa = TestDataFactory.createDigitaleVsa(true);
            DigitaleVsa__c recordId = [SELECT Id FROM DigitaleVsa__c LIMIT 1];           
            ContentVersion file = new ContentVersion();
            Blob b=Blob.valueOf('Unit Test Attachment Body');           
            file.VersionData =  EncodingUtil.base64Decode('Unit Test Attachment Body');
            file.Title = 'Test File';
            file.PathOnClient = recordId + 'pdf';
            file.Typ__c = 'Individuelle Unterlage'; 
            try{
                insert file; 
                isSuccess=true;
    
            }catch(DMLexception e){
                System.debug('Exception' + e.getMessage());
            }
            System.debug('isSuccess');
            System.debug(isSuccess);
        }

        @isTest
        private static void testPdfCreate() {          

            List<ContentVersion> listOfContentVersions = [SELECT Id, contentDocumentId, Title FROM ContentVersion WHERE Title= :'Test File' LIMIT 1];
            
            if(listOfContentVersions.isEmpty() ){
                isSuccess = false;
                
            } else {
                isSuccess = true;
                
            }

            System.debug('isSuccess INSIDE TEST ');
            System.debug(isSuccess);

            Test.startTest();
            System.assertEquals(listOfContentVersions.size(),1);
            System.assertEquals(isSuccess, true, 'isSuccess is false');
            Test.stopTest();
          
        }

    
}