force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Finanzierungsanfragen.recordType-meta.xml
<RecordType>
    <fullName>Finanzierungsanfragen</fullName>
    <active>true</active>
    <label>Finanzierungsanfragen</label>
</RecordType>

force-app/main/default/objects/Finanzierungsanfrage__c/Finanzierungsanfrage__c.object-meta.xml
<CustomObject>
    <label>Finanzierungsanfrage</label>
    <nameField>
        <label>Finanzierungsanfrage-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finanzierungsanfragen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finanzierungsanfrage__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Finanzierungsanfragen</relationshipLabel>
    <relationshipName>Finanzierungsanfragen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FinanzierungsanfrageService.cls
public without sharing class FinanzierungsanfrageService {

    public static void sendFinanzierungsbestaetigung(Id finanzierungsanfrageId) {
        if (finanzierungsanfrageId == null) {
            return;
        }

        Finanzierungsanfrage__c fa = [
            SELECT Id,
                   Name,
                   Opportunity__c,
                   Opportunity__r.Makler__c
            FROM Finanzierungsanfrage__c
            WHERE Id = :finanzierungsanfrageId
            LIMIT 1
        ];

        // If there is no Opportunity or Makler, we can't send the email
        if (fa.Opportunity__c == null || fa.Opportunity__r.Makler__c == null) {
            return;
        }

        // Build PDF from Visualforce page
        PageReference pdfPage = Page.Finanzierungsbestaetigung;
        pdfPage.getParameters().put('id', fa.Id);

        Blob pdfBody;
        if (Test.isRunningTest()) {
            // getContentAsPDF is not allowed in tests
            pdfBody = Blob.valueOf('Test PDF content');
        } else {
            try {
                pdfBody = pdfPage.getContentAsPDF();
            } catch (Exception e) {
                pdfBody = Blob.valueOf('Fehler beim Generieren des PDFs.');
            }
        }

        String fileName = 'Finanzierungsbestaetigung ' + fa.Name + '.pdf';
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setContentType('application/pdf');
        attachment.setFileName(fileName);
        attachment.setInline(false);
        attachment.setBody(pdfBody);

        // Try to get the email template, but make tests robust if it doesn't exist
        Id templateId = null;
        if (!Test.isRunningTest()) {
            try {
                templateId = [
                    SELECT Id
                    FROM EmailTemplate
                    WHERE DeveloperName = 'VSA_genehmigt'
                    AND IsActive = true
                    LIMIT 1
                ].Id;
            } catch (Exception e) {
                // leave templateId = null
            }
        }

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        if (templateId != null) {
            email.setTemplateId(templateId);
        } else {
            // Fallback for test / missing template
            email.setSubject('Finanzierungsbestätigung');
            email.setPlainTextBody('Ihre Finanzierungsbestätigung befindet sich im Anhang.');
        }

        email.setTargetObjectId(fa.Opportunity__r.Makler__c);
        email.setWhatId(fa.Opportunity__c);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });
        email.setSaveAsActivity(true);

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email }, false);

        ContentVersion file = new ContentVersion();
        file.VersionData = pdfBody;
        file.Title = fileName; 
        file.ContentLocation= 's';
        file.PathOnClient=fileName;
        Id finanzierungsanfragenRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Finanzierungsanfragen').getRecordTypeId();
        file.Typ__c = 'Finanzierungsbestätigung (FB)';
        file.RecordTypeId = finanzierungsanfragenRecordTypeId;
        insert file;
        
        List<ContentVersion> files = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :file.Id];

        if(files.size() > 0) {
            file = files[0];
            ContentDocumentLink cdeFa = new ContentDocumentLink();
            cdeFa.ContentDocumentId = file.ContentDocumentId;
            cdeFa.LinkedEntityId = fa.Id;

            ContentDocumentLink cdeOpportunity = new ContentDocumentLink();
            cdeOpportunity.ContentDocumentId = file.ContentDocumentId;
            cdeOpportunity.LinkedEntityId = fa.Opportunity__c;
            insert new List<ContentDocumentLink>{cdeFa, cdeOpportunity};
        }
    }
}