force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
            <value>
                <fullName>Storno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/MaBV.recordType-meta.xml
<RecordType>
    <fullName>MaBV</fullName>
    <active>true</active>
    <label>MaBV</label>
</RecordType>

force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRate__c/fields/DateFirstInvoice__c.field-meta.xml
<CustomField>
    <fullName>DateFirstInvoice__c</fullName>
    <label>Datum erste Rechnung</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/DateLastInvoice__c.field-meta.xml
<CustomField>
    <fullName>DateLastInvoice__c</fullName>
    <label>Datum letzte Rechnung</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/IDKunde__c.field-meta.xml
<CustomField>
    <fullName>IDKunde__c</fullName>
    <label>ID Käufer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/RechnungWurdeGeneriert__c.field-meta.xml
<CustomField>
    <fullName>RechnungWurdeGeneriert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rechnung wurde generiert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/StornoLaufnummer__c.field-meta.xml
<CustomField>
    <fullName>StornoLaufnummer__c</fullName>
    <label>Storno Laufnummer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/IDKunde__c.field-meta.xml
<CustomField>
    <fullName>IDKunde__c</fullName>
    <formula>Opportunity__r.Potenzieller_Kunde__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID Kunde</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Rechnungsdatum__c.field-meta.xml
<CustomField>
    <fullName>Rechnungsdatum__c</fullName>
    <label>Rechnungsdatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MaBVRechnungPdf.cls
/**
 * Created by frederikwitte on 26.05.20.
 */

public with sharing class MaBVRechnungPdf {
    
    //@Future(callout=true)
    public static void sendRechnungenAsPdf(List<Id> maBVRechnungenIds, Boolean storno) {
        String invoiceFileName = 'MaBV Rechnung ';
        String emailTemplateName = 'MaBVRechnungPDF';
        if(storno) {
            invoiceFileName = 'MaBV Storno ';
            emailTemplateName = 'MaBVStornoPDF';
        }
        List<MaBVRechnung__c> maBVRechnungen = [SELECT Id, Name, IDKunde__c, StornoLaufnummer__c, Rechnungsdatum__c, MaBVRechnungMaster__r.MaBVRate__c FROM MaBVRechnung__c WHERE Id IN :maBVRechnungenIds];
        Id templateId = [SELECT Id, Name FROM EmailTemplate WHERE developername = :emailTemplateName].id;
        List<OrgWideEmailAddress> oweas = new List<OrgWideEmailAddress>([SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE Address = 'maklerbetreuung@wirtschaftshaus.de']);
        Messaging.Email[] messages = new Messaging.Email[0];
        Map<Id, ContentVersion> maBVRechnungIdToFile = new Map<Id, ContentVersion>();
        List<ContentDocumentLink> fileLinks = new List<ContentDocumentLink>();
        Set<Id> mabvRateIds = new Set<Id>();

        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            mabvRateIds.add(maBVRechnung.MaBVRechnungMaster__r.MaBVRate__c);
        }

        Map<Id, MaBVRate__c> mabvRaten = new Map<Id, MaBVRate__c>([SELECT DateFirstInvoice__c, DateLastInvoice__c FROM MaBVRate__c WHERE Id IN :mabvRateIds]);
        Map<Id, MaBVRate__c> updateMaBVRaten = new Map<Id, MaBVRate__c>();

        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            PageReference pdf = Page.MaBVRechnung;
            pdf.getParameters().put('id', maBVRechnung.Id);
            if(storno) {
                pdf.getParameters().put('type', 'Storno');
            } else {
                pdf.getParameters().put('type', 'Rechnung');
            }
            // Blob und E-Mail Anhang aus dem String generieren
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
            attach.ContentType = 'application/pdf';
            Blob body;
            try {
                body = pdf.getContentAsPDF();
            } catch (Exception e) {
                body = blob.valueOf('Ein Fehler ist aufgetreten');
            }
            // Dateiname der CSV
            String fileName = invoiceFileName + maBVRechnung.Name + '.pdf';
            if(storno) {
                fileName = invoiceFileName + maBVRechnung.StornoLaufnummer__c + '.pdf';
            }
            attach.setFileName(fileName);
            attach.setInline(false);
            attach.Body = body;
            // SingleEmailMessage erstellen
            Messaging.SingleEmailMessage Emailwithattch = new Messaging.SingleEmailMessage();
            Emailwithattch.setTemplateId(templateId);
            Emailwithattch.setTargetObjectId(maBVRechnung.IDKunde__c);
            Emailwithattch.setWhatId(maBVRechnung.Id);
            Emailwithattch.treatTargetObjectAsRecipient = false;
            // Email to broker "Couldn't create"
            String[] toMails = new List < String > ();
            toMails.add('MaBV-Rechnungen@carestone.com');
            //toMails.add('frederik.witte93@gmail.com');
            Emailwithattch.setToAddresses(toMails);
            if (oweas.size() > 0) {
                Emailwithattch.setOrgWideEmailAddressId(oweas.get(0).Id);
            }
            Emailwithattch.setFileAttachments(new Messaging.EmailFileAttachment[]{
                    attach
            });
            messages.add(Emailwithattch);

            ContentVersion file = new ContentVersion();
            file.VersionData = body;
            file.Title = fileName; 
            file.ContentLocation= 's';
            file.PathOnClient=fileName;
            Id mabvRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('MaBV').getRecordTypeId();
            file.Typ__c = 'MaBV Rechnung';
            if(storno) { 
                file.Typ__c = 'Storno';
            }
            file.RecordTypeId = mabvRecordTypeId;
            maBVRechnungIdToFile.put(maBVRechnung.Id, file);
            if(storno) {
                maBVRechnung.StornoWurdeGeneriert__c = true;
            } else {
                maBVRechnung.RechnungWurdeGeneriert__c = true;
            }

            Boolean updateMabvRate = false;
            MaBVRate__c mabvRate = mabvRaten.get(maBVRechnung.MaBVRechnungMaster__r.MaBVRate__c);
            if(!storno && (mabvRate.DateFirstInvoice__c == null || mabvRate.DateFirstInvoice__c != null && mabvRate.DateFirstInvoice__c > mabvRechnung.Rechnungsdatum__c)) {
                mabvRate.DateFirstInvoice__c = mabvRechnung.Rechnungsdatum__c;
                updateMabvRate = true;
            }

            if(!storno && (mabvRate.DateLastInvoice__c == null || mabvRate.DateLastInvoice__c != null && mabvRate.DateLastInvoice__c < mabvRechnung.Rechnungsdatum__c)) {
                mabvRate.DateLastInvoice__c = mabvRechnung.Rechnungsdatum__c;
                updateMabvRate = true;
            }

            if(updateMabvRate) {
                updateMaBVRaten.put(mabvRate.Id, mabvRate);
            }
        }
        // Sends the email
        Messaging.SendEmailResult [] r = Messaging.sendEmail(messages, false);
        System.debug(r);

        insert maBVRechnungIdToFile.values();

        List<Id> fileIds = new List<Id>();
        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            ContentVersion file = maBVRechnungIdToFile.get(maBVRechnung.Id);
            System.debug(file);
            fileIds.add(file.Id);
        }

        Map<Id, ContentVersion> files = new Map<Id, ContentVersion>([SELECT ContentDocumentId FROM ContentVersion WHERE Id IN :fileIds]);

        for(MaBVRechnung__c maBVRechnung:maBVRechnungen) {
            Id fileId = maBVRechnungIdToFile.get(maBVRechnung.Id).Id;
            ContentVersion file = files.get(fileId);
            System.debug(file);
            ContentDocumentLink cde = new ContentDocumentLink();
            cde.ContentDocumentId = file.ContentDocumentId;
            cde.LinkedEntityId = mabvRechnung.Id;
            fileLinks.add(cde);
        }
        insert fileLinks;
        update maBVRechnungen;
        update updateMaBVRaten.values();
    }
}