force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/GutschriftBestaetigt__c.field-meta.xml
<CustomField>
    <fullName>GutschriftBestaetigt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift bestätigt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Provisionssumme__c.field-meta.xml
<CustomField>
    <fullName>Provisionssumme__c</fullName>
    <formula>Wert_Verk_ufer_Beratungsprovision_o_R__c +  Wert_Verk_ufer_Beratungsprovision_m_R__c +  Wert_Sonstige_2__c +  Wert_Sonstige_1__c +  Wert_Referentenverg_tung__c +  Wert_Differenzprovision__c +  Wert_Beteiligung_SMB_an_JMB__c +  TA_Beteiligung__c +  JMB_Beteiligung__c +  Erfolgsabh_ngige_Provision_direkt__c +  Erfolgsabh_ngige_Provision_indirekt__c +  Direktverkauf_Provision__c +  Wert_Tippprovision__c +  Wert_Overhead__c +  Wert_Maklerprovision__c +  WertMarketingzuschuss__c + AdditionalBrokerCommission__c +  BeratungsprovisionMitPVInEuro__c +  ClosingBonusInEuro__c + ProvisionVertriebskoordination__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provisionssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Rechnungsvorlage_verschickt_am__c.field-meta.xml
<CustomField>
    <fullName>Rechnungsvorlage_verschickt_am__c</fullName>
    <label>Rechnungsvorlage verschickt am</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Nettobetrag</inlineHelpText>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Wert_Verk_ufer_Beratungsprovision_m_R__c.field-meta.xml
<CustomField>
    <fullName>Wert_Verk_ufer_Beratungsprovision_m_R__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Beratungsprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProvisionController.cls
public without sharing class ProvisionController {

    @AuraEnabled(cacheable=true)
    public static List<Provision__c> getProvisionen() {
        Id userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        User usr = [SELECT ContactId, AccountId FROM User WHERE Id = :userId];
        Id conId = usr.ContactId;
        List<Provision__c> provs = [SELECT Wert_Maklerprovision__c, Wert_Verk_ufer_Beratungsprovision_m_R__c, Provisionssumme__c, GutschriftBestaetigt__c, Rechnungsvorlage_verschickt_am__c FROM Provision__c WHERE Makler__c = :conId];
        return provs;
    }
}