force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/GutschriftAbgelehnt__c.field-meta.xml
<CustomField>
    <fullName>GutschriftAbgelehnt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift abgelehnt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/GutschriftBestaetigt__c.field-meta.xml
<CustomField>
    <fullName>GutschriftBestaetigt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift bestätigt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GutschriftApprovalController.cls
public without sharing class GutschriftApprovalController {
    public String status {get;set;}

    public GutschriftApprovalController() {
        status = '';
    }

    public void approveGutschrift() {
        String gutschriftId = Apexpages.currentPage().getParameters().get('gutschriftId');
        String accepted = Apexpages.currentPage().getParameters().get('accepted');

        Provision__c[] prov = [SELECT Id, GutschriftBestaetigt__c, GutschriftAbgelehnt__c  FROM Provision__c WHERE Id = :gutschriftId];

        
        if (accepted != null && prov.size() > 0) {

            //Check if Provision has been already approved
            if (prov[0].GutschriftBestaetigt__c == true || prov[0].GutschriftAbgelehnt__c == true) {
                status = 'Diese Gutschrift wurde bereits bearbeitet.';
                return;
            }
            
            //Approve Provision
            if (accepted == 'true') {
                prov[0].GutschriftBestaetigt__c = true;
                status = 'Gutschrift erfolgreich bestätigt!';
            }
            //Reject Provision
            else if (accepted == 'false') {
                prov[0].GutschriftAbgelehnt__c = true;
                status = 'Gutschrift erfolgreich abgelehnt!';
            }
            //Parameter 'accepted' is not true or false
            else {
                status = 'Fehler! Bitte wenden Sie sich an Ihren Maklerbetreuer. <br/>(Fehlercode e1)';
            }

            try {
                update prov;
            } catch (Exception e) {
                System.debug('EXCEPTION: ' + e);
                status = 'Fehler! Bitte wenden Sie sich an Ihren Maklerbetreuer. <br/>(Fehlercode e2)';
            }
        }
        //Parameter 'gutschriftId' is either wrong or empty
        else if (prov.size() == 0) {
            status = 'Fehler! Bitte wenden Sie sich an Ihren Maklerbetreuer. <br/>(Fehlercode e3)';
        }

    }
}