force-app/main/default/objects/Activity_Summary__c/Activity_Summary__c.object-meta.xml
<CustomObject>
    <description>Counts all of community users logs</description>
    <label>VP Aktivitäten</label>
    <nameField>
        <displayFormat>VP Login {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VP Aktivitäten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/VPBenutzerId__c.field-meta.xml
<CustomField>
    <fullName>VPBenutzerId__c</fullName>
    <externalId>true</externalId>
    <label>VP Benutzer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FileDownloadLog__c/FileDownloadLog__c.object-meta.xml
<CustomObject>
    <label>File Download Log</label>
    <nameField>
        <displayFormat>FDL-{0000}</displayFormat>
        <label>File Download Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Download Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FileDownloadLog__c/fields/ImmobilienDMSDatei__c.field-meta.xml
<CustomField>
    <fullName>ImmobilienDMSDatei__c</fullName>
    <label>Immobilien DMS Datei</label>
    <referenceTo>ImmobilienDmsDatei__c</referenceTo>
    <relationshipLabel>File Download Logs</relationshipLabel>
    <relationshipName>File_Download_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FileDownloadLog__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Datei Downloads</relationshipLabel>
    <relationshipName>FileDownloads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/ImmobilienDmsDatei__c.object-meta.xml
<CustomObject>
    <label>Immobilien DMS Datei</label>
    <nameField>
        <label>Immobilien DMS Datei Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien DMS Dateien</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserActivitySummaryBatchTest.cls
@isTest
public class UserActivitySummaryBatchTest {   
    @TestSetup
    static void makeData(){
        
    }

   @isTest()
    private static void testUsersWithActiveSummaryCreated(){
        Account acc = TestDataFactory.createAccount(true);
        User testUser = TestDataFactory.createCommunityUser(acc.Id);
        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id LIMIT 1];
        con.VPBenutzerId__c = '1234';
        update con;
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Property__c p = TestDataFactory.createProperty(true, bautraeger.Id);
        ImmobilienDMSDatei__c dmsDatei = TestDataFactory.createImmobilienDMSDatei(true, p.Id, 'Dokumente');
        TestDataFactory.createFileDownloadLog(true, con.Id);
        
        List<Activity_Summary__c> summariesToInsert=new List<Activity_Summary__c>();
        Activity_Summary__c userSummary = TestDataFactory.createActivitySummary(false, con.Id);
        summariesToInsert.add(userSummary);
        insert summariesToInsert;

        System.Debug('summaries: '+[select count(id)from Activity_Summary__c]);
        System.debug('loginhistory: '+[select count(id) from LoginHistory]);
        
        
        Test.startTest();
        System.RunAs(testUser){
            TestDataFactory.createInteressent(true, acc.Id);
        }
        Database.executeBatch(new UserActivitySummaryBatch(new List<Id>{con.Id}));
        Test.stopTest();
    }
    
   @isTest()
    private static void testUsersWithoutActiveSummaryCreated(){
        Account acc = TestDataFactory.createAccount(true);
        User testUser = TestDataFactory.createCommunityUser(acc.Id);
        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id LIMIT 1];
        con.VPBenutzerId__c = '1234';
        update con;
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Property__c p = TestDataFactory.createProperty(true, bautraeger.Id);
        ImmobilienDMSDatei__c dmsDatei = TestDataFactory.createImmobilienDMSDatei(true, p.Id, 'Dokumente');
        TestDataFactory.createFileDownloadLog(true, con.Id);

        System.Debug('summaries: '+[select count(id)from Activity_Summary__c]);
        System.debug('loginhistory: '+[select count(id) from LoginHistory]);
        System.debug('fileDownloadLogs: '+[select count(id) from FileDownloadLog__c]);
        
        Test.startTest();
        System.RunAs(testUser){
            TestDataFactory.createInteressent(true, acc.Id);
        }
        Database.executeBatch(new UserActivitySummaryBatch(new List<Id>{con.Id}));
        Test.stopTest();
    }
}