force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/PlannedCertification__c.field-meta.xml
<CustomField>
    <fullName>PlannedCertification__c</fullName>
    <label>Planned Certification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current Month</fullName>
            </value>
            <value>
                <fullName>Next Month</fullName>
            </value>
            <value>
                <fullName>Month after next</fullName>
            </value>
            <value>
                <fullName>Uncertain</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchSwitchPlannedCertificationValueTest.cls
@isTest
public with sharing class BatchSwitchPlannedCertificationValueTest {
    @TestSetup
    static void makeData() {
        List<Opportunity> opportunitiesToInsert = new List<Opportunity>();
        Account acc = TestDataFactory.createAccount(true);
        Contact makler = TestDataFactory.createMakler(true, acc.id);
        Contact interessant = TestDataFactory.createInteressent(true, acc.id);
        Account bautraeger = testDataFactory.createBautraeger(true);
        Property__c property = TestDataFactory.createProperty(true, bautraeger.id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, property.id);
        Appartment__c appartment2 = TestDataFactory.createAppartment(true, property.id);
        Appartment__c appartment3 = TestDataFactory.createAppartment(true, property.id);

        Opportunity opp1 = TestDataFactory.createOpportunity(true, interessant.id, makler.id, property.id, appartment.id);
        opp1.PlannedCertification__c = BatchSwitchPlannedCertificationValue.PLANNED_CERTIFICATION_VALUE_CURRENT_MONTH;

    }
    @isTest
    private static void testBatchWhenBatchSwitchPlannedCertificationIsCurrenthMonth() {
        Test.startTest();
        BatchSwitchPlannedCertificationValue batch = new BatchSwitchPlannedCertificationValue();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        Opportunity opportunityAfterBatch = [
                SELECT id, PlannedCertification__c
                FROM Opportunity
                Limit 1
        ];
        system.assertEquals(null, opportunityAfterBatch.PlannedCertification__c);
    }
    @isTest
    private static void testBatchWhenBatchSwitchPlannedCertificationIsNextMonth() {
        Opportunity opportunityBeforeBatch = [
                SELECT id, PlannedCertification__c
                FROM Opportunity
                Limit 1
        ];
        opportunityBeforeBatch.PlannedCertification__c = BatchSwitchPlannedCertificationValue.PLANNED_CERTIFICATION_VALUE_NEXT_MONTH;
        update opportunityBeforeBatch;
        Test.startTest();
        BatchSwitchPlannedCertificationValue batch = new BatchSwitchPlannedCertificationValue();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        Opportunity opportunityAfterBatch = [
                SELECT id, PlannedCertification__c
                FROM Opportunity
                Limit 1
        ];
        system.assertEquals(BatchSwitchPlannedCertificationValue.PLANNED_CERTIFICATION_VALUE_CURRENT_MONTH, opportunityAfterBatch.PlannedCertification__c);
    }
    @isTest
    private static void testBatchWhenBatchSwitchPlannedCertificationIsCurrenthMonthAfterNext() {
        Opportunity opportunityBeforeBatch = [
                SELECT id, PlannedCertification__c
                FROM Opportunity
                Limit 1
        ];
        opportunityBeforeBatch.PlannedCertification__c = BatchSwitchPlannedCertificationValue.PLANNED_CERTIFICATION_VALUE_MONTH_AFTER_NEXT;
        update opportunityBeforeBatch;
        Test.startTest();
        BatchSwitchPlannedCertificationValue batch = new BatchSwitchPlannedCertificationValue();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        Opportunity opportunityAfterBatch = [
                SELECT id, PlannedCertification__c
                FROM Opportunity
                Limit 1
        ];
        system.assertEquals(BatchSwitchPlannedCertificationValue.PLANNED_CERTIFICATION_VALUE_NEXT_MONTH, opportunityAfterBatch.PlannedCertification__c);
    }
}