force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/ApartmentNummer__c.field-meta.xml
<CustomField>
    <fullName>ApartmentNummer__c</fullName>
    <formula>LPAD(TEXT(VALUE(RIGHT(SUBSTITUTE(SUBSTITUTE(Name, &apos; (Renoviert)&apos;, &apos;&apos;), &apos; (Unrenoviert)&apos;, &apos;&apos;), 3))), 3, &apos;0&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apartment Nummer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Gutschrift__c/Gutschrift__c.object-meta.xml
<CustomObject>
    <label>Gutschrift</label>
    <nameField>
        <label>Gutschrift-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gutschrift__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/GutschriftStorniert__c.field-meta.xml
<CustomField>
    <fullName>GutschriftStorniert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift storniert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/ZuDatevUebertragen__c.field-meta.xml
<CustomField>
    <fullName>ZuDatevUebertragen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Zu Datev übertragen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>Zahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>Zahlung__c.MaBVRechnung__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <label>Immobilie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/OffenerBetragNeu__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragNeu__c</fullName>
    <formula>IF((RateGesamtInEuro__c - Bezahlt__c) &lt; 0, 0, RateGesamtInEuro__c - Bezahlt__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag (neu)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Storniert__c.field-meta.xml
<CustomField>
    <fullName>Storniert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Storniert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <summarizedField>Zahlung__c.Zahldatum__c</summarizedField>
    <summaryForeignKey>Zahlung__c.MaBVRechnung__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>VkcZahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>VkcZahlung__c.Verkaufschance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt (aus Teilobjekt)</label>
    <summarizedField>Appartment__c.Bezahlt__c</summarizedField>
    <summaryForeignKey>Appartment__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Objektnummer__c.field-meta.xml
<CustomField>
    <fullName>Objektnummer__c</fullName>
    <label>Immobiliennummer</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/VKCZahlung__c.object-meta.xml
<CustomObject>
    <label>VKC Zahlung</label>
    <nameField>
        <displayFormat>EZ-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>VKC Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VKC Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VKCZahlung__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VKC Zahlungen</relationshipLabel>
    <relationshipName>VKCZahlungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/Zahlung__c.object-meta.xml
<CustomObject>
    <label>Zahlung</label>
    <nameField>
        <displayFormat>Z-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zahlung__c/fields/Betrag__c.field-meta.xml
<CustomField>
    <fullName>Betrag__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/MaBVRechnung__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnung__c</fullName>
    <label>MaBV Rechnung</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MaBVRechnung__c.MaBVRechnungMaster__r.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MaBVRechnung__c</referenceTo>
    <relationshipLabel>Zahlungen</relationshipLabel>
    <relationshipName>ZahlungenMaBVRechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduledOposSync.cls
global without sharing class ScheduledOposSync implements Schedulable {
    global static void execute(SchedulableContext sc){
        syncOposAndInvoices();
    }

    @future
    global static void syncOposAndInvoices() {
        List<MaBVRechnung__c> mabvRechnungen = [SELECT OffenerBetragNeu__c, Name FROM MaBVRechnung__c WHERE OffenerBetragNeu__c != 0 AND OffenerBetragNeu__c != null AND Storniert__c = FALSE];
        List<Gutschrift__c> gutschriften = [SELECT Bezahlt__c, Name FROM Gutschrift__c WHERE Bezahlt__c != TRUE AND ZuDatevUebertragen__c = TRUE AND GutschriftStorniert__c = FALSE];
        List<Opportunity> opps = [SELECT Id, Appartement__r.ApartmentNummer__c, Immobilie__r.Objektnummer__c FROM Opportunity WHERE StageName = 'Geschlossene und gewonnene' AND Immobilie__r.Objektnummer__c != null AND Appartement__r.ApartmentNummer__c != null];

        DateTime dt = System.Now().addHours(-2);
        List<Document> oposDocuments = [SELECT Id, Body FROM Document WHERE Folder.Name = 'opos' AND CreatedDate >= :dt];
        Map<String, List<Opos>> rechnungsNummerToOpos = new Map<String, List<Opos>>();
        String a;
        String b;
        String c;
        String d;
        String e;
        String f;
        String g;
        String h;
        String i;
        String j;
        String a2;
        String b2;
        String c2;
        String d2;
        String e2;
        String f2;
        String g2;
        String h2;
        String i2;
        String j2;
        

        for(Document oposDocument:oposDocuments) {
            String csvString = oposDocument.Body.toString();
            Boolean skipRow = true;
            for(String row:csvString.split('\n')) {
                if(skipRow) {
                    skipRow = false;
                    continue;
                }
                List<String> columns = row.split(';');
                Opos opos = new Opos(
                    columns[5], 
                    columns[6],
                    columns[2],
                    columns[8]
                );
                String rechnungsNummer = columns[3];
                if(rechnungsNummer.startsWith('"') && rechnungsNummer.endsWith('"')) {
                    rechnungsNummer = rechnungsNummer.substring(1, rechnungsNummer.length()-1);
                }

                List<Opos> oposList = rechnungsNummerToOpos.get(rechnungsNummer);
                if(oposList == null) {
                    oposList = new List<Opos>();
                }
                oposList.add(opos);
                rechnungsNummerToOpos.put(rechnungsNummer, oposList);
            }
        }

        List<Zahlung__c> zahlungen = new List<Zahlung__c>();
        for(MaBVRechnung__c mabvRechnung:mabvRechnungen) {
            List<Opos> oposList = rechnungsNummerToOpos.get(mabvRechnung.Name);
            if(oposList != null) {
                for(Opos opos:oposList) {
                    Decimal bereitsGezahlt = 0;
                    Zahlung__c zahlung = new Zahlung__c();
                    zahlung.MabvRechnung__c = mabvRechnung.Id;
                    zahlung.Zahldatum__c = opos.zahldatum;
                    zahlung.Betrag__c = opos.soll;

                    if(zahlung.Zahldatum__c != null) {
                        zahlung.UniqueId__c = zahlung.Zahldatum__c.year() + '-' + zahlung.Zahldatum__c.month() + '-' + zahlung.Zahldatum__c.day() + '-' + mabvRechnung.Id;
                    }
                    
                    if(opos.bsnr != null) {
                        zahlung.UniqueId__c += '-' + opos.bsnr;
                    }

                    if(zahlung.Betrag__c != null && zahlung.Betrag__c != 0) {
                        zahlungen.add(zahlung);
                    }
                }
            }
        }

        List<Gutschrift__c> updateGutschriften = new List<Gutschrift__c>();
        for(Gutschrift__c gutschrift:gutschriften) {
            List<Opos> oposList = rechnungsNummerToOpos.get(gutschrift.Name);
            if(oposList != null) {
                gutschrift.Bezahlt__c = true;
                gutschrift.Zahldatum__c = oposList.get(0).zahldatum;
                updateGutschriften.add(gutschrift);
            }
        }

        List<VkcZahlung__c> vkcZahlungen = new List<VkcZahlung__c>();
        for(Opportunity opp:opps) {
            String rechnungsNummer = opp.Immobilie__r.Objektnummer__c + '-' + opp.Appartement__r.ApartmentNummer__c;
            List<Opos> oposList = rechnungsNummerToOpos.get(rechnungsNummer);
            if(oposList != null) {
                for(Opos opos:oposList) {
                    Decimal bereitsGezahlt = 0;
                    VkcZahlung__c zahlung = new VkcZahlung__c();
                    zahlung.Verkaufschance__c = opp.Id;
                    zahlung.Zahldatum__c = opos.zahldatum;
                    zahlung.Betrag__c = opos.soll;

                    if(zahlung.Zahldatum__c != null) {
                        zahlung.UniqueId__c = zahlung.Zahldatum__c.year() + '-' + zahlung.Zahldatum__c.month() + '-' + zahlung.Zahldatum__c.day() + '-' + opp.Id;
                    }
                    
                    if(opos.bsnr != null) {
                        zahlung.UniqueId__c += '-' + opos.bsnr;
                    }

                    if(zahlung.Betrag__c != null && zahlung.Betrag__c != 0) {
                        vkcZahlungen.add(zahlung);
                    }
                }
            }
        }

        if(zahlungen.size() > 0) {
            database.insert(zahlungen, false);
        }

        if(updateGutschriften.size() > 0) {
            database.update(updateGutschriften);
        }

        if(vkcZahlungen.size() > 0) {
            database.insert(vkcZahlungen, false);
        }
    }

}