force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Finanzierungsanfragen.recordType-meta.xml
<RecordType>
    <fullName>Finanzierungsanfragen</fullName>
    <active>true</active>
    <label>Finanzierungsanfragen</label>
</RecordType>

force-app/main/default/objects/DatevDebitorennummerKaeufer__c/DatevDebitorennummerKaeufer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Datev Debitorennummer Käufer</label>
</CustomObject>

force-app/main/default/objects/DatevDebitorennummerKaeufer__c/fields/DatevDebitorennummerKaeufer__c.field-meta.xml
<CustomField>
    <fullName>DatevDebitorennummerKaeufer__c</fullName>
    <label>Datev Debitorennummer Käufer</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gutschrift_Laufnummer__c/Gutschrift_Laufnummer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Gutschrift Laufnummer</label>
</CustomObject>

force-app/main/default/objects/Gutschrift_Laufnummer__c/fields/Gutschrift_Laufnummer__c.field-meta.xml
<CustomField>
    <fullName>Gutschrift_Laufnummer__c</fullName>
    <label>Gutschrift Laufnummer</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gutschrift_Storno_Laufnummer__c/Gutschrift_Storno_Laufnummer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Gutschrift Storno Laufnummer</label>
</CustomObject>

force-app/main/default/objects/Gutschrift_Storno_Laufnummer__c/fields/Gutschrift_Storno_Laufnummer__c.field-meta.xml
<CustomField>
    <fullName>Gutschrift_Storno_Laufnummer__c</fullName>
    <label>Gutschrift Storno Laufnummer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungLaufnummer__c/MaBVRechnungLaufnummer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MaBV Rechnung Laufnummer</label>
</CustomObject>

force-app/main/default/objects/MaBVRechnungLaufnummer__c/fields/Laufnummer__c.field-meta.xml
<CustomField>
    <fullName>Laufnummer__c</fullName>
    <label>Laufnummer</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provisionsverhandlung__c/Provisionsverhandlung__c.object-meta.xml
<CustomObject>
    <label>Provisionsverhandlung</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Provisionsverhandlung-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionsverhandlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DMSControllerTest.cls
@IsTest
public with sharing class DMSControllerTest {

    @testSetup static void test_setup() {
        
        Contact mb = TestDataFactory.createContact(true, 'Frank', 'Köpsell', 'witte@amstammtisch.de');
        Account acc3 = TestDataFactory.createBautraeger(true);
        mb.AccountId = acc3.Id;
        update mb;

        Contact potKun = TestDataFactory.createContact(true, 'Tvvsta', 'Tekoeeric');

        Property__c immobilie = TestDataFactory.createProperty(true,acc3.Id);

        Appartment__c app2 = TestDataFactory.createAppartment(true,immobilie.Id,'TestApp2');

        Provisionsverhandlung__c provisionsverhandlung = TestDataFactory.createProvisionsverhandlung(true,acc3.Id,immobilie.Id);

        Gutschrift_Laufnummer__c gutschriftLaufnummer = Gutschrift_Laufnummer__c.getOrgDefaults();
        gutschriftLaufnummer.Gutschrift_Laufnummer__c = 0;
        insert gutschriftLaufnummer;

        Gutschrift_Storno_Laufnummer__c gutschriftStornoLaufnummer = Gutschrift_Storno_Laufnummer__c.getOrgDefaults();
        gutschriftStornoLaufnummer.Gutschrift_Storno_Laufnummer__c = 0;
        insert gutschriftStornoLaufnummer;

        MaBVRechnungLaufnummer__c maBVRechnungLaufnummer = MaBVRechnungLaufnummer__c.getOrgDefaults();
        maBVRechnungLaufnummer.Laufnummer__c = 0;
        insert maBVRechnungLaufnummer;

        DatevDebitorennummerKaeufer__c datevDebitorennummerKaeufer = DatevDebitorennummerKaeufer__c.getOrgDefaults();
        datevDebitorennummerKaeufer.DatevDebitorennummerKaeufer__c = 123456;
        insert datevDebitorennummerKaeufer;

        Opportunity opp = TestDataFactory.createOpportunity(true, potKun.Id, mb.Id, immobilie.Id, app2.Id);
    }

    private static testMethod void testDmsCalls() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Property__c immobilie = [SELECT Id FROM Property__c];
        Opportunity opp = [SELECT Id FROM Opportunity];

        Id finanzierungsanfragenRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Finanzierungsanfragen').getRecordTypeId();

        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cv.Typ__c = 'Individuelle Unterlage';
        cv.RecordTypeId = finanzierungsanfragenRecordTypeId;
        insert cv;

        Test.startTest();
        DMSController.login();
        DMSController.getDocuments('abc', 1);
        DMSController.getDocument('1234');
        DMSController.getDocumentTypes('1234');
        DMSController.uploadDocument('1234', 'aaa', '{"json": "json"}');
        Test.stopTest();
    }
    private static testMethod void testDmsCalls2() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        DMSController.updateFolder('1234', '{"json": "json"}');
        Test.stopTest();
    }

    private static testMethod void testDmsCalls3() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Property__c immobilie = [SELECT Id FROM Property__c];

        Test.startTest();
        DMSController.Requests dmr = new DMSController.Requests();
        dmr.recordId = immobilie.Id;
        dmr.updateFolder = true;
        List<DMSController.Requests> dmrs = new List<DMSController.Requests>();
        dmrs.add(dmr);
        DMSController.createUpdateFoldersFromRecordIdsApexAction(dmrs);
        Test.stopTest();
    }

    private static testMethod void testDmsCalls4() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Opportunity opp = [SELECT Id FROM Opportunity];

        Id finanzierungsanfragenRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Finanzierungsanfragen').getRecordTypeId();

        ContentVersion cv=new Contentversion();
        cv.title='ABC';
        cv.PathOnClient ='test';
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cv.Typ__c = 'Individuelle Unterlage';
        cv.RecordTypeId = finanzierungsanfragenRecordTypeId;
        insert cv;

        Test.startTest();
        DMSController.Requests dmr2 = new DMSController.Requests();
        dmr2.recordId = opp.Id;
        dmr2.updateFolder = false;
        List<DMSController.Requests> dmrs2 = new List<DMSController.Requests>();
        dmrs2.add(dmr2);
        DMSController.createUpdateFoldersFromRecordIdsApexAction(dmrs2);
        DMSController.uploadDocumentFromContentVersionId('1234', cv.Id, '111');
        Test.stopTest();
    }
}