force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailForCreditNotes__c.field-meta.xml
<CustomField>
    <fullName>EmailForCreditNotes__c</fullName>
    <inlineHelpText>Wenn dieses Feld befüllt ist, werden Gutschriften statt an die normale Email-Adresse an die hier hinterlegte Adresse gesendet.</inlineHelpText>
    <label>Email für Gutschriften</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Gutschrift__c/Gutschrift__c.object-meta.xml
<CustomObject>
    <label>Gutschrift</label>
    <nameField>
        <label>Gutschrift-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gutschrift__c/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provision</label>
    <referenceTo>Provision__c</referenceTo>
    <relationshipLabel>Gutschriften</relationshipLabel>
    <relationshipName>Gutschriften</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <label>Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EmailMessageTriggerHandlerTest.cls
@IsTest
private class EmailMessageTriggerHandlerTest {

    @TestSetup
    static void init() {
        TestDataFactory.createDatevSettings();
        User user = TestDataFactory.createCommunityUser();
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        makler.EmailForCreditNotes__c = 'test@test.dev.xyz';
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kaufvertragsunterlagen verschickt');
        Provision__c provision = TestDataFactory.createProvision(true, opp.Id, user.Id, makler.Id);
        TestDataFactory.createGutschrift(true, opp.Id, provision.Id);
    }
    
    @IsTest
    private static void testRelationCreatedForCreditNoteEmail() {
        Contact makler = [SELECT Id, Email, EmailForCreditNotes__c FROM Contact WHERE RecordType.DeveloperName = 'Makler' AND EmailForCreditNotes__c = 'test@test.dev.xyz' LIMIT 1];
        
        Test.startTest();
        EmailMessage message = new EmailMessage(
            ToAddress = makler.EmailForCreditNotes__c,
            Subject = 'Test',
            TextBody = 'Test',
            Status = '3', 
            RelatedToId = [SELECT Id FROM Gutschrift__c LIMIT 1].Id
        );
        insert message;
        Test.stopTest();

        for(EmailMessageRelation relation : [SELECT Id, EmailMessageId, RelationAddress, RelationId FROM EmailMessageRelation WHERE EmailMessageId = :message.Id AND RelationAddress = :makler.EmailForCreditNotes__c])
            System.debug(relation);

        Assert.areEqual(1, [SELECT COUNT() FROM EmailMessageRelation WHERE EmailMessageId = :message.Id AND RelationAddress = :makler.EmailForCreditNotes__c AND RelationId = :makler.Id]);

        EmailMessageTriggerHandler handler = new EmailMessageTriggerHandler();
        handler.beforeInsert(message);
        handler.beforeUpdate(message, message);
        handler.afterUpdate(message, message);
        handler.beforeDelete(message);
        handler.afterDelete(message);
    }
}