force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MaklerBetreuer_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>MaklerBetreuer_E_Mail__c</fullName>
    <label>MaklerBetreuer E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
            <value>
                <fullName>Personalausweis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Finanzierungsanfragen.recordType-meta.xml
<RecordType>
    <fullName>Finanzierungsanfragen</fullName>
    <active>true</active>
    <label>Finanzierungsanfragen</label>
</RecordType>

force-app/main/default/objects/Finanzierungsanfrage__c/Finanzierungsanfrage__c.object-meta.xml
<CustomObject>
    <label>Finanzierungsanfrage</label>
    <nameField>
        <label>Finanzierungsanfrage-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finanzierungsanfragen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finanzierungsanfrage__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finanzierungsanfrage gestellt</fullName>
                <default>true</default>
                <label>Finanzierungsanfrage gestellt</label>
            </value>
            <value>
                <fullName>VSA vorhanden</fullName>
            </value>
            <value>
                <fullName>Rückfragen gestellt</fullName>
            </value>
            <value>
                <fullName>Unterlagen angefordert</fullName>
            </value>
            <value>
                <fullName>Bankantrag</fullName>
            </value>
            <value>
                <fullName>Finanzierung pausiert</fullName>
            </value>
            <value>
                <fullName>Finanzierung genehmigt</fullName>
            </value>
            <value>
                <fullName>Finanzierung verloren</fullName>
            </value>
            <value>
                <fullName>Abgelehnt</fullName>
                <isActive>false</isActive>
                <label>Abgelehnt</label>
            </value>
            <value>
                <fullName>Abgeschlossen</fullName>
                <isActive>false</isActive>
                <label>Abgeschlossen</label>
            </value>
            <value>
                <fullName>Bankzusage</fullName>
                <isActive>false</isActive>
                <label>Bankzusage</label>
            </value>
            <value>
                <fullName>Erfolgreich</fullName>
                <isActive>false</isActive>
                <label>Erfolgreich</label>
            </value>
            <value>
                <fullName>Gewonnen</fullName>
                <isActive>false</isActive>
                <label>Gewonnen</label>
            </value>
            <value>
                <fullName>In Bearbeitung</fullName>
                <isActive>false</isActive>
                <label>In Bearbeitung</label>
            </value>
            <value>
                <fullName>In Bearbeitung CS</fullName>
                <isActive>false</isActive>
                <label>In Bearbeitung CS</label>
            </value>
            <value>
                <fullName>Keine Finanzierung möglich</fullName>
                <isActive>false</isActive>
                <label>Keine Finanzierung möglich</label>
            </value>
            <value>
                <fullName>Kreditverträge unterzeichnet</fullName>
                <isActive>false</isActive>
                <label>Kreditverträge unterzeichnet</label>
            </value>
            <value>
                <fullName>Neu</fullName>
                <isActive>false</isActive>
                <label>Neu</label>
            </value>
            <value>
                <fullName>Verloren</fullName>
                <isActive>false</isActive>
                <label>Verloren</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gutschrift__c/Gutschrift__c.object-meta.xml
<CustomObject>
    <label>Gutschrift</label>
    <nameField>
        <label>Gutschrift-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/MaklerBetreuer_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>MaklerBetreuer_E_Mail__c</fullName>
    <label>MaklerBetreuer E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerTest.cls
@IsTest
private class ContentDocumentLinkTriggerTest {

    @TestSetup
    static void makeData(){
        TestDataFactory.createDatevSettings();
    }
    
    @IsTest
    private static void testLinkOpportunityRelatedFileIsLinkedToOpportunity() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);
        Contact makler = TestDataFactory.createMakler(true, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(true, acc.Id);
        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id);
        MaBVRechnung__c rechnung = TestDataFactory.createMaBVRechnung(true, TestDataFactory.createMaBVRechnungMaster(true, opp.Id, TestDataFactory.createMaBVRate(true, immobilie.Id).Id).Id);
        Gutschrift__c gutschrift = TestDataFactory.createGutschrift(true, opp.Id, null);

        ContentVersion cvAtMaBVRechnung =new Contentversion();
        cvAtMaBVRechnung.title = 'Some File';
        cvAtMaBVRechnung.PathOnClient = 'Some File';
        cvAtMaBVRechnung.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
        cvAtMaBVRechnung.Typ__c = 'Personalausweis';
        cvAtMaBVRechnung.FirstPublishLocationId = rechnung.Id;


        ContentVersion cvAtGutschrift =new Contentversion();
        cvAtGutschrift.title = 'Some File';
        cvAtGutschrift.PathOnClient ='Some File';
        cvAtGutschrift.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
        cvAtGutschrift.Typ__c = 'Personalausweis';
        cvAtGutschrift.FirstPublishLocationId = gutschrift.Id;
        
        Test.startTest();
        insert cvAtMaBVRechnung;
        insert cvAtGutschrift;
        Test.stopTest();

        Id contentDocumentAtMaBVId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cvAtMaBVRechnung.Id].ContentDocumentId;
        Id contentDocumentAtGutschriftId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cvAtGutschrift.Id].ContentDocumentId;
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId = :opp.Id AND ContentDocumentId = :contentDocumentAtMaBVId]);
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId = :opp.Id AND ContentDocumentId = :contentDocumentAtGutschriftId]);
    }

    @IsTest
    private static void testFinanzierungsanfrageStatusSetOnAllRequiredFiles() {
        Account acc = TestDataFactory.createAccount(true);
        Contact interessent = TestDataFactory.createInteressent(true, acc.Id);
        interessent.Maklerbetreuer_E_Mail__c = 'mathis@testx.devx';
        update interessent;
        
        Finanzierungsanfrage__c fa = TestDataFactory.createFinanzierungsanfrage(true, interessent.Id, 'Personalausweis');

        Id finanzierungsanfragenRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Finanzierungsanfragen').getRecordTypeId();

        ContentVersion cv=new Contentversion();
        cv.title='Personalausweis';
        cv.PathOnClient ='Personalausweis';
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cv.Typ__c = 'Personalausweis';
        cv.RecordTypeId = finanzierungsanfragenRecordTypeId;
        cv.FirstPublishLocationId = fa.Id;
        
        Test.startTest();
        insert cv;
        Test.stopTest();

        System.assertEquals('In Bearbeitung', [SELECT Phase__c FROM Finanzierungsanfrage__c WHERE Id = :fa.Id].Phase__c);
    }

    // Needed for code coverage of the TriggerException class
    @IsTest
    private static void testTriggerException() {
        try {
            TriggerFactory.createHandler(Case.getSObjectType());
        } catch(Exception ex) {
            System.assertEquals('TriggerException', ex.getTypeName());
        }
    }
}