force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
            <value>
                <fullName>Nebenkostenzuschuss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/VKC.recordType-meta.xml
<RecordType>
    <fullName>VKC</fullName>
    <active>true</active>
    <label>VKC</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vertriebskoordinator__c.field-meta.xml
<CustomField>
    <fullName>Vertriebskoordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vertriebskoordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Verkaufschancen (Vertriebskoordinator)</relationshipLabel>
    <relationshipName>VerkaufschancenVertriebskoordinator</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityService.cls
public without sharing class OpportunityService {

    public static void sendNebenkostenzuschuss(Id opportunityId) {
        if (opportunityId == null) {
            return;
        }

        Opportunity opp = [
            SELECT Id,
                   Name,
                   Vertriebskoordinator__c,
                   Immobilie__r.Name,
                   Appartement__r.Name,
                   Potenzieller_Kunde__r.LastName
            FROM Opportunity
            WHERE Id = :opportunityId
            LIMIT 1
        ];

        // We need a recipient
        if (opp.Vertriebskoordinator__c == null) {
            return;
        }

        /* =========================
           PDF GENERATION
           ========================= */
        PageReference pdfPage = Page.Nebenkostenzuschuss; // VF page
        pdfPage.getParameters().put('id', opp.Id);

        Blob pdfBody;
        if (Test.isRunningTest()) {
            pdfBody = Blob.valueOf('Test PDF content');
        } else {
            try {
                pdfBody = pdfPage.getContentAsPDF();
            } catch (Exception e) {
                pdfBody = Blob.valueOf('Fehler beim Generieren des PDFs.');
            }
        }

        String fileName =
            opp.Immobilie__r.Name + '_' +
            opp.Appartement__r.Name + '_' +
            opp.Potenzieller_Kunde__r.LastName +
            '_Erstattung.pdf';

        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setContentType('application/pdf');
        attachment.setFileName(fileName);
        attachment.setInline(false);
        attachment.setBody(pdfBody);

        /* =========================
           EMAIL TEMPLATE
           ========================= */
        Id templateId = null;
        if (!Test.isRunningTest()) {
            try {
                templateId = [
                    SELECT Id
                    FROM EmailTemplate
                    WHERE DeveloperName = 'Nebenkostenzuschuss'
                    AND IsActive = true
                    LIMIT 1
                ].Id;
            } catch (Exception e) {
                // fallback below
            }
        }

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        if (templateId != null) {
            email.setTemplateId(templateId);
        } else {
            email.setSubject('Nebenkostenzuschuss');
            email.setPlainTextBody('Informationen zum Nebenkostenzuschuss.');
        }

        email.setTargetObjectId(opp.Vertriebskoordinator__c);
        email.setWhatId(opp.Id);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });
        email.setSaveAsActivity(true);

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email }, false);

        /* =========================
           FILE STORAGE
           ========================= */
        ContentVersion file = new ContentVersion();
        file.VersionData     = pdfBody;
        file.Title           = fileName;
        file.PathOnClient    = fileName;
        file.ContentLocation = 's';
        file.Typ__c = 'Nebenkostenzuschuss';
        file.RecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('VKC').getRecordTypeId();

        insert file;

        ContentVersion storedFile = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id = :file.Id
            LIMIT 1
        ];

        ContentDocumentLink link = new ContentDocumentLink();
        link.ContentDocumentId = storedFile.ContentDocumentId;
        link.LinkedEntityId    = opp.Id;
        link.ShareType         = 'V';
        link.Visibility        = 'AllUsers';

        insert link;
    }
}