force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Additional_Costs__c.field-meta.xml
<CustomField>
    <fullName>Additional_Costs__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Inaktives Feld - kundenspezifische Incentivierung bitte künftig auf der VKC direkt hinterlegen.</inlineHelpText>
    <label>Additional Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <label>Additional Broker Commission</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Jahresmiete__c.field-meta.xml
<CustomField>
    <fullName>Jahresmiete__c</fullName>
    <formula>Monthly_Rent__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Jahresmiete</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/KaufpreisIst__c.field-meta.xml
<CustomField>
    <fullName>KaufpreisIst__c</fullName>
    <formula>IF(!IsBlank(beurkundeter_Kaufpreis__c) &amp;&amp; TEXT(Status__c) = &apos;Sold&apos;,  beurkundeter_Kaufpreis__c,  Purchase_Price__c)</formula>
    <label>Kaufpreis Ist</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/MaklerprovisionNetto__c.field-meta.xml
<CustomField>
    <fullName>MaklerprovisionNetto__c</fullName>
    <label>Maklerprovision Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/MarketingzuschussNetto__c.field-meta.xml
<CustomField>
    <fullName>MarketingzuschussNetto__c</fullName>
    <label>Marketingzuschuss Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Monthly_Rent__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Rent</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Purchase Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kontingent</fullName>
            </value>
            <value>
                <fullName>Reservierungsvorbereitung</fullName>
            </value>
            <value>
                <fullName>Reservierung angefragt</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsangebot abgegeben</fullName>
            </value>
            <value>
                <fullName>KV wird fremd abgegeben</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsunterlagen verschickt -zweiseitig-</fullName>
            </value>
            <value>
                <fullName>Auftrag zur Beurkundung vorhanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gutschrift__c/Gutschrift__c.object-meta.xml
<CustomObject>
    <label>Gutschrift</label>
    <nameField>
        <label>Gutschrift-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gutschrift__c/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Incentivierung Makler</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/GutschriftStorniert__c.field-meta.xml
<CustomField>
    <fullName>GutschriftStorniert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift storniert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Objekt__c.field-meta.xml
<CustomField>
    <fullName>Objekt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objekt</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Gutschriften</relationshipLabel>
    <relationshipName>Gutschriften</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provision</label>
    <referenceTo>Provision__c</referenceTo>
    <relationshipLabel>Gutschriften</relationshipLabel>
    <relationshipName>Gutschriften</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/WertMarketingzuschuss__c.field-meta.xml
<CustomField>
    <fullName>WertMarketingzuschuss__c</fullName>
    <label>Wert Marketingzuschuss</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Additional_Costs__c.field-meta.xml
<CustomField>
    <fullName>Additional_Costs__c</fullName>
    <formula>Real_Estate_Transfer_Tax_1__c + Notary_And_Court_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Additional Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt (aus Teilobjekt)</label>
    <summarizedField>Appartment__c.Bezahlt__c</summarizedField>
    <summaryForeignKey>Appartment__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/IncentivierungKundeIst__c.field-meta.xml
<CustomField>
    <fullName>IncentivierungKundeIst__c</fullName>
    <label>Incentivierung Kunde Ist</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/IncentivierungMaklerNetto__c.field-meta.xml
<CustomField>
    <fullName>IncentivierungMaklerNetto__c</fullName>
    <label>Incentivierung Makler Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/MaklerprovisionGezahltBrutto__c.field-meta.xml
<CustomField>
    <fullName>MaklerprovisionGezahltBrutto__c</fullName>
    <label>Maklerprovision gezahlt Brutto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/MaklerprovisionNetto__c.field-meta.xml
<CustomField>
    <fullName>MaklerprovisionNetto__c</fullName>
    <label>Maklerprovision Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/MarketingzuschussGezahltBrutto__c.field-meta.xml
<CustomField>
    <fullName>MarketingzuschussGezahltBrutto__c</fullName>
    <label>Marketingzuschuss gezahlt Brutto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/MarketingzuschussNetto__c.field-meta.xml
<CustomField>
    <fullName>MarketingzuschussNetto__c</fullName>
    <label>Marketingzuschuss Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/MonatsmieteBeiVerkauf__c.field-meta.xml
<CustomField>
    <fullName>MonatsmieteBeiVerkauf__c</fullName>
    <label>Monatsmiete bei Verkauf</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Price__c.field-meta.xml
<CustomField>
    <fullName>Property_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Verkaufsvolumen Plan</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/VerkaufsvolumenIst__c.field-meta.xml
<CustomField>
    <fullName>VerkaufsvolumenIst__c</fullName>
    <label>Verkaufsvolumen Ist</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Incentivierung Makler</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/GutschriftStorniert__c.field-meta.xml
<CustomField>
    <fullName>GutschriftStorniert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift storniert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Objekt__c.field-meta.xml
<CustomField>
    <fullName>Objekt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objekt</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Zahlungsstatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Offen</fullName>
                <default>true</default>
                <label>Offen</label>
            </value>
            <value>
                <fullName>Im nächsten Zahlungslauf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Nettobetrag</inlineHelpText>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/WertMarketingzuschuss__c.field-meta.xml
<CustomField>
    <fullName>WertMarketingzuschuss__c</fullName>
    <inlineHelpText>Nettobetrag</inlineHelpText>
    <label>Wert Marketingzuschuss</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BatchAggregateImmos.cls
public with sharing class BatchAggregateImmos implements Database.Batchable<SObject>, Schedulable {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM Property__c WHERE Id IN (SELECT Property__c FROM Appartment__c)]);
    }

    public void execute(Database.BatchableContext bc, List<Property__c> scope) {
        for(Property__c property:scope) {
            BatchAggregateImmos.updateImmos(property.Id);
        }
    }

    public static void updateImmos(Id propertyId) {
        Map<Id, Property__c> properties = new Map<Id, Property__c>();

        for(AggregateResult agRes : [SELECT SUM(MaklerprovisionNetto__c) maklerprovisionNetto, SUM(MarketingzuschussNetto__c) marketingzuschussNetto, SUM(AdditionalBrokerCommission__c) incentivierungMaklerNetto, SUM(Additional_Costs__c) incentivierungKunde,  Property__c propertyId FROM Appartment__c WHERE Status__c = 'Sold' AND Property__c = :propertyId GROUP BY Property__c]) {
            Property__c property = properties.get(propertyId);

            if(property == null) {
                property = new Property__c(Id = propertyId);
            }
            property.MarketingzuschussNetto__c = (Decimal)agRes.get('marketingzuschussNetto');
            property.MaklerprovisionNetto__c = (Decimal)agRes.get('maklerprovisionNetto');
            property.IncentivierungMaklerNetto__c = (Decimal) agRes.get('incentivierungMaklerNetto');
            property.IncentivierungKundeIst__c = (Decimal) agRes.get('incentivierungKunde');
            properties.put(propertyId, property);
        }

        for(AggregateResult agRes : [SELECT SUM(Monthly_Rent__c) monatsMiete, SUM(Jahresmiete__c) jahresMiete, SUM(KaufpreisIst__c) kaufpreisIst, SUM(Purchase_Price__c) kaufpreisPlan, Property__c propertyId FROM Appartment__c WHERE Property__c = :propertyId GROUP BY Property__c]) {
            Property__c property = properties.get(propertyId);

            if(property == null) {
                property = new Property__c(Id = propertyId);
            }
            property.MonatsmieteBeiVerkauf__c = (Decimal) agRes.get('monatsMiete');
            property.VerkaufsvolumenIst__c = (Decimal) agRes.get('kaufpreisIst');
            property.Property_Price__c = (Decimal) agRes.get('kaufpreisPlan');
            properties.put(propertyId, property);
        }

        for(AggregateResult agRes : [SELECT SUM(Wert_Maklerprovision__c) maklerprovisionNetto, SUM(WertMarketingzuschuss__c) marketingzuschussNetto, Provision__r.Objekt__c propertyId FROM Gutschrift__c WHERE GutschriftStorniert__c = false AND Bezahlt__c = true AND Provision__r.Objekt__c = :propertyId GROUP BY Provision__r.Objekt__c]) {
            Property__c property = properties.get(propertyId);

            if(property == null) {
                property = new Property__c(Id = propertyId);
            }
            property.MarketingzuschussGezahltBrutto__c = ((Decimal)agRes.get('marketingzuschussNetto'))*1.19;
            property.MaklerprovisionGezahltBrutto__c = ((Decimal)agRes.get('maklerprovisionNetto'))*1.19;
            properties.put(propertyId, property);
        }

        update properties.values();
    }

    public void finish(Database.BatchableContext bc) {

    }
    
    public void execute(System.SchedulableContext ctx) {
        Database.executeBatch(new BatchAggregateImmos(), 1);
    }
}