force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Art__c.field-meta.xml
<CustomField>
    <fullName>Art__c</fullName>
    <formula>IF( TEXT(Property__r.Art_der_Teilobjekte__c) = &apos;Appartements&apos;, &apos;Appartement&apos;, 
IF( TEXT(Property__r.Art_der_Teilobjekte__c) = &apos;Wohnungen&apos;, &apos;Wohnung&apos;,
IF( TEXT(Property__r.Art_der_Teilobjekte__c) = &apos;Häuser&apos;, &apos;Haus&apos;,
IF( TEXT(Property__r.Art_der_Teilobjekte__c) = &apos;Ferienwohnungen&apos;, &apos;Ferienwohnung&apos;, &apos;&apos;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Art</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Gesamtkosten__c.field-meta.xml
<CustomField>
    <fullName>Gesamtkosten__c</fullName>
    <formula>Purchase_Price__c +   Property__r.Real_Estate_Transfer_Tax__c  * Purchase_Price__c + Purchase_Price__c *  Property__r.Notary_And_Court_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gesamtkosten</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Repayment_Beginning__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Beginning__c</fullName>
    <label>Repayment Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/Berechnung__c.object-meta.xml
<CustomObject>
    <label>Berechnung</label>
    <nameField>
        <label>Berechnung Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Berechnung__c/fields/Eigenkapital__c.field-meta.xml
<CustomField>
    <fullName>Eigenkapital__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Eigenkapital</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/ErsterKaeufer__c.field-meta.xml
<CustomField>
    <fullName>ErsterKaeufer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Berechnungen (1. Käufer)</relationshipLabel>
    <relationshipName>Berechnungen1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/Finanzierungsart__c.field-meta.xml
<CustomField>
    <fullName>Finanzierungsart__c</fullName>
    <formula>IF( Kreditsumme__c &gt; 0, &apos;Finanzierung&apos;, &apos;Bar&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finanzierungsart</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/Gesamtkosten__c.field-meta.xml
<CustomField>
    <fullName>Gesamtkosten__c</fullName>
    <formula>ListenpreisGesamt__c +  NotarUndGerichtskostenGesamt__c +  GrunderwerbsteuerGesamt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gesamtkosten</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/Hauptimmobilie__c.field-meta.xml
<CustomField>
    <fullName>Hauptimmobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hauptimmobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Berechnungen</relationshipLabel>
    <relationshipName>Berechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/Kreditsumme__c.field-meta.xml
<CustomField>
    <fullName>Kreditsumme__c</fullName>
    <label>Kreditsumme</label>
    <summarizedField>Finanzierungsbaustein__c.Kreditsumme__c</summarizedField>
    <summaryFilterItems>
        <field>Finanzierungsbaustein__c.Art__c</field>
        <operation>notEqual</operation>
        <value>Eigenkapital</value>
    </summaryFilterItems>
    <summaryForeignKey>Finanzierungsbaustein__c.Berechnung__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/ListenpreisGesamt__c.field-meta.xml
<CustomField>
    <fullName>ListenpreisGesamt__c</fullName>
    <label>Listenpreis gesamt</label>
    <summarizedField>BerechnungsApartment__c.Listenpreis__c</summarizedField>
    <summaryForeignKey>BerechnungsApartment__c.Berechnung__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/NebenkostenGesamt__c.field-meta.xml
<CustomField>
    <fullName>NebenkostenGesamt__c</fullName>
    <formula>GrunderwerbsteuerGesamt__c +  NotarUndGerichtskostenGesamt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nebenkosten Gesamt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/ZweiterKaeufer__c.field-meta.xml
<CustomField>
    <fullName>ZweiterKaeufer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Berechnungen (Zweiter Käufer)</relationshipLabel>
    <relationshipName>Berechnungen2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/BerechnungsApartment__c.object-meta.xml
<CustomObject>
    <label>Berechnungs-Apartment</label>
    <nameField>
        <label>Berechnungs-Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungs-Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BerechnungsApartment__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Berechnungs-Apartments</relationshipLabel>
    <relationshipName>Berechnungs_Apartments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/fields/Berechnung__c.field-meta.xml
<CustomField>
    <fullName>Berechnung__c</fullName>
    <label>Berechnung</label>
    <referenceTo>Berechnung__c</referenceTo>
    <relationshipLabel>Berechnungs-Apartments</relationshipLabel>
    <relationshipName>Berechnungs_Apartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/fields/Eigenkapital__c.field-meta.xml
<CustomField>
    <fullName>Eigenkapital__c</fullName>
    <label>Eigenkapital</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/fields/Gesamtkosten__c.field-meta.xml
<CustomField>
    <fullName>Gesamtkosten__c</fullName>
    <formula>Listenpreis__c +   PriceAdjustment__c + GrunderwerbsteuerInEuro__c  +  NotarUndGerichtskostenInEuro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gesamtkosten</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Berechnungs-Apartments</relationshipLabel>
    <relationshipName>Berechnungs_Apartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/fields/Listenpreis__c.field-meta.xml
<CustomField>
    <fullName>Listenpreis__c</fullName>
    <label>Listenpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/fields/NebenkostenInEuro__c.field-meta.xml
<CustomField>
    <fullName>NebenkostenInEuro__c</fullName>
    <formula>GrunderwerbsteuerInEuro__c +  NotarUndGerichtskostenInEuro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nebenkosten in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/Finanzierungsbaustein__c.object-meta.xml
<CustomObject>
    <label>Finanzierungsbaustein</label>
    <nameField>
        <label>Finanzierungsbaustein Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finanzierungsbausteine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/Art__c.field-meta.xml
<CustomField>
    <fullName>Art__c</fullName>
    <label>Art</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annuitäten Darlehen</fullName>
                <default>true</default>
                <label>Annuitäten Darlehen</label>
            </value>
            <value>
                <fullName>Endfälliges Darlehen</fullName>
            </value>
            <value>
                <fullName>KfW Darlehen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/Berechnung__c.field-meta.xml
<CustomField>
    <fullName>Berechnung__c</fullName>
    <label>Berechnung</label>
    <referenceTo>Berechnung__c</referenceTo>
    <relationshipLabel>Finanzierungsbausteine</relationshipLabel>
    <relationshipName>Finanzierungsbausteine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/BerechnungsApartment__c.field-meta.xml
<CustomField>
    <fullName>BerechnungsApartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Berechnungs-Apartment</label>
    <referenceTo>BerechnungsApartment__c</referenceTo>
    <relationshipLabel>Finanzierungsbausteine</relationshipLabel>
    <relationshipName>Finanzierungsbausteine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/Kreditsumme__c.field-meta.xml
<CustomField>
    <fullName>Kreditsumme__c</fullName>
    <label>Kreditsumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/TilgungInPercent__c.field-meta.xml
<CustomField>
    <fullName>TilgungInPercent__c</fullName>
    <label>Tilgung in %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/ZinsInPercent__c.field-meta.xml
<CustomField>
    <fullName>ZinsInPercent__c</fullName>
    <label>Zins in %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Hauptimmobilie__c.field-meta.xml
<CustomField>
    <fullName>Hauptimmobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hauptimmobilie</label>
    <referenceTo>Hauptimmobilie__c</referenceTo>
    <relationshipLabel>Immobilien</relationshipLabel>
    <relationshipName>Immobilien</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Repayment_Beginning__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Beginning__c</fullName>
    <label>Repayment Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sondertilgung__c/Sondertilgung__c.object-meta.xml
<CustomObject>
    <label>Sondertilgung</label>
    <nameField>
        <label>Sondertilgung Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sondertilgungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sondertilgung__c/fields/Finanzierungsbaustein__c.field-meta.xml
<CustomField>
    <fullName>Finanzierungsbaustein__c</fullName>
    <label>Finanzierungsbaustein</label>
    <referenceTo>Finanzierungsbaustein__c</referenceTo>
    <relationshipLabel>Sondertilgungen</relationshipLabel>
    <relationshipName>Sondertilgungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Verkaufsraum__c/Verkaufsraum__c.object-meta.xml
<CustomObject>
    <label>Kundenakte</label>
    <nameField>
        <label>Verkaufsraum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kundenakten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verkaufsraum__c/fields/ErsterKaeufer__c.field-meta.xml
<CustomField>
    <fullName>ErsterKaeufer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>1. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>VerkaufsraeumeErsterKaeufer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verkaufsraum__c/fields/ZweiterKaeufer__c.field-meta.xml
<CustomField>
    <fullName>ZweiterKaeufer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>VerkaufsraeumeZweiterKaeufer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BerechnungController.cls
public without sharing class BerechnungController {

    @AuraEnabled
    public static void insertBerechnungsApartments(List<BerechnungsApartment__c> berechnungsApartments) {
        Database.SaveResult[] results = Database.insert(berechnungsApartments);
    }

    @AuraEnabled 
    public static void insertFinanzierungsBausteine(List<Finanzierungsbaustein__c> finanzierungsBausteine) {
        Database.SaveResult[] results = Database.insert(finanzierungsBausteine);
    }

    @AuraEnabled
    public static void deleteBerechnungsApartments(List<Id> deletedIds) {
        delete [SELECT ID FROM BerechnungsApartment__c WHERE Id IN :deletedIds];
    }

     @AuraEnabled
     public static void insertBerechnungWithApartments(Id berechnungId, List<BerechnungsApartment__c> berechnungsApartments) {
         for(BerechnungsApartment__c ba:berechnungsApartments) {
             ba.Berechnung__c = berechnungId;
         }
         insert berechnungsApartments;
    }

    @AuraEnabled
    public static void deleteFinanzierungsBausteine(List<Id> deletedIds) {
        delete [SELECT ID FROM FinanzierungsBaustein__c WHERE Id IN :deletedIds];
    }

    @AuraEnabled(cacheable=true)
    public static Berechnung__c getBerechnung(Id recordId) {
        List<Berechnung__c> berechnungen = [SELECT Id, KreditSumme__c, Finanzierungsart__c, Hauptimmobilie__r.Repayment_Beginning__c, Hauptimmobilie__c, Hauptimmobilie__r.Name, Eigenkapital__c, Gesamtkosten__c, NebenkostenGesamt__c, ListenpreisGesamt__c, ErsterKaeufer__c, ZweiterKaeufer__c, Name, (SELECT Id, Name, Apartment__c, Apartment__r.Name, Listenpreis__c, Gesamtkosten__c, NebenkostenInEuro__c, Immobilie__c, Immobilie__r.Name FROM Berechnungs_Apartments__r ORDER BY Name ASC), (SELECT Id, Name, Art__c, Kreditsumme__c, TilgungInPercent__c, ZinsInPercent__c, TilgungProMonatInEuro__c, ZinsProMonatInEuro__c, IstEigenkapitalBaustein__c FROM Finanzierungsbausteine__r) FROM Berechnung__C WHERE Id =: recordId];
        if(berechnungen.size() == 1) {
            return berechnungen[0];
        }
        Berechnung__c berechnung = new Berechnung__c();
        return berechnung;
    }

    @AuraEnabled(cacheable=true)
    public static Finanzierungsbaustein__c getFinanzierungsbaustein(Id recordId) {
        List<Finanzierungsbaustein__c> finanzierungsbausteine = [SELECT Id, Name, Art__c, Berechnung__r.Kreditsumme__c, Berechnung__r.Gesamtkosten__c, Berechnung__r.Eigenkapital__c, Kreditsumme__c, TilgungInPercent__c, ZinsInPercent__c, TilgungProMonatInEuro__c, ZinsProMonatInEuro__c, Zinsfestschreibung__c, FesteLaufzeit__c, (SELECT Id, JahrDerAuszahlung__c, Betrag__c, Prozent__c, Name FROM Sondertilgungen__r) FROM Finanzierungsbaustein__c WHERE Id = :recordId];
        if(finanzierungsbausteine.size() >= 1) {
            return finanzierungsbausteine[0];
        }
        Finanzierungsbaustein__c finanzierungsbaustein = new Finanzierungsbaustein__c();
        return finanzierungsbaustein;
    }

    @AuraEnabled(Cacheable=true)
    public static Berechnung__c[] getBerechnungSave() {
        Id userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        Profile pf = [SELECT Name FROM Profile WHERE Id = :profileId];
        User usr = [SELECT ContactId, AccountId FROM User WHERE Id = :userId];
        Id conId = usr.ContactId;
        Id accId = usr.AccountId;
        List<Berechnung__c> berechnungen = new List<Berechnung__c>();
        if(conId == null) {
            
        } else if (pf.Name.contains('Manager')) {
            berechnungen = [
                SELECT Name, ErsterKaeufer__r.Name, ZweiterKaeufer__r.Name, Verkaufsraum__r.Name, createdDate, Id, (SELECT Name, Id FROM Berechnungs_Apartments__r)
                FROM Berechnung__c WHERE Makler__r.AccountId = :accId
            ];
        } else {
            berechnungen = [
                SELECT Name, ErsterKaeufer__r.Name, ZweiterKaeufer__r.Name, Verkaufsraum__r.Name, createdDate, Id, (SELECT Name, Id FROM Berechnungs_Apartments__r)
                FROM Berechnung__c WHERE Makler__c = :conId
            ];
        }

        return berechnungen;
    }

    @AuraEnabled(Cacheable=true)
    public static Berechnung__c[] getBerechnungSaveWithId(Id berechnungId) {
    List<Berechnung__c> berechnungSaveWithId = new List<Berechnung__c>();
        berechnungSaveWithId = [
            SELECT Id, (SELECT Name, Apartment__c FROM Berechnungs_Apartments__r)
            FROM Berechnung__c
            WHERE Id = :berechnungId
        ];
        return berechnungSaveWithId;
    }
}