force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Carestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Provisionssumme__c.field-meta.xml
<CustomField>
    <fullName>Provisionssumme__c</fullName>
    <label>Provisionssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Beratungsprotokoll__c.field-meta.xml
<CustomField>
    <fullName>Beratungsprotokoll__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Beratungsprotokoll</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finanzierung_oder_Eigenkapitalnachweis__c.field-meta.xml
<CustomField>
    <fullName>Finanzierung_oder_Eigenkapitalnachweis__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FB Bank liegt vor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis__c</fullName>
    <formula>IF( Appartement__r.DeviatingPurchasePrice__c != 0 &amp;&amp; !IsBlank(Appartement__r.DeviatingPurchasePrice__c), Appartement__r.DeviatingPurchasePrice__c, Appartement__r.Purchase_Price__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listenpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KV_eingegangen__c.field-meta.xml
<CustomField>
    <fullName>KV_eingegangen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>KV eingegangen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Letztes_Phasenupdate_am__c.field-meta.xml
<CustomField>
    <fullName>Letztes_Phasenupdate_am__c</fullName>
    <label>Letztes Phasenupdate am</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maklerbetreuer_WirtschaftsHaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_WirtschaftsHaus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Ist_Maklerbetreuer_WH__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Maklerbetreuer WirtschaftsHaus)</relationshipLabel>
    <relationshipName>Maklerbetreuer_Wirtschaftshaus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nachweis_Barzahler__c.field-meta.xml
<CustomField>
    <fullName>Nachweis_Barzahler__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EK-Nachweis liegt vor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <inlineHelpText>Wichtig: Dies ist das Datum der ursprünglichen Vertragsunterzeichnung seitens des Kunden.</inlineHelpText>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Overhead_Empf_nger__c.field-meta.xml
<CustomField>
    <fullName>Overhead_Empf_nger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overhead Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Overhead Empfänger)</relationshipLabel>
    <relationshipName>Overhead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provisionssumme__c.field-meta.xml
<CustomField>
    <fullName>Provisionssumme__c</fullName>
    <label>Provisionssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reservierungsschein_vorhanden__c.field-meta.xml
<CustomField>
    <fullName>Reservierungsschein_vorhanden__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reservierungsschein vorhanden</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Risikobelehrung__c.field-meta.xml
<CustomField>
    <fullName>Risikobelehrung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Risikobelehrung</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TippgeberProvisionEmpfaenger__c.field-meta.xml
<CustomField>
    <fullName>TippgeberProvisionEmpfaenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tippgeber Provision Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Verkaufschancen (Tippgeber Provision Empfänger)</relationshipLabel>
    <relationshipName>TippgeberOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Ausl_ser__c.field-meta.xml
<CustomField>
    <fullName>Ausl_ser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Auslöser</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen (Auslöser)</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis__c</fullName>
    <label>Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <formula>Verkaufschance__r.Notartermin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Objekt__c.field-meta.xml
<CustomField>
    <fullName>Objekt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objekt</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Provision_in__c.field-meta.xml
<CustomField>
    <fullName>Provision_in__c</fullName>
    <formula>Provisionssumme__c /  Kaufpreis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provision in % m. LNK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Provisionssumme__c.field-meta.xml
<CustomField>
    <fullName>Provisionssumme__c</fullName>
    <formula>Wert_Verk_ufer_Beratungsprovision_o_R__c +  Wert_Verk_ufer_Beratungsprovision_m_R__c +  Wert_Sonstige_2__c +  Wert_Sonstige_1__c +  Wert_Referentenverg_tung__c +  Wert_Differenzprovision__c +  Wert_Beteiligung_SMB_an_JMB__c +  TA_Beteiligung__c +  JMB_Beteiligung__c +  Erfolgsabh_ngige_Provision_direkt__c +  Erfolgsabh_ngige_Provision_indirekt__c +  Direktverkauf_Provision__c +  Wert_Tippprovision__c +  Wert_Overhead__c +  Wert_Maklerprovision__c +  WertMarketingzuschuss__c + AdditionalBrokerCommission__c +  BeratungsprovisionMitPVInEuro__c +  ClosingBonusInEuro__c + ProvisionVertriebskoordination__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provisionssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Wohneinheit__c.field-meta.xml
<CustomField>
    <fullName>Wohneinheit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wohneinheit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Objekt__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestOpportunitiesWithProvision.cls
@RestResource(urlMapping='/OpportunitiesWithProvision')
global with sharing class RestOpportunitiesWithProvision  {
    @HttpPost
    global static List<Opportunity> showOpportunities(Id accId, Id maklerId) {
        if(maklerId != null) {
            return getOpps(accId, maklerId);
        } 
        return getOpps(accId);
    }
    
    static List<Opportunity> getOpps(Id accId, Id maklerId) {
        List<Opportunity> oppsWithProvision = [SELECT Name, Potenzieller_Kunde__c, Potenzieller_Kunde__r.FirstName, Potenzieller_Kunde__r.LastName, Immobilie__r.Name, Appartement__r.Name, CreatedDate, Letztes_Phasenupdate_am__c, StageName, Kaufpreis__c, Reservierungsschein_vorhanden__c, Finanzierung_oder_Eigenkapitalnachweis__c, Nachweis_Barzahler__c, Risikobelehrung__c, Makler__r.FirstName, Makler__r.LastName, Notartermin__c, Beratungsprotokoll__c, KV_eingegangen__c, (SELECT Id, Provisionssumme__c, Provision_in__c, Makler__r.FirstName, Makler__r.LastName FROM Provisionen__r WHERE Makler__r.AccountId = : accId OR Makler__c = :maklerId) FROM Opportunity WHERE AccountId = :accId OR Immobilienberater__c = :maklerId OR TippgeberProvisionEmpfaenger__c = :maklerId OR Overhead_Empf_nger__c = :maklerId OR Maklerbetreuer_wirtschaftshaus__c = :maklerId];
        return oppsWithProvision;
    }
    
    static List<Opportunity> getOpps(Id accId) {
        List<Opportunity> oppsWithProvision = [SELECT Name, Potenzieller_Kunde__c, Potenzieller_Kunde__r.FirstName, Potenzieller_Kunde__r.LastName, Immobilie__r.Name, Appartement__r.Name, CreatedDate, Letztes_Phasenupdate_am__c, StageName, Kaufpreis__c, Reservierungsschein_vorhanden__c, Finanzierung_oder_Eigenkapitalnachweis__c, Nachweis_Barzahler__c, Risikobelehrung__c, Makler__r.FirstName, Makler__r.LastName, Notartermin__c, Beratungsprotokoll__c, KV_eingegangen__c, (SELECT Id, Provisionssumme__c, Provision_in__c, Makler__r.FirstName, Makler__r.LastName FROM Provisionen__r WHERE Makler__r.AccountId = : accId) FROM Opportunity WHERE AccountId = :accId];
        return oppsWithProvision;
    }
}