force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <label>Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <formula>Maklerprovision_nach_Nachtrag__c/100*Provisionsbasis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Verk_ufer_Beratungsprovision_m_R__c.field-meta.xml
<CustomField>
    <fullName>Wert_Verk_ufer_Beratungsprovision_m_R__c</fullName>
    <formula>if (!ISBLANK(Verkaufsprovision_nach_Nachtrag__c), Verkaufsprovision_nach_Nachtrag__c / 100 * Provisionsbasis__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Verkäufer-/Beratungsprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Nettobetrag</inlineHelpText>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Wert_Verk_ufer_Beratungsprovision_m_R__c.field-meta.xml
<CustomField>
    <fullName>Wert_Verk_ufer_Beratungsprovision_m_R__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Beratungsprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApprovalController.cls
public without sharing class ApprovalController {
    
    @AuraEnabled(cacheable=true)
    public static List<ProvisionApproval> getProvisionApprovals() {
        Id userId = UserInfo.getUserId();
        List<ProcessInstanceWorkitem> workItems = [Select p.Id, p.ProcessInstance.TargetObjectId from ProcessInstanceWorkitem p where ActorId = :userId];
        List<Id> targetObjectIds = new List<Id>();
        for(ProcessInstanceWorkItem workItem:workItems) {
            targetObjectIds.add(workItem.ProcessInstance.TargetObjectId);
        }

        Map<Id, Provision__c> provs = new Map<Id, Provision__c>([SELECT Name, Wert_Maklerprovision__c, Wert_Verk_ufer_Beratungsprovision_m_R__c, Verkaufschance__r.Immobilie__r.Name, Verkaufschance__r.Appartement__r.Name FROM Provision__c WHERE ID IN :targetObjectIds]);

        List<ProvisionApproval> provApprovals = new List<ProvisionApproval>();

        for(ProcessInstanceWorkItem workItem:workItems) { 
            Provision__c p = provs.get(workItem.ProcessInstance.TargetObjectId);
            ProvisionApproval pa = new ProvisionApproval(workItem.Id, p.Name, p.Wert_Maklerprovision__c, p.Wert_Verk_ufer_Beratungsprovision_m_R__c, p.Verkaufschance__r.Immobilie__r.Name, p.Verkaufschance__r.Appartement__r.Name);
            provApprovals.add(pa);
        }
        
        return provApprovals;
    }

    @AuraEnabled
    public static void approveProvision(Id workItemId) {
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Vom Makler über das Vertriebsportal genehmigt.');
        req.setAction('Approve');
        req.setWorkitemId(workItemId);
        Approval.process(req);
    }

    @AuraEnabled 
    public static void rejectProvision(Id workItemId) {
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Vom Makler über das Vertriebsportal abgelehnt.');
        req.setAction('Reject');
        req.setWorkitemId(workItemId);
        Approval.process(req);
    }

    public class ProvisionApproval {
        @AuraEnabled
        public String workItemId{get;set;}
        @AuraEnabled
        public String name{get;set;}
        @AuraEnabled
        public Decimal maklerProv{get;set;}
        @AuraEnabled
        public Decimal beratungProv{get;set;}
        @AuraEnabled
        public String immobilieName{get;set;}
        @AuraEnabled
        public String apartmentName{get;set;}

        public ProvisionApproval(String workItemId, String name, Decimal maklerProv, Decimal beratungProv, String immobilieName, String apartmentName) {
            this.workItemId = workItemId;
            this.name = name;
            this.maklerProv = maklerProv;
            this.beratungProv = beratungProv;
            this.immobilieName = immobilieName;
            this.apartmentName = apartmentName;
        }
    }

}