force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/OffenerBetrag__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetrag__c</fullName>
    <formula>IF( OeffentlicherStatus__c = &apos;Verkauft&apos; &amp;&amp;  KaufpreisFaellig__c,
			IF(Bezahlt__c &gt; 0,
						beurkundeter_Kaufpreis__c - Bezahlt__c, 
						IF(MaBVBezahlt__c &gt; 0,
									beurkundeter_Kaufpreis__c - MaBVBezahlt__c,
									beurkundeter_Kaufpreis__c
						)
					),
			0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AbgerechneterBetrag__c.field-meta.xml
<CustomField>
    <fullName>AbgerechneterBetrag__c</fullName>
    <formula>IF(
    IsWon,
				IF((ISPICKVAL(Immobilie__r.Kaufpreiszahlung__c, &apos;Endfällig&apos;) || ISPICKVAL(Immobilie__r.Kaufpreiszahlung__c, &apos;Externes Vertriebsprojekt (Endfällig)&apos;)) &amp;&amp; (Datum_Kaufpreisf_lligkeitsschreiben__c &lt;= TODAY() || Kaufpreis_bezahlt__c),  
				    beurkundeter_Kaufpreis__c,
							 AbgerechneterBetragMaBV__c 
				)
				, 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Abgerechneter Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>VkcZahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>VkcZahlung__c.Verkaufschance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Datum_Kaufpreisf_lligkeitsschreiben__c.field-meta.xml
<CustomField>
    <fullName>Datum_Kaufpreisf_lligkeitsschreiben__c</fullName>
    <label>Datum Kaufpreisfälligkeitsschreiben</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HatVKCZahlungen__c.field-meta.xml
<CustomField>
    <fullName>HatVKCZahlungen__c</fullName>
    <formula>AnzahlVKCZahlungen__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hat VKC Zahlungen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IncentivierungGesamt__c.field-meta.xml
<CustomField>
    <fullName>IncentivierungGesamt__c</fullName>
    <formula>AdditionalBrokerCommission__c + AdditionalCosts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incentivierung gesamt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufpreis_bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis_bezahlt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kaufpreis bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OffenerBetrag__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetrag__c</fullName>
    <formula>IF(
 Kaufpreis_bezahlt__c,
	0, 
IF(Datum_Kaufpreisf_lligkeitsschreiben__c &lt;= TODAY(), IF(ISPICKVAL(Immobilie__r.Kaufpreiszahlung__c, &apos;Endfällig&apos;) || HatVKCZahlungen__c || ISPICKVAL(Immobilie__r.Kaufpreiszahlung__c, &apos;Externes Vertriebsprojekt (Endfällig)&apos;), beurkundeter_Kaufpreis__c -  Bezahlt__c, OffenerBetragMaBV__c), 0)			
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/AbgerechneteEinmalzahlungen__c.field-meta.xml
<CustomField>
    <fullName>AbgerechneteEinmalzahlungen__c</fullName>
    <label>Abgerechnete Einmalzahlungen</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/AbgerechneterBetrag__c.field-meta.xml
<CustomField>
    <fullName>AbgerechneterBetrag__c</fullName>
    <formula>IF(!ISBLANK(MaBVAbgerechnet__c), MaBVAbgerechnet__c, 0) + IF(!ISBLANK(AbgerechneteEinmalzahlungen__c),AbgerechneteEinmalzahlungen__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Abgerechneter Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt (aus Teilobjekt)</label>
    <summarizedField>Appartment__c.Bezahlt__c</summarizedField>
    <summaryForeignKey>Appartment__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/IncentivierungIST__c.field-meta.xml
<CustomField>
    <fullName>IncentivierungIST__c</fullName>
    <label>Incentivierung IST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Kaufpreiszahlung__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreiszahlung__c</fullName>
    <label>Kaufpreiszahlung</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MaBV</fullName>
            </value>
            <value>
                <fullName>Endfällig</fullName>
            </value>
            <value>
                <fullName>Externes Vertriebsprojekt (MaBV)</fullName>
            </value>
            <value>
                <fullName>Externes Vertriebsprojekt (Endfällig)</fullName>
            </value>
            <value>
                <fullName>Bestand</fullName>
                <isActive>false</isActive>
                <label>Bestand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/OffenerBetragEinmalzahlungen__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragEinmalzahlungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offener Betrag (Einmalzahlungen Gesamt)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AggregateVkcZahlungPaymentDataQueueable.cls
public without sharing class AggregateVkcZahlungPaymentDataQueueable implements Queueable {
    
    Set<Id> opportunityIds = new Set<Id>();

    public AggregateVkcZahlungPaymentDataQueueable(Set<Id> opportunityIds) {
        this.opportunityIds = opportunityIds;
    }

    public void execute(QueueableContext ctx) {
        Map<Id,Property__c> mapImmobilienByIds = new Map<Id,Property__c>([SELECT Id FROM Property__c WHERE Id IN (SELECT Immobilie__c FROM Opportunity WHERE Id IN :this.opportunityIds)]);
        Map<Id,Appartment__c> mapTeilobjekteByIds = new Map<Id,Appartment__c>([SELECT Id FROM Appartment__c WHERE Id IN (SELECT Appartement__c FROM Opportunity WHERE Id IN :this.opportunityIds)]);

        updateImmobilien(mapImmobilienByIds.keySet());
        updateImmobilien2(mapImmobilienByIds.keySet());

        List<Appartment__c> teilobjekte = new List<Appartment__c>();
        for(AggregateResult agRes : [SELECT SUM(Bezahlt__c) bezahlt, Appartement__c teilobjektId FROM Opportunity WHERE Appartement__c IN :mapTeilobjekteByIds.keySet() AND HatVKCZahlungen__c = true AND (IsWon = true OR StageName = 'Notartermin hat stattgefunden') GROUP BY Appartement__c]) {
            Id teilobjektId = (Id) agRes.get('teilobjektId');
            Double bezahlt = (Double) agRes.get('bezahlt');

            Appartment__c teilobjekt = new Appartment__c(Id = teilobjektId);
            teilobjekt.Bezahlt__c = bezahlt;
            teilobjekte.add(teilobjekt);
        }
        update teilobjekte;
    }

    public static void updateImmobilien(Set<Id> immoIds) {
        List<Property__c> immobilien = new List<Property__c>();
        for(AggregateResult agRes : [SELECT SUM(OffenerBetrag__c) offen, SUM(AbgerechneterBetrag__c) abgerechnet, Immobilie__c immoId FROM Opportunity WHERE Immobilie__c IN :immoIds AND (Datum_Kaufpreisf_lligkeitsschreiben__c <= TODAY OR Kaufpreis_bezahlt__c = true) AND (HatVKCZahlungen__c = true OR Immobilie__r.Kaufpreiszahlung__c = 'Endfällig') AND (IsWon = true OR StageName = 'Notartermin hat stattgefunden') GROUP BY Immobilie__c]) {
            Id immoId = (Id) agRes.get('immoId');
            Double offen = (Double) agRes.get('offen');
            Double abgerechnet = (Double) agRes.get('abgerechnet');

            Property__c immo = new Property__c(Id = immoId);
            immo.OffenerBetragEinmalzahlungen__c = offen;
            immo.AbgerechneteEinmalzahlungen__c = abgerechnet;
            immobilien.add(immo);
        }
        update immobilien;
    }

    public static void updateImmobilien2(Set<Id> immoIds) {
        List<Property__c> immobilien = new List<Property__c>();
        for(AggregateResult agRes : [SELECT Immobilie__c immoId, SUM(IncentivierungGesamt__c) incentivierungGesamt FROM Opportunity WHERE incentivierunggesamt__c != 0 AND (IsWon = true OR StageName = 'Notartermin hat stattgefunden') GROUP BY Immobilie__c]) {
            Id immoId = (Id) agRes.get('immoId');
            Double incentivierungGesamt = (Double) agRes.get('incentivierungGesamt');

            Property__c immo = new Property__c(Id = immoId);
            immo.IncentivierungIST__c = incentivierungGesamt;
            immobilien.add(immo);
        }
        update immobilien;
    }
}