force-app/main/default/objects/ImmobilienDmsDatei__c/ImmobilienDmsDatei__c.object-meta.xml
<CustomObject>
    <label>Immobilien DMS Datei</label>
    <nameField>
        <label>Immobilien DMS Datei Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien DMS Dateien</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/DateiTyp__c.field-meta.xml
<CustomField>
    <fullName>DateiTyp__c</fullName>
    <label>Datei Typ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bilder</fullName>
            </value>
            <value>
                <fullName>Dokumente</fullName>
            </value>
            <value>
                <fullName>Highlights</fullName>
            </value>
            <value>
                <fullName>Grundrisse</fullName>
            </value>
            <value>
                <fullName>Baufortschritt</fullName>
            </value>
            <value>
                <fullName>Musterberechnung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/DateiUrl__c.field-meta.xml
<CustomField>
    <fullName>DateiUrl__c</fullName>
    <label>Datei Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/FileLastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>FileLastModifiedDate__c</fullName>
    <label>Datei zuletzt geändert am</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Immobilien DMS Dateien</relationshipLabel>
    <relationshipName>ImmobilienDmsDateien</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewFileEmailNotificationJobTest.cls
@IsTest
private class NewFileEmailNotificationJobTest {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.createDatevSettings();
        Account acc = TestDataFactory.createAccount(true);
        TestDataFactory.createCommunityUser(acc.Id);
        TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
    }

    @IsTest
    private static void test() {
        Id immoId = [SELECT Id FROM Property__c LIMIT 1].Id;

        insert new ImmobilienDmsDatei__c(
            Name = 'Testdatei',
            Immobilie__c = immoId,
            DateiUrl__c = 'https://www.google.com/Test.pdf',
            DateiTyp__c = 'Dokumente',
            FileLastModifiedDate__c = DateTime.now().addHours(-5)
        );

        Test.startTest();
        NewFileEmailNotificationJob.schedule();
        Test.stopTest();

        System.assertEquals(1, new NewFileOverviewController().files.size());
    }
}