force-app/main/default/objects/ImmobilienDmsDatei__c/ImmobilienDmsDatei__c.object-meta.xml
<CustomObject>
    <label>Immobilien DMS Datei</label>
    <nameField>
        <label>Immobilien DMS Datei Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien DMS Dateien</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/DateiTyp__c.field-meta.xml
<CustomField>
    <fullName>DateiTyp__c</fullName>
    <label>Datei Typ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bilder</fullName>
            </value>
            <value>
                <fullName>Dokumente</fullName>
            </value>
            <value>
                <fullName>Highlights</fullName>
            </value>
            <value>
                <fullName>Grundrisse</fullName>
            </value>
            <value>
                <fullName>Baufortschritt</fullName>
            </value>
            <value>
                <fullName>Musterberechnung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/DateiUrl__c.field-meta.xml
<CustomField>
    <fullName>DateiUrl__c</fullName>
    <label>Datei Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/FileLastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>FileLastModifiedDate__c</fullName>
    <label>Datei zuletzt geändert am</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Immobilien DMS Dateien</relationshipLabel>
    <relationshipName>ImmobilienDmsDateien</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NewFileOverviewController.cls
public without sharing class NewFileOverviewController {

    public List<File> files {get;set;}

    public NewFileOverviewController() {
        this.files = getFiles();
    }

    public static List<File> getFiles() {
        List<File> newFiles = new List<File>();
        for(ImmobilienDmsDatei__c immoDmsDatei : [
            SELECT Id, Name, Immobilie__r.Name, DateiUrl__c FROM ImmobilienDmsDatei__c 
            WHERE FileLastModifiedDate__c >= :(System.now().addHours(-24)) AND DateiTyp__c = 'Dokumente' AND Immobilie__r.Is_Public__c = true
            ORDER BY Immobilie__r.Name ASC]) {
            newFiles.add(new File(immoDmsDatei));
        }
        return newFiles;
    }

    public class File {
        public String title {get;set;}
        public String immoName {get;set;}
        public String url {get;set;}

        public File(ImmobilienDmsDatei__c immoDmsDatei) {
            this.title = immoDmsDatei.Name;
            this.immoName = immoDmsDatei.Immobilie__r.Name;
            this.url = immoDmsDatei.DateiUrl__c;
        }
    }
}