force-app/main/default/objects/Account/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Abrechnung über)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Carestone_Vertriebsvereinbarung__c.field-meta.xml
<CustomField>
    <fullName>Carestone_Vertriebsvereinbarung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carestone Vertriebsvereinbarung</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Maklerprovision__c</fullName>
    <label>Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marketingzuschuss__c.field-meta.xml
<CustomField>
    <fullName>Marketingzuschuss__c</fullName>
    <label>Marketingzuschuss</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <label>Additional Broker Commission</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Provisionsbasis__c.field-meta.xml
<CustomField>
    <fullName>Provisionsbasis__c</fullName>
    <label>Provisionsbasis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ErhaeltErfolgsabhaengigeProvision__c.field-meta.xml
<CustomField>
    <fullName>ErhaeltErfolgsabhaengigeProvision__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erhält erfolgsabhängige Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ist_Maklerbetreuer_WH__c.field-meta.xml
<CustomField>
    <fullName>Ist_Maklerbetreuer_WH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ist Maklerbetreuer CS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maklerauftrag__c.field-meta.xml
<CustomField>
    <fullName>Maklerauftrag__c</fullName>
    <formula>IF(Account.Carestone_Vertriebsvereinbarung__c, &apos;Maklerauftrag beidseitig unterzeichnet&apos;,
TEXT(Account.WHS_Maklerauftrag__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maklerauftrag</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Kunde.recordType-meta.xml
<RecordType>
    <fullName>Kunde</fullName>
    <active>true</active>
    <label>Kunde</label>
</RecordType>

force-app/main/default/objects/Gutschrift__c/Gutschrift__c.object-meta.xml
<CustomObject>
    <label>Gutschrift</label>
    <nameField>
        <label>Gutschrift-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gutschriften</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gutschrift__c/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Incentivierung Makler</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provision</label>
    <referenceTo>Provision__c</referenceTo>
    <relationshipLabel>Gutschriften</relationshipLabel>
    <relationshipName>Gutschriften</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gutschrift__c/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Abrechnung über)</relationshipLabel>
    <relationshipName>OpportunitiesNK3O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <formula>Appartement__r.AdditionalBrokerCommission__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Additional Broker Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ExterneProvisionenGeneriert__c.field-meta.xml
<CustomField>
    <fullName>ExterneProvisionenGeneriert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Externe Provisionen generiert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Maklerprovision__c</fullName>
    <label>Grundprovision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keine</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>4.5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5.5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>3.8</fullName>
            </value>
            <value>
                <fullName>4.3</fullName>
            </value>
            <value>
                <fullName>3.75</fullName>
            </value>
            <value>
                <fullName>4.25</fullName>
            </value>
            <value>
                <fullName>4.75</fullName>
            </value>
            <value>
                <fullName>5.25</fullName>
            </value>
            <value>
                <fullName>5.75</fullName>
            </value>
            <value>
                <fullName>6.25</fullName>
            </value>
            <value>
                <fullName>6.75</fullName>
            </value>
            <value>
                <fullName>7.25</fullName>
            </value>
            <value>
                <fullName>7.75</fullName>
            </value>
            <value>
                <fullName>8.25</fullName>
            </value>
            <value>
                <fullName>8.75</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <inlineHelpText>Wichtig: Dies ist das Datum der ursprünglichen Vertragsunterzeichnung seitens des Kunden.</inlineHelpText>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <label>Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provisionsbasis__c.field-meta.xml
<CustomField>
    <fullName>Provisionsbasis__c</fullName>
    <label>Provisionsbasis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <formula>Maklerprovision_nach_Nachtrag__c/100*Provisionsbasis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Incentivierung Makler</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <formula>Verkaufschance__r.Notartermin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProvisionPreviewServiceTest.cls
@IsTest
private class ProvisionPreviewServiceTest {

    /* ============================================================
       Test setup
       ============================================================ */
    @testSetup
    static void setupData() {
        TestDataFactory.createNecessaryCustomSettings();
        TestDataFactory.createDatevSettings();
    }

    /* ============================================================
       Helper: minimal valid external broker scenario
       ============================================================ */
    private static Opportunity createBaseOpportunity(
        Date notartermin,
        Decimal probability,
        Boolean externeProvisionenGeneriert
    ) {
        // --- Account + Broker
        Account acc = TestDataFactory.createAccount(true);

        Contact broker = TestDataFactory.createMakler(false, acc.Id);
        broker.Ist_Maklerbetreuer_WH__c = false;
        broker.ErhaeltErfolgsabhaengigeProvision__c = false;
        insert broker;

        // --- Kunde
        Contact kunde = TestDataFactory.createInteressent(true, acc.Id);

        // --- Objekt
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Property__c imm    = TestDataFactory.createProperty(true, bautraeger.Id);
        Appartment__c app  = TestDataFactory.createAppartment(true, imm.Id);

        // --- Opportunity
        Opportunity opp = TestDataFactory.createOpportunity(
            true,
            kunde.Id,
            broker.Id,
            imm.Id,
            app.Id
        );

        opp.StageName = 'Notartermin hat stattgefunden';
        opp.Notartermin__c = notartermin;
        opp.Probability = probability;
        opp.Provisionsbasis__c = 100000;
        opp.ExterneProvisionenGeneriert__c = externeProvisionenGeneriert;

        // required for getProvisionExtern
        opp.Makler__c = broker.Id;
        opp.Immobilienberater__c = broker.Id;

        update opp;
        return opp;
    }

    private static Opportunity createBaseOpportunity(
        Account acc,
        Contact broker,
        Date notartermin,
        Decimal probability,
        Boolean externeProvisionenGeneriert
    ) {
        // --- Kunde
        Contact kunde = TestDataFactory.createInteressent(true, acc.Id);

        // --- Objekt
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Property__c imm    = TestDataFactory.createProperty(true, bautraeger.Id);
        Appartment__c app  = TestDataFactory.createAppartment(true, imm.Id);

        Opportunity opp = TestDataFactory.createOpportunity(
            true, kunde.Id, broker.Id, imm.Id, app.Id
        );

        opp.StageName = 'Notartermin hat stattgefunden';
        opp.Notartermin__c = notartermin;
        opp.Probability = probability;
        opp.Provisionsbasis__c = 100000;
        opp.ExterneProvisionenGeneriert__c = externeProvisionenGeneriert;

        // important: these must be set to hit the new query filter
        opp.Makler__c = broker.Id;
        opp.Immobilienberater__c = broker.Id;

        update opp;
        return opp;
    }

    /* ============================================================
       1) Test: eligible opportunity is returned
       ============================================================ */
    @IsTest
static void testEligibleOpportunityReturned() {

    // --- Account drives Maklerauftrag__c
    Account acc = TestDataFactory.createAccount(true);
    acc.Carestone_Vertriebsvereinbarung__c = true;
    update acc;

    // --- Broker
    Contact broker = TestDataFactory.createMakler(true, acc.Id);

    // --- Customer
    Contact kunde = TestDataFactory.createInteressent(true, acc.Id);

    // --- Property / Appartement
    Account bautraeger = TestDataFactory.createBautraeger(true);
    Property__c imm = TestDataFactory.createProperty(true, bautraeger.Id);
    Appartment__c app = TestDataFactory.createAppartment(true, imm.Id);
    app.AdditionalBrokerCommission__c = 0;
    update app;

    // --- Opportunity
    Opportunity opp = TestDataFactory.createOpportunity(
        true,
        kunde.Id,
        broker.Id,
        imm.Id,
        app.Id
    );

    opp.StageName = 'Notartermin hat stattgefunden';
    opp.ExterneProvisionenGeneriert__c = false;
    opp.Provisionsbasis__c = 200000;

    opp.Makler__c = broker.Id;
    opp.Immobilienberater__c = null;
    opp.Abrechnung_ber__c = null;

    // Formula drivers
    opp.Maklerprovision__c = '10';
    opp.Marketingzuschuss__c = 0;

    update opp;

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
    Test.stopTest();

    System.assertEquals(
        1,
        res.size(),
        'Exactly one offene Provision should be returned'
    );
}


    /* ============================================================
       2) Test: excluded if ExterneProvisionenGeneriert__c = true
       ============================================================ */
    @IsTest
    static void testExcludedIfExternAlreadyGenerated() {
        Opportunity opp = createBaseOpportunity(
            Date.today().addDays(-5),
            50,
            true
        );

        Contact broker = [
            SELECT Id
            FROM Contact
            WHERE Id = :opp.Makler__c
        ];

        Test.startTest();
            List<ProvisionPreviewDTO> previews =
                ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
        Test.stopTest();

        System.assertEquals(
            0,
            previews.size(),
            'Opportunity must be excluded if ExterneProvisionenGeneriert__c = true'
        );
    }

    /* ============================================================
       3) Test: probability + weighted provision calculation
       ============================================================ */
    @IsTest
static void testProbabilityAndWeightedProvision() {

    Account acc = TestDataFactory.createAccount(true);
    acc.Carestone_Vertriebsvereinbarung__c = true;
    update acc;

    Contact broker = TestDataFactory.createMakler(true, acc.Id);

    Contact kunde = TestDataFactory.createInteressent(true, acc.Id);

    Account bautraeger = TestDataFactory.createBautraeger(true);
    Property__c imm = TestDataFactory.createProperty(true, bautraeger.Id);
    Appartment__c app = TestDataFactory.createAppartment(true, imm.Id);
    app.AdditionalBrokerCommission__c = 0;
    update app;

    Opportunity opp = TestDataFactory.createOpportunity(
        true,
        kunde.Id,
        broker.Id,
        imm.Id,
        app.Id
    );

    opp.StageName = 'Notartermin hat stattgefunden';
    opp.ExterneProvisionenGeneriert__c = false;
    opp.Probability = 50;
    opp.Provisionsbasis__c = 100000;

    opp.Makler__c = broker.Id;
    opp.Maklerprovision__c = '10';
    opp.Marketingzuschuss__c = 0;

    update opp;

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
    Test.stopTest();

    System.assertEquals(1, res.size());

    ProvisionPreviewDTO dto = res[0];

    System.assertEquals(50, dto.Probability);
    System.assertEquals(
        5000,
        dto.WeightedProvision,
        'WeightedProvision must equal provision * probability'
    );
}


    /* ============================================================
       4) Test: preview must NOT create Provision__c records
       ============================================================ */
    @IsTest
    static void testNoProvisionRecordsCreated() {
        Opportunity opp = createBaseOpportunity(
            Date.today().addDays(-15),
            70,
            false
        );

        Contact broker = [
            SELECT Id
            FROM Contact
            WHERE Id = :opp.Makler__c
        ];

        Test.startTest();
            ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
        Test.stopTest();

        Integer cnt = [
            SELECT COUNT()
            FROM Provision__c
            WHERE Verkaufschance__c = :opp.Id
        ];

        System.assertEquals(
            0,
            cnt,
            'Preview service must not create Provision__c records'
        );
    }

    @IsTest
static void testExistingProvisionWithUnpaidCredits() {

    Opportunity opp = createBaseOpportunity(
        Date.today().addDays(-10),
        80,
        false
    );

    Contact broker = [
        SELECT Id
        FROM Contact
        WHERE Id = :opp.Makler__c
    ];

    // Create real provision
    Provision__c prov = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), broker.Id);
    prov.Wert_Maklerprovision__c = 10000;
    insert prov;

    // Unpaid credit
    Gutschrift__c g = new Gutschrift__c(
        Provision__c = prov.Id,
        Wert_Maklerprovision__c = 4000,
        Bezahlt__c = false
    );
    insert g;

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
    Test.stopTest();

    System.assertEquals(1, res.size());
    System.assertEquals(4000, res[0].Provisionssumme);
}

@IsTest
static void testExistingProvisionAllCreditsPaidExcluded() {

    Opportunity opp = createBaseOpportunity(
        Date.today().addDays(-10),
        80,
        false
    );

    Contact broker = [
        SELECT Id
        FROM Contact
        WHERE Id = :opp.Makler__c
    ];

    Provision__c prov = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), broker.Id);
    prov.Wert_Maklerprovision__c = 6000;
    insert prov;

    // Paid credit
    insert new Gutschrift__c(
        Provision__c = prov.Id,
        Wert_Maklerprovision__c = 6000,
        Bezahlt__c = true
    );

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
    Test.stopTest();

    System.assertEquals(
        0,
        res.size(),
        'Provision with fully paid credits must not appear'
    );
}
@IsTest
static void testProvisionOfOtherBrokerIsExcluded() {

    Opportunity opp = createBaseOpportunity(
        Date.today().addDays(-5),
        60,
        false
    );

    Id accId = [SELECT AccountId FROM Contact WHERE Id = :opp.Makler__c].AccountId;

    Contact otherBroker = TestDataFactory.createMakler(true, accId);

    Provision__c prov = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), otherBroker.Id);
    prov.Wert_Maklerprovision__c = 8000;
    insert prov;

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(opp.Makler__c);
    Test.stopTest();

    System.assertEquals(
        0,
        res.size(),
        'Provisions of other brokers must not be visible'
    );
}

@IsTest
static void testAlleProvisionenRoleSeesMultipleBrokers() {

    Account acc = TestDataFactory.createAccount(true);

    Contact broker1 = TestDataFactory.createMakler(true, acc.Id);
    Contact broker2 = TestDataFactory.createMakler(true, acc.Id);

    broker1.VPRollen__c = 'Alle Provisionen';
    update broker1;

    // IMPORTANT: create opp on same account; choose one broker for opp fields
    Opportunity opp = createBaseOpportunity(
        acc, broker1, Date.today().addDays(-3), 70, false
    );

    Provision__c p1 = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), broker1.Id);
    p1.Wert_Maklerprovision__c = 3000;

    Provision__c p2 = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), broker2.Id);
    p2.Wert_Maklerprovision__c = 5000;

    insert new List<Provision__c>{ p1, p2 };

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(broker1.Id);
    Test.stopTest();

    System.assertEquals(2, res.size());
}


@IsTest
static void testExistingProvisionSuppressesForecast() {

    Opportunity opp = createBaseOpportunity(
        Date.today().addDays(-7),
        50,
        false
    );

    Contact broker = [
        SELECT Id
        FROM Contact
        WHERE Id = :opp.Makler__c
    ];

    Provision__c prov = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), broker.Id);
    prov.Wert_Maklerprovision__c = 7000;
    insert prov;

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(broker.Id);
    Test.stopTest();

    System.assertEquals(
        1,
        res.size(),
        'Forecast must not be shown when real provision exists'
    );
}

@IsTest
static void testBrokerNameFromProvisionMakler() {

    Account acc = TestDataFactory.createAccount(true);

    Contact otherBroker = TestDataFactory.createMakler(false, acc.Id);
    otherBroker.FirstName = 'Max';
    otherBroker.LastName  = 'Mustermann';
    insert otherBroker;

    // IMPORTANT: opp must match query filter by having Makler__c etc. = otherBroker
    Opportunity opp = createBaseOpportunity(
        acc, otherBroker, Date.today().addDays(-5), 90, false
    );

    Provision__c prov = TestDataFactory.createProvision(false, opp.Id, UserInfo.getUserId(), otherBroker.Id);
    prov.Wert_Maklerprovision__c = 9000;
    insert prov;

    Test.startTest();
        List<ProvisionPreviewDTO> res =
            ProvisionPreviewService.getOpenBrokerProvisions(otherBroker.Id);
    Test.stopTest();

    System.assert(!res.isEmpty(), 'Expected at least one DTO');
    System.assertEquals('Max Mustermann', res[0].BrokerName);
}


}