force-app/main/default/objects/Account/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Abrechnung über)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Makler ist auf unbestimmte Zeit geschützt</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neu</fullName>
                <default>true</default>
                <label>Neu</label>
            </value>
            <value>
                <fullName>Kontaktiert</fullName>
            </value>
            <value>
                <fullName>Terminiert</fullName>
            </value>
            <value>
                <fullName>Aktiv</fullName>
            </value>
            <value>
                <fullName>Inaktiv</fullName>
            </value>
            <value>
                <fullName>Verloren</fullName>
            </value>
            <value>
                <fullName>Blacklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte (Customer)</relationshipLabel>
    <relationshipName>gekaufte_Appartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Reserviert_bis__c.field-meta.xml
<CustomField>
    <fullName>Reserviert_bis__c</fullName>
    <label>Reserviert bis</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/ReserviertFuer__c.field-meta.xml
<CustomField>
    <fullName>ReserviertFuer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reserviert für</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>ReservierteTeilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kontingent</fullName>
            </value>
            <value>
                <fullName>Reservierungsvorbereitung</fullName>
            </value>
            <value>
                <fullName>Reservierung angefragt</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsangebot abgegeben</fullName>
            </value>
            <value>
                <fullName>KV wird fremd abgegeben</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsunterlagen verschickt -zweiseitig-</fullName>
            </value>
            <value>
                <fullName>Auftrag zur Beurkundung vorhanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Berater_text__c.field-meta.xml
<CustomField>
    <fullName>Berater_text__c</fullName>
    <label>Berater text</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Kontakt hat bereits ein Apartment gekauft und ist somit dauerhaft geschützt.</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Kampagnenquelle__c.field-meta.xml
<CustomField>
    <fullName>Kampagnenquelle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kampagnenquelle</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Kontakte</relationshipLabel>
    <relationshipName>Interessenten</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Kunden_Maklerschutz__c.field-meta.xml
<CustomField>
    <fullName>Kunden_Maklerschutz__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kundenschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LetzteImmobiliennummer__c.field-meta.xml
<CustomField>
    <fullName>LetzteImmobiliennummer__c</fullName>
    <label>Letzte Immobiliennummer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Abrechnung über)</relationshipLabel>
    <relationshipName>OpportunitiesNK3O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Berater_text__c.field-meta.xml
<CustomField>
    <fullName>Berater_text__c</fullName>
    <label>Berater text</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Grundprovision_Provisionsverhandlung__c.field-meta.xml
<CustomField>
    <fullName>Grundprovision_Provisionsverhandlung__c</fullName>
    <label>Grundprovision Provisionsverhandlung</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufpreis_bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis_bezahlt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kaufpreis bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kunde2__c.field-meta.xml
<CustomField>
    <fullName>Kunde2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Verkaufschancen (2. Käufer)</relationshipLabel>
    <relationshipName>Verkaufschancen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projektbeauftragte__c.field-meta.xml
<CustomField>
    <fullName>Projektbeauftragte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projektbeauftragte</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Projektbeauftragte)</relationshipLabel>
    <relationshipName>Opportunities8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <label>Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/reserviert_bis__c.field-meta.xml
<CustomField>
    <fullName>reserviert_bis__c</fullName>
    <label>reserviert bis</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verkaufsprovision_Provisionsverhandlung__c.field-meta.xml
<CustomField>
    <fullName>Verkaufsprovision_Provisionsverhandlung__c</fullName>
    <label>Verkaufsprovision Provisionsverhandlung</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Objektnummer__c.field-meta.xml
<CustomField>
    <fullName>Objektnummer__c</fullName>
    <label>Immobiliennummer</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Projektbeauftragte__c.field-meta.xml
<CustomField>
    <fullName>Projektbeauftragte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projektbeauftragte</label>
    <referenceTo>Realty_User__c</referenceTo>
    <relationshipLabel>Immobilien</relationshipLabel>
    <relationshipName>Projektbeauftragte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Kaufpreis_bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis_bezahlt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kaufpreis bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Zahlungsstatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Offen</fullName>
                <default>true</default>
                <label>Offen</label>
            </value>
            <value>
                <fullName>Im nächsten Zahlungslauf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provisionen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
@IsTest
private class OpportunityTriggerHandlerTest {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.createDatevSettings();
    }

    /*
    @IsTest
    private static void testApartmentCannotBeReservedTwice() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        System.debug([SELECT StageName FROM Opportunity WHERE Id = :opp.Id]);
        System.debug([SELECT Status__c FROM Appartment__c WHERE Id = :appartment.Id]);
        Opportunity oppTwo = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        
        opp.StageName = 'Reserviert';
        update opp;

        System.assertEquals(opp.Id, [SELECT ReserviertFuer__c FROM Appartment__c WHERE Id = :appartment.Id].ReserviertFuer__c);
        System.assertEquals('Reserved', [SELECT Status__c FROM Appartment__c WHERE Id = :appartment.Id].Status__c);

        Test.startTest();
        try {
            oppTwo.StageName = 'Reserviert';
            update oppTwo;
        } catch(Exception ex) {
            System.debug(ex.getMessage());
            System.debug(OpportunityTriggerHandler.APARTMENT_RESERVED_ERROR.replace('{0}', opp.Name));
            System.assert(ex.getMessage().contains(OpportunityTriggerHandler.APARTMENT_RESERVED_ERROR.replace('{0}', opp.Name)));
        }
        Test.stopTest();
    }
    */

    @IsTest
    private static void testSetProvisionOnInsert() {
        Account acc = TestDataFactory.createAccount(false);
        Account abrechnungsAccount = TestDataFactory.createAccount(false);

        insert new List<Account> {acc, abrechnungsAccount};

        Contact abrechnungsMakler = TestDataFactory.createMakler(false, abrechnungsAccount.Id);    
        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent, abrechnungsMakler};

        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);

        TestDataFactory.createProvisionsverhandlung(true, abrechnungsAccount.Id, immobilie.Id);

        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Test.startTest();
        Opportunity opp = TestDataFactory.createOpportunity(false, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        opp.Abrechnung_ber__c = abrechnungsMakler.Id;
        opp.Immobilienberater__c = makler.Id;
        insert opp;
        Test.stopTest();

        opp = [SELECT Grundprovision_Provisionsverhandlung__c, Verkaufsprovision_Provisionsverhandlung__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(5.0, opp.Grundprovision_Provisionsverhandlung__c);
        System.assertEquals(10, opp.Verkaufsprovision_Provisionsverhandlung__c);
    }

    @IsTest
    private static void testSetStageOnInsert() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Test.startTest();
        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, null, 'Kontingent');
        Test.stopTest();

        System.assertEquals('Nachrücker', [SELECT StageName FROM Opportunity WHERE Id = :opp.Id].StageName);
    }

    @IsTest
    private static void testSetCampaignSource() {
        Campaign campaign = TestDataFactory.createCampaign(true);
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        interessent.Kampagnenquelle__c = campaign.Id;
        insert new List<Contact> {makler, interessent};

        Test.startTest();
        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        Test.stopTest();

        System.assertEquals(campaign.Id, [SELECT CampaignId FROM Opportunity WHERE Id = :opp.Id].CampaignId);
    }

    @IsTest
    private static void testSetBeratertext() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Test.startTest();
        Opportunity opp = TestDataFactory.createOpportunity(false, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        opp.Immobilienberater__c = makler.Id;
        insert opp;
        Test.stopTest();

        System.assertEquals(makler.Id, [SELECT Berater_text__c FROM Opportunity WHERE Id = :opp.Id].Berater_text__c);
    }

    @IsTest
    private static void testSetProjektbeauftragte() {
        Account acc = TestDataFactory.createAccount(true);
        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Realty_User__c immoUser = TestDataFactory.createImmoUser(true, makler.Id);

        Property__c immobilie = TestDataFactory.createProperty(false, TestDataFactory.createBautraeger(true).Id);
        immobilie.Projektbeauftragte__c = immoUser.Id;
        insert immobilie;
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Test.startTest();
        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        Test.stopTest();
        
        System.assertEquals(makler.Id, [SELECT Projektbeauftragte__c FROM Opportunity WHERE Id = :opp.Id].Projektbeauftragte__c);
    }

    @IsTest
    private static void testSetCustomerToContinouslyProtected() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Test.startTest();
        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kaufvertragsunterlagen verschickt');
        Test.stopTest();

        System.assert([SELECT Dauerhaft_gesch_tzt__c FROM Contact WHERE Id = :interessent.Id].Dauerhaft_gesch_tzt__c);
    }

    @IsTest
    private static void testUpdateProvisionsWithOppValues() {
        User user = TestDataFactory.createCommunityUser();
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kaufvertragsunterlagen verschickt');
        Provision__c provi1 = TestDataFactory.createProvision(false, opp.Id, user.Id, makler.Id);
        Provision__c provi2 = TestDataFactory.createProvision(false, opp.Id, user.Id, makler.Id);
        insert new List<Provision__c> { provi1, provi2 };

        Test.startTest();
        opp.Kaufpreis_bezahlt__c = true;
        update opp;
        Test.stopTest();

        System.assertEquals(2, [SELECT COUNT() FROM Provision__c WHERE Verkaufschance__c = :opp.Id AND Kaufpreis_bezahlt__c = true]);

    }

    @IsTest
    private static void testIncreaseCustomerProtection() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        
        Test.startTest();
        opp.StageName = 'Reserviert';
        update opp;
        Test.stopTest();

        System.assertEquals(DateTimeHelper.checkAndSetDateTimeIfWeekend(System.today().addDays(OpportunityTriggerHandler.DEFAULT_RESERVATION_DURATION)), [SELECT reserviert_bis__c FROM Opportunity WHERE Id = :opp.Id].reserviert_bis__c);
        System.assert([SELECT Kunden_Maklerschutz__c FROM Contact WHERE Id = :interessent.Id].Kunden_Maklerschutz__c);
    }

    @IsTest
    private static void testOpportunityWasWOn() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        Contact interessent2 = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent, interessent2};

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);

        Opportunity opp = TestDataFactory.createOpportunity(false, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');
        opp.Immobilienberater__c = makler.Id;
        opp.Kunde2__c = interessent2.Id;
        insert opp;

        Test.startTest();
        opp.StageName = 'Geschlossene und gewonnene';
        update opp;
        Test.stopTest();

        System.assertEquals(2, [SELECT COUNT() FROM Contact WHERE LetzteImmobiliennummer__c = :immobilie.Objektnummer__c]);
    }

    @IsTest
    private static void testSetApartmentFieldsOnInsert() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);
        
        Test.startTest();
        
        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Reserviert');
        appartment = [SELECT Status__c, Customer__c, Makler__c FROM Appartment__c WHERE Id = :appartment.Id];
        System.assertEquals(interessent.Id, appartment.Customer__c);
        System.assertEquals('Reserved', appartment.Status__c);

        Test.stopTest();
    }

    @IsTest
    private static void testSetApartmentFields() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        Contact interessent2 = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent, interessent2};

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Reserviert');

        System.debug([SELECT Status__c, Customer__c, Makler__c FROM Appartment__c WHERE Id = :appartment.Id]);

        Test.startTest();
        
        opp.StageName = 'VKC ausgelaufen';
        opp.Grund_VKC_verloren__c = 'Interessent möchte sein Kapital jetzt anlegen';
        update opp;

        System.assertEquals(null, [SELECT Customer__c FROM Appartment__c WHERE Id = :appartment.Id].Customer__c);

        Opportunity opp2 = TestDataFactory.createOpportunity(true, interessent2.Id, makler.Id, immobilie.Id, appartment.Id, 'Kontingent');


        System.assertEquals('Kontingent', [SELECT Status__c FROM Appartment__c WHERE Id = :appartment.Id].Status__c);

        opp2.StageName = 'Reserviert';
        update opp2;
        System.assertEquals('Reserved', [SELECT Status__c FROM Appartment__c WHERE Id = :appartment.Id].Status__c);
        System.assertEquals(interessent2.Id, [SELECT Customer__c FROM Appartment__c WHERE Id = :appartment.Id].Customer__c);
        Test.stopTest();
    }

    @IsTest
    private static void testCreateZahlungseingangPdfOnZahlungseingangApproval() {
        User user = TestDataFactory.createCommunityUser();
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Kaufvertragsunterlagen verschickt');

        Test.startTest();
        opp.ZahlungseingangApproved__c = true;
        update opp;
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM ContentVersion WHERE FirstPublishLocationId = :opp.Id AND Typ__c = 'Notar-Anschreiben']);
    }

    @IsTest
    private static void testClearNotarterminOnLostOpportunity() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        Contact interessent2 = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent, interessent2};

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);

        Opportunity opp = TestDataFactory.createOpportunity(false, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Reserviert');
        opp.Notartermin__c = Date.today().addDays(-5);
        insert opp;

        Test.startTest();        
        opp.StageName = 'VKC ausgelaufen';
        opp.Grund_VKC_verloren__c = 'Interessent möchte sein Kapital jetzt anlegen';
        update opp;
        Test.stopTest();

        System.assertEquals(null, [SELECT Notartermin__c FROM Opportunity WHERE Id = :opp.Id].Notartermin__c);
    }

    @IsTest
    private static void testCumulatedProvisionAggregation() {
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        Contact interessent2 = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent, interessent2};

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);

        Opportunity opp = TestDataFactory.createOpportunity(true, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Reserviert');

        opp.Provisionsbasis__c = 500;
        opp.KumulierteProvisionExtern__c = 3;
        Test.startTest();
        update opp;
        Test.stopTest();

        Assert.isNotNull([SELECT SummeWertKumulierteProvisionExtern__c FROM Property__c WHERE Id = :opp.Immobilie__c].SummeWertKumulierteProvisionExtern__c);
    }
}