force-app/main/default/objects/Account/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Abrechnung über)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Carestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Provisionsbasis__c.field-meta.xml
<CustomField>
    <fullName>Provisionsbasis__c</fullName>
    <label>Provisionsbasis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Abrechnung über)</relationshipLabel>
    <relationshipName>OpportunitiesNK3O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AufschiebendeBedingungErfuellt__c.field-meta.xml
<CustomField>
    <fullName>AufschiebendeBedingungErfuellt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Gibt an, dass die aufschiebende Bedingung erfüllt wurde. Erst dann können Provisionen und Gutschriften erzeugt werden.</inlineHelpText>
    <label>Aufschiebende Bedingung erfüllt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DatumBedingungErfuellt__c.field-meta.xml
<CustomField>
    <fullName>DatumBedingungErfuellt__c</fullName>
    <inlineHelpText>Datum, an dem die aufschiebende Bedingung erfüllt wurde.</inlineHelpText>
    <label>Datum Bedingung erfüllt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HatAufschiebendeBedingung__c.field-meta.xml
<CustomField>
    <fullName>HatAufschiebendeBedingung__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Gibt an, ob diese VKC eine aufschiebende Bedingung hat. Solange die Bedingung nicht erfüllt ist, werden keine Provisionen oder Gutschriften erzeugt.</inlineHelpText>
    <label>Hat aufschiebende Bedingung</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufdatum__c.field-meta.xml
<CustomField>
    <fullName>Kaufdatum__c</fullName>
    <label>Kaufdatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maklerbetreuer_WirtschaftsHaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_WirtschaftsHaus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Ist_Maklerbetreuer_WH__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Maklerbetreuer WirtschaftsHaus)</relationshipLabel>
    <relationshipName>Maklerbetreuer_Wirtschaftshaus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketingzuschussNichtAusweisen__c.field-meta.xml
<CustomField>
    <fullName>MarketingzuschussNichtAusweisen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketingzuschuss nicht ausweisen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <inlineHelpText>Wichtig: Dies ist das Datum der ursprünglichen Vertragsunterzeichnung seitens des Kunden.</inlineHelpText>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provisionsbasis__c.field-meta.xml
<CustomField>
    <fullName>Provisionsbasis__c</fullName>
    <label>Provisionsbasis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProvisionsvoraussetzungenErfuellt__c.field-meta.xml
<CustomField>
    <fullName>ProvisionsvoraussetzungenErfuellt__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Wird automatisch aus den PV-Feldern der Immobilie und den damit zusammengehörenden Feldern der Verkaufschance angehakt</description>
    <inlineHelpText>Wird automatisch aus den PV-Feldern der Immobilie und den damit zusammengehörenden Feldern der Verkaufschance angehakt</inlineHelpText>
    <label>Provisionsvoraussetzungen erfüllt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Provisionen</relationshipLabel>
    <relationshipName>Provision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/MarketingzuschussNichtAusweisen__c.field-meta.xml
<CustomField>
    <fullName>MarketingzuschussNichtAusweisen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketingzuschuss nicht ausweisen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <formula>Verkaufschance__r.Notartermin__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AufschiebendeBedingungTest.cls
@IsTest
private class AufschiebendeBedingungTest {

    @TestSetup
    static void makeData() {
        TestDataFactory.createNecessaryCustomSettings();
        TestDataFactory.createDatevSettings();

        Account acc = TestDataFactory.createAccount(true);
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Contact makler = TestDataFactory.createMakler(true, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(true, acc.Id);
        Property__c immobilie = TestDataFactory.createProperty(true, bautraeger.Id);
        Appartment__c app = TestDataFactory.createAppartment(true, immobilie.Id);
        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);
    }

    private static Opportunity createTestOpportunity(Boolean doInsert) {
        Contact makler = [SELECT Id, AccountId FROM Contact WHERE RecordType.DeveloperName = 'Makler' LIMIT 1];
        Contact interessent = [SELECT Id FROM Contact WHERE RecordType.DeveloperName = 'Interessent' LIMIT 1];
        Property__c immobilie = [SELECT Id FROM Property__c LIMIT 1];
        Appartment__c app = [SELECT Id FROM Appartment__c LIMIT 1];

        return TestDataFactory.createOpportunity(
            doInsert, interessent.Id, makler.Id, immobilie.Id, app.Id, 'Reserviert', 100000
        );
    }

    @IsTest
    static void testKaufdatumCannotBeInFuture() {
        Opportunity opp = createTestOpportunity(true);
        opp.Kaufdatum__c = Date.today().addDays(1);

        Test.startTest();
        Boolean exceptionThrown = false;
        try {
            update opp;
        } catch (DmlException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Validation rule should block future Kaufdatum');
    }

    @IsTest
    static void testKaufdatumCannotBeBeforeNotartermin() {
        Opportunity opp = createTestOpportunity(true);
        opp.Notartermin__c = Date.today().addDays(-5);
        opp.Kaufdatum__c = Date.today().addDays(-10);

        Test.startTest();
        Boolean exceptionThrown = false;
        try {
            update opp;
        } catch (DmlException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Validation rule should block Kaufdatum before Notartermin');
    }

    @IsTest
    static void testKaufdatumBlockedWhenConditionPending() {
        Opportunity opp = createTestOpportunity(true);
        opp.HatAufschiebendeBedingung__c = true;
        opp.Kaufdatum__c = Date.today();

        Test.startTest();
        Boolean exceptionThrown = false;
        try {
            update opp;
        } catch (DmlException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        System.assert(exceptionThrown, 'Validation rule should block Kaufdatum when condition is pending');
    }

    @IsTest
    static void testKaufdatumAllowedWhenConditionFulfilled() {
        Opportunity opp = createTestOpportunity(true);
        opp.HatAufschiebendeBedingung__c = true;
        opp.AufschiebendeBedingungErfuellt__c = true;
        opp.DatumBedingungErfuellt__c = Date.today();
        opp.Notartermin__c = Date.today().addDays(-5);
        opp.Kaufdatum__c = Date.today();

        Test.startTest();
        update opp;
        Test.stopTest();

        Opportunity result = [SELECT Kaufdatum__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(Date.today(), result.Kaufdatum__c, 'Kaufdatum should be set when condition is fulfilled');
    }

    @IsTest
    static void testKaufdatumValidOnBoundary() {
        Opportunity opp = createTestOpportunity(true);
        opp.Notartermin__c = Date.today();
        opp.Kaufdatum__c = Date.today();

        Test.startTest();
        update opp;
        Test.stopTest();

        Opportunity result = [SELECT Kaufdatum__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(Date.today(), result.Kaufdatum__c,
            'Kaufdatum equal to today and Notartermin should be valid');
    }

    @IsTest
    static void testProvisionPrerequisitesWithFulfilledCondition() {
        Opportunity opp = createTestOpportunity(true);
        opp.StageName = 'Notartermin hat stattgefunden';
        opp.Notartermin__c = Date.today().addDays(-5);
        opp.Kaufdatum__c = Date.today();
        opp.HatAufschiebendeBedingung__c = true;
        opp.AufschiebendeBedingungErfuellt__c = true;
        opp.DatumBedingungErfuellt__c = Date.today();

        Test.startTest();
        update opp;
        Test.stopTest();

        Opportunity result = [SELECT ProvisionsvoraussetzungenErfuellt__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(true, result.ProvisionsvoraussetzungenErfuellt__c,
            'Provision prerequisites should be met when condition is fulfilled');
    }

    @IsTest
    static void testProvisionPrerequisitesWithoutCondition() {
        Opportunity opp = createTestOpportunity(true);
        opp.StageName = 'Notartermin hat stattgefunden';
        opp.Notartermin__c = Date.today().addDays(-5);
        opp.Kaufdatum__c = Date.today();

        Test.startTest();
        update opp;
        Test.stopTest();

        Opportunity result = [SELECT ProvisionsvoraussetzungenErfuellt__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(true, result.ProvisionsvoraussetzungenErfuellt__c,
            'Provision prerequisites should be met without aufschiebende Bedingung');
    }

    @IsTest
    static void testProvisionServiceFiltersBlockedOpportunities() {
        Opportunity opp = createTestOpportunity(true);
        opp.HatAufschiebendeBedingung__c = true;
        update opp;

        opp = [
            SELECT Id, HatAufschiebendeBedingung__c, AufschiebendeBedingungErfuellt__c,
                   Notartermin__c, Makler__c, Maklerbetreuer_WirtschaftsHaus__c, Immobilie__c,
                   Appartement__c, Potenzieller_Kunde__c, Provisionsbasis__c, OwnerId,
                   MarketingzuschussNichtAusweisen__c, Immobilienberater__c, Abrechnung_ber__c,
                   Overhead_Empf_nger__c, TippgeberProvisionEmpfaenger__c, Vertriebskoordinator__c,
                   Provision_Thoben__c
            FROM Opportunity WHERE Id = :opp.Id
        ];

        Map<Id, Opportunity> opps = new Map<Id, Opportunity>{ opp.Id => opp };
        Map<Id, Opportunity> oldOpps = new Map<Id, Opportunity>{ opp.Id => opp };
        ProvisionService ps = new ProvisionService(opps, oldOpps, 'extern', null);

        Test.startTest();
        ps.upsertProvisionen();
        Test.stopTest();

        List<Provision__c> provisions = [SELECT Id FROM Provision__c WHERE Verkaufschance__c = :opp.Id];
        System.assertEquals(0, provisions.size(), 'No provisions should be created for blocked opportunity');
    }
}