force-app/main/default/objects/Account/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Abrechnung über)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/OffenerBetrag__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetrag__c</fullName>
    <formula>IF( OeffentlicherStatus__c = &apos;Verkauft&apos; &amp;&amp;  KaufpreisFaellig__c,
			IF(Bezahlt__c &gt; 0,
						beurkundeter_Kaufpreis__c - Bezahlt__c, 
						IF(MaBVBezahlt__c &gt; 0,
									beurkundeter_Kaufpreis__c - MaBVBezahlt__c,
									beurkundeter_Kaufpreis__c
						)
					),
			0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Abrechnung über)</relationshipLabel>
    <relationshipName>OpportunitiesNK3O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>VkcZahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>VkcZahlung__c.Verkaufschance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Datum_Kaufpreisf_lligkeitsschreiben__c.field-meta.xml
<CustomField>
    <fullName>Datum_Kaufpreisf_lligkeitsschreiben__c</fullName>
    <label>Datum Kaufpreisfälligkeitsschreiben</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OffenerBetrag__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetrag__c</fullName>
    <formula>IF(
 Kaufpreis_bezahlt__c,
	0, 
IF(Datum_Kaufpreisf_lligkeitsschreiben__c &lt;= TODAY(), IF(ISPICKVAL(Immobilie__r.Kaufpreiszahlung__c, &apos;Endfällig&apos;) || HatVKCZahlungen__c || ISPICKVAL(Immobilie__r.Kaufpreiszahlung__c, &apos;Externes Vertriebsprojekt (Endfällig)&apos;), beurkundeter_Kaufpreis__c -  Bezahlt__c, OffenerBetragMaBV__c), 0)			
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt (aus Teilobjekt)</label>
    <summarizedField>Appartment__c.Bezahlt__c</summarizedField>
    <summaryForeignKey>Appartment__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Kaufpreiszahlung__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreiszahlung__c</fullName>
    <label>Kaufpreiszahlung</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MaBV</fullName>
            </value>
            <value>
                <fullName>Endfällig</fullName>
            </value>
            <value>
                <fullName>Externes Vertriebsprojekt (MaBV)</fullName>
            </value>
            <value>
                <fullName>Externes Vertriebsprojekt (Endfällig)</fullName>
            </value>
            <value>
                <fullName>Bestand</fullName>
                <isActive>false</isActive>
                <label>Bestand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/OffenerBetragEinmalzahlungen__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragEinmalzahlungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offener Betrag (Einmalzahlungen Gesamt)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/VKCZahlung__c.object-meta.xml
<CustomObject>
    <label>VKC Zahlung</label>
    <nameField>
        <displayFormat>EZ-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>VKC Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VKC Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VKCZahlung__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VKCZahlung__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VKC Zahlungen</relationshipLabel>
    <relationshipName>VKCZahlungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VkcZahlungTriggerHandlerTest.cls
@IsTest
private class VkcZahlungTriggerHandlerTest {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.createDatevSettings();
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(false, TestDataFactory.createBautraeger(true).Id);
        immobilie.Kaufpreiszahlung__c = 'Endfällig';
        insert immobilie;
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(false, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Notartermin hat stattgefunden', 100000);
        opp.Abrechnung_ber__c = makler.Id;
        opp.Immobilienberater__c = makler.Id;
        opp.Datum_Kaufpreisf_lligkeitsschreiben__c = Date.today().addDays(-10);
        insert opp;
    }

    @IsTest
    private static void testCalculateImmoSumOnInsert(){
        Opportunity opp = [SELECT Id, Immobilie__c, OffenerBetrag__c, Appartement__c FROM Opportunity LIMIT 1];

        List<VKCZahlung__c> zahlungen = new List<VKCZahlung__c>();
        for(Integer i = 0; i < 3; i++) {
            zahlungen.add(new VKCZahlung__c(
                Verkaufschance__c = opp.Id,
                UniqueId__c = String.valueOf(i),
                Betrag__c = 10
            ));
        }

        Test.startTest();
        insert zahlungen;
        Test.stopTest();

        System.assertEquals(opp.OffenerBetrag__c - 30, [SELECT OffenerBetragEinmalzahlungen__c FROM Property__c WHERE Id = :opp.Immobilie__c].OffenerBetragEinmalzahlungen__c);
        System.assertEquals(30, [SELECT Bezahlt__c FROM Appartment__c WHERE Id = :opp.Appartement__c].Bezahlt__c);
    }

    @IsTest
    private static void testCalculateImmoSumOnUpdate(){
        Opportunity opp = [SELECT Id, Immobilie__c, OffenerBetrag__c FROM Opportunity LIMIT 1];

        List<VKCZahlung__c> zahlungen = new List<VKCZahlung__c>();
        for(Integer i = 0; i < 3; i++) {
            zahlungen.add(new VKCZahlung__c(
                Verkaufschance__c = opp.Id,
                UniqueId__c = String.valueOf(i),
                Betrag__c = 10
            ));
        }

        Test.startTest();
        insert zahlungen;

        for(VkcZahlung__c zahlung : zahlungen) {
            zahlung.Betrag__c = 100;
        }
        update zahlungen;

        Test.stopTest();

        System.assertEquals(opp.OffenerBetrag__c - 300, [SELECT OffenerBetragEinmalzahlungen__c FROM Property__c WHERE Id = :opp.Immobilie__c].OffenerBetragEinmalzahlungen__c);
    }
    
    @IsTest
    private static void testCalculateImmoSumOnDelete(){
        Opportunity opp = [SELECT Id, Immobilie__c, OffenerBetrag__c FROM Opportunity LIMIT 1];

        List<VKCZahlung__c> zahlungen = new List<VKCZahlung__c>();
        for(Integer i = 0; i < 3; i++) {
            zahlungen.add(new VKCZahlung__c(
                Verkaufschance__c = opp.Id,
                UniqueId__c = String.valueOf(i),
                Betrag__c = 10
            ));
        }

        insert zahlungen;

        Test.startTest();
        delete zahlungen[0];
        Test.stopTest();

        System.assertEquals(opp.OffenerBetrag__c - 20, [SELECT OffenerBetragEinmalzahlungen__c FROM Property__c WHERE Id = :opp.Immobilie__c].OffenerBetragEinmalzahlungen__c);
    }
}