force-app/main/default/objects/Account/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Abrechnung über)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/beurkundeter_Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>beurkundeter_Kaufpreis__c</fullName>
    <label>beurkundeter Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRate__c/fields/GesamtanzahlRechnungen__c.field-meta.xml
<CustomField>
    <fullName>GesamtanzahlRechnungen__c</fullName>
    <formula>GezahlteRechnungen__c + OffeneRechnungen__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gesamtanzahl Rechnungen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/GezahlteRechnungen__c.field-meta.xml
<CustomField>
    <fullName>GezahlteRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gezahlte Rechnungen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/OffeneRechnungen__c.field-meta.xml
<CustomField>
    <fullName>OffeneRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offene Rechnungen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/SummeGezahlterRechnungen__c.field-meta.xml
<CustomField>
    <fullName>SummeGezahlterRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Summe gezahlter Rechnungen</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/SummeOffenerRechnungen__c.field-meta.xml
<CustomField>
    <fullName>SummeOffenerRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Summe offener Rechnungen</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>Zahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>Zahlung__c.MaBVRechnung__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/IstBezahlt__c.field-meta.xml
<CustomField>
    <fullName>IstBezahlt__c</fullName>
    <formula>OffenerBetragNeu__c &lt;= 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ist Bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/OffenerBetragNeu__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragNeu__c</fullName>
    <formula>IF((RateGesamtInEuro__c - Bezahlt__c) &lt; 0, 0, RateGesamtInEuro__c - Bezahlt__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag (neu)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/RateGesamtInEuro__c.field-meta.xml
<CustomField>
    <fullName>RateGesamtInEuro__c</fullName>
    <formula>RateInEuro__c + SicherheitPlusInEuro__c - SicherheitseinbehaltInEuro__c + PreisanpassungInEuro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate gesamt in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/RateInEuro__c.field-meta.xml
<CustomField>
    <fullName>RateInEuro__c</fullName>
    <label>Rate in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Abrechnung über)</relationshipLabel>
    <relationshipName>OpportunitiesNK3O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/beurkundeter_Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>beurkundeter_Kaufpreis__c</fullName>
    <label>beurkundeter Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>VkcZahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>VkcZahlung__c.Verkaufschance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt (aus Teilobjekt)</label>
    <summarizedField>Appartment__c.Bezahlt__c</summarizedField>
    <summaryForeignKey>Appartment__c.Property__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/GesamtanzahlRechnungen__c.field-meta.xml
<CustomField>
    <fullName>GesamtanzahlRechnungen__c</fullName>
    <formula>AktuelleMaBVRateLookup__r.GesamtanzahlRechnungen__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gesamtanzahl der Rechnungen (akt. Rate)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zahlung__c/Zahlung__c.object-meta.xml
<CustomObject>
    <label>Zahlung</label>
    <nameField>
        <displayFormat>Z-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zahlung__c/fields/Betrag__c.field-meta.xml
<CustomField>
    <fullName>Betrag__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/MaBVRechnung__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnung__c</fullName>
    <label>MaBV Rechnung</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MaBVRechnung__c.MaBVRechnungMaster__r.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MaBVRechnung__c</referenceTo>
    <relationshipLabel>Zahlungen</relationshipLabel>
    <relationshipName>ZahlungenMaBVRechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MaBVRechnungTriggerHandlerTest.cls
@IsTest
private class MaBVRechnungTriggerHandlerTest {

    @TestSetup
    static void makeData(){
        TestDataFactory.createDatevSettings();
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
        Appartment__c appartment = TestDataFactory.createAppartment(true, immobilie.Id);

        TestDataFactory.createProvisionsverhandlung(true, acc.Id, immobilie.Id);

        Contact makler = TestDataFactory.createMakler(false, acc.Id);
        Contact interessent = TestDataFactory.createInteressent(false, acc.Id);
        insert new List<Contact> {makler, interessent};

        Opportunity opp = TestDataFactory.createOpportunity(false, interessent.Id, makler.Id, immobilie.Id, appartment.Id, 'Geschlossene und gewonnene', 100000);
        opp.Abrechnung_ber__c = makler.Id;
        opp.Immobilienberater__c = makler.Id;
        insert opp;
    }
    
    @IsTest
    private static void testNewRechnungSetsRateValues() {
        Opportunity opp = [SELECT Id, beurkundeter_Kaufpreis__c FROM Opportunity LIMIT 1];
        System.debug(opp.beurkundeter_Kaufpreis__c);
        Property__c immo = [SELECT Id FROM Property__c LIMIT 1];
        
        MaBVRate__c rate = TestDataFactory.createMaBVRate(true, immo.Id, 0.5);
        
        List<MaBVRechnungMaster__c> masterList = new List<MaBVRechnungMaster__c>();

        for(Integer i = 0; i < 1; i++) { //CS-160: Set to 1 to fix testclass because of failing MaBVRechnungenBatch
            masterList.add(TestDataFactory.createMaBVRechnungMaster(false, opp.Id, rate.Id));
        }
        insert masterList;

        List<MaBVRechnung__c> rechnungen = new List<MaBVRechnung__c>();
        for(MaBVRechnungMaster__c master : masterList) {
            for(Integer i = 0; i < 3; i++) {
                MaBVRechnung__c rechnung = TestDataFactory.createMaBVRechnung(false, '123-123-1-' + i, master.Id);
                rechnungen.add(rechnung);
            }
        }

        insert rechnungen;

        System.debug([SELECT RateInEuro__c, OffenerBetragNeu__c FROM MaBVRechnung__c]);
        Double rateGesamtInEuro = [SELECT RateGesamtInEuro__c FROM MaBVRechnung__c WHERE Id IN :rechnungen LIMIT 1].RateGesamtInEuro__c; 

        List<Zahlung__c> zahlungen = new List<Zahlung__c>();
        for(MaBVRechnung__c rechnung : rechnungen) {
            if(rechnung.Name.endsWith('1')) {
                zahlungen.add(TestDataFactory.createZahlung(false, rateGesamtInEuro, rechnung.Id));
            }
        }

        Test.startTest();
        insert zahlungen;
        Test.stopTest();

        System.debug([SELECT OffenerBetragNeu__c, Bezahlt__c, RateGesamtInEuro__c, IstBezahlt__c FROM MaBVRechnung__c WHERE Id NOT IN (SELECT MaBVRechnung__c FROM Zahlung__c)]);

        rate = [SELECT GesamtanzahlRechnungen__c, OffeneRechnungen__c, GezahlteRechnungen__c, SummeGezahlterRechnungen__c, SummeOffenerRechnungen__c FROM MaBVRate__c WHERE Id = :rate.Id]; 
        System.assertEquals(3, rate.GesamtanzahlRechnungen__c);
        System.assertEquals(2, rate.OffeneRechnungen__c);
        System.assertEquals(1, rate.GezahlteRechnungen__c);
        System.assertEquals(472.5, rate.SummeGezahlterRechnungen__c);
        System.assertEquals(945, rate.SummeOffenerRechnungen__c);
    }

    @IsTest
    private static void testUpdateZahlungSetsRateValues() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Property__c immo = [SELECT Id FROM Property__c LIMIT 1];
        
        MaBVRate__c rate = TestDataFactory.createMaBVRate(true, immo.Id, 0.5);
        
        List<MaBVRechnungMaster__c> masterList = new List<MaBVRechnungMaster__c>();

        for(Integer i = 0; i < 1; i++) { //CS-160: Set to 1 to fix testclass because of failing MaBVRechnungenBatch
            masterList.add(TestDataFactory.createMaBVRechnungMaster(false, opp.Id, rate.Id));
        }
        insert masterList;

        List<MaBVRechnung__c> rechnungen = new List<MaBVRechnung__c>();
        for(MaBVRechnungMaster__c master : masterList) {
            for(Integer i = 0; i < 3; i++) {
                MaBVRechnung__c rechnung = TestDataFactory.createMaBVRechnung(false, '123-123-1-' + i, master.Id); 
                rechnungen.add(rechnung);
            }
        }

        insert rechnungen;

        Double rateGesamtInEuro = [SELECT RateGesamtInEuro__c FROM MaBVRechnung__c WHERE Id IN :rechnungen LIMIT 1].RateGesamtInEuro__c; 

        List<Zahlung__c> zahlungen = new List<Zahlung__c>();
        for(MaBVRechnung__c rechnung : rechnungen) {
            if(rechnung.Name.endsWith('1')) {
                zahlungen.add(TestDataFactory.createZahlung(false, 0, rechnung.Id));
            }
        }

        Test.startTest();
        insert zahlungen;

        for(Zahlung__c zahlung : zahlungen) {
            zahlung.Betrag__c = rateGesamtInEuro;
        }

        update zahlungen;

        Test.stopTest();

        System.debug([SELECT OffenerBetragNeu__c, Bezahlt__c, RateGesamtInEuro__c, IstBezahlt__c FROM MaBVRechnung__c WHERE Id IN (SELECT MaBVRechnung__c FROM Zahlung__c)]);

        rate = [SELECT GesamtanzahlRechnungen__c, OffeneRechnungen__c, GezahlteRechnungen__c, SummeGezahlterRechnungen__c, SummeOffenerRechnungen__c FROM MaBVRate__c WHERE Id = :rate.Id]; 
        System.assertEquals(3, rate.GesamtanzahlRechnungen__c);
        System.assertEquals(2, rate.OffeneRechnungen__c);
        System.assertEquals(1, rate.GezahlteRechnungen__c);
        System.assertEquals(472.5, rate.SummeGezahlterRechnungen__c);
        System.assertEquals(945, rate.SummeOffenerRechnungen__c);
    }


    @IsTest
    private static void testDeleteRechnungSetsRateValues() {
        
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Property__c immo = [SELECT Id FROM Property__c LIMIT 1];
        
        MaBVRate__c rate = TestDataFactory.createMaBVRate(true, immo.Id, 0.5);
        
        List<MaBVRechnungMaster__c> masterList = new List<MaBVRechnungMaster__c>();

        for(Integer i = 0; i < 1; i++) { //CS-160: Set to 1 to fix testclass because of failing MaBVRechnungenBatch
            masterList.add(TestDataFactory.createMaBVRechnungMaster(false, opp.Id, rate.Id));
        }
        insert masterList;

        List<MaBVRechnung__c> rechnungen = new List<MaBVRechnung__c>();
        for(MaBVRechnungMaster__c master : masterList) {
            for(Integer i = 0; i < 3; i++) {
                MaBVRechnung__c rechnung = TestDataFactory.createMaBVRechnung(false, '123-123-1-' + i, master.Id); 
                rechnungen.add(rechnung);
            }
        }

        insert rechnungen;

        Test.startTest();
        delete [SELECT Id FROM MaBVRechnung__c LIMIT 1];
        delete [SELECT Id FROM Zahlung__c LIMIT 1];
        Test.stopTest();

        rate = [SELECT GesamtanzahlRechnungen__c, OffeneRechnungen__c, GezahlteRechnungen__c, SummeGezahlterRechnungen__c, SummeOffenerRechnungen__c FROM MaBVRate__c WHERE Id = :rate.Id]; 
        System.assertEquals(2, rate.GesamtanzahlRechnungen__c);
        System.assertEquals(2, rate.OffeneRechnungen__c);
    }
}