force-app/main/default/objects/Account/fields/AnzahlBewertungen__c.field-meta.xml
<CustomField>
    <fullName>AnzahlBewertungen__c</fullName>
    <label>Anzahl Bewertungen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DurchschnittBewertungen__c.field-meta.xml
<CustomField>
    <fullName>DurchschnittBewertungen__c</fullName>
    <label>Durchschnitt Bewertungen</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/FacebookUrl__c.field-meta.xml
<CustomField>
    <fullName>FacebookUrl__c</fullName>
    <label>Facebook Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Feldaenderungen__c.field-meta.xml
<CustomField>
    <fullName>Feldaenderungen__c</fullName>
    <label>Feldänderungen</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GoogleMyBusinessUrl__c.field-meta.xml
<CustomField>
    <fullName>GoogleMyBusinessUrl__c</fullName>
    <label>Google My Business Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gruendungsjahr__c.field-meta.xml
<CustomField>
    <fullName>Gruendungsjahr__c</fullName>
    <label>Gründungsjahr</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/InstagramUrl__c.field-meta.xml
<CustomField>
    <fullName>InstagramUrl__c</fullName>
    <label>Instagram Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/LinkedInUrl__c.field-meta.xml
<CustomField>
    <fullName>LinkedInUrl__c</fullName>
    <label>LinkedIn Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/NamePotenzialanalyse__c.field-meta.xml
<CustomField>
    <fullName>NamePotenzialanalyse__c</fullName>
    <inlineHelpText>Der Name der als Ergebnis der Potenzialanalyse gefunden wurde. Falls richtig, bitte den Account-Namen damit ersetzen</inlineHelpText>
    <label>Name Potenzialanalyse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NewsArtikel__c.field-meta.xml
<CustomField>
    <fullName>NewsArtikel__c</fullName>
    <label>News Artikel</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Potenzialanalyse__c.field-meta.xml
<CustomField>
    <fullName>Potenzialanalyse__c</fullName>
    <label>Potenzialanalyse</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/PotenzialanalyseErfasst__c.field-meta.xml
<CustomField>
    <fullName>PotenzialanalyseErfasst__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Potenzialanalyse erfasst</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PotenzialanalyseErfasstAm__c.field-meta.xml
<CustomField>
    <fullName>PotenzialanalyseErfasstAm__c</fullName>
    <label>Potenzialanalyse erfasst am</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaererAnsprechpartner__c.field-meta.xml
<CustomField>
    <fullName>PrimaererAnsprechpartner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primärer Ansprechpartner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primärer Ansprechpartner)</relationshipLabel>
    <relationshipName>AccountsPrimaryContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rechtsform__c.field-meta.xml
<CustomField>
    <fullName>Rechtsform__c</fullName>
    <label>Rechtsform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TrustpilotUrl__c.field-meta.xml
<CustomField>
    <fullName>TrustpilotUrl__c</fullName>
    <label>Trustpilot Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/XingUrl__c.field-meta.xml
<CustomField>
    <fullName>XingUrl__c</fullName>
    <label>Xing Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Feldaenderungen__c.field-meta.xml
<CustomField>
    <fullName>Feldaenderungen__c</fullName>
    <label>Feldänderungen</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Position_Abteilung__c.field-meta.xml
<CustomField>
    <fullName>Position_Abteilung__c</fullName>
    <description>Hier soll die Position (vor allem Geschäftsführung/Inhaber) oder eine Abteilung angeben werden, um später besser selektieren zu können</description>
    <inlineHelpText>Bitte mindestens eine Position/Zuordnung (z.B. Geschäftsführer) auswählen</inlineHelpText>
    <label>Position/Abteilung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Privatperson (ohne Firma)</fullName>
                <default>true</default>
                <label>Privatperson (ohne Firma)</label>
            </value>
            <value>
                <fullName>------------------------------------</fullName>
            </value>
            <value>
                <fullName>Firmeninhaber</fullName>
            </value>
            <value>
                <fullName>Primärer Ansprechpartner</fullName>
            </value>
            <value>
                <fullName>Geschäftsführer/Vorstand</fullName>
            </value>
            <value>
                <fullName>Leitender Angestellter</fullName>
            </value>
            <value>
                <fullName>Vertriebsleiter</fullName>
            </value>
            <value>
                <fullName>Vertrieb</fullName>
            </value>
            <value>
                <fullName>Sachbearbeiter</fullName>
            </value>
            <value>
                <fullName>Buchhaltung</fullName>
            </value>
            <value>
                <fullName>Kundenservice</fullName>
            </value>
            <value>
                <fullName>Assistenz</fullName>
            </value>
            <value>
                <fullName>Sonstige</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompanyImportAPI.cls
@RestResource(urlMapping='/CompanyImportAPI/*')
global with sharing class CompanyImportAPI {
    
    global class NewsArticle {
        public String title;
        public String url;
    }

    global class CompanyDTO {
        public String accountId;
        public String name;
        public String legalName;
        public String legalForm;
        public String street;
        public String postalCode;
        public String city;
        public String websiteUrl;
        public String facebookUrl;
        public String instagramUrl;
        public String linkedInUrl;
        public String xingUrl;
        public String trustpilotUrl;
        public String googleMyBusinessUrl;
        public Integer ratings;
        public Decimal ratingsAverage;
        public String phone;
        public String email;
        public Integer foundationYear;
        public String aiSummary;
        public Integer employees;
        public List<NewsArticle> newsArticles;
        public String industry;
    }

    global class ContactDTO {
        public String salutation;
        public String firstName;
        public String lastName;
        public String email;
        public String phone;
        public String role;
        public String existingContactId;
    }

    global class RequestWrapper {
        public CompanyDTO company;
        public ContactDTO primaryContact;
        public List<ContactDTO> contacts;
    }

    @HttpPost
    global static void handlePost() {
        RestRequest req = RestContext.request;
        RequestWrapper input = (RequestWrapper) JSON.deserialize(req.requestBody.toString(), RequestWrapper.class);

        if (input == null || input.company == null) {
            throw new AuraHandledException('Invalid payload');
        }

        String changeLog = '';
        Account acc = [SELECT Id, NamePotenzialanalyse__c, Unternehmensname__c, Rechtsform__c, BillingStreet, BillingPostalCode,
                       BillingCity, Website, FacebookUrl__c, InstagramUrl__c, LinkedInUrl__c, XingUrl__c,
                       TrustpilotUrl__c, GoogleMyBusinessUrl__c, AnzahlBewertungen__c, DurchschnittBewertungen__c,
                       Phone, Email__c, Gruendungsjahr__c, NumberOfEmployees, Industry
                       FROM Account WHERE Id = :input.company.accountId LIMIT 1];

        // Set RecordType and Industry
        acc.RecordTypeId = '01267000000OmcUAAS';
        List<String> allowedIndustries = new List<String>{
            'Immobilienmakler', 'Finanzmakler', 'Versicherungsmakler', 'Bank', 'Pflegeimmobilienspezialist'
        };
        String industryInput = input.company.industry;
        if (String.isNotBlank(industryInput) && allowedIndustries.contains(industryInput)) {
            acc.Industry = industryInput;
        } else {
            acc.Industry = 'Andere';
        }

        // Track and update fields
        changeLog += compareAndUpdate(acc, 'NamePotenzialanalyse__c', acc.NamePotenzialanalyse__c, input.company.name);
        changeLog += compareAndUpdate(acc, 'Unternehmensname__c', acc.Unternehmensname__c, input.company.legalName);
        changeLog += compareAndUpdate(acc, 'Rechtsform__c', acc.Rechtsform__c, input.company.legalForm);
        changeLog += compareAndUpdate(acc, 'BillingStreet', acc.BillingStreet, input.company.street);
        changeLog += compareAndUpdate(acc, 'BillingPostalCode', acc.BillingPostalCode, input.company.postalCode);
        changeLog += compareAndUpdate(acc, 'BillingCity', acc.BillingCity, input.company.city);
        changeLog += compareAndUpdate(acc, 'Website', acc.Website, input.company.websiteUrl);
        changeLog += compareAndUpdate(acc, 'FacebookUrl__c', acc.FacebookUrl__c, input.company.facebookUrl);
        changeLog += compareAndUpdate(acc, 'InstagramUrl__c', acc.InstagramUrl__c, input.company.instagramUrl);
        changeLog += compareAndUpdate(acc, 'LinkedInUrl__c', acc.LinkedInUrl__c, input.company.linkedInUrl);
        changeLog += compareAndUpdate(acc, 'XingUrl__c', acc.XingUrl__c, input.company.xingUrl);
        changeLog += compareAndUpdate(acc, 'TrustpilotUrl__c', acc.TrustpilotUrl__c, input.company.trustpilotUrl);
        changeLog += compareAndUpdate(acc, 'GoogleMyBusinessUrl__c', acc.GoogleMyBusinessUrl__c, input.company.googleMyBusinessUrl);
        changeLog += compareAndUpdate(acc, 'Phone', acc.Phone, input.company.phone);
        changeLog += compareAndUpdate(acc, 'Email__c', acc.Email__c, input.company.email);
        changeLog += compareAndUpdate(acc, 'Gruendungsjahr__c', acc.Gruendungsjahr__c != null ? acc.Gruendungsjahr__c : null, input.company.foundationYear != null ? input.company.foundationYear : null);
        changeLog += compareAndUpdate(acc, 'NumberOfEmployees', acc.NumberOfEmployees != null ? acc.NumberOfEmployees : null, input.company.employees != null ? input.company.employees : null);
        changeLog += compareAndUpdate(acc, 'AnzahlBewertungen__c', acc.AnzahlBewertungen__c != null ? acc.AnzahlBewertungen__c : null, input.company.ratings != null ? input.company.ratings : null);
        changeLog += compareAndUpdate(acc, 'DurchschnittBewertungen__c', acc.DurchschnittBewertungen__c != null ? acc.DurchschnittBewertungen__c : null, input.company.ratingsAverage != null ? input.company.ratingsAverage : null);

        acc.Potenzialanalyse__c = input.company.aiSummary;
        acc.PotenzialanalyseErfasst__c = true;
        acc.PotenzialanalyseErfasstAm__c = Date.today();

        if (input.company.newsArticles != null && !input.company.newsArticles.isEmpty()) {
            List<String> articleStrings = new List<String>();
            for (NewsArticle a : input.company.newsArticles) {
                articleStrings.add(a.title + ': ' + a.url);
            }
            acc.NewsArtikel__c = String.join(articleStrings, '\r\n');
        }

        acc.Feldaenderungen__c = changeLog.trim();
        update acc;

        // Primary Contact
        Contact primary;
        if (String.isNotBlank(input.primaryContact?.existingContactId)) {
            primary = [SELECT Id, Salutation, FirstName, LastName, Email, Phone, Title FROM Contact WHERE Id = :input.primaryContact.existingContactId LIMIT 1];
            primary.RecordTypeId = '012b0000000UV0IAAW';
            String contactChange = '';
            contactChange += compareAndUpdate(primary, 'Salutation', primary.Salutation, input.primaryContact.salutation);
            contactChange += compareAndUpdate(primary, 'FirstName', primary.FirstName, input.primaryContact.firstName);
            contactChange += compareAndUpdate(primary, 'LastName', primary.LastName, input.primaryContact.lastName);
            contactChange += compareAndUpdate(primary, 'Email', primary.Email, input.primaryContact.email);
            contactChange += compareAndUpdate(primary, 'Phone', primary.Phone, input.primaryContact.phone);
            contactChange += compareAndUpdate(primary, 'Title', primary.Title, input.primaryContact.role);
            primary.Feldaenderungen__c = contactChange.trim();
            update primary;
        } else if(input.primaryContact != null && input.primaryContact?.LastName != null) {
            primary = new Contact(
                AccountId = acc.Id,
                RecordTypeId = '012b0000000UV0IAAW',
                Salutation = input.primaryContact.salutation,
                FirstName = input.primaryContact.firstName,
                LastName = input.primaryContact.lastName,
                Email = input.primaryContact.email,
                Phone = input.primaryContact.phone,
                Title = input.primaryContact.role,
                Position_Abteilung__c = 'Sonstige',
                Gesch_ftsbeziehung__c = 'Mitarbeiter'
            );
            insert primary;
        }

        if(primary != null) {
            acc.PrimaererAnsprechpartner__c = primary.Id;
            update acc;
        }

        // Other contacts
        List<Contact> newContacts = new List<Contact>();
        if(input.contacts != null) {
            for (ContactDTO c : input.contacts) {
                if (String.isNotBlank(c.existingContactId)) {
                    Contact con = [SELECT Id, Salutation, FirstName, LastName, Email, Phone, Title FROM Contact WHERE Id = :c.existingContactId LIMIT 1];
                    con.RecordTypeId = '012b0000000UV0IAAW';
                    con.Salutation = c.salutation;
                    con.FirstName = c.firstName;
                    con.LastName = c.lastName;
                    con.Email = c.email;
                    con.Phone = c.phone;
                    con.Title = c.role;
                    update con;
                } else if(String.isNotBlank(c.lastName)) {
                    newContacts.add(new Contact(
                        AccountId = acc.Id,
                        RecordTypeId = '012b0000000UV0IAAW',
                        Salutation = c.salutation,
                        FirstName = c.firstName,
                        LastName = c.lastName,
                        Email = c.email,
                        Phone = c.phone,
                        Title = c.role,
                        Position_Abteilung__c = 'Sonstige',
                        Gesch_ftsbeziehung__c = 'Mitarbeiter'
                    ));
                }
            }
        }

        if (!newContacts.isEmpty()) {
            insert newContacts;
        }

        AccountService.updateAccountScore(new List<Id>{ acc.Id });
    }

    private static String compareAndUpdate(SObject obj, String field, Object oldValRaw, Object newValRaw) {
        String oldValue = oldValRaw == null ? null : String.valueOf(oldValRaw);
        String newValue = newValRaw == null ? null : String.valueOf(newValRaw);
        
        if (newValue == null || oldValue == newValue) return '';
        obj.put(field, newValRaw); // set with original data type

        if (String.isBlank(oldValue)) {
            return fieldLabel(field) + ' von leer auf "' + newValue + '" geupdated\r\n';
        } else {
            return fieldLabel(field) + ' von "' + oldValue + '" auf "' + newValue + '" geupdated\r\n';
        }
    }


    private static String fieldLabel(String apiName) {
        Map<String, String> labels = new Map<String, String>{
            'NamePotenzialanalyse__c' => 'Name Potenzialanalyse',
            'Unternehmensname__c' => 'Unternehmensname',
            'Rechtsform__c' => 'Rechtsform',
            'BillingStreet' => 'Straße',
            'BillingPostalCode' => 'PLZ',
            'BillingCity' => 'Stadt',
            'Website' => 'Website',
            'FacebookUrl__c' => 'Facebook URL',
            'InstagramUrl__c' => 'Instagram URL',
            'LinkedInUrl__c' => 'LinkedIn URL',
            'XingUrl__c' => 'Xing URL',
            'TrustpilotUrl__c' => 'Trustpilot URL',
            'GoogleMyBusinessUrl__c' => 'Google Business URL',
            'Phone' => 'Telefon',
            'Email__c' => 'E-Mail',
            'Gruendungsjahr__c' => 'Gründungsjahr',
            'NumberOfEmployees' => 'Mitarbeiteranzahl',
            'AnzahlBewertungen__c' => 'Anzahl Bewertungen',
            'DurchschnittBewertungen__c' => 'Durchschnitt Bewertungen',
            'Salutation' => 'Anrede',
            'FirstName' => 'Vorname',
            'LastName' => 'Nachname',
            'Email' => 'E-Mail',
            'Title' => 'Rolle'
        };
        return labels.containsKey(apiName) ? labels.get(apiName) : apiName;
    }
}