force-app/main/default/objects/Account/fields/CalculationsCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>CalculationsCurrentYear__c</fullName>
    <label>Berechnungen aktuelles Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomersCreatedCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>CustomersCreatedCurrentYear__c</fullName>
    <label>Angelegte Interessenten aktuelles Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IncomingCallsCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallsCurrentYear__c</fullName>
    <label>Anzahl eingehende Telefonate dieses Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastCalculation__c.field-meta.xml
<CustomField>
    <fullName>LastCalculation__c</fullName>
    <label>Datum letzte Berechnung</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastIncomingCall__c.field-meta.xml
<CustomField>
    <fullName>LastIncomingCall__c</fullName>
    <label>Datum letztes eingehendes Telefonat</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastOutgoingCall__c.field-meta.xml
<CustomField>
    <fullName>LastOutgoingCall__c</fullName>
    <label>Datum letztes ausgehendes Telefonat</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/OutgoingCallsCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>OutgoingCallsCurrentYear__c</fullName>
    <label>Anzahl ausgehende Telefonate dieses Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/VPUserLastLogin__c.field-meta.xml
<CustomField>
    <fullName>VPUserLastLogin__c</fullName>
    <label>VP Benutzer Letzter Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Brokerage.recordType-meta.xml
<RecordType>
    <fullName>Brokerage</fullName>
    <active>true</active>
    <label>Vertriebspartner</label>
</RecordType>

force-app/main/default/objects/Berechnung__c/Berechnung__c.object-meta.xml
<CustomObject>
    <label>Berechnung</label>
    <nameField>
        <label>Berechnung Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Berechnung__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Berechnungen</relationshipLabel>
    <relationshipName>Berechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CommunityUser__c.field-meta.xml
<CustomField>
    <fullName>CommunityUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VPBenutzerLetzterLogin__c.field-meta.xml
<CustomField>
    <fullName>VPBenutzerLetzterLogin__c</fullName>
    <label>VP Benutzer Letzter Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Kunde.recordType-meta.xml
<RecordType>
    <fullName>Kunde</fullName>
    <active>true</active>
    <label>Kunde</label>
</RecordType>

force-app/main/default/classes/AccountActivitiesSummaryBatch.cls
public without sharing class AccountActivitiesSummaryBatch implements Database.Batchable<sObject> {
    static final DateTime FIRST_DAY_OF_CURRENT_YEAR = DateTime.newInstance(Date.today().year(), 1, 1);
    public Database.QueryLocator start(Database.BatchableContext bc) {
        system.debug('----------started-----------');
        Id brokerageRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Brokerage').getRecordTypeId();
        String query = 'SELECT Id, VPUserLastLogin__c, CalculationsCurrentYear__c, CustomersCreatedCurrentYear__c, LastCalculation__c, LastIncomingCall__c, LastOutgoingCall__c, IncomingCallsCurrentYear__c, OutgoingCallsCurrentYear__c, (SELECT Id, AccountId FROM Contacts) FROM Account WHERE RecordTypeId = :brokerageRecordTypeId';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, list<Account> scope) {

        Map<Id, Account> updateAccountsMap = new Map<Id, Account>();
        Map<Id, Account> accountIdToAccounts = new Map<Id, Account>();
        Map<Id, Contact> contactIdToContacts = new Map<Id, Contact>();
        for(Account acc:scope) {
            acc.CalculationsCurrentYear__c = 0;
            acc.CustomersCreatedCurrentYear__c = 0;
            acc.IncomingCallsCurrentYear__c = 0;
            acc.OutgoingCallsCurrentYear__c = 0;
            accountIdToAccounts.put(acc.Id, acc);
            for(Contact con:acc.Contacts) {
                contactIdToContacts.put(con.Id, con);
            }
        }

        // Created Calculations and last calculation date
        for(Berechnung__c b:[SELECT Id, Account__c, CreatedDate FROM Berechnung__c WHERE Account__c IN :accountIdToAccounts.keySet() AND CreatedDate > :FIRST_DAY_OF_CURRENT_YEAR]) {
            Account acc = accountIdToAccounts.get(b.Account__c);
            acc.CalculationsCurrentYear__c++;
            if(acc.LastCalculation__c == null || (acc.LastCalculation__c != null && b.CreatedDate > acc.LastCalculation__c)) {
                acc.LastCalculation__c = b.CreatedDate;
            } 
            updateAccountsMap.put(acc.Id, acc);
        }

        // Created Customers 
        Id interessentRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Interessent').getRecordTypeId();
        Id kundeRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Kunde').getRecordTypeId();
        for(Contact con:[SELECT Id, AccountId FROM Contact WHERE AccountId IN :accountIdToAccounts.keySet() AND CreatedBy.ContactId != null AND CreatedDate > :FIRST_DAY_OF_CURRENT_YEAR AND (RecordTypeId = :interessentRecordTypeId OR RecordTypeId = :kundeRecordTypeId)]) {
            Account acc = updateAccountsMap.get(con.AccountId) != null ? updateAccountsMap.get(con.AccountId) : accountIdToAccounts.get(con.AccountId);
            acc.CustomersCreatedCurrentYear__c++;
            updateAccountsMap.put(acc.Id, acc);
        }

        // Last Login Date
        for(Contact con:[SELECT Id, AccountId, VPBenutzerLetzterLogin__c FROM Contact WHERE AccountId IN :accountIdToAccounts.keySet() AND CommunityUser__c != null AND VPBenutzerLetzterLogin__c != null]) {
            Account acc = updateAccountsMap.get(con.AccountId) != null ? updateAccountsMap.get(con.AccountId) : accountIdToAccounts.get(con.AccountId);
            if(acc.VPUserLastLogin__c == null || (acc.VPUserLastLogin__c != null && con.VPBenutzerLetzterLogin__c > acc.VPUserLastLogin__c)) {
                acc.VPUserLastLogin__c = con.VPBenutzerLetzterLogin__c;
            }
            updateAccountsMap.put(acc.Id, acc);
        }

        // Tasks data
        for(Task t:[SELECT WhoId, WhatId, Subject, CreatedDate FROM Task WHERE CreatedDate > :FIRST_DAY_OF_CURRENT_YEAR AND WhatId IN :accountIdToAccounts.keySet()]) {
            Contact con = contactIdToContacts.get(t.WhoId);
            Account acc = updateAccountsMap.get(con.AccountId) != null ? updateAccountsMap.get(con.AccountId) : accountIdToAccounts.get(con.AccountId);
            if(t.Subject.toLowerCase().indexOf('eingehend') > -1 || t.Subject.toLowerCase().indexOf('incoming') > -1) {
                acc.IncomingCallsCurrentYear__c++;
                if(acc.LastIncomingCall__c == null || (acc.LastIncomingCall__c != null && t.CreatedDate > acc.LastIncomingCall__c)) {
                    acc.LastIncomingCall__c = t.CreatedDate;
                } 
            } else if(t.Subject.toLowerCase().indexOf('ausgehend') > -1 || t.Subject.toLowerCase().indexOf('outgoing') > -1) {
                acc.OutgoingCallsCurrentYear__c++;
                if(acc.LastOutgoingCall__c == null || (acc.LastOutgoingCall__c != null && t.CreatedDate > acc.LastOutgoingCall__c)) {
                    acc.LastOutgoingCall__c = t.CreatedDate;
                } 
            }
            updateAccountsMap.put(acc.Id, acc);
        }

        update updateAccountsMap.values();
    }

    public void finish(Database.BatchableContext BC) {
        system.debug('----------finished-----------');
    }
}