force-app/main/default/objects/Account/fields/CalculationsCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>CalculationsCurrentYear__c</fullName>
    <label>Berechnungen aktuelles Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomersCreatedCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>CustomersCreatedCurrentYear__c</fullName>
    <label>Angelegte Interessenten aktuelles Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/IncomingCallsCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallsCurrentYear__c</fullName>
    <label>Anzahl eingehende Telefonate dieses Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastCalculation__c.field-meta.xml
<CustomField>
    <fullName>LastCalculation__c</fullName>
    <label>Datum letzte Berechnung</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastIncomingCall__c.field-meta.xml
<CustomField>
    <fullName>LastIncomingCall__c</fullName>
    <label>Datum letztes eingehendes Telefonat</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastOutgoingCall__c.field-meta.xml
<CustomField>
    <fullName>LastOutgoingCall__c</fullName>
    <label>Datum letztes ausgehendes Telefonat</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/OutgoingCallsCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>OutgoingCallsCurrentYear__c</fullName>
    <label>Anzahl ausgehende Telefonate dieses Jahr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/VPUserLastLogin__c.field-meta.xml
<CustomField>
    <fullName>VPUserLastLogin__c</fullName>
    <label>VP Benutzer Letzter Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/Berechnung__c.object-meta.xml
<CustomObject>
    <label>Berechnung</label>
    <nameField>
        <label>Berechnung Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/CommunityUser__c.field-meta.xml
<CustomField>
    <fullName>CommunityUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VPBenutzerLetzterLogin__c.field-meta.xml
<CustomField>
    <fullName>VPBenutzerLetzterLogin__c</fullName>
    <label>VP Benutzer Letzter Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountActivitiesSummaryTest.cls
@isTest
private class AccountActivitiesSummaryTest {
    @isTest
    private static void testAccountActivitiesSummary(){
        Account acc = TestDataFactory.createAccount(true);
        User testUser = TestDataFactory.createCommunityUser(acc.Id);
        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id LIMIT 1];
        con.VPBenutzerLetzterLogin__c = DateTime.now();
        con.CommunityUser__c = testUser.Id;
        update con;
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Property__c p = TestDataFactory.createProperty(true, bautraeger.Id);
        Task incomingCallTask = TestDataFactory.createTask(true, con.Id, 'Eingehender Anruf');
        Task outgoingCallTask = TestDataFactory.createTask(true, con.Id, 'Ausgehender Anruf');
        
        Berechnung__c b;
        Test.startTest();
        System.RunAs(testUser){
            TestDataFactory.createInteressent(true, acc.Id);
            b = TestDataFactory.createCalculation(true, con.Id);
        }
        AccountActivitiesSummarySchedulable.scheduleMe();
        Database.executeBatch(new AccountActivitiesSummaryBatch());
        Test.stopTest();
        
        acc = [SELECT VPUserLastLogin__c, CalculationsCurrentYear__c, CustomersCreatedCurrentYear__c, IncomingCallsCurrentYear__c, OutgoingCallsCurrentYear__c, LastOutgoingCall__c, LastIncomingCall__c, LastCalculation__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(1, acc.CalculationsCurrentYear__c, 'Expected 1 created calculation');
        System.assertEquals(1, acc.CustomersCreatedCurrentYear__c, 'Expected 1 created customer');
        System.assertEquals(1, acc.IncomingCallsCurrentYear__c, 'Expected 1 incoming call');
        System.assertEquals(1, acc.OutgoingCallsCurrentYear__c, 'Expected 1 outgoing call');
        outgoingCallTask = [SELECT CreatedDate FROM Task WHERE Id = :outgoingCallTask.Id];
        incomingCallTask = [SELECT CreatedDate FROM Task WHERE Id = :incomingCallTask.Id];
        System.assertEquals(outgoingCallTask.CreatedDate, acc.LastOutgoingCall__c, 'Expected last outgoing call to match with task created date');
        System.assertEquals(incomingCallTask.CreatedDate, acc.LastIncomingCall__c, 'Expected last incoming call to match with task created date');
        b = [SELECT CreatedDate FROM Berechnung__c WHERE Id = :b.Id];
        System.assertEquals(b.CreatedDate, acc.LastCalculation__c, 'Expected last calculation to match with calculation created date');
        System.assertEquals(con.VPBenutzerLetzterLogin__c, acc.VPUserLastLogin__c, 'Expected last login to match with contact last login date');
    }
}