force-app/main/default/objects/Account/fields/Carestone_Vertriebsvereinbarung__c.field-meta.xml
<CustomField>
    <fullName>Carestone_Vertriebsvereinbarung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carestone Vertriebsvereinbarung</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/WHS_Maklerauftrag__c.field-meta.xml
<CustomField>
    <fullName>WHS_Maklerauftrag__c</fullName>
    <description>Abbildung des Prozesses zur Auslösung eines Maklerauftrags; letzter Status heisst unterschrieben vom Vorstand und versendet an den Makler (d.h. Vereinbarung ist ab diesem Tag gültig)</description>
    <inlineHelpText>Abbildung des Prozesses zur Auslösung eines Maklerauftrags; letzter Status heisst unterschrieben vom Vorstand und versendet an den Makler (d.h. Vereinbarung ist ab diesem Tag gültig)</inlineHelpText>
    <label>WH Maklerauftrag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Keine Vereinbarung</fullName>
                <default>true</default>
                <label>Keine Vereinbarung</label>
            </value>
            <value>
                <fullName>Vom Maklerbetreuer angefordert</fullName>
            </value>
            <value>
                <fullName>Erstellt und an Makler versendet</fullName>
            </value>
            <value>
                <fullName>Unterschrieben eingegangen</fullName>
            </value>
            <value>
                <fullName>Maklerauftrag beidseitig unterzeichnet</fullName>
            </value>
            <value>
                <fullName>Makler mit altem Vertrag</fullName>
            </value>
            <value>
                <fullName>Makler ohne eigenen Vertrag</fullName>
            </value>
            <value>
                <fullName>Vom Makler gekündigt</fullName>
            </value>
            <value>
                <fullName>Vom WH gekündigt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Objektliste_abbestellen__c.field-meta.xml
<CustomField>
    <fullName>Objektliste_abbestellen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E-Mail Objektliste abbestellen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/classes/ImmobilienAsExcelBatch.cls
global without sharing class ImmobilienAsExcelBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        String query = 'SELECT Id, Gesch_ftsbeziehung__c, Email, Account.Maklerbetreuer_Wirtschaftshaus_2__r.Name FROM Contact WHERE HasOptedOutOfEmail = FALSE AND Objektliste_abbestellen__c = FALSE AND Gesch_ftsbeziehung__c includes (\'Finanzmakler\',\'Finanz- und Versicherungsmakler\', \'Immobilien- oder Versicherungsmakler\', \'Versicherungsmakler\', \'Immobilienmakler\', \'Mitarbeiter WH\') AND Gesch_ftsbeziehung__c != null AND Email != null AND (Account.WHS_Maklerauftrag__c = \'Maklerauftrag beidseitig unterzeichnet\' OR Account.WHS_Maklerauftrag__c = \'Makler mit altem Vertrag\' OR Account.Carestone_Vertriebsvereinbarung__c = true) Order By AccountId';
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<Contact> scope)
    {
        ImmobilienAsExcel iae = new ImmobilienAsExcel();
        iae.sendexcelfile(scope);
    }  
    global void finish(Database.BatchableContext BC)
    {
    }
}