force-app/main/default/objects/Account/fields/Carestone_Vertriebsvereinbarung__c.field-meta.xml
<CustomField>
    <fullName>Carestone_Vertriebsvereinbarung__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carestone Vertriebsvereinbarung</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Makler ist auf unbestimmte Zeit geschützt</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/GeschaeftsfuehrerNeu__c.field-meta.xml
<CustomField>
    <fullName>GeschaeftsfuehrerNeu__c</fullName>
    <label>Geschäftsführer</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesetzliche_MwSt_auf_Provisionszahlung__c.field-meta.xml
<CustomField>
    <fullName>Gesetzliche_MwSt_auf_Provisionszahlung__c</fullName>
    <label>Gesetzliche MwSt. auf Provisionszahlung</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hinweis_zur_MwSt__c.field-meta.xml
<CustomField>
    <fullName>Hinweis_zur_MwSt__c</fullName>
    <inlineHelpText>Bitte gib hier an, woher die Information kommt, welchen MwSt-Satz der Makler hat</inlineHelpText>
    <label>Hinweis zur MwSt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rechtsform__c.field-meta.xml
<CustomField>
    <fullName>Rechtsform__c</fullName>
    <label>Rechtsform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RestAccountHierarchyTest.cls
@isTest
private class RestAccountHierarchyTest {

	@isTest static void TestAccountHiearchyWithZeroLevels() {
		// TestClass with no of hierarchy
		Account acc = TestDataFactory.createAccount(true);

		RestAccountHierarchy.show(acc.Id);
	}

	@isTest static void TestAccountHiearchyWithOneLevel() {
		// TestClass with one level of hierarchy
		Account acc = TestDataFactory.createAccount(true);

		Account childAccount = TestDataFactory.createAccount(true, 'TestAccount2', null);
		childAccount.ParentId = acc.Id;
		update childAccount;

		RestAccountHierarchy.show(acc.Id);
	}

	@isTest static void TestAccountHiearchyWithTwoLevels() {
		// TestClass with multiple levels of hierarchy
		Account acc = TestDataFactory.createAccount(true);

		Account childAccount = TestDataFactory.createAccount(true, 'TestAccount2', null);
		childAccount.ParentId = acc.Id;
		update childAccount;

		Database.DMLOptions dml = new Database.DMLOptions();
		dml.DuplicateRuleHeader.AllowSave = true;

		Account childChildAccount = new Account();

		childChildAccount.Name = 'TestAccount3';
		childChildAccount.Email__c = 'f.witte@wirtschaftshaus.de';
		childChildAccount.BIC__c  = 'SPKHDE2HXXX';
		childChildAccount.GeschaeftsfuehrerNeu__c = 'Sandro Pawils';
		childChildAccount.Gesetzliche_MwSt_auf_Provisionszahlung__c = 0.4;
		childChildAccount.Hinweis_zur_MwSt__c = 'Vertrag';
		childChildAccount.IBAN__c = 'DE43250501801900212158';
		childChildAccount.Rechtsform__c = 'GbR';
		childChildAccount.Unternehmensname__c = 'CareStone';
		childChildAccount.Carestone_Vertriebsvereinbarung__c = true;
		childChildAccount.Dauerhaft_gesch_tzt__c = true;
		childChildAccount.ParentId = childAccount.Id;

		Database.insert(childChildAccount, dml);

		RestAccountHierarchy.show(acc.Id);
	}

}