force-app/main/default/objects/Account/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Makler ist auf unbestimmte Zeit geschützt</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerschutz_besteht__c.field-meta.xml
<CustomField>
    <fullName>Maklerschutz_besteht__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Wenn angehakt besteht aktuell ein Maklerschutz für den Makler</inlineHelpText>
    <label>Maklerschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Kontakt hat bereits ein Apartment gekauft und ist somit dauerhaft geschützt.</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Kunden_Maklerschutz__c.field-meta.xml
<CustomField>
    <fullName>Kunden_Maklerschutz__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kundenschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maklerschutz_besteht__c.field-meta.xml
<CustomField>
    <fullName>Maklerschutz_besteht__c</fullName>
    <formula>if(INCLUDES(Gesch_ftsbeziehung__c, &quot;Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Immobilienmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Immobilien- oder Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Finanz- und Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Finanzmakler&quot;), Account.Maklerschutz_besteht__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Liegt auf der Accountebene</inlineHelpText>
    <label>Maklerschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GlobalSearchController.cls
public class GlobalSearchController {

    public GlobalSearchController() {

    }

    List < List < SObject >> searchList = new List < List < SObject >> ();

    Public String searchValue {
        get;
        set;
    }

    // Searches Accounts, Contacts and Leads with the value of the inputText field "searchValue" and sets the searchList with these values
    public void search() {
        searchList = [FIND: searchValue IN ALL FIELDS RETURNING Account(Id, Name, Maklerbetreuer_Wirtschaftshaus_2__r.FirstName, Maklerbetreuer_Wirtschaftshaus_2__r.LastName, Email__c, Maklerschutz_besteht__c, Dauerhaft_gesch_tzt__c), Contact(FirstName, LastName, Email, Kunden_Maklerschutz__c, Maklerschutz_besteht__c, Account.Name, Account.Maklerbetreuer_Wirtschaftshaus_2__r.FirstName, Account.Maklerbetreuer_Wirtschaftshaus_2__r.LastName, MailingPostalCode, Dauerhaft_gesch_tzt__c), Lead(FirstName, Email, CreatedDate, LastName, PostalCode)];
    }

    // Returns either null if nothing is searched yet, or the List of Contacts
    public List < Contact > getPossibleDups() {
        if (searchList.size() > 0) {
            return ((List < Contact > ) searchList[1]);
        }
        return null;
    }

    // Returns either null if nothing is searched yet, or the List of Leads
    public List < Lead > getPossibleDupLeads() {
        if (searchList.size() > 0) {
            return ((List < Lead > ) searchList[2]);
        }
        return null;
    }

    // Returns either null if nothing is searched yet, or the List of Accounts
    public List < Account > getPossibleDupAccounts() {
        if (searchList.size() > 0) {
            return ((List < Account >) searchList[0]);
        }
        return null;
    }
}