force-app/main/default/objects/Account/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Makler ist auf unbestimmte Zeit geschützt</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerschutz_besteht__c.field-meta.xml
<CustomField>
    <fullName>Maklerschutz_besteht__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Wenn angehakt besteht aktuell ein Maklerschutz für den Makler</inlineHelpText>
    <label>Maklerschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerschutz_bis__c.field-meta.xml
<CustomField>
    <fullName>Maklerschutz_bis__c</fullName>
    <inlineHelpText>Das Datum, bis zu welchem ein Makler geschützt ist</inlineHelpText>
    <label>Maklerschutz bis</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Art_des_Termins__c.field-meta.xml
<CustomField>
    <fullName>Art_des_Termins__c</fullName>
    <label>Art des Termins</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Persönlich</fullName>
            </value>
            <value>
                <fullName>Telefonisch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Datum_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Datum_Meeting__c</fullName>
    <label>Datum Meeting</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Dauerhaft_gesch_tzt__c.field-meta.xml
<CustomField>
    <fullName>Dauerhaft_gesch_tzt__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Dieser Kontakt hat bereits ein Apartment gekauft und ist somit dauerhaft geschützt.</inlineHelpText>
    <label>Dauerhaft geschützt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/E_Mail_Portalnutzer__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_Portalnutzer__c</fullName>
    <label>E-Mail Portalnutzer</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Firma__c.field-meta.xml
<CustomField>
    <fullName>Firma__c</fullName>
    <label>Firma</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/In_Genehmigungsprozess__c.field-meta.xml
<CustomField>
    <fullName>In_Genehmigungsprozess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Genehmigungsprozess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Kunden_Maklerschutz__c.field-meta.xml
<CustomField>
    <fullName>Kunden_Maklerschutz__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kundenschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Kundenschutz__c.field-meta.xml
<CustomField>
    <fullName>Kundenschutz__c</fullName>
    <label>Kundenschutz bis</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Makler_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>Makler_E_Mail__c</fullName>
    <label>E-Mail übergeordneter Betreuer</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maklerschutz_besteht__c.field-meta.xml
<CustomField>
    <fullName>Maklerschutz_besteht__c</fullName>
    <formula>if(INCLUDES(Gesch_ftsbeziehung__c, &quot;Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Immobilienmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Immobilien- oder Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Finanz- und Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Finanzmakler&quot;), Account.Maklerschutz_besteht__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Liegt auf der Accountebene</inlineHelpText>
    <label>Maklerschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maklerschutz_bis__c.field-meta.xml
<CustomField>
    <fullName>Maklerschutz_bis__c</fullName>
    <formula>if(INCLUDES(Gesch_ftsbeziehung__c, &quot;Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Immobilienmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Immobilien- oder Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Finanz- und Versicherungsmakler&quot;) || INCLUDES(Gesch_ftsbeziehung__c, &quot;Finanzmakler&quot;), Account.Maklerschutz_bis__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maklerschutz bis</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kundenveranstaltung teilgenommen</fullName>
            </value>
            <value>
                <fullName>Termin/Beratung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Position_Abteilung__c.field-meta.xml
<CustomField>
    <fullName>Position_Abteilung__c</fullName>
    <description>Hier soll die Position (vor allem Geschäftsführung/Inhaber) oder eine Abteilung angeben werden, um später besser selektieren zu können</description>
    <inlineHelpText>Bitte mindestens eine Position/Zuordnung (z.B. Geschäftsführer) auswählen</inlineHelpText>
    <label>Position/Abteilung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Privatperson (ohne Firma)</fullName>
                <default>true</default>
                <label>Privatperson (ohne Firma)</label>
            </value>
            <value>
                <fullName>------------------------------------</fullName>
            </value>
            <value>
                <fullName>Firmeninhaber</fullName>
            </value>
            <value>
                <fullName>Primärer Ansprechpartner</fullName>
            </value>
            <value>
                <fullName>Geschäftsführer/Vorstand</fullName>
            </value>
            <value>
                <fullName>Leitender Angestellter</fullName>
            </value>
            <value>
                <fullName>Vertriebsleiter</fullName>
            </value>
            <value>
                <fullName>Vertrieb</fullName>
            </value>
            <value>
                <fullName>Sachbearbeiter</fullName>
            </value>
            <value>
                <fullName>Buchhaltung</fullName>
            </value>
            <value>
                <fullName>Kundenservice</fullName>
            </value>
            <value>
                <fullName>Assistenz</fullName>
            </value>
            <value>
                <fullName>Sonstige</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/classes/DupConController.cls
public with sharing class DupConController {

    private ApexPages.StandardController StandardController;
    Integer offset = 0;
    Integer size = 0;

    public DupConController(ApexPages.StandardController stdController) {
        this.StandardController = stdController;
    }

    private Contact displayCon = [SELECT Id, Position_Abteilung__c, AccountID, Account.Name, OwnerId, LastName, FirstName, Phone, MobilePhone, Firma__c, MailingStreet, MailingPostalCode, MailingCity, Meeting__c, Datum_Meeting__c, LeadSource, Email, Birthdate, Title, Salutation, Art_des_Termins__c, Makler_E_Mail__c, Kundenschutz__c, E_Mail_Portalnutzer__c, Gesch_ftsbeziehung__c FROM Contact
        WHERE Id = : ApexPages.currentPage().getParameters().get('id')
    ];

    private ID uid = UserInfo.getUserId();

    public String contIdChosen {
        get;
        set;
    }

    // The List for the possible duplicate contacts
    public List < Contact > setCon {
        get {
            if (setCon == null) {
                setCon = [SELECT id, LastName, Maklerschutz_besteht__c, Gesch_ftsbeziehung__c, Account.Name, FirstName, phone, Firma__c, MailingStreet, MailingPostalCode, MailingCity, Email, Kundenschutz__c, Dauerhaft_gesch_tzt__c FROM Contact Where LastName = : displayCon.LastName AND id != : displayCon.id];
            }
            return setCon;
        }
        set;
    }

    // Make displayCon availbe for visualforce
    public Contact getFirst() {
        return displayCon;
    }

    // Make the duplicate contact list availble for visualforce
    public List < Contact > getPossibleDups() {
        return setCon;
    }

    public List < Lead > getPossibleDupLeads() {
        return [SELECT CreatedDate, FirstName, LastName, bergeordneter_Account__c, Street, PostalCode, City, Email, Phone FROM Lead Where LastName = : displayCon.LastName];
    }

    public PageReference mergeCont() {
        mergeContacts(contIdChosen);
        return redUrl();
    }

    // Approve the contact (used by commandButton on the page)
    public PageReference approve() {
        processApproval('approve', displayCon.Id);
        return redurl();
    }

    public PageReference reject() {
        try {
            processApproval('dismiss', displayCon.Id);
            delete displayCon;
        } catch(Exception ex) {
            System.debug(ex.getMessage());
        }
        return redurl();
    }

    public PageReference redurl() {
        try {
            ProcessInstanceWorkitem process = [SELECT p.ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem p WHERE p.ProcessInstance.Status = 'Pending'
                AND p.ProcessInstance.TargetObjectId != : ApexPages.currentPage().getParameters().get('id') AND p.ProcessInstance.TargetObject.Type = 'Contact'
                AND ActorId = : uid LIMIT 1
            ];
            Id tid = process.ProcessInstance.TargetObjectId;
            return new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/apex/dupcon?id=' + tid);
        } catch (Exception e) {
            return new PageReference(URL.getSalesforceBaseUrl().toExternalForm());
        }

    }

    public void mergeContacts(String id) {
        Contact conToMerge = [SELECT OwnerID, AccountID, Makler_E_Mail__c, Meeting__c, Datum_Meeting__c, LeadSource, Email, Birthdate, Title, Salutation, Art_des_Termins__c, Position_Abteilung__c, Phone, MobilePhone, Kundenschutz__c, Kunden_Maklerschutz__c, MailingStreet, MailingPostalCode, MailingCity, OtherStreet, OtherPostalCode, OtherCity, E_Mail_Portalnutzer__c, Gesch_ftsbeziehung__c FROM Contact WHERE id = : id];
        Database.DMLOptions dml = new Database.DMLOptions();
    dml.DuplicateRuleHeader.AllowSave = true;
        if(displayCon.Phone != null)
        	conToMerge.Phone = displayCon.Phone;
        conToMerge.E_Mail_Portalnutzer__c = displayCon.E_Mail_Portalnutzer__c;
        if(displayCon.MobilePhone != null)
        	conToMerge.MobilePhone = displayCon.MobilePhone;
        conToMerge.Position_Abteilung__c = displayCon.Position_Abteilung__c;
        conToMerge.Art_des_Termins__c = displayCon.Art_des_Termins__c;
        if(displayCon.Salutation != null)
        	conToMerge.Salutation = displayCon.Salutation;
        if(displayCon.Title != null)
        	conToMerge.Title = displayCon.Title;
        if(displayCon.Birthdate != null)
        	conToMerge.Birthdate = displayCon.Birthdate;
        if(displayCon.Email != null)
        	conToMerge.Email = displayCon.Email;
        conToMerge.LeadSource = displayCon.LeadSource;
        conToMerge.Datum_Meeting__c = displayCon.Datum_Meeting__c;
        conToMerge.Meeting__c = displayCon.Meeting__c;
        conToMerge.In_GenehmigungsProzess__c = true;
        try {
            conToMerge.MailingStreet = displayCon.MailingStreet;
            conToMerge.OtherStreet = displayCon.MailingStreet;
            conToMerge.MailingPostalCode = displayCon.MailingPostalCode;
            conToMerge.OtherPostalCode = displayCon.MailingPostalCode;
            conToMerge.MailingCity = displayCon.MailingCity;
            conToMerge.OtherCity = displayCon.MailingCity;
        } catch (Exception e) {}
        String accId = displayCon.AccountID;
        conToMerge.AccountId = accId;
        Database.update(conToMerge, dml);
         try {
        	processApproval('approve', conToMerge.Id);
        } catch(Exception e) {}
        //conToMerge.accountId = accId;
        //Database.SaveResult sr = Database.update(conToMerge, dml);
        //if(!sr.isSuccess())
        //System.debug(sr.getErrors());
        System.debug('AccId After: ' + conToMerge.AccountId);
        Database.delete(displayCon);

    }

    // Processing the approval. Enter "approve" or "dismiss"
    public void processApproval(String val, String id) {
        Contact con = [SELECT Kundenschutz__c, Kunden_Maklerschutz__c, Gesch_ftsbeziehung__c, AccountId FROM Contact WHERE id = : id];
        Account acc = [SELECT Maklerschutz_besteht__c, Maklerschutz_bis__c, (SELECT ID FROM Contacts) FROM Account WHERE Id =: con.AccountId];
        Approval.ProcessWorkitemRequest req2 =
            new Approval.ProcessWorkitemRequest();
        if (val == 'approve') {
        	con.In_GenehmigungsProzess__c = false;
           if (con.Gesch_ftsbeziehung__c.contains('Interessent')) {

        } else if(acc.Contacts.size() == 1) {
            acc.Maklerschutz_bis__c = datetime.now().addMonths(3);
        }
        if(con.Kunden_Maklerschutz__c != true && con.Gesch_ftsbeziehung__c.contains('Interessent')) {
        	con.Kunden_Maklerschutz__c = true;
        } else if(acc.Maklerschutz_besteht__c != true && acc.Contacts.size() == 1) {
        	acc.Maklerschutz_besteht__c = true;
        }
        Database.DMLOptions dml = new Database.DMLOptions();
    dml.DuplicateRuleHeader.AllowSave = true;
            Database.update(acc, dml);
            Database.update(con, dml);
            req2.setComments('Keine Duplikate entdeckt.');
            req2.setAction('Approve');
        } else if (val == 'dismiss') {
            req2.setComments('Duplikat entdeckt.');
            req2.setAction('Reject');
        }
        Id workitemid = getWorkItemId(displayCon.id);
        req2.setWorkitemId(workitemid);
        Approval.process(req2);
    }

    // Get the WorkItemId for the process of the contact
    public Id getWorkItemId(Id targetObjectId) {
        Id retVal = null;
        for (ProcessInstanceWorkitem workItem: [Select p.Id from ProcessInstanceWorkitem p
                where p.ProcessInstance.TargetObjectId = : targetObjectId
            ]) {
            retVal = workItem.Id;
        }
        return retVal;
    }

}