force-app/main/default/objects/Account/fields/E_Mail_bergeordneter_Makler__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_bergeordneter_Makler__c</fullName>
    <inlineHelpText>Die E-Mail Adresse des übergeordneten Maklers</inlineHelpText>
    <label>E-Mail übergeordneter Makler</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neu</fullName>
                <default>true</default>
                <label>Neu</label>
            </value>
            <value>
                <fullName>Kontaktiert</fullName>
            </value>
            <value>
                <fullName>Terminiert</fullName>
            </value>
            <value>
                <fullName>Aktiv</fullName>
            </value>
            <value>
                <fullName>Inaktiv</fullName>
            </value>
            <value>
                <fullName>Verloren</fullName>
            </value>
            <value>
                <fullName>Blacklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Admin_Costs_Increase_After_Years__c.field-meta.xml
<CustomField>
    <fullName>Admin_Costs_Increase_After_Years__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Admin Costs Increase After Years</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Admin_Costs_Increase_In__c.field-meta.xml
<CustomField>
    <fullName>Admin_Costs_Increase_In__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Admin Costs Increase In%</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Afa_Art__c.field-meta.xml
<CustomField>
    <fullName>Afa_Art__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Afa Art</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/AFA_Total__c.field-meta.xml
<CustomField>
    <fullName>AFA_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AFA Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Area_sq_m__c.field-meta.xml
<CustomField>
    <fullName>Area_sq_m__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Area (sq.m)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Depreciation_Value__c.field-meta.xml
<CustomField>
    <fullName>Depreciation_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Depreciation Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Opt_Zusatzkosten_auf_Kaufpreis_addieren__c.field-meta.xml
<CustomField>
    <fullName>Opt_Zusatzkosten_auf_Kaufpreis_addieren__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt. Zusatzkosten auf Kaufpreis addieren</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Purchase Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kontingent</fullName>
            </value>
            <value>
                <fullName>Reservierungsvorbereitung</fullName>
            </value>
            <value>
                <fullName>Reservierung angefragt</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsangebot abgegeben</fullName>
            </value>
            <value>
                <fullName>KV wird fremd abgegeben</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsunterlagen verschickt -zweiseitig-</fullName>
            </value>
            <value>
                <fullName>Auftrag zur Beurkundung vorhanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Value_Parking_Space__c.field-meta.xml
<CustomField>
    <fullName>Value_Parking_Space__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Value Parking Space</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Wert_K_che__c.field-meta.xml
<CustomField>
    <fullName>Wert_K_che__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Wert Küche</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Wert_Photovoltaik_Anlage__c.field-meta.xml
<CustomField>
    <fullName>Wert_Photovoltaik_Anlage__c</fullName>
    <label>Wert Photovoltaik Anlage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/AFA_Art__c.field-meta.xml
<CustomField>
    <fullName>AFA_Art__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AFA Art</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTeilobjekte.cls
@isTest
private class TestTeilobjekte {

    @testSetup static void makeData() {
        //TODO create all data for methods here, atm just partially created

        Account bautraeger = TestDataFactory.createBautraeger(true);

        Account makler = TestDataFactory.createAccount(true,'Makler GmbH');
        Contact mb = TestDataFactory.createMakler(true, 'Makler');

        Property__c prop = TestDataFactory.createProperty(true,bautraeger.Id);
        Appartment__c app = TestDataFactory.createAppartment(true,prop.Id, 'Test App');

        Contact potKun = TestDataFactory.createContact(true, 'Tvvsta', 'Tekoeric');

        Opportunity opp = TestDataFactory.createOpportunity(true, potKun.Id, mb.Id, prop.Id, app.Id, 'Reservierung angefragt');
    }
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Account account1 = new Account(Name='test account', OwnerID = '005b0000001V30P', Email__c = 'test@mail.com', E_Mail_bergeordneter_Makler__c = 'tester@test.de');
        insert account1;

        Property__c prop = new Property__c(Name = 'TestImmobilie',  Account__c = account1.id);
        insert prop;

        Appartment__c app = new Appartment__c(Name ='Test Appartment', Property__c = prop.ID, Area_sq_m__c = 15, Opt_Zusatzkosten_auf_Kaufpreis_addieren__c = true, Afa_Art__c = 0, AFA_Total__c = 0, Depreciation_Value__c = 0, Admin_Costs_Increase_After_Years__c = 0, Admin_Costs_Increase_In__c = 0, Purchase_Price__c = 123, Wert_Photovoltaik_Anlage__c = 23, Value_Parking_Space__c = 0, wert_k_che__c = 0);
        insert app;

        List<Appartment__c> appToUpdate= new List<Appartment__c>();
        for(Appartment__c app2: [SELECT Status__c FROM Appartment__c WHERE Property__c = :prop.id]){
            app2.Status__c = 'Verkauft';
            appToUpdate.add(app2);

        }
        update appToUpdate;
    }

    static testMethod void testStatusChange() {
        Appartment__c app = [SELECT Id, Status__c FROM Appartment__c WHERE Name = 'Test App' LIMIT 1];

        Test.startTest();
        app.Status__c = 'Reserviert';
        update app;
        Test.stopTest();
    }
}