force-app/main/default/objects/Account/fields/E_Mail_bergeordneter_Makler__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_bergeordneter_Makler__c</fullName>
    <inlineHelpText>Die E-Mail Adresse des übergeordneten Maklers</inlineHelpText>
    <label>E-Mail übergeordneter Makler</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WHS_Maklerauftrag__c.field-meta.xml
<CustomField>
    <fullName>WHS_Maklerauftrag__c</fullName>
    <description>Abbildung des Prozesses zur Auslösung eines Maklerauftrags; letzter Status heisst unterschrieben vom Vorstand und versendet an den Makler (d.h. Vereinbarung ist ab diesem Tag gültig)</description>
    <inlineHelpText>Abbildung des Prozesses zur Auslösung eines Maklerauftrags; letzter Status heisst unterschrieben vom Vorstand und versendet an den Makler (d.h. Vereinbarung ist ab diesem Tag gültig)</inlineHelpText>
    <label>WH Maklerauftrag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Keine Vereinbarung</fullName>
                <default>true</default>
                <label>Keine Vereinbarung</label>
            </value>
            <value>
                <fullName>Vom Maklerbetreuer angefordert</fullName>
            </value>
            <value>
                <fullName>Erstellt und an Makler versendet</fullName>
            </value>
            <value>
                <fullName>Unterschrieben eingegangen</fullName>
            </value>
            <value>
                <fullName>Maklerauftrag beidseitig unterzeichnet</fullName>
            </value>
            <value>
                <fullName>Makler mit altem Vertrag</fullName>
            </value>
            <value>
                <fullName>Makler ohne eigenen Vertrag</fullName>
            </value>
            <value>
                <fullName>Vom Makler gekündigt</fullName>
            </value>
            <value>
                <fullName>Vom WH gekündigt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchedulableDashboardControllingATest.cls
@isTest
private class SchedulableDashboardControllingATest {

  @isTest static void test_method_one() {

    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Account acc = new Account(WHS_Maklerauftrag__c = 'Maklerauftrag beidseitig unterzeichnet', Name = 'Test Tester', Email__c ='test@test.test', E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com');
        insert acc;

        Contact con = new Contact(AccountId = acc.id, Email='f.witte@wirtschaftshaus.de', FirstName='Frederik', LastName='Witte', Gesch_ftsbeziehung__c = 'Finanzmakler');
        insert con;

        Test.startTest();

        // Schedule the test job

        String jobId = System.schedule('testBasicScheduledApex',
          '0 0 0 3 9 ? 2022',
            new SchedulableDashboardControllingActivum   ());

      // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same
      System.assertEquals('0 0 0 3 9 ? 2022',
         ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run
      System.assertEquals('2022-09-03 00:00:00',
         String.valueOf(ct.NextFireTime));

       Test.stopTest();
  }

}