force-app/main/default/objects/Account/fields/E_Mail_bergeordneter_Makler__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_bergeordneter_Makler__c</fullName>
    <inlineHelpText>Die E-Mail Adresse des übergeordneten Maklers</inlineHelpText>
    <label>E-Mail übergeordneter Makler</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/BatchAccountUpdateChildAccounts.cls
public class BatchAccountUpdateChildAccounts implements Database.Batchable<sObject> {

    public Set<Id> accountIds = new Set<Id>();

    public BatchAccountUpdateChildAccounts(List<Account> accounts) {
        this.accountIds = new Map<Id,Account>(accounts).keySet();
    }

    @InvocableMethod(label='Update Child Account from Account Changes')
    public static void updateChildAccounts(List<Account> accounts) {
        Database.executeBatch(new BatchAccountUpdateChildAccounts(accounts));
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        
        return Database.getQueryLocator(
            [SELECT Id, E_Mail_bergeordneter_Makler__c, Parent.Email__c
            FROM Account 
            WHERE ParentId IN :accountIds]);
    }

    public void execute(Database.BatchableContext context, List<Account> accList) {
        List<Account> accUpdateList = new List<Account>();

        for (Account acc : accList) {
            acc.E_Mail_bergeordneter_Makler__c = acc.Parent.Email__c;
            accUpdateList.add(acc);
            
        }
        update accUpdateList;
    }

    public void finish(Database.BatchableContext context) {
        
    }
}