force-app/main/default/objects/Account/fields/E_Mail_bergeordneter_Makler__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_bergeordneter_Makler__c</fullName>
    <inlineHelpText>Die E-Mail Adresse des übergeordneten Maklers</inlineHelpText>
    <label>E-Mail übergeordneter Makler</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Geschueftsfuehrer__c.field-meta.xml
<CustomField>
    <fullName>Geschueftsfuehrer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geschäftsführer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Geschäftsführer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Aus_Maklerportal__c.field-meta.xml
<CustomField>
    <fullName>Aus_Maklerportal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked, wenn der Kontakt aus dem Maklerportal über das Interessenten- / Maklerschutz Formular importiert wurde.</description>
    <inlineHelpText>Ist Kontakt aus Maklerportal( Interessenten- / Maklerschutz Formular )</inlineHelpText>
    <label>Aus Maklerportal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Kunden_Maklerschutz__c.field-meta.xml
<CustomField>
    <fullName>Kunden_Maklerschutz__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kundenschutz besteht</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Kunde.recordType-meta.xml
<RecordType>
    <fullName>Kunde</fullName>
    <active>true</active>
    <label>Kunde</label>
</RecordType>

force-app/main/default/classes/DupConControllerTests.cls
@isTest

public class DupConControllerTests {

    public static testMethod void testMyController() {
        Database.DMLOptions dml2 = new Database.DMLOptions();
        dml2.DuplicateRuleHeader.AllowSave = true;
        
        User testUser = TestDataFactory.createTestUser(true, 'TestAdmin', 1);
        try{
            PermissionSet ps_status = [SELECT Id FROM PermissionSet WHERE Name = 'Can_change_stage_status'];
            PermissionSet ps_contact = [SELECT Id FROM PermissionSet WHERE Name = 'ChangeContactAccount'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_status.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_contact.Id);
        }
        catch(DmlException e){
            System.debug(e.getMessage());
        }
        
        System.runAs(testUser){
        
            Contact mb = TestDataFactory.createContact(false,'Frank', 'Köpsell', 'witte@amstammtisch.de');
            Database.insert(mb, dml2);

            Account acc1 = TestDataFactory.createAccount(false, 'test name', null);
            acc1.Maklerbetreuer_Wirtschaftshaus__c = 'Frank Köpsell';
            acc1.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
            acc1.Geschueftsfuehrer__c = mb.id;
            Database.insert(acc1, dml2);

            mb.AccountId = acc1.Id;
            Database.update(mb, dml2);

            Account account1 = TestDataFactory.createAccount(false, 'testxyz account2', null);
            account1.ParentID = acc1.id;
            account1.Maklerbetreuer_Wirtschaftshaus__c = 'Lars Wagner';
            account1.Email__c='test@testabc.test';
            account1.E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com'; 
            Database.insert(account1, dml2);

            Contact contact1 = TestDataFactory.createContact(false,'Mike', 'Vacation', 'tesss456d@mail.com');
            contact1.AccountID=account1.id;
            contact1.Gesch_ftsbeziehung__c = 'Interessent';
            Database.insert(contact1, dml2);

            Account account2 = TestDataFactory.createAccount(false, 'Greg Holiday', null);
            account2.ParentID = account1.Id;
            account2.Maklerbetreuer_Wirtschaftshaus_2__c = contact1.id;
            account2.Email__c ='testdev@test.test';
            account2.E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com';
            account2.BIC__c ='1';
            account2.Geschueftsfuehrer__c=mb.id;
            Database.insert(account2, dml2);

            Contact contact2 = TestDataFactory.createContact(false,'Paul', 'Fastest', 'tesss123d@mail.com');
            contact2.AccountID = account2.id;
            contact2.Gesch_ftsbeziehung__c = 'Kunde';
            Database.insert(contact2, dml2);

            Contact con2 = TestDataFactory.createContact(false,'Paul', 'Smith', 'tesss123d@mail.com');
            con2.AccountID = account1.id;
            Database.insert(con2, dml2);

            Contact[] cons = new List<Contact>();

            cons.add(contact1);
            Contact newContact = TestDataFactory.createContact(false,'Lars', 'Slow', 'tesssd01@mail.com');
            newContact.AccountId = account2.Id;
            newContact.Gesch_ftsbeziehung__c = 'Interessent';
            newContact.Aus_Maklerportal__c = true;
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
            Database.SaveResult sr = Database.insert(newContact, dml);
            
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Kontakt für Genehmigung eingereicht.');
            req1.setObjectId(newContact.id);
            req1.setProcessDefinitionNameOrId('Interessentenschutz');
            Approval.process(req1);

            //Construct your pagereference
            PageReference testPage = new pagereference('/apex/dupcon');
            testPage.getParameters().put('id', newContact.Id);
            Test.setCurrentPage(testPage);

            ApexPages.StandardController ssc = new ApexPages.StandardController(newContact);
            DupConController dupCon = new DupConController(ssc);
            dupCon.getFirst();
            dupCon.getPossibleDups();
            dupCon.getPossibleDupLeads();

            ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(cons);
            setCon.setSelected(cons);

            Test.startTest();
            dupCon.mergeContacts(contact1.Id);
            Test.stopTest();
            
            Contact aftercon = [Select AccountId FROM Contact WHERE ID = : contact1.Id];
            //System.assertEquals(account2.Id, aftercon.AccountId);

            System.debug('aftercon: ' + aftercon.AccountId);
            System.debug('account2: ' + account2.Id);
        }
    }

    public static testMethod void testMyControllerTwo() {

        Database.DMLOptions dml2 = new Database.DMLOptions();
        dml2.DuplicateRuleHeader.AllowSave = true;

        Contact mb = TestDataFactory.createContact(false,'Frank', 'Köpsell', 'witte@amstammtisch.de');
        Database.insert(mb, dml2);

        Account acc1 = TestDataFactory.createAccount(false, 'test name', null);
        acc1.Maklerbetreuer_Wirtschaftshaus__c = 'Frank Köpsell';
        acc1.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
        acc1.Geschueftsfuehrer__c = mb.id;
        Database.insert(acc1, dml2);

        mb.AccountId = acc1.Id;
        Database.update(mb, dml2);

        Account account1 = TestDataFactory.createAccount(false, 'testxyz account2', null);
        account1.ParentID = acc1.id;
        account1.Maklerbetreuer_Wirtschaftshaus__c = 'Lars Wagner';
        account1.Email__c='test@testabc.test';
        account1.E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com'; 
        Database.insert(account1, dml2);
        

        Contact contact1 = TestDataFactory.createContact(false,'Mike', 'Vacation', 'tesss456d@mail.com');
        contact1.AccountID=account1.id;
        contact1.Gesch_ftsbeziehung__c = 'Interessent';
        Database.insert(contact1, dml2);

        Account account2 = TestDataFactory.createAccount(false, 'Greg Holiday', null);
        account2.ParentID = account1.Id;
        account2.Maklerbetreuer_Wirtschaftshaus_2__c = contact1.id;
        account2.Email__c ='testdev@test.test';
        account2.E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com';
        account2.BIC__c ='1';
        account2.Geschueftsfuehrer__c=mb.id;
        Database.insert(account2, dml2);

        Contact contact2 = TestDataFactory.createContact(false,'Paul', 'Fastest', 'tesss123d@mail.com');
        contact2.AccountID = account2.id;
        contact2.Gesch_ftsbeziehung__c = 'Kunde';
        Database.insert(contact2, dml2);

        Contact con2 = TestDataFactory.createContact(false,'Paul', 'Smith', 'tesss123d@mail.com');
        con2.AccountID = account1.id;
        Database.insert(con2, dml2);

        contact1.Kunden_Maklerschutz__c = false;
        con2.Kunden_Maklerschutz__c = false;
        update contact1;
        update contact2;

        Contact[] cons = new List<Contact>();

        cons.add(contact1);
        Contact newContact = TestDataFactory.createContact(false,'Lars', 'Slow', 'tesssd01@mail.com');
        newContact.AccountId = account2.Id;
        newContact.Gesch_ftsbeziehung__c = 'Versicherungsmakler';
        newContact.Aus_Maklerportal__c = true;

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;
        Database.SaveResult sr = Database.insert(newContact, dml);

        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Kontakt für Genehmigung eingereicht.');
        req1.setObjectId(newContact.id);
        req1.setProcessDefinitionNameOrId('Maklerschutz');
        Approval.process(req1);

        //Construct your pagereference
        PageReference testPage = new pagereference('/apex/dupcon');
        testPage.getParameters().put('id', newContact.Id);
        Test.setCurrentPage(testPage);

        ApexPages.StandardController ssc = new ApexPages.StandardController(newContact);
        DupConController dupCon = new DupConController(ssc);
        dupCon.getFirst();

        ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(cons);
        setCon.setSelected(cons);
        Test.startTest();
        dupCon.mergeContacts(contact1.Id);
        Test.stopTest();
        Contact aftercon = [Select AccountId FROM Contact WHERE ID = : contact1.Id];

        System.debug('aftercon: ' + aftercon.AccountId);
    }

    public static testMethod void testMyControllerThree() {

        Database.DMLOptions dml2 = new Database.DMLOptions();
        dml2.DuplicateRuleHeader.AllowSave = true;

        User testUser = TestDataFactory.createTestUser(true, 'TestAdmin', 1);

        try{
            PermissionSet ps_status = [SELECT Id FROM PermissionSet WHERE Name = 'Can_change_stage_status'];
            PermissionSet ps_contact = [SELECT Id FROM PermissionSet WHERE Name = 'ChangeContactAccount'];
            PermissionSet ps_reparent = [SELECT Id FROM PermissionSet WHERE Name = 'ReparentAccount'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_status.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_contact.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_reparent.Id);
        }
        catch(DmlException e){
            System.debug(e.getMessage());
        }

        System.runAs(testUser){
            Contact mb = TestDataFactory.createContact(false,'Frank', 'Köpsell', 'witte@amstammtisch.de');
            Database.insert(mb, dml2);

            Account acc1 = TestDataFactory.createAccount(false, 'test name', null);
            acc1.Maklerbetreuer_Wirtschaftshaus__c = 'Frank Köpsell';
            acc1.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
            acc1.Geschueftsfuehrer__c = mb.id;
            Database.insert(acc1, dml2);

            mb.AccountId = acc1.Id;
            Database.update(mb, dml2);

            Account account1 = TestDataFactory.createAccount(false, 'testxyz account2', null);
            account1.ParentID = acc1.id;
            account1.Maklerbetreuer_Wirtschaftshaus__c = 'Lars Wagner';
            account1.Email__c='test@testabc.test';
            account1.E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com'; 
            Database.insert(account1, dml2);

            Contact contact1 = TestDataFactory.createContact(false,'Mike', 'Vacation', 'tesss456d@mail.com');
            contact1.AccountID=account1.id;
            contact1.Gesch_ftsbeziehung__c = 'Interessent';
            Database.insert(contact1, dml2);

            Account account2 = TestDataFactory.createAccount(false, 'Greg Holiday', null);
            account2.ParentID = account1.Id;
            account2.Maklerbetreuer_Wirtschaftshaus_2__c = contact1.id;
            account2.Email__c ='testdev@test.test';
            account2.E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com';
            account2.BIC__c ='1';
            account2.Geschueftsfuehrer__c=mb.id;
            Database.insert(account2, dml2);

            Contact contact2 = TestDataFactory.createContact(false,'Paul', 'Fastest', 'tesss123d@mail.com');
            contact2.AccountID = account2.id;
            contact2.Gesch_ftsbeziehung__c = 'Kunde';
            Database.insert(contact2, dml2);

            Contact con2 = TestDataFactory.createContact(false,'Paul', 'Smith', 'tesss123d@mail.com');
            con2.AccountID = account1.id;
            Database.insert(con2, dml2);

            Contact[] cons = new List<Contact>();

            cons.add(contact1);
            Contact newContact = TestDataFactory.createContact(false,'Lars', 'Slow', 'tesssd01@mail.com');
            newContact.AccountId = account2.Id;
            newContact.Gesch_ftsbeziehung__c = 'Interessent';
            newContact.Aus_Maklerportal__c = true;
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
            Database.SaveResult sr = Database.insert(newContact, dml);

            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Kontakt für Genehmigung eingereicht.');
            req1.setObjectId(newContact.id);
            req1.setProcessDefinitionNameOrId('Interessentenschutz');
            Approval.process(req1);

            //Construct your pagereference
            PageReference testPage = new pagereference('/apex/dupcon');
            testPage.getParameters().put('id', newContact.Id);
            Test.setCurrentPage(testPage);

            ApexPages.StandardController ssc = new ApexPages.StandardController(newContact);
            DupConController dupCon = new DupConController(ssc);
            dupCon.getFirst();
            dupCon.reject();
        }
    }
}