force-app/main/default/objects/Account/fields/E_Mail_bergeordneter_Makler__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_bergeordneter_Makler__c</fullName>
    <inlineHelpText>Die E-Mail Adresse des übergeordneten Maklers</inlineHelpText>
    <label>E-Mail übergeordneter Makler</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RestOpportunitiesWithProvisionTest.cls
@isTest
public with sharing class RestOpportunitiesWithProvisionTest {
    @isTest public static void RestOpportunitiesWithProvisionTest() {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;
        // TestClass with no of hierarchy
        Account acc = new Account(Name='TestAccount', Email__c='tesaat@mahil.com', E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com');
        Database.insert(acc, dml);

        Test.startTest();
        RestOpportunitiesWithProvision.showOpportunities(acc.Id, null);
        Test.stopTest();
    }
    
    @isTest public static void RestOpportunitiesWithProvisionTest2() {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;
        // TestClass with no of hierarchy
        Account acc = new Account(Name='TestAccount', Email__c='tesaat@mahil.com', E_Mail_bergeordneter_Makler__c = 'tesaat@mahil.com');
        Database.insert(acc, dml);
        
        Contact potKun = new Contact();
        potKun.FirstName = 'Tvvsta';
        potKun.LastName = 'Tekoeeric';
        insert potKun;

        Test.startTest();
        RestOpportunitiesWithProvision.showOpportunities(acc.Id, potKun.Id);
        Test.stopTest();
    }
}