force-app/main/default/objects/Account/fields/Externer_Maklerbetreuer__c.field-meta.xml
<CustomField>
    <fullName>Externer_Maklerbetreuer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Externer Maklerbetreuer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Externer Maklerbetreuer)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Carestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/Berechnungsemails__c.object-meta.xml
<CustomObject>
    <label>Berechnungsemail</label>
    <nameField>
        <label>Berechnungsemails-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungsemails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Berechnungsemails__c/fields/An_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>An_E_Mail__c</fullName>
    <label>An E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Benachrichtigung_an__c.field-meta.xml
<CustomField>
    <fullName>Benachrichtigung_an__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benachrichtigung an</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Berechnungsemails</relationshipLabel>
    <relationshipName>Berechnungsemails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Berechnungsmakler__c.field-meta.xml
<CustomField>
    <fullName>Berechnungsmakler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Berechnungsmakler</label>
    <referenceTo>Realty_User__c</referenceTo>
    <relationshipLabel>Berechnungsemails</relationshipLabel>
    <relationshipName>Berechnungsemails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Externe__c.field-meta.xml
<CustomField>
    <fullName>Externe__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Es handelt sich um einen externen Makler, welcher nicht in direkter Beziehung zum Kunden steht</description>
    <inlineHelpText>Es handelt sich um einen externen Makler, welcher nicht in direkter Beziehung zum Kunden steht</inlineHelpText>
    <label>Externe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Immo_Berechnung__c.field-meta.xml
<CustomField>
    <fullName>Immo_Berechnung__c</fullName>
    <label>Immo Berechnung</label>
    <referenceTo>Calculation__c</referenceTo>
    <relationshipLabel>Berechnungsemails</relationshipLabel>
    <relationshipName>Berechnungsemails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Berechnungsemails</relationshipLabel>
    <relationshipName>Berechnungsemails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Kunde__c.field-meta.xml
<CustomField>
    <fullName>Kunde__c</fullName>
    <label>Kunde</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Berechnungsemails__c/fields/Teilobjekt__c.field-meta.xml
<CustomField>
    <fullName>Teilobjekt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teilobjekt</label>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Berechnungsemails</relationshipLabel>
    <relationshipName>Berechnungsemails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/Calculation__c.object-meta.xml
<CustomObject>
    <label>Immo Berechnung</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Immo Berechnung Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Immo Berechnungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calculation__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Appartment__c.field-meta.xml
<CustomField>
    <fullName>Appartment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appartment</label>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Brokers_Person__c.field-meta.xml
<CustomField>
    <fullName>Brokers_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokers Person</label>
    <referenceTo>Realty_User__c</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>First Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Last Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MaklerBetreuer_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>MaklerBetreuer_E_Mail__c</fullName>
    <label>MaklerBetreuer E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Kunde.recordType-meta.xml
<RecordType>
    <fullName>Kunde</fullName>
    <active>true</active>
    <label>Kunde</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Realty_User__c/Realty_User__c.object-meta.xml
<CustomObject>
    <label>Immo Benutzer</label>
    <nameField>
        <label>Immo Benutzer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immo Benutzer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realty_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Realty_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Berechnungsemail.cls
global class Berechnungsemail {
    public Berechnungsemail(){
        
    }
    public static void Berechnungsemail(Calculation__c calc1){

        
        List<Berechnungsemails__c> emailToInsert = new List<Berechnungsemails__c>();
        boolean neueMail = true;
        Realty_User__c immoUser;
        Calculation__c calc = calc1;
        Id oldID = null;
        Account maklerBetreuer;
        Contact con;
        String kundenName;
        kundenName = calc.Last_Name__c + ', ' + calc.First_Name__c;
        Boolean extern = false;
        Boolean isFirstInHierarchy = false;
        
        try{
            maklerBetreuer = Maklerbetreuer(calc.Agency__c);
            con = Maklerprov(maklerBetreuer.Externer_Maklerbetreuer__c);
            
            if(!con.HasOptedOutOfEmail){
                neueMail(emailToInsert, calc.Name, con.id, con.Email, calc.Brokers_Person__c, kundenName, calc.Property__c, calc.Appartment__c, calc.id, false);
            }
        }catch (Exception e){
            
            try{
                immoUser = [SELECT Contact__c FROM Realty_User__c WHERE id = :calc.Brokers_Person__c];
                con = Maklerprov(immoUser.Contact__c);
                Contact mBetreuerWH = [SELECT ID FROM Contact WHERE Email = :con.MaklerBetreuer_E_Mail__c Limit 1];
                if(!con.HasOptedOutOfEmail){
                    neueMail(emailToInsert, calc.Name, mBetreuerWH.id, con.MaklerBetreuer_E_Mail__c, calc.Brokers_Person__c, kundenName, calc.Property__c, calc.Appartment__c, calc.id, false);
                }
            }catch(Exception f){
                
            }
        }
        
        while (neueMail){
            try{
                maklerBetreuer = Maklerbetreuer(con.AccountID);
                if(oldId != maklerBetreuer.Externer_Maklerbetreuer__c)
                {
                    oldId = maklerBetreuer.Externer_Maklerbetreuer__c;
                    con = Maklerprov(maklerBetreuer.Externer_Maklerbetreuer__c);
                    neueMail(emailToInsert, calc.Name, con.id, con.Email, calc.Brokers_Person__c, kundenName, calc.Property__c, calc.Appartment__c, calc.id, true);
                }
                else
                {
                    throw new applicationException('Infinite Loop');
                }
            }catch(Exception e){
                neueMail = false;
                try{
                    immoUser = [SELECT Contact__c FROM Realty_User__c WHERE id = :calc.Brokers_Person__c];
                    
                    con = Maklerprov(immoUser.Contact__c);
                    Contact mBetreuerWH = [SELECT ID FROM Contact WHERE Email = :con.MaklerBetreuer_E_Mail__c Limit 1];
                    
                    if(con.MaklerBetreuer_E_Mail__c != null && mBetreuerWH.id != null && con.HasOptedOutOfEmail == false){
                        neueMail(emailToInsert, calc.Name, mBetreuerWH.id, con.MaklerBetreuer_E_Mail__c, calc.Brokers_Person__c, kundenName, calc.Property__c, calc.Appartment__c, calc.id, false);
                    }
                }catch(Exception f){
                    
                }
                
            }
        }
        
        if(!emailToInsert.isEmpty()){
            insert emailToInsert;
        }
        
    }
    
    public static void Berechnungsmail (){
        
    }
    
    public static Account Maklerbetreuer(Id AccountID){
            Account acc = [SELECT Externer_Maklerbetreuer__c, Maklerbetreuer_Wirtschaftshaus__c FROM Account WHERE Id = :AccountID];
            return acc;
    }
    
    public static Contact Maklerprov (Id ContactID){
            Contact con = [SELECT Id, Name, AccountID, Email, MaklerBetreuer_E_Mail__c, HasOptedOutOfEmail FROM Contact WHERE Id = :ContactID];
            if(con != null){
                if((con.Email == null || con.Email == '' || con.MaklerBetreuer_E_Mail__c == null || con.MaklerBetreuer_E_Mail__c == '')&& con.HasOptedOutOfEmail == false){
                    fehlerMail(con.Name);
                }
                
            }
            return con; 
    }
    
    public static void neueMail(List<Berechnungsemails__c> emailToInsert, String Name1, ID mailAn, String eMail, ID vonMakler, String Kunde, ID immo, ID app, ID berechnung, Boolean isExtern){
        emailToInsert.add(new Berechnungsemails__c( Name = 'E-Mail für Berechnugn: ' +Name1,
                                                    Benachrichtigung_an__c = mailAn,
                                                    An_E_Mail__c = eMail,
                                                    Berechnungsmakler__c = vonMakler,
                                                    Kunde__c = Kunde,
                                                    Immobilie__c = immo,
                                                    Teilobjekt__c = app,
                                                    Immo_Berechnung__c = berechnung,
                                                    Externe__c = isExtern));
    }
    
    public static void fehlerMail(String name){
        Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();
        String[] toAdress = new String[] {  'dr@wirtschaftshaus.de',
                                            'p.kredig@wirtschaftshaus.de'};
        mail.setToAddresses(toAdress);
        mail.setSubject('Bitte Email überprüfen');
        mail.setBccSender(false);
        mail.setPlainTextBody('Bitte überprüfen ob die E-Mail Adresse und die Makler Betreuer Email Adresse vom Kontakt: ' + name + ' angegeben ist');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
    }
    
}