force-app/main/default/objects/Account/fields/Geschueftsfuehrer__c.field-meta.xml
<CustomField>
    <fullName>Geschueftsfuehrer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geschäftsführer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Geschäftsführer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesetzliche_MwSt_auf_Provisionszahlung__c.field-meta.xml
<CustomField>
    <fullName>Gesetzliche_MwSt_auf_Provisionszahlung__c</fullName>
    <label>Gesetzliche MwSt. auf Provisionszahlung</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hinweis_zur_MwSt__c.field-meta.xml
<CustomField>
    <fullName>Hinweis_zur_MwSt__c</fullName>
    <inlineHelpText>Bitte gib hier an, woher die Information kommt, welchen MwSt-Satz der Makler hat</inlineHelpText>
    <label>Hinweis zur MwSt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rechtsform__c.field-meta.xml
<CustomField>
    <fullName>Rechtsform__c</fullName>
    <label>Rechtsform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MaklerBetreuer_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>MaklerBetreuer_E_Mail__c</fullName>
    <label>MaklerBetreuer E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RelatedListControllerTest.cls
@isTest
public with sharing class RelatedListControllerTest {
    @isTest public static void testInit(){
        Contact cnt = new Contact();
        cnt.FirstNAme = 'Frank';
        cnt.LastName = 'Köpsell';
        cnt.Email = 'witte@amstammtisch.de';
        cnt.MaklerBetreuer_E_Mail__c = 'witte@amstammtisch.de';
        insert cnt;
        Account acc = new Account();
        acc.Name = 'WH Maklerbetreuer - Frank Köpsell';
        acc.Email__c = 'witte@amstammtisch.de';
        acc.Maklerbetreuer_Wirtschaftshaus__c = 'Frank Köpsell';
        acc.Maklerbetreuer_Wirtschaftshaus_2__c = cnt.Id;
        acc.BIC__c  = '1';
        acc.Geschueftsfuehrer__c = cnt.id;
        acc.Gesetzliche_MwSt_auf_Provisionszahlung__c = 0.4;
        acc.Hinweis_zur_MwSt__c = 'Vertrag';
        acc.IBAN__c = 'DE43250501801900212158';
        acc.Rechtsform__c = 'GbR';
        acc.Unternehmensname__c = 'CareStone';
        insert acc;
        cnt.AccountId = acc.Id;
        update cnt;
                
        Map<String, Object> requestMap = new Map<String, Object>(); 
        requestMap.put(RelatedListController.FIELDS_PARAM, 'Name, Title, Email, Phone');
        requestMap.put(RelatedListController.RELATED_FIELD_API_NAME_PARAM, 'AccountId');
        requestMap.put(RelatedListController.RECORD_ID_PARAM, acc.Id);
        requestMap.put(RelatedListController.NUMBER_OF_RECORDS_PARAM, 1);
        requestMap.put(RelatedListController.SOBJECT_API_NAME_PARAM, 'Contact');
        requestMap.put(RelatedListController.SORTED_BY_PARAM, 'Name');
        requestMap.put(RelatedListController.SORTED_DIRECTION_PARAM, 'ASC');
                
        String jsonData = RelatedListController.initData(JSON.serialize(requestMap));
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonData);
        List<Object> records = (List<Object>)responseMap.get(RelatedListController.RECORDS_PARAM);
        System.assert(!records.isEmpty());
        String iconName = (String)responseMap.get(RelatedListController.ICON_NAME_PARAM);
        System.assert(String.isNotBlank(iconName));
    }
}