force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neu</fullName>
                <default>true</default>
                <label>Neu</label>
            </value>
            <value>
                <fullName>Kontaktiert</fullName>
            </value>
            <value>
                <fullName>Terminiert</fullName>
            </value>
            <value>
                <fullName>Aktiv</fullName>
            </value>
            <value>
                <fullName>Inaktiv</fullName>
            </value>
            <value>
                <fullName>Verloren</fullName>
            </value>
            <value>
                <fullName>Blacklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kontingent</fullName>
            </value>
            <value>
                <fullName>Reservierungsvorbereitung</fullName>
            </value>
            <value>
                <fullName>Reservierung angefragt</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsangebot abgegeben</fullName>
            </value>
            <value>
                <fullName>KV wird fremd abgegeben</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsunterlagen verschickt -zweiseitig-</fullName>
            </value>
            <value>
                <fullName>Auftrag zur Beurkundung vorhanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/TeamProQId__c.field-meta.xml
<CustomField>
    <fullName>TeamProQId__c</fullName>
    <description>External ID for TeamproQ Integration</description>
    <externalId>true</externalId>
    <label>TeamProQ ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kunde2__c.field-meta.xml
<CustomField>
    <fullName>Kunde2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Verkaufschancen (2. Käufer)</relationshipLabel>
    <relationshipName>Verkaufschancen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TeamProQId__c.field-meta.xml
<CustomField>
    <fullName>TeamProQId__c</fullName>
    <externalId>true</externalId>
    <label>TeamProQ ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/TeamProQId__c.field-meta.xml
<CustomField>
    <fullName>TeamProQId__c</fullName>
    <description>External ID for TeamproQ Integration</description>
    <externalId>true</externalId>
    <label>TeamProQ ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RestTeamProQOpportunityTest.cls
@isTest
private class RestTeamProQOpportunityTest {
    @TestSetup
    static void makeData() {
        Account bautraeger = TestDataFactory.createBautraeger(true);
        Property__c property = TestDataFactory.createProperty(false, bautraeger.Id);
        property.TeamProQId__c = '1234';
        insert property;
        Appartment__c app = TestDataFactory.createAppartment(false, property.Id);
        app.TeamProQId__c = '5678';
        insert app;
        Account acc = TestDataFactory.createAccount(true);
        Contact broker = TestDataFactory.createMakler(false, acc.Id);
        broker.Phone = '0511 - 153434';
        broker.Birthdate = Date.today()-12000;
        broker.Email = 'test@tester.de';
        insert broker;
    }

    @isTest
    private static void testSuccessfulOpportunityCreation() {
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = getFullTestData();
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        List<Opportunity> opps = [SELECT Makler__r.FirstName, Makler__r.LastName, AccountId, Potenzieller_Kunde__c, Potenzieller_Kunde__r.FirstName, Potenzieller_Kunde__r.LastName, Kunde2__r.FirstName, Kunde2__r.LastName, Appartement__r.TeamProQId__c, Immobilie__r.TeamProQId__c FROM Opportunity LIMIT 1];
        System.assertEquals(1, opps.size(), 'There should be exactly one opportunity.');
        Opportunity opp = opps[0];
        System.assertEquals(true, res.success, 'The returned status code is false, should be true.');
        System.assertEquals(0, res.errors.size(), 'There should be 0 errors returned.');
        System.assertEquals(data.accountId, opp.AccountId, 'The accountId is different from payload.');
        System.assertEquals(data.propertyExternalId, opp.Immobilie__r.TeamProQId__C, 'The external propertyId is different from payload.');
        System.assertEquals(data.apartmentExternalId, opp.Appartement__r.TeamProQId__c, 'The external apartmentId is different from payload.');
        System.assertEquals(data.firstBuyer.FirstName, opp.Potenzieller_Kunde__r.FirstName, 'The first name of the first buyer is different from payload.');
        System.assertEquals(data.firstBuyer.LastName, opp.Potenzieller_Kunde__r.LastName, 'The last name of the first buyer is different from payload.');
        System.assertEquals(data.secondBuyer.FirstName, opp.Kunde2__r.FirstName, 'The first name of the second buyer is different from payload.');
        System.assertEquals(data.secondBuyer.LastName, opp.Kunde2__r.LastName, 'The last name of the second buyer is different from payload.');
        System.assertEquals(data.broker.FirstName, opp.Makler__r.FirstName, 'The first name of the broker is different from payload.');
        System.assertEquals(data.broker.LastName, opp.Makler__r.LastName, 'The last name of the broker is different from payload.');
    }

    @isTest
    private static void testMissingAccountId() {
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = new RestTeamProQOpportunity.RestTeamProQOpportunityRequest();
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        System.assertEquals(false, res.success, 'The returned status code is true, should be false.');
        System.assertEquals(1, res.errors.size(), 'There should be 1 error returned.');
        System.assertEquals('AccountIdEmpty', res.errors[0].code, 'The error code is other than expected.');
    }

    @isTest
    private static void testWrongAccountId() {
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = new RestTeamProQOpportunity.RestTeamProQOpportunityRequest();
        data.accountId = '0016700005ScvRiAAJ';
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        System.assertEquals(false, res.success, 'The returned status code is true, should be false.');
        System.assertEquals(1, res.errors.size(), 'There should be 1 error returned.');
        System.assertEquals('AccountNotFound', res.errors[0].code, 'The error code is other than expected.');
    }

    @isTest
    private static void testWrongPropertyId() {
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = new RestTeamProQOpportunity.RestTeamProQOpportunityRequest();
        data = getFullTestData();
        data.propertyExternalId = '1111';
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        System.assertEquals(false, res.success, 'The returned status code is true, should be false.');
        System.assertEquals(1, res.errors.size(), 'There should be 1 error returned.');
        System.assertEquals('PropertyNotFound', res.errors[0].code, 'The error code is other than expected.');
    }

    @isTest
    private static void testWrongApartmentId() {
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = new RestTeamProQOpportunity.RestTeamProQOpportunityRequest();
        data = getFullTestData();
        data.apartmentExternalId = '2222';
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        System.assertEquals(false, res.success, 'The returned status code is true, should be false.');
        System.assertEquals(1, res.errors.size(), 'There should be 1 error returned.');
        System.assertEquals('ApartmentNotFound', res.errors[0].code, 'The error code is other than expected.');
    }

    @isTest
    private static void testMissingFirstBuyer() {
        Account acc = [SELECT Id FROM Account WHERE Gesch_ftsbeziehung__c != 'Bauträger' LIMIT 1];
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = new RestTeamProQOpportunity.RestTeamProQOpportunityRequest();
        data.accountId = acc.Id;
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        System.assertEquals(false, res.success, 'The returned status code is true, should be false.');
        System.assertEquals(1, res.errors.size(), 'There should be 1 error returned.');
        System.assertEquals('FirstBuyerEmpty', res.errors[0].code, 'The error code is other than expected.');
    }

    @isTest
    private static void testApartmentAlreadyReserved() {
        Account acc = [SELECT Id FROM Account WHERE Gesch_ftsbeziehung__c != 'Bauträger' LIMIT 1];
        Contact broker = [SELECT FirstName, LastName FROM Contact LIMIT 1];
        Property__c property = [SELECT Id FROM Property__c LIMIT 1];
        Appartment__c app = [SELECT Id FROM Appartment__c LIMIT 1];
        app.Status__c = 'Reservierungsvorbereitung';
        update app;
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = getFullTestData();
        Test.startTest();
        RestTeamProQOpportunity.RestTeamProQOpportunityResponse res = RestTeamProQOpportunity.createOpportunity(data);
        Test.stopTest();

        // Verify Data
        System.assertEquals(false, res.success, 'The returned status code is true, should be false.');
        System.assertEquals(1, res.errors.size(), 'There should be 1 error returned.');
        System.assertEquals('OpportunityNotCreated', res.errors[0].code, 'The error code is other than expected.');
    }

    public static RestTeamProQOpportunity.RestTeamProQOpportunityRequest getFullTestData() {
        Account acc = [SELECT Id FROM Account WHERE Gesch_ftsbeziehung__c != 'Bauträger' LIMIT 1];
        Contact broker = [SELECT FirstName, LastName FROM Contact LIMIT 1];
        Property__c property = [SELECT Id, TeamProQId__c FROM Property__c LIMIT 1];
        Appartment__c app = [SELECT Id, TeamProQId__c FROM Appartment__c LIMIT 1];
        RestTeamProQOpportunity.RestTeamProQOpportunityRequest data = new RestTeamProQOpportunity.RestTeamProQOpportunityRequest();
        data.propertyExternalId = property.TeamProQId__c;
        data.apartmentExternalId = app.TeamProQId__c;
        data.accountId = acc.Id;
        data.firstBuyer = new Contact();
        data.firstBuyer.FirstName = 'Frederik';
        data.firstBuyer.LastName = 'Witte';
        data.firstBuyer.MailingStreet = 'Lister Meile 45';
        data.firstBuyer.MailingCity = 'Hannover';
        data.firstBuyer.MailingPostalCode = '30161';
        data.firstBuyer.Phone = '0511123123';
        data.firstBuyer.Email = 'frederik.witte93@gmail.com';
        data.firstBuyer.BirthDate = Date.today() - 12000;
        data.secondBuyer = new Contact();
        data.secondBuyer.FirstName = 'Elise';
        data.secondBuyer.LastName = 'Witte';
        data.secondBuyer.MailingStreet = 'Lister Meile 45';
        data.secondBuyer.MailingCity = 'Hannover';
        data.secondBuyer.MailingPostalCode = '30161';
        data.secondBuyer.Phone = '0511123113';
        data.secondBuyer.Email = 'elise.witte@gmail.com';
        data.secondBuyer.BirthDate = Date.today() - 11000;
        data.broker = new Contact();
        data.broker.FirstName = broker.FirstName;
        data.broker.LastName = broker.LastName;
        return data;
    }
}