force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Geschueftsfuehrer__c.field-meta.xml
<CustomField>
    <fullName>Geschueftsfuehrer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geschäftsführer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Geschäftsführer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/ContentVersion/recordTypes/Finanzierungsanfragen.recordType-meta.xml
<RecordType>
    <fullName>Finanzierungsanfragen</fullName>
    <active>true</active>
    <label>Finanzierungsanfragen</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Amtsgericht__c.field-meta.xml
<CustomField>
    <fullName>Amtsgericht__c</fullName>
    <label>Amtsgericht</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Gesch_ftsf_hrer__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsf_hrer__c</fullName>
    <label>Geschäftsführer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/HRB__c.field-meta.xml
<CustomField>
    <fullName>HRB__c</fullName>
    <label>HRB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provisionsverhandlung__c/Provisionsverhandlung__c.object-meta.xml
<CustomObject>
    <label>Provisionsverhandlung</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Provisionsverhandlung-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionsverhandlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateAttachmentsFromFilesTest.cls
@IsTest
public with sharing class CreateAttachmentsFromFilesTest {

    @testSetup static void test_setup() {
        User testUser = TestDataFactory.createTestUser(true, 'TestAdmin', 1);
        try{
            PermissionSet ps_status = [SELECT Id FROM PermissionSet WHERE Name = 'Can_change_stage_status'];
            PermissionSet ps_contact = [SELECT Id FROM PermissionSet WHERE Name = 'ChangeContactAccount'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_status.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_contact.Id);
        }
        catch(DmlException e){
            System.debug(e.getMessage());
        }
        System.runAs(testUser){
        
            Contact mb = TestDataFactory.createContact(true,'Frank', 'Köpsell', 'witte@amstammtisch.de');
            
            Account acc3 = TestDataFactory.createBautraeger(false);
            acc3.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
            acc3.Gesch_ftsbeziehung__c = 'Bauträger';
            acc3.Geschueftsfuehrer__c = mb.id;
            insert acc3;

            mb.AccountId = acc3.Id;
            update mb;

            Contact potKun = TestDataFactory.createContact(true,'Tvvsta', 'Tekoeeric', 'test@tester.de');

            Property__c immobilie = TestDataFactory.createProperty(false, null, 'Immobilie');    
            immobilie.Gesch_ftsf_hrer__c = mb.id;
            immobilie.Amtsgericht__c = 'test';
            immobilie.HRB__c = '123';
            insert immobilie;

            Appartment__c app2 = TestDataFactory.createAppartment(true, immobilie.Id);

            Provisionsverhandlung__c provisionsverhandlung = TestDataFactory.createProvisionsverhandlung(true, acc3.Id, immobilie.Id);
            
            TestDataFactory.createDatevSettings();
            TestDataFactory.createNecessaryCustomSettings();

            Opportunity opp = Testdatafactory.createOpportunity(false, potKun.Id, mb.Id, immobilie.Id, app2.Id, 'Available', 100000);
            opp.AccountId = acc3.Id;
            insert opp;
        }
    }

    private static testMethod void testCreateAttachmentsFromFiles() {

        Property__c immobilie = [SELECT Id FROM Property__c];
        Opportunity opp = [SELECT Id FROM Opportunity];

        Id finanzierungsanfragenRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Finanzierungsanfragen').getRecordTypeId();

        ContentVersion cv=new Contentversion();
        cv.title='Rechnung';
        cv.PathOnClient ='Rechnung';
        cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        cv.Typ__c = 'Individuelle Unterlage';
        cv.RecordTypeId = finanzierungsanfragenRecordTypeId;
        insert cv;

        List<ContentVersion> files = [SELECT ContentDocumentId FROM ContentVersion];

        for(ContentVersion currentCv:files) {
            ContentDocumentLink cde = new ContentDocumentLink();
            cde.ContentDocumentId = currentCv.ContentDocumentId;
            cde.LinkedEntityId = opp.Id;
            insert cde;
        }

        List<CreateAttachmentsFromFiles.Requests> rqs = new List<CreateAttachmentsFromFiles.Requests>();
        CreateAttachmentsFromFiles.Requests rq = new CreateAttachmentsFromFiles.Requests();
        rq.recordId = opp.Id;
        rq.parentId = immobilie.Id;
        rq.isStorno = false;
        rqs.add(rq);

        Test.startTest();
        CreateAttachmentsFromFiles.createAttachmentsFromFiles(rqs);
        Test.stopTest();
    }
}