force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Berechnung__c/Berechnung__c.object-meta.xml
<CustomObject>
    <label>Berechnung</label>
    <nameField>
        <label>Berechnung Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Berechnung__c/fields/ErsterKaeufer__c.field-meta.xml
<CustomField>
    <fullName>ErsterKaeufer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Berechnungen (1. Käufer)</relationshipLabel>
    <relationshipName>Berechnungen1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Berechnung__c/fields/Verkaufsraum__c.field-meta.xml
<CustomField>
    <fullName>Verkaufsraum__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Verkaufsraum</label>
    <referenceTo>Verkaufsraum__c</referenceTo>
    <relationshipLabel>Berechnungen</relationshipLabel>
    <relationshipName>Berechnungen</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BerechnungsApartment__c/BerechnungsApartment__c.object-meta.xml
<CustomObject>
    <label>Berechnungs-Apartment</label>
    <nameField>
        <label>Berechnungs-Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungs-Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BerechnungsApartment__c/fields/Berechnung__c.field-meta.xml
<CustomField>
    <fullName>Berechnung__c</fullName>
    <label>Berechnung</label>
    <referenceTo>Berechnung__c</referenceTo>
    <relationshipLabel>Berechnungs-Apartments</relationshipLabel>
    <relationshipName>Berechnungs_Apartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Ist_Maklerbetreuer_WH__c.field-meta.xml
<CustomField>
    <fullName>Ist_Maklerbetreuer_WH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ist Maklerbetreuer CS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MaklerBetreuer_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>MaklerBetreuer_E_Mail__c</fullName>
    <label>MaklerBetreuer E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Finanzierungsbaustein__c/Finanzierungsbaustein__c.object-meta.xml
<CustomObject>
    <label>Finanzierungsbaustein</label>
    <nameField>
        <label>Finanzierungsbaustein Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finanzierungsbausteine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/Berechnung__c.field-meta.xml
<CustomField>
    <fullName>Berechnung__c</fullName>
    <label>Berechnung</label>
    <referenceTo>Berechnung__c</referenceTo>
    <relationshipLabel>Finanzierungsbausteine</relationshipLabel>
    <relationshipName>Finanzierungsbausteine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Finanzierungsbaustein__c/fields/BerechnungsApartment__c.field-meta.xml
<CustomField>
    <fullName>BerechnungsApartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Berechnungs-Apartment</label>
    <referenceTo>BerechnungsApartment__c</referenceTo>
    <relationshipLabel>Finanzierungsbausteine</relationshipLabel>
    <relationshipName>Finanzierungsbausteine</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verkaufsraum__c/Verkaufsraum__c.object-meta.xml
<CustomObject>
    <label>Kundenakte</label>
    <nameField>
        <label>Verkaufsraum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kundenakten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verkaufsraum__c/fields/BeratungsportalZugangAnlegen__c.field-meta.xml
<CustomField>
    <fullName>BeratungsportalZugangAnlegen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Zugriff für Kunden erlauben</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verkaufsraum__c/fields/ErsterKaeufer__c.field-meta.xml
<CustomField>
    <fullName>ErsterKaeufer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>1. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>VerkaufsraeumeErsterKaeufer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BerechnungControllerTest.cls
@isTest
public with sharing class BerechnungControllerTest {
    
    @TestSetup
    static void makeData(){
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;
        // Maklerbetreuer + Account erstellen
        Contact mb = new Contact();
        mb.FirstNAme = 'Frank';
        mb.LastName = 'Köpsell';
        mb.Email = 'f.witte@wirtschaftshaus.de';
        mb.MaklerBetreuer_E_Mail__c = 'f.witte@wirtschaftshaus.de';
        mb.Ist_Maklerbetreuer_WH__c = true;
        mb.Gesch_ftsbeziehung__c = 'Mitarbeiter WH';
        Database.insert(mb, dml);
        Account acc = new Account();
        acc.Name = 'Makler GmbH%';
        acc.Email__c = 'f.witte@wirtschaftshaus.de';
        acc.Maklerbetreuer_Wirtschaftshaus__c = 'Frank Köpsell';
        acc.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
        Database.insert(acc, dml);
        mb.AccountId = acc.Id;
        Database.update(mb, dml);

        Id interessentRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('Interessent').getRecordTypeId();
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.Gesch_ftsbeziehung__c = 'Interessent';
        con.FirstName = 'Max';
        con.MailingStreet = 'Teststr. 24';
        con.MailingCity = 'Hannover';
        con.MailingPostalCode = '30159';
        con.LastName = 'Interessentenmann 6';
        con.RecordTypeId = interessentRecordTypeId;
        insert con;
    }

    private static testMethod void insertBerechnungsApartmentsTest() {
        List<BerechnungsApartment__c> bAs = new List<BerechnungsApartment__c>();
        BerechnungController.insertBerechnungsApartments(bAs);
    }

    private static testMethod void insertBerechnungWithApartmentsTest() {
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Interessentenmann 6'];
        Verkaufsraum__c vkr = new Verkaufsraum__c();
        vkr.ErsterKaeufer__c = con.Id;
        vkr.BeratungsPortalZugangAnlegen__c = false;
        insert vkr;
        Berechnung__c b = new Berechnung__c(Name='Test', Verkaufsraum__c=vkr.Id);
        insert b;
        List<BerechnungsApartment__c> bAs = new List<BerechnungsApartment__c>();
        BerechnungController.insertBerechnungWithApartments(b.Id, bAs);
    }

    private static testMethod void insertFinanzierungsBausteineTest() {
        List<Finanzierungsbaustein__c> fBs = new List<Finanzierungsbaustein__c>();
        BerechnungController.insertFinanzierungsBausteine(fBs);
    }

    private static testMethod void deleteBerechnungsApartmentsTest() {
        List<Id> bAIds = new List<Id>();
        BerechnungController.deleteBerechnungsApartments(bAIds);
    }

    private static testMethod void deleteFinanzierungsBausteineTest() {
        List<Id> fBIds = new List<Id>();
        BerechnungController.deleteFinanzierungsBausteine(fBIds);
    }

    private static testMethod void getBerechnungTest() {
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Interessentenmann 6'];
        Verkaufsraum__c vkr = new Verkaufsraum__c();
        vkr.ErsterKaeufer__c = con.Id;
        vkr.BeratungsPortalZugangAnlegen__c = false;
        insert vkr;
        Berechnung__c b = new Berechnung__c(Name='Test', Verkaufsraum__c=vkr.Id);
        insert b;
        BerechnungController.getBerechnung(b.Id);
    }

    private static testMethod void getFinanzierungsbausteinTest() {
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Interessentenmann 6'];
        Verkaufsraum__c vkr = new Verkaufsraum__c();
        vkr.ErsterKaeufer__c = con.Id;
        vkr.BeratungsPortalZugangAnlegen__c = false;
        insert vkr;
        Berechnung__c b = new Berechnung__c(Name='Test', Verkaufsraum__c=vkr.Id);
        insert b;
        BerechnungController.getFinanzierungsbaustein(b.Id);
    }

    private static testMethod void getBerechnungSaveTest() {
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Interessentenmann 6'];
        Verkaufsraum__c vkr = new Verkaufsraum__c();
        vkr.ErsterKaeufer__c = con.Id;
        vkr.BeratungsPortalZugangAnlegen__c = false;
        insert vkr;
        Berechnung__c b = new Berechnung__c(Name='Test', Verkaufsraum__c=vkr.Id);
        insert b;
        BerechnungController.getBerechnungSave();
    }

    private static testMethod void getBerechnungSaveIdTest() {
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'Interessentenmann 6'];
        Verkaufsraum__c vkr = new Verkaufsraum__c();
        vkr.ErsterKaeufer__c = con.Id;
        vkr.BeratungsPortalZugangAnlegen__c = false;
        insert vkr;
        Berechnung__c b = new Berechnung__c(Name='Test', Verkaufsraum__c=vkr.Id);
        insert b;
        BerechnungController.getBerechnungSaveWithId(b.Id);
    }
    
}