force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/classes/GlobalSearchControllerTest.cls
@isTest
                    
public class GlobalSearchControllerTest {

    public static testMethod void testControllerWithRecords() {

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;

        Account acc1 = new Account(Name = 'test', Email__c ='test@test.test');
        Database.insert(acc1, dml);
        
        Account account1 = new Account(Name='test', ParentID = acc1.id, OwnerID = '005b0000000YeZDAA0', Maklerbetreuer_Wirtschaftshaus__c = 'Lars Wagner');
        Database.insert(account1, dml);

        Contact contact1 = new Contact(AccountID=account1.id, FirstName = 'test', LastName='contact1', Gesch_ftsbeziehung__c = 'Interessent');
        Database.insert(contact1, dml);
        
        Lead lead1 = new Lead(LastName = 'test');
        Database.insert(lead1, dml);
        
        GlobalSearchController gS = new GlobalSearchController();
        
        gS.searchValue = 'test';
        gS.search();
        
        gS.getPossibleDups();
        gS.getPossibleDupLeads();
        gS.getPossibleDupAccounts();

    }    
    
    public static testMethod void testControllerWithout() {

        GlobalSearchController gS = new GlobalSearchController();
        
        gS.getPossibleDups();
        gS.getPossibleDupLeads();
        gS.getPossibleDupAccounts();

    }    
    
}