force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/TeamProQId__c.field-meta.xml
<CustomField>
    <fullName>TeamProQId__c</fullName>
    <description>External ID for TeamproQ Integration</description>
    <externalId>true</externalId>
    <label>TeamProQ ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BrokerInformation__c.field-meta.xml
<CustomField>
    <fullName>BrokerInformation__c</fullName>
    <label>Makler Infos</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FirstBuyerInformation__c.field-meta.xml
<CustomField>
    <fullName>FirstBuyerInformation__c</fullName>
    <label>Erster Käufer Infos</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KfwWunsch__c.field-meta.xml
<CustomField>
    <fullName>KfwWunsch__c</fullName>
    <label>KfW Wunsch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KfW-Darlehen 261 - energieeffzient sanieren</fullName>
            </value>
            <value>
                <fullName>KfW-Darlehen 298 - Klimafreundlicher Neubau</fullName>
            </value>
            <value>
                <fullName>Bestand</fullName>
            </value>
            <value>
                <fullName>Kein KfW</fullName>
            </value>
            <value>
                <fullName>KfW-Zuschuss (461)</fullName>
                <isActive>false</isActive>
                <label>KfW-Zuschuss (461)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kunde2__c.field-meta.xml
<CustomField>
    <fullName>Kunde2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2. Käufer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Verkaufschancen (2. Käufer)</relationshipLabel>
    <relationshipName>Verkaufschancen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SecondBuyerInformation__c.field-meta.xml
<CustomField>
    <fullName>SecondBuyerInformation__c</fullName>
    <label>Zweiter Käufer Infos</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SourceCreation__c.field-meta.xml
<CustomField>
    <fullName>SourceCreation__c</fullName>
    <label>Quelle Anlage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TeamProQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TeamProQId__c.field-meta.xml
<CustomField>
    <fullName>TeamProQId__c</fullName>
    <externalId>true</externalId>
    <label>TeamProQ ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/TeamProQId__c.field-meta.xml
<CustomField>
    <fullName>TeamProQId__c</fullName>
    <description>External ID for TeamproQ Integration</description>
    <externalId>true</externalId>
    <label>TeamProQ ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RestTeamProQOpportunity.cls
@RestResource(urlMapping='/teamproq/opportunity')
global without sharing class RestTeamProQOpportunity {
    
    @HttpPost
    global static RestTeamProQOpportunityResponse createOpportunity(RestTeamProQOpportunityRequest data) {
        RestRequest restRequest = RestContext.request;
        RestResponse restResponse = RestContext.response;

        // Account id empty error
        RestTeamProQOpportunityResponse res = new RestTeamProQOpportunityResponse();
        if(data.accountId == null) {
            res.success = false;
            RestTeamProQOpportunityError teamProQError = new RestTeamProQOpportunityError();
            teamProQError.message = 'Die "accountId" darf nicht leer sein.';
            teamProQError.code = 'AccountIdEmpty';
            res.errors.add(teamProQError);
            return res;
        }

        // No Accounts found error
        if([SELECT Id FROM Account WHERE Id = :data.accountId].size() == 0) {
            res.success = false;
            RestTeamProQOpportunityError teamProQError = new RestTeamProQOpportunityError();
            teamProQError.message = 'Zur "accountId" wurde kein Account im System gefunden.';
            teamProQError.code = 'AccountNotFound';
            res.errors.add(teamProQError);
            return res;
        }

        // First Buyer empty error
        if(data.firstBuyer == null) {
            res.success = false;
            RestTeamProQOpportunityError teamProQError = new RestTeamProQOpportunityError();
            teamProQError.message = 'Der Wert "firstBuyer" darf nicht leer sein.';
            teamProQError.code = 'FirstBuyerEmpty';
            res.errors.add(teamProQError);
            return res;
        }

        // Property not found error
        if([SELECT Id FROM Property__c WHERE TeamProQId__c = :data.propertyExternalId].size() == 0) {
            res.success = false;
            RestTeamProQOpportunityError teamProQError = new RestTeamProQOpportunityError();
            teamProQError.message = 'Zur "propertyId" wurde keine Immobilie im System gefunden.';
            teamProQError.code = 'PropertyNotFound';
            res.errors.add(teamProQError);
            return res;
        }

        // Apartment not found error
        if([SELECT Id FROM Appartment__c WHERE TeamProQId__c = :data.apartmentExternalId].size() == 0) {
            res.success = false;
            RestTeamProQOpportunityError teamProQError = new RestTeamProQOpportunityError();
            teamProQError.message = 'Zur "apartmentId" wurde kein Apartment im System gefunden.';
            teamProQError.code = 'ApartmentNotFound';
            res.errors.add(teamProQError);
            return res;
        }
        
        // Get information from custom labels
        // A dummy first buyer is being used if we can't create the contact automatically
        Id dummyFirstBuyerId = System.Label.TeamProQDummyFirstBuyerId;
        Id dummyBrokerId = System.Label.TeamProQDummyBrokerId;
        String onlineReservationStageName = System.Label.OnlineReservationStageName;

        // Query or if not found try to insert the contact
        // If duplicate rules deny the creation, the buyer will be null and thus the dummy buyer used
        Savepoint sp = Database.setSavePoint();
        Contact firstBuyer = getOrInsertContact(data.firstBuyer, data.accountId);
        Contact secondBuyer;
        if(data.secondBuyer != null) {
            secondBuyer = getOrInsertContact(data.secondBuyer, data.accountId);
        }

        List<Contact> makler = [SELECT Id FROM Contact WHERE FirstName = :data.broker.FirstName AND LastName = :data.broker.LastName AND AccountId = :data.accountId];

        // Create the opportunity with data from the request, but also default values 
        Opportunity opp = new Opportunity();
        Property__c propertyReference = new Property__c(
            TeamProQId__c=data.propertyExternalId); 
        opp.Immobilie__r = propertyReference;               

        Appartment__c apartmentReference = new Appartment__c(
            TeamProQId__c=data.apartmentExternalId); 
        opp.Appartement__r = apartmentReference;
        if(firstBuyer != null) {
            opp.Potenzieller_Kunde__c = firstBuyer.Id;
        } else {
            opp.Potenzieller_Kunde__c = dummyFirstBuyerId;
        }
        if(secondBuyer != null) {
            opp.Kunde2__c = secondBuyer.Id;
        }
        opp.AccountId = data.accountId;
        if(makler.size() == 1) {
            opp.Makler__c = makler[0].Id;
            opp.Immobilienberater__c = makler[0].Id;
        } else {
            opp.Makler__c = dummyBrokerId;
            opp.Immobilienberater__c = dummyBrokerId;
        }
        opp.StageName = onlineReservationStageName;
        opp.CloseDate = Date.today().addMonths(3);
        opp.SourceCreation__c = 'TeamProQ';
        opp.KfwWunsch__c = 'Kein KfW';

        // Fill in text area fields so that information can be checked 
        // or contacts can be created manually 
        opp.FirstBuyerInformation__c = getContactInformationString(data.firstBuyer);
        if(data.secondBuyer != null) {
            opp.SecondBuyerInformation__c = getContactInformationString(data.secondBuyer);
        }
        opp.BrokerInformation__c = getContactInformationString(data.broker);
        Database.SaveResult oppSaveResult = Database.insert(opp, false);
        
        if(oppSaveResult.isSuccess() == false) {
            Database.rollBack(sp);
        }

        // Return success true / false and if applicable error messages of the opp insert
        res.success = oppSaveResult.isSuccess();
        if(oppSaveResult.getErrors().size() > 0) {
            res.errors = new List<RestTeamProQOpportunityError>();
        }
        for(Database.Error error:oppSaveResult.getErrors()) {
            RestTeamProQOpportunityError teamProQError = new RestTeamProQOpportunityError();
            teamProQError.code = 'OpportunityNotCreated';
            teamProQError.message = error.getMessage();
            res.errors.add(teamProQError);
        }
        return res;
    }

    /**
     * Queries a contact or tries to inserts it if none is found
     */
    public static Contact getOrInsertContact(Contact buyer, Id accountId) {
        // Searches within the hierarchy of the parentId, as the contact might already exists somewhere in MLP
        List<Contact> buyerContacts = [SELECT Id FROM Contact WHERE LastName = :buyer.LastName AND FirstName = :buyer.FirstName AND AccountId = :accountId];
        
        if(buyerContacts.size() == 1) {
            buyer = buyerContacts[0];
        }

        Database.SaveResult buyerSaveResult;
        if(buyer.Id == null) {
            buyer.AccountId = accountId;
            buyer.Gesch_ftsbeziehung__c = 'Interessent';
            buyerSaveResult = Database.insert(buyer, false);
        }
        
        if((buyerSaveResult != null && buyerSaveResult.isSuccess() == false) || buyer == null) {
            return null;
        } else {
            return buyer;
        }
    }

    /**
     * Returns a string containing the contact information on new lines
     */
    public static String getContactInformationString(Contact con) {
        if(con == null) {
            return '';
        }
        String contactInformation = '';
        if(con.FirstName != null) {
            contactInformation += 'Vorname: ' + con.FirstName + '\r\n';
        }
        if(con.LastName != null) {
            contactInformation += 'Nachname: ' + con.LastName + '\r\n';
        }
        if(con.MailingStreet != null) {
            contactInformation += 'Straße: ' + con.MailingStreet + '\r\n';
        }
        if(con.MailingPostalCode != null) {
            contactInformation += 'PLZ: ' + con.MailingPostalCode + '\r\n';
        }
        if(con.MailingCity != null) {
            contactInformation += 'Stadt: ' + con.MailingCity + '\r\n';
        }
        if(con.Phone != null) {
            contactInformation += 'Telefon: ' + con.Phone + '\r\n';
        }
        if(con.Email != null) {
            contactInformation += 'E-Mail: ' + con.Email + '\r\n';
        }
        if(con.Birthdate != null) {
            contactInformation += 'Geburtsdatum: ' + con.Birthdate + '\r\n';
        }
        return contactInformation;
    }

    global class RestTeamProQOpportunityRequest {
        global String propertyExternalId;
        global String apartmentExternalId;
        global Id accountId;
        global Contact firstBuyer;
        global Contact secondBuyer;
        global Contact broker;
    }

    global class RestTeamProQOpportunityResponse {
        global Boolean success;
        global List<RestTeamProQOpportunityError> errors;

        global RestTeamProQOpportunityResponse() {
            errors = new List<RestTeamProQOpportunityError>();
        }
    }

    global class RestTeamProQOpportunityError {
        global String message;
        global String code;
    }
}