force-app/main/default/objects/Account/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hausbank</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
            <value>
                <fullName>Bauträger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Geschueftsfuehrer__c.field-meta.xml
<CustomField>
    <fullName>Geschueftsfuehrer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geschäftsführer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Geschäftsführer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Maklerprovision__c</fullName>
    <label>Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Steuernummer__c.field-meta.xml
<CustomField>
    <fullName>Steuernummer__c</fullName>
    <label>Steuernummer</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/beurkundeter_Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>beurkundeter_Kaufpreis__c</fullName>
    <label>beurkundeter Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Teilobjekte</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gesch_ftsbeziehung__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsbeziehung__c</fullName>
    <label>Geschäftsbeziehung</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kunde</fullName>
            </value>
            <value>
                <fullName>Interessent</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter WH</fullName>
            </value>
            <value>
                <fullName>Maklerbetreuer</fullName>
            </value>
            <value>
                <fullName>Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Immobilienmakler</fullName>
            </value>
            <value>
                <fullName>Regional Direktor</fullName>
            </value>
            <value>
                <fullName>Notar</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Dienstleister</fullName>
            </value>
            <value>
                <fullName>Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>Anbahnung</fullName>
            </value>
            <value>
                <fullName>Immobilien- oder Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanz- und Versicherungsmakler</fullName>
            </value>
            <value>
                <fullName>Finanzmakler</fullName>
            </value>
            <value>
                <fullName>Gekündigt vom WirtschaftsHaus</fullName>
            </value>
            <value>
                <fullName>Gekündigt von Extern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Steuernummer__c.field-meta.xml
<CustomField>
    <fullName>Steuernummer__c</fullName>
    <label>Steuernummer</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Makler.recordType-meta.xml
<RecordType>
    <fullName>Makler</fullName>
    <active>true</active>
    <description>Ansicht wenn der Kontakt ein Makler ist</description>
    <label>Mitarbeiter</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/beurkundeter_Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>beurkundeter_Kaufpreis__c</fullName>
    <label>beurkundeter Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufdatum__c.field-meta.xml
<CustomField>
    <fullName>Kaufdatum__c</fullName>
    <label>Kaufdatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis__c</fullName>
    <formula>IF( Appartement__r.DeviatingPurchasePrice__c != 0 &amp;&amp; !IsBlank(Appartement__r.DeviatingPurchasePrice__c), Appartement__r.DeviatingPurchasePrice__c, Appartement__r.Purchase_Price__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listenpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Maklerprovision__c</fullName>
    <label>Grundprovision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Keine</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>4.5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5.5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>3.8</fullName>
            </value>
            <value>
                <fullName>4.3</fullName>
            </value>
            <value>
                <fullName>3.75</fullName>
            </value>
            <value>
                <fullName>4.25</fullName>
            </value>
            <value>
                <fullName>4.75</fullName>
            </value>
            <value>
                <fullName>5.25</fullName>
            </value>
            <value>
                <fullName>5.75</fullName>
            </value>
            <value>
                <fullName>6.25</fullName>
            </value>
            <value>
                <fullName>6.75</fullName>
            </value>
            <value>
                <fullName>7.25</fullName>
            </value>
            <value>
                <fullName>7.75</fullName>
            </value>
            <value>
                <fullName>8.25</fullName>
            </value>
            <value>
                <fullName>8.75</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <label>Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verk_ufer_Beratungsprovision__c.field-meta.xml
<CustomField>
    <fullName>Verk_ufer_Beratungsprovision__c</fullName>
    <label>Verkäufer-/Beratungsprovision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Keine</fullName>
                <default>true</default>
                <label>Keine</label>
            </value>
            <value>
                <fullName>0.365</fullName>
            </value>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>0.75</fullName>
            </value>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.25</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Steuernummer__c.field-meta.xml
<CustomField>
    <fullName>Steuernummer__c</fullName>
    <label>Steuernummer</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis__c</fullName>
    <label>Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApprovalControllerTest.cls
@IsTest
public class ApprovalControllerTest {

    @testSetup static void test_setup() {
        User testUser = TestDataFactory.createTestUser(true, 'TestAdmin', 345);
        User testUserRole = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' Limit 1];
        testUser.UserRoleId = testUserRole.UserRoleId;
        update testUser;
        try{
            PermissionSet ps_status = [SELECT Id FROM PermissionSet WHERE Name = 'Can_change_stage_status'];
            PermissionSet ps_contact = [SELECT Id FROM PermissionSet WHERE Name = 'ChangeContactAccount'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_status.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_contact.Id);
        }
        catch(DmlException e){
            System.debug(e.getMessage());
        }
        System.runAs(testUser){
            Contact mb = TestDataFactory.createContact(true,'Frank', 'Köpsell', 'witte@amstammtisch.de');
            Account acc3 = TestDataFactory.createAccount(true, 'WH Maklerbetreuer - Frank Köpsell', null);
            acc3.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
            acc3.BIC__c  = '1';
            acc3.Geschueftsfuehrer__c = mb.id;
            acc3.Steuernummer__c = '24/231/123';
            update acc3;

            mb.AccountId = acc3.Id;
            update mb;

            Contact potKun = TestDataFactory.createContact(true,'Tvvsta', 'Tekoeeric', 'test@tester.de');
            Property__c immobilie = TestDataFactory.createProperty(true, null, 'Immobilie');    
            
            Appartment__c app2 = TestDataFactory.createAppartment(true, immobilie.Id);
            
            Provisionsverhandlung__c provisionsverhandlung = TestDataFactory.createProvisionsverhandlung(true, acc3.Id, immobilie.Id);

            TestDataFactory.createDatevSettings();
            TestDataFactory.createNecessaryCustomSettings();
        }
    }

    private static testMethod void approveProvision() {
        User testUser = TestDataFactory.createTestUser(true, 'TestAdmin', 123);
        User testUserRole = [Select Id, UserRoleId From User Where Profile.Name='System Administrator' Limit 1];
        testUser.UserRoleId = testUserRole.UserRoleId;
        update testUser;

        try{
            PermissionSet ps_status = [SELECT Id FROM PermissionSet WHERE Name = 'Can_change_stage_status'];
            PermissionSet ps_contact = [SELECT Id FROM PermissionSet WHERE Name = 'ChangeContactAccount'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_status.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_contact.Id);
        }
        catch(DmlException e){
            System.debug(e.getMessage());
        }

        System.runAs(testUser){

            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;

            Account acc3 = [SELECT Id FROM Account];
            
            Id maklerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
            .get('Makler').getRecordTypeId();
            Contact con = TestDataFactory.createContact(true,'Max', 'Maklermann 6', 'wittexyz@amstammtisch.de');
            con.AccountId = acc3.Id;
            con.Gesch_ftsbeziehung__c = 'Versicherungsmakler';
            con.RecordTypeId = maklerRecordTypeId;
            update con;

            Database.insert(con, dml);

            Profile portalProfileUser = [SELECT Id FROM Profile WHERE Name LIKE '%Partner Community%User' Limit 1];
            Profile portalProfileManager = [SELECT Id FROM Profile WHERE Name LIKE '%Partner Community%Manager' Limit 1];
            
            List<PermissionSetAssignment> pmas = new List<PermissionSetAssignment>();
            List<PermissionSet> pms = [SELECT Id, Name FROM PermissionSet WHERE Name Like '%Community%'];
            PermissionSet accPm;
            PermissionSet conPm;
            PermissionSet provPm;
            PermissionSet immPm;
            for(PermissionSet pm:pms) {
                if(pm.Name.contains('Accounts')) { 
                    accPm = pm;
                } else if(pm.Name.contains('Kontakte')) { 
                    conPm = pm;
                } else if(pm.Name.contains('Provision')) { 
                    provPm = pm;
                } else if(pm.Name.contains('Immobilie')) {
                    immPm = pm;
                }
            }

            List<User> communityUsers = new List<User>();
            String sbName = UserInfo.getUserName().substringAfterLast('.');
            
            User usr = TestDataFactory.createTestUser(false);
            usr.Firstname=con.firstName;
            usr.Lastname=con.LastName;
            usr.ContactId=con.Id;
            usr.Username = 'salesaccount5@test.de';
            usr.profileId = portalProfileUser.Id;
            usr.Alias = usr.Username.substring(0,6);
            insert usr;

            Contact mb = [SELECT Id, Email, OwnerId FROM Contact WHERE LastName = 'Köpsell'];
            Contact potKun = [SELECT Id FROM Contact WHERE LastName = 'Tekoeeric'];
            Property__c immobilie = [SELECT ID From Property__c];
            Appartment__c app2 = [SELECT ID From Appartment__c];
            Opportunity opp2 = Testdatafactory.createOpportunity(false, potKun.Id, mb.Id, immobilie.Id, app2.Id, 'Reservierung angefragt', 100000);
            opp2.AccountId = acc3.Id;
            opp2.Kaufdatum__c = System.Today();
            opp2.Immobilienberater__c = mb.Id;
            opp2.Maklerprovision__c = '4.5';
            opp2.Verk_ufer_Beratungsprovision__c = '1.5';
            insert opp2;

            Test.startTest();

            opp2.StageName = 'Geschlossene und gewonnene';
            opp2.beurkundeter_Kaufpreis__c = 123123.23;
            update opp2;

            Provision__c provision = Testdatafactory.createProvision(false, opp2.Id, mb.OwnerId, opp2.Makler__c);
            provision.E_Mail__c = mb.Email;
            provision.Ausl_ser__c = mb.Id;
            provision.Kaufpreis__c = opp2.Provisionsbasis__c;
            provision.Maklerbetreuer__c = '005b0000001V30P';
            insert provision;

            User user = [SELECT Id FROM User WHERE LastName = 'Maklermann 6'];

            Test.stopTest();

    //        TODO run in Maklerbetreuer context
    //        List<ApprovalController.ProvisionApproval> pas = ApprovalController.getProvisionApprovals();
    //        ApprovalController.approveProvision(pas[0].workItemId);
        }
    }
}