force-app/main/default/objects/Account/fields/Geschueftsfuehrer__c.field-meta.xml
<CustomField>
    <fullName>Geschueftsfuehrer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geschäftsführer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Geschäftsführer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gesetzliche_MwSt_auf_Provisionszahlung__c.field-meta.xml
<CustomField>
    <fullName>Gesetzliche_MwSt_auf_Provisionszahlung__c</fullName>
    <label>Gesetzliche MwSt. auf Provisionszahlung</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hinweis_zur_MwSt__c.field-meta.xml
<CustomField>
    <fullName>Hinweis_zur_MwSt__c</fullName>
    <inlineHelpText>Bitte gib hier an, woher die Information kommt, welchen MwSt-Satz der Makler hat</inlineHelpText>
    <label>Hinweis zur MwSt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Wirtschaftshaus(veraltet)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andreas Pohl</fullName>
            </value>
            <value>
                <fullName>Attila Dachwitz</fullName>
            </value>
            <value>
                <fullName>Bastian Dörge</fullName>
            </value>
            <value>
                <fullName>Boris Bökert</fullName>
            </value>
            <value>
                <fullName>Christoph Ellermann</fullName>
            </value>
            <value>
                <fullName>Erich Pilz</fullName>
            </value>
            <value>
                <fullName>Frank Köpsell</fullName>
            </value>
            <value>
                <fullName>Harald Senftleben</fullName>
            </value>
            <value>
                <fullName>Jana Pawils</fullName>
            </value>
            <value>
                <fullName>Johann Kuipers</fullName>
            </value>
            <value>
                <fullName>Jonas Laue</fullName>
            </value>
            <value>
                <fullName>Jürgen Engler</fullName>
            </value>
            <value>
                <fullName>Karsten Fengler</fullName>
            </value>
            <value>
                <fullName>Kelvin Schwabe</fullName>
            </value>
            <value>
                <fullName>Lars Wagner</fullName>
            </value>
            <value>
                <fullName>Marc Claes</fullName>
            </value>
            <value>
                <fullName>Marco Ellermann</fullName>
            </value>
            <value>
                <fullName>Martin Ledvinka</fullName>
            </value>
            <value>
                <fullName>Maurice Fuhrmann</fullName>
            </value>
            <value>
                <fullName>Max Hergt</fullName>
            </value>
            <value>
                <fullName>Mirco Buchholz</fullName>
            </value>
            <value>
                <fullName>Nils Nebel</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>Peter Eulitz</fullName>
            </value>
            <value>
                <fullName>Raik Lubitz</fullName>
            </value>
            <value>
                <fullName>Ralf Döring</fullName>
            </value>
            <value>
                <fullName>Robin Bergmann</fullName>
            </value>
            <value>
                <fullName>Rüdiger Panzer-Sennholz</fullName>
            </value>
            <value>
                <fullName>Sandro Pawils</fullName>
            </value>
            <value>
                <fullName>Susanne Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rechtsform__c.field-meta.xml
<CustomField>
    <fullName>Rechtsform__c</fullName>
    <label>Rechtsform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Area_sq_m__c.field-meta.xml
<CustomField>
    <fullName>Area_sq_m__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Area (sq.m)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Maklerbetreuer_Wirtschaftshaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus__c</fullName>
    <label>Maklerbetreuer Carestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Repayment_Beginning__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Beginning__c</fullName>
    <label>Repayment Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calculation__c/Calculation__c.object-meta.xml
<CustomObject>
    <label>Immo Berechnung</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Immo Berechnung Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Immo Berechnungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calculation__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Appartment__c.field-meta.xml
<CustomField>
    <fullName>Appartment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Appartment</label>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Brokers_Person__c.field-meta.xml
<CustomField>
    <fullName>Brokers_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brokers Person</label>
    <referenceTo>Realty_User__c</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>First Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Last Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Calculations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Repayment_Beginning__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Beginning__c</fullName>
    <label>Repayment Beginning</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Starting__c.field-meta.xml
<CustomField>
    <fullName>Starting__c</fullName>
    <label>Starting</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Street</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calculation__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Zip Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MaklerBetreuer_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>MaklerBetreuer_E_Mail__c</fullName>
    <label>MaklerBetreuer E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Place</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Repayment_Beginning__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Beginning__c</fullName>
    <label>Repayment Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Street</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/Realty_User__c.object-meta.xml
<CustomObject>
    <label>Immo Benutzer</label>
    <nameField>
        <label>Immo Benutzer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immo Benutzer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realty_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Realty_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Login_Email__c.field-meta.xml
<CustomField>
    <fullName>Login_Email__c</fullName>
    <label>Login Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Normal Agency</fullName>
            </value>
            <value>
                <fullName>Manager Agency</fullName>
            </value>
            <value>
                <fullName>Free Lancer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBerechnungsmail.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBerechnungsmail {

    static testMethod void myUnitTest() {
		Contact mb = new Contact();
		mb.FirstNAme = 'Frank';
		mb.LastName = 'Köpsell';
		mb.Email = 'witte@amstammtisch.de';
		mb.MaklerBetreuer_E_Mail__c = 'witte@amstammtisch.de';
		insert mb;
		Account acc = new Account();
		acc.Name = 'WH Maklerbetreuer - Frank Köpsell';
		acc.Email__c = 'witte@amstammtisch.de';
		acc.Maklerbetreuer_Wirtschaftshaus__c = 'Frank Köpsell';
		acc.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
		acc.BIC__c  = '1';
		acc.Geschueftsfuehrer__c = mb.id;
		acc.Gesetzliche_MwSt_auf_Provisionszahlung__c = 0.4;
		acc.Hinweis_zur_MwSt__c = 'Vertrag';
		acc.IBAN__c = 'DE02120300000000202051';
		acc.Rechtsform__c = 'GbR';
		acc.Unternehmensname__c = 'CareStone';
		insert acc;
		mb.AccountId = acc.Id;
		update mb;
        
        Contact con1 = new Contact (LastName = 'test', accountID = acc.id, Email = 'test@test.test');
        insert con1;
        
        Property__c prop = new Property__c(Name = 'TestImmobilie', Place__c = 'Hannover', Zip_Code__c = '30159', Street__c = 'Am hohen Ufer 5A');
        insert prop;
        
		Appartment__c app = new Appartment__c(Name ='Test Appartment', Property__c = prop.ID, Area_sq_m__c = 15);
		insert app;
		
		Realty_User__c immoUser = new Realty_User__c(Name = 'test', Email__c = 'test@test.test', Login_Email__c = 'test@test.test', Password__c = 'test', Type__c = 'Normal Agency', Contact__c = con1.id);
		insert immoUser;
		
        Calculation__c calc = new Calculation__c(	Property__c = prop.id,
        											Appartment__c = app.id,
        											Starting__c = date.today(),
        											Sale_Price__c = 123456,
        											Repayment_Beginning__c = date.today(),
        											Agency__c = acc.id,
        											Brokers_Person__c = immoUser.id,
        											Last_Name__c = 'test',
        											First_Name__c = 'test');
    	insert calc;
    }
}