force-app/main/default/objects/Account/fields/Geschueftsfuehrer__c.field-meta.xml
<CustomField>
    <fullName>Geschueftsfuehrer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geschäftsführer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Geschäftsführer)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Amtsgericht__c.field-meta.xml
<CustomField>
    <fullName>Amtsgericht__c</fullName>
    <label>Amtsgericht</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Gesch_ftsf_hrer__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsf_hrer__c</fullName>
    <label>Geschäftsführer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/HRB__c.field-meta.xml
<CustomField>
    <fullName>HRB__c</fullName>
    <label>HRB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Provisionsverhandlung__c/Provisionsverhandlung__c.object-meta.xml
<CustomObject>
    <label>Provisionsverhandlung</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Provisionsverhandlung-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionsverhandlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DocuSignHandlerTest.cls
@isTest
public class DocuSignHandlerTest {
    
    @testSetup static void test_setup() {
        User testUser = TestDataFactory.createTestUser(true, 'TestAdmin', 1);
        try{
            PermissionSet ps_status = [SELECT Id FROM PermissionSet WHERE Name = 'Can_change_stage_status'];
            PermissionSet ps_contact = [SELECT Id FROM PermissionSet WHERE Name = 'ChangeContactAccount'];
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_status.Id);
            insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = ps_contact.Id);
        }
        catch(DmlException e){
            System.debug(e.getMessage());
        }

        System.runAs(testUser){
        
            Contact mb = TestDataFactory.createContact(true,'Frank', 'Köpsell', 'witte@amstammtisch.de');
            Account acc3 = TestDataFactory.createAccount(false, 'WH Maklerbetreuer - Frank Köpsell', null);
            acc3.Maklerbetreuer_Wirtschaftshaus_2__c = mb.Id;
            acc3.BIC__c  = '1';
            acc3.Geschueftsfuehrer__c = mb.id;
            insert acc3;
            
            mb.AccountId = acc3.Id;
            update mb;

            Contact potKun = TestDataFactory.createContact(true,'Tvvsta', 'Tekoeeric', 'wittetest@amstammtisch.de');
            
            Property__c immobilie = TestDataFactory.createProperty(false, null, 'Immobilie');    
            immobilie.Gesch_ftsf_hrer__c = mb.id;
            immobilie.Amtsgericht__c = 'test';
            immobilie.HRB__c = '123';
            insert immobilie;
            
            Appartment__c app2 = TestDataFactory.createAppartment(true, immobilie.Id);

            Provisionsverhandlung__c provisionsverhandlung = TestDataFactory.createProvisionsverhandlung(true, acc3.Id, immobilie.Id);

            TestDataFactory.createDatevSettings();
            TestDataFactory.createNecessaryCustomSettings();

            Opportunity opp3 = Testdatafactory.createOpportunity(true, potKun.Id, mb.Id, immobilie.Id, app2.Id, 'Available', 100000);
        }
    }

    /**
     * Test sending the envelope to a lead
     */
    static testMethod void testSendingDocuSignEnvelope() {

        User DocuSignUser = TestDataFactory.createTestUser(true, 'TestAdmin', 2);

        PermissionSet ps_sender = [SELECT Id FROM PermissionSet WHERE Name = 'DocuSign_Sender'];
        insert new PermissionSetAssignment(AssigneeId = DocuSignUser.id, PermissionSetId = ps_sender.Id);
                
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];

        List<DocuSignHandler.Variables> requestList = new List<DocuSignHandler.Variables>();
        DocuSignHandler.Variables variable = new DocuSignHandler.Variables();
        variable.docuSignTemplateId = '90869f0d-e2d7-4765-87dc-39d2290a5ac2';
        variable.ids = null;
        variable.id = o.Id;
        variable.emailSubject = 'Test subject';
        variable.emailContent = 'Test content';
        requestList.add(variable);

        System.runAs(DocuSignUser){
            Test.startTest();
        
                DocuSignHandler.sendEnvelopes(requestList);
        
            Test.stopTest();
        }
    }
}