force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neu</fullName>
                <default>true</default>
                <label>Neu</label>
            </value>
            <value>
                <fullName>Kontaktiert</fullName>
            </value>
            <value>
                <fullName>Terminiert</fullName>
            </value>
            <value>
                <fullName>Aktiv</fullName>
            </value>
            <value>
                <fullName>Inaktiv</fullName>
            </value>
            <value>
                <fullName>Verloren</fullName>
            </value>
            <value>
                <fullName>Blacklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/Appartment__c.object-meta.xml
<CustomObject>
    <label>Teilobjekt</label>
    <nameField>
        <label>Appartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilobjekte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appartment__c/fields/Area_sq_m__c.field-meta.xml
<CustomField>
    <fullName>Area_sq_m__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Area (sq.m)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Monthly_Rent__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Rent</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Monthly_rent_sq_m__c.field-meta.xml
<CustomField>
    <fullName>Monthly_rent_sq_m__c</fullName>
    <label>Monthly rent (sq m)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Teilobjekte</relationshipLabel>
    <relationshipName>Appartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Purchase Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kontingent</fullName>
            </value>
            <value>
                <fullName>Reservierungsvorbereitung</fullName>
            </value>
            <value>
                <fullName>Reservierung angefragt</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsangebot abgegeben</fullName>
            </value>
            <value>
                <fullName>KV wird fremd abgegeben</fullName>
            </value>
            <value>
                <fullName>Kaufvertragsunterlagen verschickt -zweiseitig-</fullName>
            </value>
            <value>
                <fullName>Auftrag zur Beurkundung vorhanden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appartment__c/fields/Zimmerart__c.field-meta.xml
<CustomField>
    <fullName>Zimmerart__c</fullName>
    <label>Zimmerart</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Einzelzimmer</fullName>
            </value>
            <value>
                <fullName>Doppelzimmer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aktiv</fullName>
                <default>true</default>
                <label>Aktiv</label>
            </value>
            <value>
                <fullName>Komplettverkauft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ImmobilienAsExcel.cls
global class ImmobilienAsExcel implements Schedulable {
	public List<Property__c> properties {get;set;}
	public List<Contact> contacts {get;set;}
	public String subject { get; set; }
	public String body { get; set; }

	global void execute(SchedulableContext sc) {
		ImmobilienAsExcelBatch iaeb = new ImmobilienAsExcelBatch();
		Database.executebatch(iaeb, 800);
	}

	public void sendexcelfile(List<Contact> contacts){
		// Liste aller Objekte mit Apartments
		properties = [SELECT Name, Property__c, (SELECT Name, Area_sq_m__c, Monthly_rent_sq_m__c,Zimmerart__c, Monthly_rent__c, Purchase_Price__c, Status__c FROM Appartments__r WHERE Status__c='Available' OR Status__c = 'Reservierung angefragt' OR Status__c = 'Reservierungsvorbereitung' OR Status__c = 'Reserved' ORDER BY Name) FROM Property__c WHERE (Is_Public__c = true AND Status_Reason__c = 'Aktiv') ORDER BY Name];

		// Die Header Columns der CSV Datei
		string header ='Objekt;Objektart;Apartment;Größe m²;Zimmerart;Miete / m²;Miete / Monat;Kaufpreis \n';//;Status
		String finalstr = header;

		PageReference pdf = Page.ImmobilienAsExcel;

		// Blob und E-Mail Anhang aus dem String generieren
		Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
		attach.ContentType = 'application/pdf';
		Blob body;
		try {
			body = pdf.getContentAsPDF();
		} catch(Exception e) {
			body = blob.valueOf('Ein Fehler ist aufgetreten');
		}
		// Dateiname der CSV
		String fileName = 'Carestone Objekte ' + String.valueOf(Date.today().format()) + '.pdf';
		attach.setFileName(fileName);
		attach.setInline(false);
		attach.Body = body;

		Id templateId = [select id, name from EmailTemplate where developername = 'Excel_Objekte'].id;
		Set<OrgWideEmailAddress> oweas = new Set<OrgWideEmailAddress>([select Id, DisplayName from OrgWideEmailAddress]);
		Map<String, Id> oweaStringToId = new Map<String, Id>();
		for(OrgWideEmailAddress owea:oweas) {
			oweaStringToId.put(owea.DisplayName, owea.Id);
		}
		// Contact con = [SELECT Id FROM Contact WHERE Email = 'f.witte@wirtschaftshaus.de' LIMIT 1];
		Messaging.Email[] messages = new Messaging.Email[0];
		Set<String> mails = new Set<String>();
		for(Contact con:contacts) {
			if(!mails.contains(con.Email)) {
				// SingleEmailMessage erstellen
				Messaging.singleEmailMessage Emailwithattch = new Messaging.singleEmailMessage();
				Emailwithattch.setTemplateId(templateId);
				Emailwithattch.setTargetObjectId(con.Id);
				if ( oweas.size() > 0 ) {
					if(con.Account.Maklerbetreuer_Wirtschaftshaus_2__c != null && oweaStringToId.containsKey(con.Account.Maklerbetreuer_Wirtschaftshaus_2__r.Name) && con.Account.Maklerbetreuer_Wirtschaftshaus_2__r.Name != 'Mirco Buchholz') {
						Emailwithattch.setOrgWideEmailAddressId(oweaStringToId.get(con.Account.Maklerbetreuer_Wirtschaftshaus_2__r.Name));
					} else {
						Emailwithattch.setOrgWideEmailAddressId(oweaStringToId.get('Carestone Service'));
					}
				}
				Emailwithattch.setFileAttachments(new Messaging.EmailFileAttachment[]{attach});
				// Sends the email
				messages.add(Emailwithattch);
				mails.add(con.Email);
			}
		}

		Messaging.SendEmailResult [] r = Messaging.sendEmail(messages, false);
	}
}