force-app/main/default/objects/Account/fields/Maklerbetreuer__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/Activity_Summary__c.object-meta.xml
<CustomObject>
    <description>Counts all of community users logs</description>
    <label>VP Aktivitäten</label>
    <nameField>
        <displayFormat>VP Login {0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VP Aktivitäten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ActivitySummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>For the Account Monitoring component</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activity_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Maklerbetreuer__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ActivitySummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Number_of_downloads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_downloads__c</fullName>
    <label>Anzahl Downloads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Number_of_Logins__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Logins__c</fullName>
    <description>For the Account Monitoring component</description>
    <label>Number of Logins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Number_of_new_prospects__c.field-meta.xml
<CustomField>
    <fullName>Number_of_new_prospects__c</fullName>
    <label>Anzahl angelegte Interessenten</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/HatVPZugang__c.field-meta.xml
<CustomField>
    <fullName>HatVPZugang__c</fullName>
    <formula>!IsBlank(VPBenutzerId__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hat VP Zugang</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Interessent.recordType-meta.xml
<RecordType>
    <fullName>Interessent</fullName>
    <active>true</active>
    <label>Interessent</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Kunde.recordType-meta.xml
<RecordType>
    <fullName>Kunde</fullName>
    <active>true</active>
    <label>Kunde</label>
</RecordType>

force-app/main/default/objects/FileDownloadLog__c/FileDownloadLog__c.object-meta.xml
<CustomObject>
    <label>File Download Log</label>
    <nameField>
        <displayFormat>FDL-{0000}</displayFormat>
        <label>File Download Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Download Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FileDownloadLog__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Datei Downloads</relationshipLabel>
    <relationshipName>FileDownloads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FileDownloadLog__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>File_Download_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Month.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <default>true</default>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <description>choose month</description>
    <masterLabel>Month</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
        <default>true</default>
        <label>2022</label>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <description>pick a year for Account Monitoring component</description>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserActivitySummaryBatch.cls
public with sharing class UserActivitySummaryBatch implements Database.Batchable<sObject> {
    static final DateTime FIRST_DAY_OF_CURRENT_MONTH = DateTime.newInstance(Date.today().year(), Date.today().month(), 1);
    List<id> contactsIds;
    public UserActivitySummaryBatch(List<id> ContactsIds) {
        this.contactsIds = contactsIds;
    }
    public UserActivitySummaryBatch() {
        this.contactsIds = null;
    }
    public List<contact> start(Database.BatchableContext bc) {
        system.debug('----------started-----------');
        if (contactsIds != null) {
            return [SELECT Id, AccountId, Account.OwnerId FROM Contact WHERE Id = :this.contactsIds];
        } else {
            return [SELECT Id, AccountId, Account.OwnerId FROM Contact WHERE HatVPZugang__c = true];
        }
    }
    public void execute(Database.BatchableContext BC, list<contact> scope) {

        Map<id, contact> contacts = new Map<Id, contact>(scope);
        Set<Id> accIds = new Set<Id>();
        System.Debug('contacts: ' + contacts.keyset());
        List<Id> contactIds = new List<Id>();
        for(Contact con:scope) {
            contactIds.add(con.Id);
            accIds.add(con.AccountId);
        }
        //map that contains contactid and activity summary id related to that contact
        Map<id, id> contactsIdsWithActivitySummary = new Map<id, id>();
        //get all existsing activity summaries for contacts(scope) that matches criteria:
        //* month = currentMonth AND year=currentYear
        Map<id, Activity_Summary__c> existingSummaries = new Map<id, Activity_Summary__c>(
        [
                SELECT id, number_of_logins__c, Contact__c
                FROM Activity_Summary__c
                WHERE Contact__c = :contacts.keySet()
                AND month__c = :String.valueOf(Date.today().month())
                AND year__c = :String.valueOf(Date.today().year())
        ]);

        //fill map with contact Id and related activity Summary
        for (Activity_Summary__c summary : existingSummaries.values()) {
            contactsIdsWithActivitySummary.put(summary.Contact__c, summary.id);
        }

        Map<Id, List<FileDownloadLog__c>> contactToFdlsMap = new Map<Id, List<FileDownloadLog__c>>();
        for(FileDownloadLog__c fdl:[SELECT Contact__c FROM FileDownloadLog__c WHERE Contact__c IN :contactIds AND CreatedDate > :FIRST_DAY_OF_CURRENT_MONTH]) {
            List<FileDownloadLog__c> fdls = contactToFdlsMap.get(fdl.Contact__c);
            if(fdls == null) {
                fdls = new List<FileDownloadLog__c>();
            }
            fdls.add(fdl);
            contactToFdlsMap.put(fdl.Contact__c, fdls);
        }

        Id interessentRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Interessent').getRecordTypeId();
        Id kundeRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Kunde').getRecordTypeId();
        Map<Id, List<Contact>> accountToContactsMap = new Map<Id, List<Contact>>();
        for(Contact con:[SELECT Id, AccountId FROM Contact WHERE AccountId IN :accIds AND CreatedDate > :FIRST_DAY_OF_CURRENT_MONTH AND (RecordTypeId = :interessentRecordTypeId OR RecordTypeId = :kundeRecordTypeId)]) {
            List<Contact> cons = accountToContactsMap.get(con.AccountId);
            if(cons == null) {
                cons = new List<Contact>();
            }
            cons.add(con);
            accountToContactsMap.put(con.AccountId, cons);
        }

        List<Activity_Summary__c> summariesToUpsert = new List<Activity_Summary__c>();
        for (Contact con : scope) {

            integer numberOfNewProspects = accountToContactsMap.get(con.AccountId)?.size();
            if(numberOfNewProspects == null) {
                numberOfNewProspects = 0;
            }

            integer numberOfDownloads = contactToFdlsMap.get(con.Id)?.size();
            if(numberOfDownloads == null) {
                numberOfDownloads = 0;
            }

            Id summaryId = contactsIdsWithActivitySummary.get(con.id);
            if (summaryId != null) {
                Activity_Summary__c summary = existingSummaries.get(summaryId);
                summary.number_of_new_prospects__c = numberOfNewProspects;
                summary.number_of_downloads__c = numberOfDownloads;
                summariesToUpsert.add(summary);
            } else {
                Activity_Summary__c newSummary = new Activity_summary__c();
                newSummary.year__c = String.valueOf(Date.Today().Year());
                newSummary.month__c = String.valueOf(date.today().Month());
                newSummary.number_of_new_prospects__c = numberOfNewProspects;
                newSummary.number_of_downloads__c = numberOfDownloads;
                newSummary.Contact__c = con.Id;
                newSummary.Account__c = con.AccountId;
                newSummary.Maklerbetreuer__c = con.Account.OwnerId;
                summariesToUpsert.add(newSummary);
            }
        }
        upsert summariesToUpsert;
    }
    public void finish(Database.BatchableContext BC) {
        system.debug('----------finished-----------');
    }
}