force-app/main/default/objects/Account/fields/Maklerbetreuer_Wirtschaftshaus_2__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_Wirtschaftshaus_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Maklerbetreuer Wirtschaftshaus)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ankuendigung__c/Ankuendigung__c.object-meta.xml
<CustomObject>
    <label>Ankündigung</label>
    <nameField>
        <label>Ankündigungen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ankündigungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ankuendigung__c/fields/AnzeigenBis__c.field-meta.xml
<CustomField>
    <fullName>AnzeigenBis__c</fullName>
    <label>Anzeigen bis</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ankuendigung__c/fields/AnzeigenVon__c.field-meta.xml
<CustomField>
    <fullName>AnzeigenVon__c</fullName>
    <label>Anzeigen von</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ankuendigung__c/fields/Inhalt__c.field-meta.xml
<CustomField>
    <fullName>Inhalt__c</fullName>
    <label>Inhalt</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/AnkuendigungController.cls
public without sharing class AnkuendigungController {

    @AuraEnabled(cacheable=true)
    public static Ankuendigung__c getAnkuendigung() {
        Id userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        Profile pf = [SELECT Name FROM Profile WHERE Id = :profileId];
        User usr = [SELECT ContactId, AccountId FROM User WHERE Id = :userId];
        Id conId = usr.ContactId;
        Id accId = usr.AccountId;
        List<Contact> mbCons = [SELECT OwnerId FROM Contact WHERE Id IN (SELECT Maklerbetreuer_Wirtschaftshaus_2__c FROM Account WHERE Id = :accId)];
        Id mbOwnerId;
        if(mbCons.size() > 0) {
            mbOwnerId = mbCons[0].ownerId;
        }
        DateTime now = DateTime.now();
        List<Ankuendigung__c> ankuendigungen = [SELECT Id, Inhalt__c, Name FROM Ankuendigung__c WHERE OwnerId = :mbOwnerId AND AnzeigenVon__c <= :now AND AnzeigenBis__c >= :now];
        if(ankuendigungen.size() > 0) {
            return ankuendigungen[0];
        }

        return null;
    }

}