force-app/main/default/objects/Account/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Afa_Outdoor__c.field-meta.xml
<CustomField>
    <fullName>Afa_Outdoor__c</fullName>
    <defaultValue>0.0667</defaultValue>
    <label>Afa Outdoor</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Amtsgericht__c.field-meta.xml
<CustomField>
    <fullName>Amtsgericht__c</fullName>
    <label>Amtsgericht</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/BIC__c.field-meta.xml
<CustomField>
    <fullName>BIC__c</fullName>
    <label>BIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Gesch_ftsf_hrer__c.field-meta.xml
<CustomField>
    <fullName>Gesch_ftsf_hrer__c</fullName>
    <label>Geschäftsführer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/HRB__c.field-meta.xml
<CustomField>
    <fullName>HRB__c</fullName>
    <label>HRB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Place</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Repayment_Beginning__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Beginning__c</fullName>
    <label>Repayment Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <label>Street</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Telefon__c.field-meta.xml
<CustomField>
    <fullName>Telefon__c</fullName>
    <label>Telefon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Unternehmensname__c.field-meta.xml
<CustomField>
    <fullName>Unternehmensname__c</fullName>
    <label>Unternehmensname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestImmobilie.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestImmobilie {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Contact contact1 = new Contact( LastName='test');
        insert contact1;

        Account acc1 = TestDataFactory.createAccount(true, 'Test1', 'Type1');

        Property__c immobilie = new Property__c();
        immobilie.Name = 'Immobilie';
        immobilie.Place__c = 'test';
        immobilie.Street__c = 'test2';
        immobilie.Zip_Code__c = '12312';
        immobilie.Account__c = acc1.id;
        immobilie.Unternehmensname__c = 'asd';
        immobilie.Gesch_ftsf_hrer__c = contact1.id;
        immobilie.BIC__c = '123';
        immobilie.Amtsgericht__c = 'test';
        immobilie.HRB__c = '123';
        immobilie.Telefon__c = '05123123';
        immobilie.E_Mail__c = 'test@test.de';
        immobilie.Website__c = 'www.test.de';
        insert immobilie;

        immobilie.Afa_Outdoor__c = 3.3;
        immobilie.Repayment_Beginning__c = Date.today();
		update immobilie;

    }
}