force-app/main/default/objects/Account/fields/WHS_Maklerauftrag__c.field-meta.xml
<CustomField>
    <fullName>WHS_Maklerauftrag__c</fullName>
    <description>Abbildung des Prozesses zur Auslösung eines Maklerauftrags; letzter Status heisst unterschrieben vom Vorstand und versendet an den Makler (d.h. Vereinbarung ist ab diesem Tag gültig)</description>
    <inlineHelpText>Abbildung des Prozesses zur Auslösung eines Maklerauftrags; letzter Status heisst unterschrieben vom Vorstand und versendet an den Makler (d.h. Vereinbarung ist ab diesem Tag gültig)</inlineHelpText>
    <label>WH Maklerauftrag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Keine Vereinbarung</fullName>
                <default>true</default>
                <label>Keine Vereinbarung</label>
            </value>
            <value>
                <fullName>Vom Maklerbetreuer angefordert</fullName>
            </value>
            <value>
                <fullName>Erstellt und an Makler versendet</fullName>
            </value>
            <value>
                <fullName>Unterschrieben eingegangen</fullName>
            </value>
            <value>
                <fullName>Maklerauftrag beidseitig unterzeichnet</fullName>
            </value>
            <value>
                <fullName>Makler mit altem Vertrag</fullName>
            </value>
            <value>
                <fullName>Makler ohne eigenen Vertrag</fullName>
            </value>
            <value>
                <fullName>Vom Makler gekündigt</fullName>
            </value>
            <value>
                <fullName>Vom WH gekündigt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WHS_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>WHS_Maklerprovision__c</fullName>
    <description>Angabe der Provision vom Makler bei WH Service für alle Objekte global</description>
    <inlineHelpText>Angabe der Provision vom Makler bei WH Service für alle Objekte global</inlineHelpText>
    <label>CS Maklerprovision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>keine</fullName>
                <default>true</default>
                <label>keine</label>
            </value>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>4.5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>5.5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>0.75</fullName>
            </value>
            <value>
                <fullName>1.25</fullName>
            </value>
            <value>
                <fullName>1.75</fullName>
            </value>
            <value>
                <fullName>2.25</fullName>
            </value>
            <value>
                <fullName>2.75</fullName>
            </value>
            <value>
                <fullName>3.25</fullName>
            </value>
            <value>
                <fullName>3.75</fullName>
            </value>
            <value>
                <fullName>4.25</fullName>
            </value>
            <value>
                <fullName>4.75</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestAccountHierarchy.cls
@RestResource(urlMapping='/AccountHierarchy')
global with sharing class RestAccountHierarchy  {

    @HttpPost
    global static List<Account> show(Id accId) {

    // Dynamic query to dynamically set the amount of levels
    // level 1 = ChildAccounts
    // level 2 = ChildAccounts + the ChildAccounts of each of those, etc
    String queryString = 'SELECT Id, Name, WHS_Maklerprovision__c, WHS_Maklerauftrag__c, (SELECT Id, Name, WHS_Maklerprovision__c, WHS_Maklerauftrag__c FROM ChildAccounts) FROM Account WHERE Id =: accId';
        List<Account> accs = Database.query(queryString);

        return accs;

    }

}