force-app/main/default/objects/Immoframe_Konfiguration__c/Immoframe_Konfiguration__c.object-meta.xml
<CustomObject>
    <label>Immoframe Konfiguration</label>
    <nameField>
        <displayFormat>IK-{000000}</displayFormat>
        <label>Immoframe Konfiguration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Immoframe Konfigurationen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;#3ad235&quot;</defaultValue>
    <label>Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Exposee__c.field-meta.xml
<CustomField>
    <fullName>Exposee__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Exposé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Factsheets__c.field-meta.xml
<CustomField>
    <fullName>Factsheets__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Factsheet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Grundriss__c.field-meta.xml
<CustomField>
    <fullName>Grundriss__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Grundriss</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Lightcolor__c.field-meta.xml
<CustomField>
    <fullName>Lightcolor__c</fullName>
    <label>Light Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Makler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Immoframe Konfigurationen</relationshipLabel>
    <relationshipName>Immoframe_Konfigurationen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Mikroapartments__c.field-meta.xml
<CustomField>
    <fullName>Mikroapartments__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Mikroapartments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Pflegeapartments__c.field-meta.xml
<CustomField>
    <fullName>Pflegeapartments__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Pflegeapartments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/ServiceWohnungen__c.field-meta.xml
<CustomField>
    <fullName>ServiceWohnungen__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Service-Wohnungen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Theme</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Transparent__c.field-meta.xml
<CustomField>
    <fullName>Transparent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Transparenter Hintergrund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Ihre URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Immoframe_Konfiguration__c/fields/Wohnimmobilien__c.field-meta.xml
<CustomField>
    <fullName>Wohnimmobilien__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Wohnimmobilien</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ImmoframeController.cls
public without sharing class ImmoframeController {

    @AuraEnabled(cacheable=true)
    public static Immoframe_Konfiguration__c getImmoframeKonfiguration() {
        Id userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        User usr = [SELECT ContactId, AccountId FROM User WHERE Id = :userId];
        Id conId = usr.ContactId;
        List<Immoframe_Konfiguration__c> imks = [SELECT Id, Name, URL__c, ServiceWohnungen__c, Pflegeapartments__c, Mikroapartments__c, Wohnimmobilien__c, Theme__c, Color__c, Lightcolor__c, Exposee__c, Grundriss__c, Factsheets__c, Transparent__c FROM Immoframe_Konfiguration__c WHERE Makler__c = :conId];
        Immoframe_Konfiguration__c imk;
        if (imks.size() > 0) {
            imk = imks[0];
        }

        return imk;
    }

    @AuraEnabled
    public static void insertImmoframeKonfiguration() {
        Id userId = UserInfo.getUserId();
        Id profileId = UserInfo.getProfileId();
        User usr = [SELECT ContactId, AccountId FROM User WHERE Id = :userId];
        Id conId = usr.ContactId;
        Immoframe_Konfiguration__c imk = new Immoframe_Konfiguration__c(Makler__c=conId);
        insert imk;
    }
}