force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/Zahlung__c.object-meta.xml
<CustomObject>
    <label>Zahlung</label>
    <nameField>
        <displayFormat>Z-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zahlung__c/fields/MaBVRechnung__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnung__c</fullName>
    <label>MaBV Rechnung</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MaBVRechnung__c.MaBVRechnungMaster__r.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MaBVRechnung__c</referenceTo>
    <relationshipLabel>Zahlungen</relationshipLabel>
    <relationshipName>ZahlungenMaBVRechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity which this Payment belongs to via MaBV records.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Zahlungen</relationshipLabel>
    <relationshipName>MabvPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZahlungTriggerHandler.cls
public without sharing class ZahlungTriggerHandler implements ITrigger {
    
    
    Map<Id, MaBVRechnung__c> rechnungenByIds = new Map<Id, MaBVRechnung__c>();
    Set<Id> rateIds = new Set<Id>();
    Set<Id> opportunityIds = new Set<Id>();
    
    public ZahlungTriggerHandler() {

    }

    public void bulkBefore() {
        
    }

    public void bulkAfter() {
        List<Zahlung__c> zahlungen;
        if(Trigger.isDelete) {
            zahlungen = (List<Zahlung__c>) Trigger.old;
        } else {
            zahlungen = (List<Zahlung__c>) Trigger.new;
        }
        Set<Id> rechnungIds = new Set<Id>();
        for(Zahlung__c zahlung : zahlungen) {
            rechnungIds.add(zahlung.MaBVRechnung__c);
        }

        rechnungenByIds = new Map<Id, MaBVRechnung__c>([SELECT Id, MaBVRechnungMaster__r.MaBVRate__c, MaBVRechnungMaster__r.Opportunity__c FROM MaBVRechnung__c WHERE Id IN :rechnungIds]);
    }

    public void beforeInsert(SObject so) {
        
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        
    }

    public void beforeDelete(SObject so) {

    }

    public void afterInsert(SObject so) {
        Zahlung__c zahlung = (Zahlung__c) so;
        MaBVRechnung__c rechnung = rechnungenByIds.get(zahlung.MaBVRechnung__c);
        rateIds.add(rechnung.MaBVRechnungMaster__r.MaBVRate__c);
        opportunityIds.add(rechnung.MaBVRechnungMaster__r.Opportunity__c);
    }

    public void afterUpdate(SObject oldSo, SObject so) {
        Zahlung__c zahlung = (Zahlung__c) so;
        MaBVRechnung__c rechnung = rechnungenByIds.get(zahlung.MaBVRechnung__c);
        rateIds.add(rechnung.MaBVRechnungMaster__r.MaBVRate__c);
        opportunityIds.add(rechnung.MaBVRechnungMaster__r.Opportunity__c);
    }

    public void afterDelete(SObject so) {
        Zahlung__c zahlung = (Zahlung__c) so;
        MaBVRechnung__c rechnung = rechnungenByIds.get(zahlung.MaBVRechnung__c);
        rateIds.add(rechnung.MaBVRechnungMaster__r.MaBVRate__c);
        opportunityIds.add(rechnung.MaBVRechnungMaster__r.Opportunity__c);
    }

    public void andFinally() {
        if(!rateIds.isEmpty() && Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
            System.enqueueJob(new AggregateRatePaymentDataQueueable(rateIds, opportunityIds));
        }
    }
}