force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRate__c/fields/GezahlteRechnungen__c.field-meta.xml
<CustomField>
    <fullName>GezahlteRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gezahlte Rechnungen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/OffeneRechnungen__c.field-meta.xml
<CustomField>
    <fullName>OffeneRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offene Rechnungen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/SummeGezahlterRechnungen__c.field-meta.xml
<CustomField>
    <fullName>SummeGezahlterRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Summe gezahlter Rechnungen</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/SummeOffenerRechnungen__c.field-meta.xml
<CustomField>
    <fullName>SummeOffenerRechnungen__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Summe offener Rechnungen</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>Zahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>Zahlung__c.MaBVRechnung__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/IstBezahlt__c.field-meta.xml
<CustomField>
    <fullName>IstBezahlt__c</fullName>
    <formula>OffenerBetragNeu__c &lt;= 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ist Bezahlt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/OffenerBetragNeu__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragNeu__c</fullName>
    <formula>IF((RateGesamtInEuro__c - Bezahlt__c) &lt; 0, 0, RateGesamtInEuro__c - Bezahlt__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag (neu)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/RateGesamtInEuro__c.field-meta.xml
<CustomField>
    <fullName>RateGesamtInEuro__c</fullName>
    <formula>RateInEuro__c + SicherheitPlusInEuro__c - SicherheitseinbehaltInEuro__c + PreisanpassungInEuro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate gesamt in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Storniert__c.field-meta.xml
<CustomField>
    <fullName>Storniert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Storniert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AbgerechneterBetragMaBV__c.field-meta.xml
<CustomField>
    <fullName>AbgerechneterBetragMaBV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Abgerechneter Betrag (MaBV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bezahlt__c.field-meta.xml
<CustomField>
    <fullName>Bezahlt__c</fullName>
    <label>Bezahlt</label>
    <summarizedField>VkcZahlung__c.Betrag__c</summarizedField>
    <summaryForeignKey>VkcZahlung__c.Verkaufschance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OffenerBetragMaBV__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragMaBV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offener Betrag (MaBV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AggregateRatePaymentDataQueueable.cls
public with sharing class AggregateRatePaymentDataQueueable implements Queueable {

    Set<Id> rateIds = new Set<Id>();
    Set<Id> opportunityIds = new Set<Id>();

    public AggregateRatePaymentDataQueueable(Set<Id> rateIds, Set<Id> opportunityIds) {
        this.rateIds = rateIds;
        this.opportunityIds = opportunityIds;
    }

    public void execute(QueueableContext ctx) {
        Map<Id,MaBVRate__c> mabvRateByIds = new Map<Id,MaBVRate__c>();
        Map<Id,Opportunity> opportunitiesByIds = new Map<Id,Opportunity>();

        for(AggregateResult agRes : [SELECT COUNT(Id) num, MaBVRechnungMaster__r.MaBVRate__c rate, IstBezahlt__c istBezahlt FROM MaBVRechnung__c WHERE MaBVRechnungMaster__r.MaBVRate__c IN :this.rateIds AND Storniert__c = false GROUP BY MaBVRechnungMaster__r.MaBVRate__c, IstBezahlt__c]) {
            Id rateId = (Id) agRes.get('rate');
            Integer count = (Integer) agRes.get('num');
            Boolean istBezahlt = (Boolean) agRes.get('istBezahlt');

            String field = istBezahlt ? 'GezahlteRechnungen__c' : 'OffeneRechnungen__c';

            MaBVRate__c rate = mabvRateByIds.containsKey(rateId) ? mabvRateByIds.get(rateId) : new MaBVRate__c(Id = rateId);
            rate.put(field, count);
            mabvRateByIds.put(rateId, rate);             
        }

        for(AggregateResult agRes : [SELECT SUM(RateGesamtInEuro__c) total, SUM(Bezahlt__c) bezahlt, SUM(OffenerBetragNeu__c) offen, MaBVRechnungMaster__r.MaBVRate__c rate, IstBezahlt__c istBezahlt FROM MaBVRechnung__c WHERE MaBVRechnungMaster__r.MaBVRate__c IN :this.rateIds AND Storniert__c = false GROUP BY MaBVRechnungMaster__r.MaBVRate__c, IstBezahlt__c]) {
            Id rateId = (Id) agRes.get('rate');
            Double total = (Double) agRes.get('total');
            Double bezahlt = (Double) agRes.get('bezahlt');
            Double offen = (Double) agRes.get('offen');
            Boolean istBezahlt = (Boolean) agRes.get('istBezahlt');


            MaBVRate__c rate = mabvRateByIds.containsKey(rateId) ? mabvRateByIds.get(rateId) : new MaBVRate__c(Id = rateId);
            rate.SummeGezahlterRechnungen__c = rate.SummeGezahlterRechnungen__c != null ? rate.SummeGezahlterRechnungen__c += bezahlt : bezahlt;
            rate.SummeOffenerRechnungen__c = rate.SummeOffenerRechnungen__c != null ? rate.SummeOffenerRechnungen__c += offen : offen;
            
            mabvRateByIds.put(rateId, rate);        
        }

        for(AggregateResult agRes : [SELECT SUM(RateGesamtInEuro__c) total, SUM(Bezahlt__c) bezahlt, SUM(OffenerBetragNeu__c) offen, MaBVRechnungMaster__r.Opportunity__c opp, IstBezahlt__c istBezahlt FROM MaBVRechnung__c WHERE MaBVRechnungMaster__r.Opportunity__c IN :this.opportunityIds AND Storniert__c = false GROUP BY MaBVRechnungMaster__r.Opportunity__c, IstBezahlt__c]) {
            Id opportunityId = (Id) agRes.get('opp');
            Double total = (Double) agRes.get('total');
            Double bezahlt = (Double) agRes.get('bezahlt');
            Double offen = (Double) agRes.get('offen');
            Boolean istBezahlt = (Boolean) agRes.get('istBezahlt');
            
            Opportunity opportunity = opportunitiesByIds.containsKey(opportunityId) ? opportunitiesByIds.get(opportunityId) : new Opportunity(Id = opportunityId);
            opportunity.AbgerechneterBetragMaBV__c = opportunity.AbgerechneterBetragMaBV__c != null ? opportunity.AbgerechneterBetragMaBV__c += total : total;
            opportunity.OffenerBetragMaBV__c = opportunity.OffenerBetragMaBV__c != null ? opportunity.OffenerBetragMaBV__c += offen : offen;
            opportunitiesByIds.put(opportunityId, opportunity);
        }

        update opportunitiesByIds.values();

        update mabvRateByIds.values();
    }
}