force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRate__c/fields/Faelligkeitsdatum__c.field-meta.xml
<CustomField>
    <fullName>Faelligkeitsdatum__c</fullName>
    <label>Fälligkeitsdatum</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>MaBV Raten</relationshipLabel>
    <relationshipName>MaBV_Raten</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRate__c/fields/RateNummer__c.field-meta.xml
<CustomField>
    <fullName>RateNummer__c</fullName>
    <label>Rate Nummer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Faelligkeitsdatum__c.field-meta.xml
<CustomField>
    <fullName>Faelligkeitsdatum__c</fullName>
    <label>Fälligkeitsdatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Abnahmeprotokoll__c.field-meta.xml
<CustomField>
    <fullName>Abnahmeprotokoll__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Abnahmeprotokoll</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Kaufpreis_f_llig__c.field-meta.xml
<CustomField>
    <fullName>Kaufpreis_f_llig__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kaufpreis fällig</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KeineMaBVRechnungGenerieren__c.field-meta.xml
<CustomField>
    <fullName>KeineMaBVRechnungGenerieren__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Keine MaBV Rechnung generieren</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MaBVRechnungMasterUtil.cls
/**
 * Created by frederikwitte on 25.05.20.
 */

public with sharing class
MaBVRechnungMasterUtil {

    public static void createMaBVRechnung(List<Opportunity> opps) {
        if(opps.size() == 0) {
            return;
        }
        Set<Id> propertyIdsSet = new Set<Id>();
        for(Opportunity opp:opps) {
            propertyIdsSet.add(opp.Immobilie__c);
        }
        List<Id> propertyIds = new List<Id>(propertyIdsSet);
        List<MaBVRate__c> maBVRaten = [SELECT Faelligkeitsdatum__c, RateNummer__c, Immobilie__c FROM MaBVRate__c WHERE Immobilie__c IN :propertyIds AND Faelligkeitsdatum__c != NULL Order By RateNummer__c ASC];
        createMaBVRechnung(opps, maBVRaten);
    }

    public static void createMaBVRechnung(List<MaBVRate__c> maBVRaten) {
        if(maBVRaten.size() == 0) {
            return;
        }
        Set<Id> propertyIdsSet = new Set<Id>();
        for(MaBVRate__c maBVRate:maBVRaten) {
            propertyIdsSet.add(maBVRate.Immobilie__c);
        }
        List<Id> propertyIds = new List<Id>(propertyIdsSet);
        List<Opportunity> opps = [SELECT Id, Immobilie__c, Abnahmeprotokoll__c, OwnerId FROM Opportunity WHERE Kaufpreis_f_llig__c = TRUE AND Immobilie__c IN :propertyIds AND KeineMaBVRechnungGenerieren__c = FALSE];
        createMaBVRechnung(opps, maBVRaten);
    }

    public static void createMaBVRechnung(List<Opportunity> opps, List<MaBVRate__c> maBVRaten) {
        List<MaBVRechnungMaster__c> maBVRechnungenMaster = new List<MaBVRechnungMaster__c>();
        Map<Id, Map<Id, MaBVRechnungMaster__c>> oppToMaBVRateToMaBVRechnungMasterMap = getOppToMaBVRateToMaBVRechnungMasterMap(maBVRaten);

        for(Opportunity opp:opps) {
            for(MaBVRate__c maBVRate:maBVRaten) {
                if(maBVRate.Immobilie__c != opp.Immobilie__c) {
                    continue;
                }
                if(maBVRate.RateNummer__c == '7' && opp.Abnahmeprotokoll__c == false) {
                    continue;
                }
                MaBVRechnungMaster__c maBVRechnungMaster;
                if(oppToMaBVRateToMaBVRechnungMasterMap.get(opp.Id) != null && oppToMaBVRateToMaBVRechnungMasterMap.get(opp.Id).get(maBVRate.Id) != null) {
                    maBVRechnungMaster = oppToMaBVRateToMaBVRechnungMasterMap.get(opp.Id).get(maBVRate.Id);
                    maBVRechnungMaster.OwnerId = opp.OwnerId;
                    if(maBVRechnungMaster.Faelligkeitsdatum__c > Date.Today()) {
                        maBVRechnungMaster.Faelligkeitsdatum__c = maBVRate.Faelligkeitsdatum__c;
                        maBVRechnungenMaster.add(maBVRechnungMaster);
                    }
                } else {
                    maBVRechnungMaster = new MaBVRechnungMaster__c();
                    maBVRechnungMaster.OwnerId = opp.OwnerId;
                    maBVRechnungMaster.Opportunity__c = opp.Id;
                    maBVRechnungMaster.MaBVRate__c = maBVRate.Id;
                    maBVRechnungMaster.Faelligkeitsdatum__c = maBVRate.Faelligkeitsdatum__c;
                    maBVRechnungenMaster.add(maBVRechnungMaster);
                }
            }
        }

        if(maBVRechnungenMaster.size() > 0) {
            database.upsert(maBVRechnungenMaster);
        }
    }

    public static Map<Id, Map<Id, MaBVRechnungMaster__c>> getOppToMaBVRateToMaBVRechnungMasterMap(List<MaBVRate__c> maBVRaten) {
        List<Id> maBVRatenIds = new List<Id>();
        for(MaBVRate__c maBVRate:maBVRaten) {
            maBVRatenIds.add(maBVRate.Id);
        }
        List<MaBVRechnungMaster__c> maBVRechnungenMaster = [SELECT Id, Opportunity__c, MaBVRate__c, Faelligkeitsdatum__c FROM MaBVRechnungMaster__c WHERE MaBVRate__c IN :maBVRatenIds];
        Map<Id, Map<Id, MaBVRechnungMaster__c>> oppToMaBVRateToMaBVRechnungMasterMap = new Map<Id, Map<Id, MaBVRechnungMaster__c>>();

        for(MaBVRechnungMaster__c maBVRechnungMaster:maBVRechnungenMaster) {
            Id oppId = maBVRechnungMaster.Opportunity__c;
            Id maBVRateId = maBVRechnungMaster.MaBVRate__c;
            Map<Id, MaBVRechnungMaster__c> maBVRateToMaBVRechnungMasterMap = oppToMaBVRateToMaBVRechnungMasterMap.get(oppId);
            if(maBVRateToMaBVRechnungMasterMap == null) {
                maBVRateToMaBVRechnungMasterMap = new Map<Id, MaBVRechnungMaster__c>();
            }
            maBVRateToMaBVRechnungMasterMap.put(maBVRechnungMaster.MaBVRate__c, maBVRechnungMaster);
            oppToMaBVRateToMaBVRechnungMasterMap.put(oppId, maBVRateToMaBVRechnungMasterMap);
        }

        return oppToMaBVRateToMaBVRechnungMasterMap;

    }

}