force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/Leistung__c.field-meta.xml
<CustomField>
    <fullName>Leistung__c</fullName>
    <label>Leistung</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/OffenerBetragNeu__c.field-meta.xml
<CustomField>
    <fullName>OffenerBetragNeu__c</fullName>
    <formula>IF((RateGesamtInEuro__c - Bezahlt__c) &lt; 0, 0, RateGesamtInEuro__c - Bezahlt__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offener Betrag (neu)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/RateGesamtInEuro__c.field-meta.xml
<CustomField>
    <fullName>RateGesamtInEuro__c</fullName>
    <formula>RateInEuro__c + SicherheitPlusInEuro__c - SicherheitseinbehaltInEuro__c + PreisanpassungInEuro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate gesamt in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/RateNummer__c.field-meta.xml
<CustomField>
    <fullName>RateNummer__c</fullName>
    <label>Rate Nummer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Storniert__c.field-meta.xml
<CustomField>
    <fullName>Storniert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Storniert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <summarizedField>Zahlung__c.Zahldatum__c</summarizedField>
    <summaryForeignKey>Zahlung__c.MaBVRechnung__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MaBVRechnung__c/fields/ZahlungszielInTagen__c.field-meta.xml
<CustomField>
    <fullName>ZahlungszielInTagen__c</fullName>
    <label>Zahlungsziel in Tagen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Rechnungsdatum__c.field-meta.xml
<CustomField>
    <fullName>Rechnungsdatum__c</fullName>
    <label>Rechnungsdatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/beurkundeter_Kaufpreis__c.field-meta.xml
<CustomField>
    <fullName>beurkundeter_Kaufpreis__c</fullName>
    <label>beurkundeter Kaufpreis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/Zahlung__c.object-meta.xml
<CustomObject>
    <label>Zahlung</label>
    <nameField>
        <displayFormat>Z-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zahlung__c/fields/Betrag__c.field-meta.xml
<CustomField>
    <fullName>Betrag__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/MaBVRechnung__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnung__c</fullName>
    <label>MaBV Rechnung</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MaBVRechnung__c.MaBVRechnungMaster__r.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MaBVRechnung__c</referenceTo>
    <relationshipLabel>Zahlungen</relationshipLabel>
    <relationshipName>ZahlungenMaBVRechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity which this Payment belongs to via MaBV records.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Zahlungen</relationshipLabel>
    <relationshipName>MabvPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Zahldatum__c.field-meta.xml
<CustomField>
    <fullName>Zahldatum__c</fullName>
    <label>Zahldatum</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OpportunityController.cls
public without sharing class OpportunityController {
    @AuraEnabled(cacheable=true)
    public static MaBVOverview getMabvInvoices(Id oppId) {
        MaBVOverview mo = new MaBVOverview();
        mo.mabvInvoices = [SELECT Id, OffenerBetragNeu__c, (SELECT Id, Betrag__c, Zahldatum__c FROM ZahlungenMaBVRechnungen__r), MaBVRechnungMaster__r.Opportunity__r.Beurkundeter_Kaufpreis__c, MaBVRechnungMaster__r.MaBVRate__r.Name, RateGesamtInEuro__c, Rechnungsdatum__c, Name, ZahlungszielInTagen__c, Leistung__c FROM MaBVRechnung__c WHERE MaBVRechnungMaster__r.Opportunity__c = :oppId AND Storniert__c = false ORDER BY RateNummer__c ASC];
        mo.opp = [SELECT Id, beurkundeter_Kaufpreis__c FROM Opportunity WHERE Id = :oppId];

        return mo;
    }

    public class MaBVOverview {
        @AuraEnabled
        public Opportunity opp{get;set;}

        @AuraEnabled
        public List<MaBVRechnung__c> mabvInvoices{get;set;}

        public MaBVOverview() {
            this.mabvInvoices = new List<MaBVRechnung__c>();
        }
    }
}