force-app/main/default/objects/MaBVRate__c/MaBVRate__c.object-meta.xml
<CustomObject>
    <label>MaBV Rate</label>
    <nameField>
        <label>MaBV Rate-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Raten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/MaBVRechnung__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung</label>
    <nameField>
        <label>MaBV Rechnung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnung__c/fields/MaBVRechnungMaster__c.field-meta.xml
<CustomField>
    <fullName>MaBVRechnungMaster__c</fullName>
    <label>MaBV Rechnung Master</label>
    <referenceTo>MaBVRechnungMaster__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/MaBVRechnungMaster__c.object-meta.xml
<CustomObject>
    <label>MaBV Rechnung Master</label>
    <nameField>
        <displayFormat>MaBV-Master-{YYYY}-{00000}</displayFormat>
        <label>MaBV Rechnung Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MaBV Rechnungen Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/MaBVRate__c.field-meta.xml
<CustomField>
    <fullName>MaBVRate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MaBV Rate</label>
    <referenceTo>MaBVRate__c</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaBVRechnungMaster__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>MaBV Rechnungen Master</relationshipLabel>
    <relationshipName>MaBV_Rechnungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MaBVRechnungTriggerHandler.cls
public with sharing class MaBVRechnungTriggerHandler implements ITrigger {

    Map<Id,Opportunity> mapOpportunitiesByIds = new Map<Id,Opportunity>();

    Map<Id, MaBVRechnungMaster__c> masterByIds = new Map<Id, MaBVRechnungMaster__c>();
    Set<Id> rateIds = new Set<Id>();
    Set<Id> opportunityIds = new Set<Id>();
    
    public MaBVRechnungTriggerHandler() {

    }

    public void bulkBefore() {
        
    }

    public void bulkAfter() {
        List<MaBVRechnung__c> rechnungen;
        if(Trigger.isDelete) {
            rechnungen = (List<MaBVRechnung__c>) Trigger.old;
        } else {
            rechnungen = (List<MaBVRechnung__c>) Trigger.new;
        }
        Set<Id> masterIds = new Set<Id>();
        for(MaBVRechnung__c rechnung : rechnungen) {
            masterIds.add(rechnung.MaBVRechnungMaster__c);
        }

        masterByIds = new Map<Id, MaBVRechnungMaster__c>([SELECT Id, MaBVRate__c, Opportunity__c FROM MaBVRechnungMaster__c WHERE Id IN :masterIds]);
    }

    public void beforeInsert(SObject so) {
        
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        
    }

    public void beforeDelete(SObject so) {

    }

    public void afterInsert(SObject so) {
        MaBVRechnung__c rechnung = (MaBVRechnung__c) so;
        MaBVRechnungMaster__c master = masterByIds.get(rechnung.MaBVRechnungMaster__c);
        rateIds.add(master.MaBVRate__c);
        opportunityIds.add(master.Opportunity__c);
    }

    public void afterUpdate(SObject oldSo, SObject so) {
        MaBVRechnung__c rechnung = (MaBVRechnung__c) so;
        MaBVRechnungMaster__c master = masterByIds.get(rechnung.MaBVRechnungMaster__c);
        rateIds.add(master.MaBVRate__c);
        opportunityIds.add(master.Opportunity__c);
    }

    public void afterDelete(SObject so) {
        MaBVRechnung__c rechnung = (MaBVRechnung__c) so;
        MaBVRechnungMaster__c master = masterByIds.get(rechnung.MaBVRechnungMaster__c);
        rateIds.add(master.MaBVRate__c);
        opportunityIds.add(master.Opportunity__c);
    }

    public void andFinally() {
        if(!rateIds.isEmpty() && Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
            System.enqueueJob(new AggregateRatePaymentDataQueueable(rateIds, opportunityIds));
        }
    }
}