force-app/main/default/objects/FileDownloadLog__c/FileDownloadLog__c.object-meta.xml
<CustomObject>
    <label>File Download Log</label>
    <nameField>
        <displayFormat>FDL-{0000}</displayFormat>
        <label>File Download Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Download Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FileDownloadLog__c/fields/ImmobilienDMSDatei__c.field-meta.xml
<CustomField>
    <fullName>ImmobilienDMSDatei__c</fullName>
    <label>Immobilien DMS Datei</label>
    <referenceTo>ImmobilienDmsDatei__c</referenceTo>
    <relationshipLabel>File Download Logs</relationshipLabel>
    <relationshipName>File_Download_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/ImmobilienDmsDatei__c.object-meta.xml
<CustomObject>
    <label>Immobilien DMS Datei</label>
    <nameField>
        <label>Immobilien DMS Datei Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien DMS Dateien</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FileDownloadLogTriggerHandlerTest.cls
@isTest
public with sharing class FileDownloadLogTriggerHandlerTest {
    @istest
    private static void testInsertingRecordsWithNumberOfRecordsThatNotExceedsLimit(){
        ImmobilienDMSDatei__c dmsDatei =TestDataFactory.createImmobilienDMSDatei(true);
        Contact con=TestDataFactory.createContact(true);

        List<FileDownloadLog__c> logs =new List<FileDownloadLog__c>();
        string errorMessage=null;
        for(integer i=0;i<FileDownloadLogTriggerHandler.FILE_DOWNLOAD_LOG_RECORDS_LIMIT_TEST;i++){    
            FileDownloadLog__c fdl =TestDataFactory.createFileDownloadLog(false,con.id,dmsDatei.id);
            logs.add(fdl);
        }
        try{ 
            insert logs;           
        }catch(exception ex){
            errorMessage= ex.getMessage();
        }finally{
            System.assertEquals(null,errorMessage);
        }      
        
    }
    @istest
    private static void testInsertingRecordsWithNumberOfRecordsThatExceedsLimitByOne(){
        ImmobilienDMSDatei__c dmsDatei =TestDataFactory.createImmobilienDMSDatei(true);
        Contact con=TestDataFactory.createContact(true);
        
        string errorMessage=null;
        List<FileDownloadLog__c> logs =new List<FileDownloadLog__c>();
        for(integer i=0;i<FileDownloadLogTriggerHandler.FILE_DOWNLOAD_LOG_RECORDS_LIMIT_TEST;i++){           
            FileDownloadLog__c fdl =TestDataFactory.createFileDownloadLog(false,con.id,dmsDatei.id);
            logs.add(fdl);
        }
        insert logs;
        try{              
            FileDownloadLog__c fdl =TestDataFactory.createFileDownloadLog(true,con.id,dmsDatei.id);
        }catch(exception ex){
            errorMessage= ex.getMessage();
        }finally{
            System.assert(errorMessage.contains(FileDownloadLogTriggerHandler.LIMIT_ERROR_MESSAGE));
        }      

    }
}