force-app/main/default/objects/FileDownloadLog__c/FileDownloadLog__c.object-meta.xml
<CustomObject>
    <label>File Download Log</label>
    <nameField>
        <displayFormat>FDL-{0000}</displayFormat>
        <label>File Download Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Download Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FileDownloadLog__c/fields/ImmobilienDMSDatei__c.field-meta.xml
<CustomField>
    <fullName>ImmobilienDMSDatei__c</fullName>
    <label>Immobilien DMS Datei</label>
    <referenceTo>ImmobilienDmsDatei__c</referenceTo>
    <relationshipLabel>File Download Logs</relationshipLabel>
    <relationshipName>File_Download_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/ImmobilienDmsDatei__c.object-meta.xml
<CustomObject>
    <label>Immobilien DMS Datei</label>
    <nameField>
        <label>Immobilien DMS Datei Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien DMS Dateien</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FileDownloadLogControllerTest.cls
@IsTest
public class FileDownloadLogControllerTest {
    @isTest
    private static void wasFileDownloadLogCreated(){
        Contact con =TestDataFactory.createContact(true);
        ImmobilienDMSDatei__c dmsDatei = TestDataFactory.createImmobilienDMSDatei(true);

        List<FileDownloadLog__c> logslist =[SELECT id FROM FileDownloadLog__c];
        System.assertEquals(0, logslist.size());

        FileDownloadLogController.createFileDownloadLog(con.id, dmsDatei.id);

        logslist =[SELECT id FROM FileDownloadLog__c];
        System.assertEquals(1, logslist.size());
    }
}