force-app/main/default/objects/Berechnung__c/Berechnung__c.object-meta.xml
<CustomObject>
    <label>Berechnung</label>
    <nameField>
        <label>Berechnung Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Berechnungen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Berechnung__c/fields/LiquidityMonthlyFirstYear__c.field-meta.xml
<CustomField>
    <fullName>LiquidityMonthlyFirstYear__c</fullName>
    <label>Liquidität monatlich 1. Jahr</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Vertriebsportal.recordType-meta.xml
<RecordType>
    <fullName>Vertriebsportal</fullName>
    <active>true</active>
    <label>Vertriebsportal</label>
</RecordType>

force-app/main/default/classes/RestQuote.cls
@RestResource(urlMapping='/quote/*')
global without sharing class RestQuote {

    @HttpGet
    global static String getQuoteFromCalculation() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String calculationId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        List<Berechnung__c> calculations = [SELECT Id FROM Berechnung__c WHERE Id = :calculationId];
        Berechnung__c c;
        if(calculations.size() == 1) {
            c = calculations[0];

            PageReference pdf = Page.CalculationQuote;
            pdf.getParameters().put('id', c.Id);
            Blob body;
            try {
                body = pdf.getContentAsPDF();
            } catch (Exception e) {
                return null;
            }

            return RestQuote.attachQuoteFromId(c.Id);
        }
        return null;
    }
    
    @future(callout=true)
    global static void attachQuoteFromIdFuture(Id calculationId) {
        RestQuote.attachQuoteFromId(calculationId);
    }

    global static String attachQuoteFromId(Id calculationId) {
        PageReference pdf = Page.CalculationQuote;
        pdf.getParameters().put('id', calculationId);
        Blob body;
        try {
            if(Test.isRunningTest()) { 
                body = blob.valueOf('Unit.Test');
              } else {
                body = pdf.getContentAsPDF();
              }
        } catch (Exception e) {
            return null;
        }

        // Dateiname der CSV
        String fileName = 'Berechnung ' + date.today().day() + '.' + date.today().month() + '.' + date.today().year() + ' - ' + datetime.now().hour() + ':' + Datetime.now().minute() + '.pdf';

        User u = [SELECT IsActive,IsPortalEnabled,LastName FROM User WHERE Id = :UserInfo.getUserId()];
        ContentVersion file = new ContentVersion();
        file.VersionData = body;
        file.Title = fileName; 
        file.ContentLocation= 's';
        file.PathOnClient=fileName;
        Id angebotRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Vertriebsportal').getRecordTypeId();
        file.Typ__c = 'Angebot';
        file.RecordTypeId = angebotRecordTypeId;
        if(u.IsPortalEnabled) {
            Id networkId = [SELECT Id FROM Network LIMIT 1].Id;
            file.NetworkId = networkId;
        }
        insert file;
        
        List<ContentVersion> files = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :file.Id];

        if(files.size() > 0) {
            file = files[0];
            ContentDocumentLink cde = new ContentDocumentLink();
            cde.ContentDocumentId = file.ContentDocumentId;
            cde.LinkedEntityId = calculationId;
            insert cde;
        }

        FinanceCalculator fc = new FinanceCalculator();
        fc.initFinanceModules(calculationId);
        if(fc.cumulatedYearlyValues.get(fc.firstFullYear) != null) {
            fc.c.LiquidityMonthlyFirstYear__c = (Decimal)fc.cumulatedYearlyValues.get(fc.firstFullYear).get('monthlyOverageInEuro');
            update fc.c;
        }

        return EncodingUtil.base64Encode(body);
    }

    @InvocableMethod(label='Angebot als PDF an Berechnung anhängen')
    public static void attachQuoteFromIdFlowAction(List<Id> calculationIds) {
        for(Id calculationId:calculationIds) {
            RestQuote.attachQuoteFromIdFuture(calculationId);
        }
    }

}