force-app/main/default/objects/Opportunity/fields/Abrechnung_ber__c.field-meta.xml
<CustomField>
    <fullName>Abrechnung_ber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abrechnung über</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Abrechnung über)</relationshipLabel>
    <relationshipName>OpportunitiesNK3O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AbrechnungUeberNurFuerGrundprovision__c.field-meta.xml
<CustomField>
    <fullName>AbrechnungUeberNurFuerGrundprovision__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Wenn dieses Feld angehakt ist, wird nur die Grundprovision über das Feld &quot;Abrechnung über&quot; abgerechnet</inlineHelpText>
    <label>Abrechnung über nur für Grundprovision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AdditionalBrokerCommission__c.field-meta.xml
<CustomField>
    <fullName>AdditionalBrokerCommission__c</fullName>
    <formula>Appartement__r.AdditionalBrokerCommission__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Additional Broker Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilienberater__c.field-meta.xml
<CustomField>
    <fullName>Immobilienberater__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Hier wird der Makler eingetragen, der die Beratungsleistung am Kunden durchgeführt hat.</inlineHelpText>
    <label>Immobilienberater</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Immobilienberater)</relationshipLabel>
    <relationshipName>Immobilienberater</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maklerbetreuer_WirtschaftsHaus__c.field-meta.xml
<CustomField>
    <fullName>Maklerbetreuer_WirtschaftsHaus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maklerbetreuer Carestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Ist_Maklerbetreuer_WH__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Maklerbetreuer WirtschaftsHaus)</relationshipLabel>
    <relationshipName>Maklerbetreuer_Wirtschaftshaus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketingzuschussNichtAusweisen__c.field-meta.xml
<CustomField>
    <fullName>MarketingzuschussNichtAusweisen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketingzuschuss nicht ausweisen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notartermin__c.field-meta.xml
<CustomField>
    <fullName>Notartermin__c</fullName>
    <inlineHelpText>Wichtig: Dies ist das Datum der ursprünglichen Vertragsunterzeichnung seitens des Kunden.</inlineHelpText>
    <label>Notartermin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Overhead_Empf_nger__c.field-meta.xml
<CustomField>
    <fullName>Overhead_Empf_nger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overhead Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Overhead Empfänger)</relationshipLabel>
    <relationshipName>Overhead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provision_Thoben__c.field-meta.xml
<CustomField>
    <fullName>Provision_Thoben__c</fullName>
    <label>Provision Finanzierung</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Provisionsbasis__c.field-meta.xml
<CustomField>
    <fullName>Provisionsbasis__c</fullName>
    <label>Provisionsbasis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TippgeberProvisionEmpfaenger__c.field-meta.xml
<CustomField>
    <fullName>TippgeberProvisionEmpfaenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tippgeber Provision Empfänger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Verkaufschancen (Tippgeber Provision Empfänger)</relationshipLabel>
    <relationshipName>TippgeberOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verkaufsprovision_intern__c.field-meta.xml
<CustomField>
    <fullName>Verkaufsprovision_intern__c</fullName>
    <formula>if( Immobilienberater__r.Ist_Maklerbetreuer_WH__c  , Immobilienberater__r.FirstName + &apos; &apos; + Immobilienberater__r.LastName, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Beratung durch intern</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Maklerprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Maklerprovision__c</fullName>
    <formula>Maklerprovision_nach_Nachtrag__c/100*Provisionsbasis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Maklerprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Overhead__c.field-meta.xml
<CustomField>
    <fullName>Wert_Overhead__c</fullName>
    <formula>IF(TEXT(Overhead__c) != &apos;Keine&apos; &amp;&amp; !IsBlank(TEXT(Overhead__c)), (VALUE(TEXT(Overhead__c))/100)*Provisionsbasis__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Overhead</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Provision_Thoben__c.field-meta.xml
<CustomField>
    <fullName>Wert_Provision_Thoben__c</fullName>
    <formula>if(TEXT(Provision_Thoben__c) != null, VALUE(TEXT(Provision_Thoben__c))/100, 0) * Provisionsbasis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Provision Thoben</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Tippprovision__c.field-meta.xml
<CustomField>
    <fullName>Wert_Tippprovision__c</fullName>
    <formula>IF(TEXT(Tippprovision__c) != &apos;Keine&apos; &amp;&amp; !IsBlank(TEXT(Tippprovision__c)), (VALUE(TEXT(Tippprovision__c))/100)*Provisionsbasis__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Tippprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wert_Verk_ufer_Beratungsprovision_m_R__c.field-meta.xml
<CustomField>
    <fullName>Wert_Verk_ufer_Beratungsprovision_m_R__c</fullName>
    <formula>if (!ISBLANK(Verkaufsprovision_nach_Nachtrag__c), Verkaufsprovision_nach_Nachtrag__c / 100 * Provisionsbasis__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Verkäufer-/Beratungsprovision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WertErfolgsabhaengigeProvision__c.field-meta.xml
<CustomField>
    <fullName>WertErfolgsabhaengigeProvision__c</fullName>
    <formula>ErfolgsabhaengigeProvision__c *  Provisionsbasis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert erfolgsabhängige Provision</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WertMarketingzuschuss__c.field-meta.xml
<CustomField>
    <fullName>WertMarketingzuschuss__c</fullName>
    <formula>Marketingzuschuss__c / 100 *  Provisionsbasis__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Wert Marketingzuschuss</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GenerateInternalCommissionBatch.cls
global without sharing class GenerateInternalCommissionBatch implements Database.Batchable<sObject> {
    // month || quarter || year
    String schedule;

    global GenerateInternalCommissionBatch(String schedule) {
        this.schedule = schedule;
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        Date todaysDate = Date.today();
        Integer thisMonth = todaysDate.month();
        Integer lastMonth = todaysDate.month() - 1;
        Integer thisYear = todaysDate.year();
        Integer lastYearOrThisYear = todaysDate.year();
        if(thisMonth == 1 && todaysDate.day() <= 10) {
            lastMonth = 12;
            lastYearOrThisYear -= 1;
        }
        Integer lastQuarter = getQuarterByMonth(lastMonth);
        String query = 'SELECT Id, Notartermin__c, Provision_Thoben__c, Makler__c, WertErfolgsabhaengigeProvision__c, Maklerbetreuer_WirtschaftsHaus__c, Immobilie__c, Appartement__c, Potenzieller_Kunde__c, Provisionsbasis__c, OwnerId, MarketingzuschussNichtAusweisen__c, Immobilienberater__c, Abrechnung_ber__c, AbrechnungUeberNurFuerGrundprovision__c, Wert_Verk_ufer_Beratungsprovision_m_R__c, Wert_Maklerprovision__c, WertMarketingzuschuss__c, AdditionalBrokerCommission__c, Verkaufsprovision_intern__c, TippgeberProvisionEmpfaenger__c, Wert_Tippprovision__c, Overhead_Empf_nger__c, Wert_Overhead__c, Wert_Provision_Thoben__c FROM Opportunity';
        if(this.schedule == 'month') {
            if(todaysDate.day() <= 10) {
                query += ' WHERE CALENDAR_MONTH(Notartermin__c) >= :lastMonth AND (CALENDAR_YEAR(Notartermin__c) = :thisYear OR CALENDAR_YEAR(Notartermin__c) = :lastYearOrThisYear)';
            } else if(todaysDate.day() > 10) {
                query += ' WHERE CALENDAR_MONTH(Notartermin__c) = :thisMonth AND (CALENDAR_YEAR(Notartermin__c) = :thisYear OR CALENDAR_YEAR(Notartermin__c) = :lastYearOrThisYear)';
            }
        } else if(this.schedule == 'quarter') {
            query += ' WHERE CALENDAR_QUARTER(Notartermin__c) = :lastQuarter AND (CALENDAR_YEAR(Notartermin__c) = :thisYear OR CALENDAR_YEAR(Notartermin__c) = :lastYearOrThisYear)';
        } else if(this.schedule == 'year') {
            query += ' WHERE CALENDAR_YEAR(Notartermin__c) = :lastYearOrThisYear';
        }

        query += ' AND StageName = \'Geschlossene und gewonnene\'';
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Opportunity> scope)
    {
        Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>();
        for(Opportunity opp:scope){
            oppsMap.put(opp.Id, opp);
        }
        Map<Id, Opportunity> oldOpps = new Map<Id, Opportunity>();
        ProvisionService ps = new ProvisionService(oppsMap, oldOpps, 'intern', this.schedule);
        ps.upsertProvisionen();
    }  
    global void finish(Database.BatchableContext BC)
    {
    }

    public Integer getQuarterByMonth(Integer month) {
        return math.round((month+1)/3.0);
    }

}