force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchAggregateImmoPayment.cls
public with sharing class BatchAggregateImmoPayment implements Database.Batchable<SObject>, Schedulable {
    

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM Property__c WHERE Id IN (SELECT Immobilie__c FROM Opportunity)]);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        Map<Id,SObject> scopeMap = new Map<Id, SObject>(scope);
        AggregateVkcZahlungPaymentDataQueueable.updateImmobilien(scopeMap.keySet());
    }

    public void finish(Database.BatchableContext bc) {

    }
    
    public void execute(System.SchedulableContext ctx) {
        Database.executeBatch(new BatchAggregateImmoPayment());
    }
}