force-app/main/default/objects/DigitaleVsa__c/DigitaleVsa__c.object-meta.xml
<CustomObject>
    <label>Digitale VSA</label>
    <nameField>
        <displayFormat>DVSA-{yyyy}-{0000}</displayFormat>
        <label>Digitale VSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digitale VSAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VSAImmobilie__c/VSAImmobilie__c.object-meta.xml
<CustomObject>
    <label>VSA Immobilie</label>
    <nameField>
        <label>Bezeichnung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA Immobilien</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VSAImmobilie__c/fields/DigitaleVsa__c.field-meta.xml
<CustomField>
    <fullName>DigitaleVsa__c</fullName>
    <label>Digitale VSA</label>
    <referenceTo>DigitaleVsa__c</referenceTo>
    <relationshipLabel>Immobilien</relationshipLabel>
    <relationshipName>VsaImmobilien</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/VsaVerbindlichkeit__c.object-meta.xml
<CustomObject>
    <label>VSA Verbindlichkeit</label>
    <nameField>
        <label>Bezeichnung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA Verbindlichtkeiten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/DigitaleVsa__c.field-meta.xml
<CustomField>
    <fullName>DigitaleVsa__c</fullName>
    <label>Digitale VSA</label>
    <referenceTo>DigitaleVsa__c</referenceTo>
    <relationshipLabel>Verbindlichkeiten</relationshipLabel>
    <relationshipName>VsaVerbindlichkeiten</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/VsaVermoegenswert__c.object-meta.xml
<CustomObject>
    <label>VSA Vermögenswert</label>
    <nameField>
        <label>Bezeichnung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA Vermögenswerte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VsaVermoegenswert__c/fields/DigitaleVsa__c.field-meta.xml
<CustomField>
    <fullName>DigitaleVsa__c</fullName>
    <label>Digitale VSA</label>
    <referenceTo>DigitaleVsa__c</referenceTo>
    <relationshipLabel>Vermögenswerte</relationshipLabel>
    <relationshipName>VsaVermoegenswerte</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DigitaleVSAControllerTest.cls
@isTest
public with sharing class DigitaleVSAControllerTest {

    @testSetup
    static void makeData() {

        // Create a test DigitaleVsa__c record
        DigitaleVsa__c digitaleVsa = TestDataFactory.createDigitaleVsa(true);

        // Create a VsaVerbindlichkeit__c record
        VsaVerbindlichkeit__c verbindlichkeit = new VsaVerbindlichkeit__c(
                DigitaleVsa__c = digitaleVsa.Id
        );
        insert verbindlichkeit;

        // create a VsaVermoegenswert__c record
        VsaVermoegenswert__c vermogenswert = new VsaVermoegenswert__c(
                DigitaleVsa__c = digitaleVsa.Id
        );
        insert vermogenswert;

        // create a VSAImmobilie__c record
        VSAImmobilie__c immobilie = new VSAImmobilie__c(
                DigitaleVsa__c = digitaleVsa.Id
        );
        insert immobilie;
    }

    //testGetVSA();
    @isTest
    private static void testGetVSA() {



        DigitaleVsa__c dv = [SELECT Id FROM DigitaleVsa__c LIMIT 1];
        PageReference pageRef = Page.Digitale_VSA_PDF;
        pageRef.getParameters().put('id', dv.Id);
        Test.setCurrentPage(pageRef);
        Test.startTest();
        ApexPages.StandardController std = new ApexPages.StandardController(dv);
        DigitaleVSAController dvc = new DigitaleVSAController(std);

        System.assertEquals(dvc.immobilie.size(), 1);
        System.assertEquals(dvc.verbindlichkeiten.size(), 1);
        System.assertEquals(dvc.vermoegenswert.size(), 1);
    }

}