force-app/main/default/objects/DigitaleVsa__c/DigitaleVsa__c.object-meta.xml
<CustomObject>
    <label>Digitale VSA</label>
    <nameField>
        <displayFormat>DVSA-{yyyy}-{0000}</displayFormat>
        <label>Digitale VSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digitale VSAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VSAImmobilie__c/VSAImmobilie__c.object-meta.xml
<CustomObject>
    <label>VSA Immobilie</label>
    <nameField>
        <label>Bezeichnung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA Immobilien</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VSAImmobilie__c/fields/Art__c.field-meta.xml
<CustomField>
    <fullName>Art__c</fullName>
    <label>Art</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Eigenheim</fullName>
            </value>
            <value>
                <fullName>Anlageimmobilie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VSAImmobilie__c/fields/DigitaleVsa__c.field-meta.xml
<CustomField>
    <fullName>DigitaleVsa__c</fullName>
    <label>Digitale VSA</label>
    <referenceTo>DigitaleVsa__c</referenceTo>
    <relationshipLabel>Immobilien</relationshipLabel>
    <relationshipName>VsaImmobilien</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VSAImmobilie__c/fields/MonatlicheNettokaltmiete__c.field-meta.xml
<CustomField>
    <fullName>MonatlicheNettokaltmiete__c</fullName>
    <label>Monatliche Nettokaltmiete</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VSAImmobilie__c/fields/PostleitzahlOrtDerImmobilie__c.field-meta.xml
<CustomField>
    <fullName>PostleitzahlOrtDerImmobilie__c</fullName>
    <label>Postleitzahl / Ort der Immobilie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSAImmobilie__c/fields/Restschuld__c.field-meta.xml
<CustomField>
    <fullName>Restschuld__c</fullName>
    <label>Restschuld</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VSAImmobilie__c/fields/Verkehrswert__c.field-meta.xml
<CustomField>
    <fullName>Verkehrswert__c</fullName>
    <label>Verkehrswert</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/VsaVerbindlichkeit__c.object-meta.xml
<CustomObject>
    <label>VSA Verbindlichkeit</label>
    <nameField>
        <label>Bezeichnung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA Verbindlichtkeiten</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/AktuelleRestschuld__c.field-meta.xml
<CustomField>
    <fullName>AktuelleRestschuld__c</fullName>
    <label>Aktuelle Restschuld</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/Art__c.field-meta.xml
<CustomField>
    <fullName>Art__c</fullName>
    <label>Art</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ratendarlehen</fullName>
            </value>
            <value>
                <fullName>Leasingdarlehen</fullName>
            </value>
            <value>
                <fullName>Sonstige Schulden</fullName>
            </value>
            <value>
                <fullName>Bürgschaften</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/DigitaleVsa__c.field-meta.xml
<CustomField>
    <fullName>DigitaleVsa__c</fullName>
    <label>Digitale VSA</label>
    <referenceTo>DigitaleVsa__c</referenceTo>
    <relationshipLabel>Verbindlichkeiten</relationshipLabel>
    <relationshipName>VsaVerbindlichkeiten</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/Kreditgeber__c.field-meta.xml
<CustomField>
    <fullName>Kreditgeber__c</fullName>
    <label>Kreditgeber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/MonatlicheRate__c.field-meta.xml
<CustomField>
    <fullName>MonatlicheRate__c</fullName>
    <label>Monatliche Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/TilgungBis__c.field-meta.xml
<CustomField>
    <fullName>TilgungBis__c</fullName>
    <label>Tilgung bis</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VsaVerbindlichkeit__c/fields/UrspruenglicherDarlehensbetrag__c.field-meta.xml
<CustomField>
    <fullName>UrspruenglicherDarlehensbetrag__c</fullName>
    <label>Ursprünglicher Darlehensbetrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/VsaVermoegenswert__c.object-meta.xml
<CustomObject>
    <label>VSA Vermögenswert</label>
    <nameField>
        <label>Bezeichnung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA Vermögenswerte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VsaVermoegenswert__c/fields/AktuellesGuthaben__c.field-meta.xml
<CustomField>
    <fullName>AktuellesGuthaben__c</fullName>
    <label>Aktuelles Guthaben</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/fields/Art__c.field-meta.xml
<CustomField>
    <fullName>Art__c</fullName>
    <label>Art</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sparvertrag</fullName>
            </value>
            <value>
                <fullName>Lebensversicherung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/fields/DigitaleVsa__c.field-meta.xml
<CustomField>
    <fullName>DigitaleVsa__c</fullName>
    <label>Digitale VSA</label>
    <referenceTo>DigitaleVsa__c</referenceTo>
    <relationshipLabel>Vermögenswerte</relationshipLabel>
    <relationshipName>VsaVermoegenswerte</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/fields/Gesellschaft__c.field-meta.xml
<CustomField>
    <fullName>Gesellschaft__c</fullName>
    <label>Gesellschaft</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/fields/MonatlicheZahlung__c.field-meta.xml
<CustomField>
    <fullName>MonatlicheZahlung__c</fullName>
    <label>Monatliche Zahlung</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/fields/Sparbeginn__c.field-meta.xml
<CustomField>
    <fullName>Sparbeginn__c</fullName>
    <label>Sparbeginn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VsaVermoegenswert__c/fields/Vertragssumme__c.field-meta.xml
<CustomField>
    <fullName>Vertragssumme__c</fullName>
    <label>Vertragssumme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DigitaleVSAController.cls
public with sharing class DigitaleVSAController {
    public DigitaleVSAController(ApexPages.StandardController controller) {

    }

    private Id digitaleVsaId = ApexPages.currentPage().getParameters().get('id');

    //all Verbindlichkeiten connected to DigitaleVsa

    //TODO list of fields
    public List < VsaVerbindlichkeit__c > verbindlichkeiten {
        get {
            if (verbindlichkeiten == null) {
                verbindlichkeiten = [select id, name, DigitaleVsa__c, Art__c, Kreditgeber__c, UrspruenglicherDarlehensbetrag__c, ZinsbindungBis__c, TilgungBis__c, MonatlicheRate__c, AktuelleRestschuld__c   from VsaVerbindlichkeit__c where DigitaleVsa__c = :digitaleVsaId];
            }
            return verbindlichkeiten;
        }
        set;
    }
    //all Vermögenswerte connected to DigitaleVsa
    public List < VsaVermoegenswert__c > vermoegenswert {
        get {
            if (vermoegenswert == null) {
                vermoegenswert = [ select id, name, DigitaleVsa__c, Art__c, Gesellschaft__c, Vertragssumme__c, Sparbeginn__c, MonatlicheZahlung__c, AktuellesGuthaben__c from VsaVermoegenswert__c where DigitaleVsa__c = :digitaleVsaId];
            }
            return vermoegenswert;
        }
        set;
    }

    //all Immobilien connected to DigitaleVsa
    public List < VSAImmobilie__c > immobilie {
        get {
            if (immobilie == null) {
                immobilie = [ select id, name, DigitaleVsa__c,  Art__c, Verkehrswert__c, Restschuld__c, Kreditgeber__c, MonatlicheRate__c, MonatlicheNettokaltmiete__c, PostleitzahlOrtDerImmobilie__c	from VSAImmobilie__c where DigitaleVsa__c = :digitaleVsaId ];
            }
            return immobilie;
        }
        set;
    }
}