force-app/main/default/objects/Nebenkostenzuschuss__c/Nebenkostenzuschuss__c.object-meta.xml
<CustomObject>
    <label>Nebenkostenzuschuss</label>
    <nameField>
        <label>Nebenkostenzuschuss-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nebenkostenzusch&#252;sse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/Empfaenger__c.field-meta.xml
<CustomField>
    <fullName>Empfaenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empf&#228;nger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Nebenkostenzusch&#252;sse</relationshipLabel>
    <relationshipName>Nebenkostenzuschuesse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/Kunde__c.field-meta.xml
<CustomField>
    <fullName>Kunde__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kunde</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Nebenkostenzusch&#252;sse (Kunde)</relationshipLabel>
    <relationshipName>Nebenkostenzuschuesse1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/Objekt__c.field-meta.xml
<CustomField>
    <fullName>Objekt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objekt</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Nebenkostenzusch&#252;sse</relationshipLabel>
    <relationshipName>Nebenkostenzuschuesse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Nebenkostenzusch&#252;sse</relationshipLabel>
    <relationshipName>Nebenkostenzuschuesse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/Teilobjekt__c.field-meta.xml
<CustomField>
    <fullName>Teilobjekt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teilobjekt</label>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Nebenkostenzusch&#252;sse</relationshipLabel>
    <relationshipName>Nebenkostenzuschuesse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Appartement__c.field-meta.xml
<CustomField>
    <fullName>Appartement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Appartment__c.Property__c</field>
            <operation>equals</operation>
            <valueField>$Source.Immobilie__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Appartment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Makler__c.field-meta.xml
<CustomField>
    <fullName>Makler__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Makler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e0X000000S342</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00eb0000000VEnA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Kontakt)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Potenzieller_Kunde__c.field-meta.xml
<CustomField>
    <fullName>Potenzieller_Kunde__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Käufer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.In_Genehmigungsprozess__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NebenkostenzuschussService.cls
public without sharing class NebenkostenzuschussService {

    public class NebenkostenzuschussException extends Exception {}

    public static Nebenkostenzuschuss__c createFromOpportunity(Id opportunityId) {
        List<Nebenkostenzuschuss__c> results = createFromOpportunities(new List<Id>{ opportunityId });
        return results.isEmpty() ? null : results[0];
    }

    public static List<Nebenkostenzuschuss__c> createFromOpportunities(List<Id> opportunityIds) {
        if (opportunityIds == null || opportunityIds.isEmpty()) {
            return new List<Nebenkostenzuschuss__c>();
        }

        Set<Id> uniqueIds = new Set<Id>(opportunityIds);
        uniqueIds.remove(null);

        if (uniqueIds.isEmpty()) {
            return new List<Nebenkostenzuschuss__c>();
        }

        Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>([
            SELECT Id, Immobilie__c, Appartement__c, Potenzieller_Kunde__c, Makler__c
            FROM Opportunity
            WHERE Id IN :uniqueIds
        ]);

        Set<Id> existingOppIds = new Set<Id>();
        for (Nebenkostenzuschuss__c existing : [
            SELECT Opportunity__c
            FROM Nebenkostenzuschuss__c
            WHERE Opportunity__c IN :uniqueIds
              AND Storniert__c = false
        ]) {
            existingOppIds.add(existing.Opportunity__c);
        }

        List<Nebenkostenzuschuss__c> toInsert = new List<Nebenkostenzuschuss__c>();

        for (Id oppId : uniqueIds) {
            Opportunity opp = opportunities.get(oppId);
            if (opp == null) {
                throw new NebenkostenzuschussException(
                    'Opportunity nicht gefunden: ' + oppId
                );
            }

            if (existingOppIds.contains(oppId)) {
                throw new NebenkostenzuschussException(
                    'Es existiert bereits ein aktiver Nebenkostenzuschuss fuer diese Opportunity: ' + oppId
                );
            }

            if (opp.Appartement__c == null) {
                throw new NebenkostenzuschussException(
                    'Opportunity hat kein Teilobjekt (Appartement): ' + oppId
                );
            }

            Nebenkostenzuschuss__c nkz = new Nebenkostenzuschuss__c();
            nkz.Opportunity__c = opp.Id;
            nkz.Objekt__c = opp.Immobilie__c;
            nkz.Teilobjekt__c = opp.Appartement__c;
            nkz.Kunde__c = opp.Potenzieller_Kunde__c;
            nkz.Empfaenger__c = opp.Makler__c;
            toInsert.add(nkz);
        }

        if (!toInsert.isEmpty()) {
            insert toInsert;
        }

        return toInsert;
    }
}