force-app/main/default/objects/Contact/fields/DatevDebitorenKundennummerKaeufer__c.field-meta.xml
<CustomField>
    <fullName>DatevDebitorenKundennummerKaeufer__c</fullName>
    <label>Datev Debitoren- / Kundennummer Käufer</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatevDebitorennummerKaeufer__c/DatevDebitorennummerKaeufer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Datev Debitorennummer Käufer</label>
</CustomObject>

force-app/main/default/objects/DatevDebitorennummerKaeufer__c/fields/DatevDebitorennummerKaeufer__c.field-meta.xml
<CustomField>
    <fullName>DatevDebitorennummerKaeufer__c</fullName>
    <label>Datev Debitorennummer Käufer</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GenerateDatevDebitorNumberBuyers.cls
/**
 * Created by frederikwitte on 02.11.20.
 */

public class GenerateDatevDebitorNumberBuyers {
    
    public void generateDatevDebitorNumberBuyers(List<Id> conIds) {
        try {
            List<Contact> cons = [SELECT DatevDebitorenKundennummerKaeufer__c FROM Contact WHERE Id IN :conIds];

            DatevDebitorennummerKaeufer__c datevDebitorennummerKaeuferSetting = DatevDebitorennummerKaeufer__c.getOrgDefaults();
            Decimal datevDebitorenNummerKaeufer = datevDebitorennummerKaeuferSetting.DatevDebitorennummerKaeufer__c;
            for (Contact con : cons) {
                if (con.DatevDebitorenKundennummerKaeufer__c == null) {
                    con.DatevDebitorenKundennummerKaeufer__c = String.valueOf((Integer) datevDebitorenNummerKaeufer);
                    datevDebitorenNummerKaeufer++;
                }
            }

            if (datevDebitorenNummerKaeufer != datevDebitorennummerKaeuferSetting.DatevDebitorennummerKaeufer__c) {
                datevDebitorennummerKaeuferSetting.DatevDebitorennummerKaeufer__c = datevDebitorenNummerKaeufer;
                update datevDebitorennummerKaeuferSetting;
                update cons;
            }

        } catch(Exception e) {
            throw e;
        }

    }

}