force-app/main/default/objects/Contact/fields/EmailForCreditNotes__c.field-meta.xml
<CustomField>
    <fullName>EmailForCreditNotes__c</fullName>
    <inlineHelpText>Wenn dieses Feld befüllt ist, werden Gutschriften statt an die normale Email-Adresse an die hier hinterlegte Adresse gesendet.</inlineHelpText>
    <label>Email für Gutschriften</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Monate durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>6 Wochen durchgehende Kontoauszüge aller privaten Girokonten</fullName>
            </value>
            <value>
                <fullName>aktuelle BWA inkl. Summen- und Saldenliste</fullName>
            </value>
            <value>
                <fullName>aktueller Rentenbescheid (bei Rentner)</fullName>
            </value>
            <value>
                <fullName>Angebot</fullName>
            </value>
            <value>
                <fullName>Aufhebungsvertrag</fullName>
            </value>
            <value>
                <fullName>Aufstellung der geplanten Modernisierungskosten (bei geplanter Modernisierung / Sanierung)</fullName>
            </value>
            <value>
                <fullName>Bausparvertrag: letzter Jahreskontoauszug</fullName>
            </value>
            <value>
                <fullName>bei abzulösenden Darlehen die Kopie vom Jahreskontoauszug vom letzten Jahr (alternativ: Nachweis aktueller Darlehensstand)</fullName>
            </value>
            <value>
                <fullName>Belegungsrecht</fullName>
            </value>
            <value>
                <fullName>Beratungsprotokoll (BP)</fullName>
            </value>
            <value>
                <fullName>Berechnung zum KfW-Antrag im Original gem. Online-Bestätigung (bei KfW-Anträgen)</fullName>
            </value>
            <value>
                <fullName>BWA inkl. Summen- und Saldenliste per letzten Jahresende (wenn kein JA bzw. EÜR vorliegt)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag: Kopien sämtlicher Darlehensverträge (Ersten vier Seiten)</fullName>
            </value>
            <value>
                <fullName>Darlehensvertrag (DV)</fullName>
            </value>
            <value>
                <fullName>Datenerfassungsbogen</fullName>
            </value>
            <value>
                <fullName>DSGVO</fullName>
            </value>
            <value>
                <fullName>Eigenkapitalnachweis (EK)</fullName>
            </value>
            <value>
                <fullName>EK Nachweise mit persönlichen Angaben (Name, Konto-/Depot Nr., Datum, Betrag)</fullName>
            </value>
            <value>
                <fullName>EÜ-Rechnung/vollständiger Jahresabschluss der letzten 2 Jahre</fullName>
            </value>
            <value>
                <fullName>Fälligkeitsmitteilung</fullName>
            </value>
            <value>
                <fullName>Finanzierungsbestätigung (FB)</fullName>
            </value>
            <value>
                <fullName>für Nicht-EU-Bürger ist eine unbefristete Aufenthaltsgenehmigung erforderlich</fullName>
            </value>
            <value>
                <fullName>Grundschuld (GS)</fullName>
            </value>
            <value>
                <fullName>Gutschrift</fullName>
            </value>
            <value>
                <fullName>Immobilienaufstellung mit Mieterliste bzw. Mietverträge und Kontoauszug des Mieteingangs für weitere Immobilien (bei Vermietungsobjekt)</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlage</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 1</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 2</fullName>
            </value>
            <value>
                <fullName>Individuelle Unterlagen 3</fullName>
            </value>
            <value>
                <fullName>Nebenkostenzuschuss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/recordTypes/Gutschriften.recordType-meta.xml
<RecordType>
    <fullName>Gutschriften</fullName>
    <active>true</active>
    <label>Gutschriften</label>
</RecordType>

force-app/main/default/objects/Nebenkostenzuschuss__c/Nebenkostenzuschuss__c.object-meta.xml
<CustomObject>
    <label>Nebenkostenzuschuss</label>
    <nameField>
        <label>Nebenkostenzuschuss-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nebenkostenzusch&#252;sse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/BelegWurdeGeneriert__c.field-meta.xml
<CustomField>
    <fullName>BelegWurdeGeneriert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Beleg wurde generiert?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/Empfaenger__c.field-meta.xml
<CustomField>
    <fullName>Empfaenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empf&#228;nger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Nebenkostenzusch&#252;sse</relationshipLabel>
    <relationshipName>Nebenkostenzuschuesse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nebenkostenzuschuss__c/fields/LaufnummerNew__c.field-meta.xml
<CustomField>
    <fullName>LaufnummerNew__c</fullName>
    <formula>'NK ' + TEXT(YEAR( DatumGenehmigungBackoffice__c )) + ' ' + LPAD(TEXT( Laufnummer_Zahl__c ), 4, '0')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Laufnummer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NebenkostenzuschussDocument.cls
public without sharing class NebenkostenzuschussDocument {

    @Future(callout=true)
    public static void sendNKZAsPdf(Id id) {
        if (id == null) {
            return;
        }

        List<Nebenkostenzuschuss__c> records = [SELECT Id, LaufnummerNew__c, Empfaenger__c, Empfaenger__r.Email, Empfaenger__r.EmailForCreditNotes__c FROM Nebenkostenzuschuss__c WHERE Id = :id];
        if (records.isEmpty()) {
            return;
        }
        Nebenkostenzuschuss__c nkzRecord = records.get(0);
        PageReference pdf = Page.NebenkostenzuschussBeleg;
        pdf.getParameters().put('id', nkzRecord.Id);


        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
        attach.ContentType = 'application/pdf';
        Blob body;
        try {
            body = pdf.getContentAsPDF();
        } catch (Exception e) {
            body = blob.valueOf('Ein Fehler ist aufgetreten');
        }
        String fileName = 'Nebenkostenzuschuss ' + nkzRecord.LaufnummerNew__c + '.pdf';
        attach.setFileName(fileName);
        attach.setInline(false);
        attach.Body = body;

        Id templateId;
        try {
            templateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'NKZ'].Id;
        } catch (Exception e) {
            templateId = null;
        }
        List<OrgWideEmailAddress> oweas = new List<OrgWideEmailAddress>([SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE Address = 'maklerbetreuung@wirtschaftshaus.de']);
        Boolean emailToRecipientSent = false;
        Messaging.SingleEmailMessage emailToEmpfaenger;

        if (nkzRecord.Empfaenger__c != null) {
            Messaging.Email[] messages = new Messaging.Email[0];
            emailToEmpfaenger = new Messaging.SingleEmailMessage();
            if (templateId != null) {
                emailToEmpfaenger.setTemplateId(templateId);
            }
            emailToEmpfaenger.setTargetObjectId(nkzRecord.Empfaenger__c);
            if(nkzRecord.Empfaenger__r.EmailForCreditNotes__c != null) {
                emailToEmpfaenger.setTreatTargetObjectAsRecipient(false);
                emailToEmpfaenger.setToAddresses(new String[]{nkzRecord.Empfaenger__r.EmailForCreditNotes__c});
            }
            emailToEmpfaenger.setWhatId(nkzRecord.Id);
            if (oweas.size() > 0) {
                emailToEmpfaenger.setOrgWideEmailAddressId(oweas.get(0).Id);
            }
            emailToEmpfaenger.setFileAttachments(new Messaging.EmailFileAttachment[]{
                    attach
            });
            messages.add(emailToEmpfaenger);
            try {
                Messaging.SendEmailResult [] r = Messaging.sendEmail(messages, false);
                emailToRecipientSent = !r.isEmpty() && r[0].isSuccess();
                System.debug(r);
            } catch (Exception e) {
                emailToRecipientSent = false;
            }
        }

        Messaging.SingleEmailMessage emailToFibu = new Messaging.SingleEmailMessage();

        String[] toMails = new List < String > ();
        toMails.add('fibu@carestone.com');
        emailToFibu.setToAddresses(toMails);
        if (oweas.size() > 0) {
            emailToFibu.setOrgWideEmailAddressId(oweas.get(0).Id);
        }

        if(emailToRecipientSent && emailToEmpfaenger != null) {
            emailToFibu.setHtmlBody(emailToEmpfaenger.getHtmlBody());

            emailToFibu.setPlainTextBody(emailToEmpfaenger.getPlainTextBody());

            emailToFibu.setSubject(emailToEmpfaenger.getSubject());

            emailToFibu.setFileAttachments(emailToEmpfaenger.getFileAttachments());
        } else {
            emailToFibu.setPlainTextBody('Für den Nebenkostenzuschuss wurde ein Beleg generiert und konnte nicht per Mail an den Empfänger zugestellt werden.');

            emailToFibu.setSubject('Nebenkostenzuschuss ' + nkzRecord.LaufnummerNew__c);

            emailToFibu.setFileAttachments(new Messaging.EmailFileAttachment[]{
                    attach
            });
        }

        if(Utility.checkIfDeliverabilityIsEnabled()) {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                emailToFibu
            });
        }
        User u = [SELECT IsActive,IsPortalEnabled,LastName FROM User WHERE Id = :UserInfo.getUserId()];
        ContentVersion file = new ContentVersion();
        file.VersionData = body;
        file.Title = fileName;
        file.ContentLocation= 's';
        file.PathOnClient=fileName;
        Id nkzRecordTypeId = Schema.getGlobalDescribe().get('ContentVersion').getDescribe().getRecordTypeInfosByName().get('Gutschriften').getRecordTypeId();
        file.Typ__c = 'Nebenkostenzuschuss';
        file.RecordTypeId = nkzRecordTypeId;
        if(u.IsPortalEnabled) {
            Id networkId = [SELECT Id FROM Network LIMIT 1].Id;
            file.NetworkId = networkId;
        }
        nkzRecord.BelegWurdeGeneriert__c = true;
        insert file;

        List<ContentVersion> files = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :file.Id];

        if(files.size() > 0) {
            file = files[0];
            ContentDocumentLink cde = new ContentDocumentLink();
            cde.ContentDocumentId = file.ContentDocumentId;
            cde.LinkedEntityId = nkzRecord.Id;
            insert cde;
            update nkzRecord;
        }
    }
}