force-app/main/default/objects/Realty_User__c/Realty_User__c.object-meta.xml
<CustomObject>
    <label>Immo Benutzer</label>
    <nameField>
        <label>Immo Benutzer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immo Benutzer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realty_User__c/fields/AGBs_angenommen__c.field-meta.xml
<CustomField>
    <fullName>AGBs_angenommen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AGBs angenommen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Datenschutzerkl_rung_angenommen__c.field-meta.xml
<CustomField>
    <fullName>Datenschutzerkl_rung_angenommen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Datenschutzerklärung angenommen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Herkunft__c.field-meta.xml
<CustomField>
    <fullName>Herkunft__c</fullName>
    <inlineHelpText>Beschreibt auf welcher Seite sich der Immobenutzer registriert hat.</inlineHelpText>
    <label>Herkunft</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/lb_AGB_angenommen__c.field-meta.xml
<CustomField>
    <fullName>lb_AGB_angenommen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>lb_AGB_angenommen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Login_Email__c.field-meta.xml
<CustomField>
    <fullName>Login_Email__c</fullName>
    <label>Login Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Passwort_vergessen__c.field-meta.xml
<CustomField>
    <fullName>Passwort_vergessen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passwort vergessen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Telefonnummer__c.field-meta.xml
<CustomField>
    <fullName>Telefonnummer__c</fullName>
    <label>Telefonnummer</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Realty_User__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Normal Agency</fullName>
            </value>
            <value>
                <fullName>Manager Agency</fullName>
            </value>
            <value>
                <fullName>Free Lancer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ImmobenutzerRegistrierung.cls
global class ImmobenutzerRegistrierung implements Messaging.InboundEmailHandler {
	
	global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email,
																Messaging.InboundEnvelope env) {
 
		// Create an InboundEmailResult object for returning the result of the
		// Apex Email Service
		
		Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
		
		String[] emailBody = email.plainTextBody.split('\n');

		String type = emailBody[0];

		if(type == 'register')
		{
			// Generate Random Password for User
			Integer len = 8;
			Blob blobKey = Crypto.generateAesKey(128);
			String key = EncodingUtil.convertToHex(blobKey);
			String pwd = key.substring(0,len);

			Realty_User__c newImmobenutzer = new Realty_User__c();

			newImmobenutzer.Name = emailBody[1];
			newImmobenutzer.Email__c = emailBody[2];
			newImmobenutzer.Login_Email__c = emailBody[2];
			newImmobenutzer.Telefonnummer__c = emailBody[3];
			newImmobenutzer.Herkunft__c =  emailBody[4];
			newImmobenutzer.Type__c = 'Normal Agency';
			newImmobenutzer.Password__c = pwd;
			newImmobenutzer.Active__c = false;
			newImmobenutzer.Datenschutzerkl_rung_angenommen__c = TRUE;
			newImmobenutzer.AGBs_angenommen__c = TRUE;
			newImmobenutzer.lb_AGB_angenommen__c = TRUE;

			insert newImmobenutzer;
		}
		else if(type == 'password')
		{
			String mail = emailBody[1];
			try
			{
				Realty_User__c immoBenutzer = [SELECT Passwort_vergessen__c FROM Realty_User__c WHERE Login_Email__c =: mail];
				immoBenutzer.Passwort_vergessen__c = true;

				update immoBenutzer;
			}
			catch(Exception e){}
		}
		
		result.success = true;
		return result;
	}
}