force-app/main/default/objects/VKCZahlung__c/VKCZahlung__c.object-meta.xml
<CustomObject>
    <label>VKC Zahlung</label>
    <nameField>
        <displayFormat>EZ-{YYYY}-{MM}-{DD}-{0000000}</displayFormat>
        <label>VKC Zahlung Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VKC Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VKCZahlung__c/fields/Verkaufschance__c.field-meta.xml
<CustomField>
    <fullName>Verkaufschance__c</fullName>
    <label>Verkaufschance</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>VKC Zahlungen</relationshipLabel>
    <relationshipName>VKCZahlungen</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VkcZahlungTriggerHandler.cls
public without sharing class VkcZahlungTriggerHandler implements ITrigger {
    
    Set<Id> opportunityIds = new Set<Id>();

    public VkcZahlungTriggerHandler() {

    }

    public void bulkBefore() {
        
    }

    public void bulkAfter() {
        
    }

    public void beforeInsert(SObject so) {
        
    }

    public void beforeUpdate(SObject oldSo, SObject so) {
        
    }

    public void beforeDelete(SObject so) {

    }

    public void afterInsert(SObject so) {
        VkcZahlung__c zahlung = (VkcZahlung__c) so;
        opportunityIds.add(zahlung.Verkaufschance__c);
    }

    public void afterUpdate(SObject oldSo, SObject so) {
        VkcZahlung__c zahlung = (VkcZahlung__c) so;
        opportunityIds.add(zahlung.Verkaufschance__c);
    }

    public void afterDelete(SObject so) {
        VkcZahlung__c zahlung = (VkcZahlung__c) so;
        opportunityIds.add(zahlung.Verkaufschance__c);
    }

    public void andFinally() {
        if(!opportunityIds.isEmpty() && Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
            System.enqueueJob(new AggregateVkcZahlungPaymentDataQueueable(opportunityIds));
        }
    }
}