force-app/main/default/objects/AutomationController__c/AutomationController__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Allows to toggle execution of triggers, flows etc.</description>
    <label>Automation Controller</label>
</CustomObject>

force-app/main/default/objects/AutomationController__c/fields/GutschriftFlows__c.field-meta.xml
<CustomField>
    <fullName>GutschriftFlows__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Gutschrift Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <label>Provision</label>
    <nameField>
        <displayFormat>Provision-{0000}</displayFormat>
        <label>Provision-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisionen</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/GutschriftAbgelehnt__c.field-meta.xml
<CustomField>
    <fullName>GutschriftAbgelehnt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift abgelehnt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/GutschriftBestaetigt__c.field-meta.xml
<CustomField>
    <fullName>GutschriftBestaetigt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gutschrift bestätigt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GutschriftApprovalControllerTest.cls
@isTest
public without sharing class GutschriftApprovalControllerTest {
    private static Id provId;

    @TestSetup
    static void setup(){
        TestDataFactory.createDatevSettings();
        TestDataFactory.createNecessaryCustomSettings();
        TestDataFactory.createProvision(true);
        AutomationController__c ac = new AutomationController__c(GutschriftFlows__c = false);
        insert ac;
    }

    @isTest
    static void testGutschriftApproval() {
        Provision__c prov = TestDataFactory.createProvision(true);

        PageReference pageRef = Page.GutschriftApproval;
        pageRef.getParameters().put('gutschriftId', prov.Id);
        pageRef.getParameters().put('accepted', 'true');
        Test.setCurrentPage(pageRef);

        Test.startTest();
        GutschriftApprovalController gap = new GutschriftApprovalController();
        gap.approveGutschrift();
        
        //Check status message
        Assert.areEqual('Gutschrift erfolgreich bestätigt!', gap.status);

        //TODO Adapt to new event-driven architecture
        // //Check record update
        // Provision__c updatedProv = [SELECT GutschriftBestaetigt__c FROM Provision__c WHERE Id = :prov.Id];
        // Assert.isTrue(updatedProv.GutschriftBestaetigt__c);

        Test.stopTest();

    }

    @isTest
    static void testGutschriftRejection() {
        Provision__c prov = TestDataFactory.createProvision(true);

        PageReference pageRef = Page.GutschriftApproval;
        pageRef.getParameters().put('gutschriftId', prov.Id);
        pageRef.getParameters().put('accepted', 'false');
        Test.setCurrentPage(pageRef);

        Test.startTest();
        GutschriftApprovalController gap = new GutschriftApprovalController();
        gap.approveGutschrift();
        
        //Check status message
        Assert.areEqual('Gutschrift erfolgreich abgelehnt!', gap.status);

/*         //Can't check record change since WOrkflow rule immediately unchecks field
        Provision__c updatedProv = [SELECT GutschriftBestaetigt__c, GutschriftAbgelehnt__c FROM Provision__c WHERE Id = :prov.Id];
        System.debug('Bestätigt? ' + updatedProv.GutschriftBestaetigt__c + ' || Abgelehnt? ' + updatedProv.GutschriftAbgelehnt__c);
        Assert.isTrue(updatedProv.GutschriftAbgelehnt__c); */

        Test.stopTest();
    }

    // @isTest
    // static void testGutschriftAlreadyApproved() {
    //     Provision__c prov = TestDataFactory.createProvision(true);

    //     // Provision__c prov = [SELECT ID FROM Provision__c];
    //     // prov.GutschriftBestaetigt__c = true;
    //     // update prov;

    //     PageReference pageRef = Page.GutschriftApproval;
    //     pageRef.getParameters().put('gutschriftId', prov.Id);
    //     pageRef.getParameters().put('accepted', 'true');
    //     Test.setCurrentPage(pageRef);

    //     Test.startTest();
    //     GutschriftApprovalController gap = new GutschriftApprovalController();
    //     gap.approveGutschrift();
    //     gap.approveGutschrift();

    //     Test.stopTest();

    //      //Check status message
    //      Assert.areEqual('Diese Gutschrift wurde bereits bearbeitet.', gap.status);
    // }

    @isTest
    static void testCorruptedGutschriftParameter() {

        Provision__c prov = [SELECT ID FROM Provision__c];

        PageReference pageRef = Page.GutschriftApproval;
        pageRef.getParameters().put('gutschriftId', '12345');
        pageRef.getParameters().put('accepted', 'true');
        Test.setCurrentPage(pageRef);

        Test.startTest();
        GutschriftApprovalController gap = new GutschriftApprovalController();
        gap.approveGutschrift();
        
        //Check status message
        Assert.areEqual('Fehler! Bitte wenden Sie sich an Ihren Maklerbetreuer. <br/>(Fehlercode e3)', gap.status);

        Test.stopTest();
    }

    @isTest
    static void testCorruptedAcceptedParameter() {

        Provision__c prov = [SELECT ID FROM Provision__c];

        PageReference pageRef = Page.GutschriftApproval;
        pageRef.getParameters().put('gutschriftId', prov.Id);
        pageRef.getParameters().put('accepted', 'test');
        Test.setCurrentPage(pageRef);

        Test.startTest();
        GutschriftApprovalController gap = new GutschriftApprovalController();
        gap.approveGutschrift();
        
        //Check status message
        Assert.areEqual('Fehler! Bitte wenden Sie sich an Ihren Maklerbetreuer. <br/>(Fehlercode e2)', gap.status);

        Test.stopTest();
    }

}