force-app/main/default/objects/HiddenProperty__c/HiddenProperty__c.object-meta.xml
<CustomObject>
    <label>Versteckte Immobilie</label>
    <nameField>
        <displayFormat>VI-{00000}</displayFormat>
        <label>Versteckte Immobilie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Versteckte Immobilien</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HiddenProperty__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Versteckte Immobilien</relationshipLabel>
    <relationshipName>HiddenProperties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HiddenProperty__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Versteckt vor Accounts</relationshipLabel>
    <relationshipName>HiddenForAccounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Property_Selector.cls
public with sharing class Property_Selector extends Selector {

    private static final String fromObject = 'Property__c ';

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Property__c.Id,
            Property__c.Name
        };
    }

    Id accountId;
    
    public Property_Selector(Id accountId) {
        super();
        this.accountId = accountId;
        setConditionWithSharing(null);
    }

    public List<Property__c> getRecords() {
        return (List<Property__c>) query();
    }

    public Schema.SObjectType getSObjectType() {
        return Property__c.SObjectType;
    }

    public final String visibilityBaseCondition = 'Id NOT IN (SELECT Property__c FROM HiddenProperty__c WHERE Account__c = ' + String.escapeSingleQuotes(this.accountId) + ')';

    public Property_Selector setConditionWithSharing(String condition) {
        if (condition == null) {
            condition = visibilityBaseCondition;
        } else {
            condition = '(' + condition + ') AND ' + visibilityBaseCondition;
        }
        setCondition(visibilityBaseCondition);
        return this;
    }
}