force-app/main/default/objects/HiddenProperty__c/HiddenProperty__c.object-meta.xml
<CustomObject>
    <label>Versteckte Immobilie</label>
    <nameField>
        <displayFormat>VI-{00000}</displayFormat>
        <label>Versteckte Immobilie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Versteckte Immobilien</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HiddenProperty__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Versteckte Immobilien</relationshipLabel>
    <relationshipName>HiddenProperties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HiddenProperty__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Versteckt vor Accounts</relationshipLabel>
    <relationshipName>HiddenForAccounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountPropertyVisibilityControllerTest.cls
@IsTest
private class AccountPropertyVisibilityControllerTest {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.createDatevSettings();
        Account acc = TestDataFactory.createAccount(true);
        Property__c immobilie = TestDataFactory.createProperty(true, TestDataFactory.createBautraeger(true).Id);
    }
    
    @IsTest
    private static void testGetProperties() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Test.startTest();
        Assert.areEqual([SELECT COUNT() FROM Property__c WHERE Is_Public__c = true], AccountPropertyVisibilityController.getProperties(accountId).size());
        Test.stopTest();
    }

    @IsTest
    private static void testHideProperty() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Id propertyId = [SELECT Id FROM Property__c WHERE Is_Public__c = true LIMIT 1].Id;
        Test.startTest();
        AccountPropertyVisibilityController.hideProperty(accountId, propertyId);
        Assert.areEqual(1, [SELECT COUNT() FROM HiddenProperty__c WHERE Account__c = :accountId AND Property__c = :propertyId]);
        Test.stopTest();
    }

    @IsTest
    private static void testUnhideProperty() {
        Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
        Id propertyId = [SELECT Id FROM Property__c WHERE Is_Public__c = true LIMIT 1].Id;
        insert new HiddenProperty__c(Account__c = accountId, Property__c = propertyId);
        Test.startTest();
        AccountPropertyVisibilityController.unhideProperty(accountId, propertyId);
        Assert.areEqual(0, [SELECT COUNT() FROM HiddenProperty__c WHERE Account__c = :accountId AND Property__c = :propertyId]);
        Test.stopTest();
    }
}