force-app/main/default/objects/HiddenProperty__c/HiddenProperty__c.object-meta.xml
<CustomObject>
    <label>Versteckte Immobilie</label>
    <nameField>
        <displayFormat>VI-{00000}</displayFormat>
        <label>Versteckte Immobilie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Versteckte Immobilien</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HiddenProperty__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Versteckte Immobilien</relationshipLabel>
    <relationshipName>HiddenProperties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HiddenProperty__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Versteckt vor Accounts</relationshipLabel>
    <relationshipName>HiddenForAccounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountPropertyVisibilityController.cls
public without sharing class AccountPropertyVisibilityController {
    
    
    @AuraEnabled
    public static List<PropertyWithVisibility> getProperties(Id accountId){
        List<PropertyWithVisibility> properties = new List<PropertyWithVisibility>();

        for(Property__c property : getPublicPropertiesWithVisibility(accountId)) {
            PropertyWithVisibility propertyWithVisibility = new PropertyWithVisibility();
            propertyWithVisibility.propertyId = property.Id;
            propertyWithVisibility.propertyName = property.Name;
            propertyWithVisibility.isVisible = property.HiddenForAccounts__r.isEmpty();
            properties.add(propertyWithVisibility);
        }

        return properties;
    }

    @AuraEnabled
    public static void hideProperty(Id accountId, Id propertyId){
        insert new HiddenProperty__c(Account__c = accountId, Property__c = propertyId);
    }

    @AuraEnabled
    public static void unhideProperty(Id accountId, Id propertyId){
        delete [SELECT Id FROM HiddenProperty__c WHERE Account__c = :accountId AND Property__c = :propertyId];
    }

    private static List<Property__c> getPublicPropertiesWithVisibility(Id accountId){
        return [SELECT Id, Name, (SELECT Id FROM HiddenForAccounts__r WHERE Account__c = :accountId) FROM Property__c WHERE Is_Public__c = true ORDER BY Name ASC];
    }

    public class PropertyWithVisibility {
        @AuraEnabled public String propertyId {get;set;}
        @AuraEnabled public String propertyName {get;set;}
        @AuraEnabled public Boolean isVisible {get;set;}
    }
}