force-app/main/default/objects/Connector__c/Connector__c.object-meta.xml
<CustomObject>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector__c/fields/AccessTokenExpiry__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenExpiry__c</fullName>
    <label>Access Token Expiry</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/AccessTokenRequested__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenRequested__c</fullName>
    <label>Access Token Requested</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>NOT(ISBLANK(AccessToken__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/ConnectorType__c.field-meta.xml
<CustomField>
    <fullName>ConnectorType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connector Type</label>
    <referenceTo>ConnectorType__c</referenceTo>
    <relationshipLabel>Connectors</relationshipLabel>
    <relationshipName>Connectors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/RefreshTokenRequested__c.field-meta.xml
<CustomField>
    <fullName>RefreshTokenRequested__c</fullName>
    <label>Refresh Token Requested</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/ConnectorType__c.object-meta.xml
<CustomObject>
    <label>Connector Type</label>
    <nameField>
        <label>Connector Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connector Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectorType__c/fields/AuthorizationEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationEndpoint__c</fullName>
    <label>Authorization Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/CallbackURL__c.field-meta.xml
<CustomField>
    <fullName>CallbackURL__c</fullName>
    <label>Callback URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>Developer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ExtraUrlParameters__c.field-meta.xml
<CustomField>
    <fullName>ExtraUrlParameters__c</fullName>
    <label>Extra Url Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/RedirectUri__c.field-meta.xml
<CustomField>
    <fullName>RedirectUri__c</fullName>
    <label>Redirect URI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ScopeRequired__c.field-meta.xml
<CustomField>
    <fullName>ScopeRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scope Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/TokenEndpoint__c.field-meta.xml
<CustomField>
    <fullName>TokenEndpoint__c</fullName>
    <label>Token Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConnectorControllerTest.cls
@isTest
public with sharing class ConnectorControllerTest {

    @TestSetup
    static void makeData(){
        ConnectorType__c ct = new ConnectorType__c();
        ct.Name = 'Google Drive';
        ct.AuthorizationEndpoint__c = 'https://accounts.google.com/o/oauth2/auth';
        ct.TokenEndpoint__c = 'https://accounts.google.com/o/oauth2/token';
        ct.ClientId__c = '166550496015-h41c6c5pe3jtu799iefm6gidetre397c.apps.googleusercontent.com';
        ct.ClientSecret__c = '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';
        ct.RedirectUri__c = 'https://wirtschaftshaus.lightning.force.com/apex/connector';
        ct.ScopeRequired__c = true;
        ct.Scope__c = 'https://www.googleapis.com/auth/drive';
        ct.ExtraUrlParameters__c = 'access_type=offline';
        insert ct;

        Connector__c c = new Connector__c();
        c.Name = 'Google Drive';
        c.ConnectorType__c = ct.Id;
        insert c;
    }
    
    private static testMethod void testConnectorController() {
        Connector__c c = [SELECT Id FROM Connector__c];
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        PageReference pageRef = Page.Connector;
        pageRef.getParameters().put('id', c.Id);
        Test.setCurrentPage(pageRef);
        Test.startTest();
        ApexPages.StandardController std = new ApexPages.StandardController(c);
        ConnectorController cc = new ConnectorController(std);
        cc.save();
        cc.cancel();
        cc.RequestAuthorizationCode();
        cc.error('test');
        cc.info('test');
        cc.isConfigured();
        cc.getServiceName();
        cc.getRecordName();
        cc.getIsAuthorized();
        cc.getIsDirty();
        cc.getisConfigured();
        Test.stopTest();
    }
    
    private static testMethod void testConnectorControllerExchangeAuthCode() {
        Connector__c c = [SELECT Id FROM Connector__c];
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        PageReference pageRef = Page.Connector;
        pageRef.getParameters().put('id', c.Id);
        Test.setCurrentPage(pageRef);
        Test.startTest();
        ApexPages.StandardController std = new ApexPages.StandardController(c);
        ConnectorController cc = new ConnectorController(std);
        cc.exchangeAuthCode();
        Test.stopTest();
    }
    
    private static testMethod void testConnectorService() {
        Connector__c c = [SELECT c.TokenType__c, c.RefreshToken__c, c.RefreshTokenRequested__c, c.Name, c.Id, c.AccessToken__c, 
                       c.AccessTokenRequested__c, c.AccessTokenExpiry__c, c.Active__c, 
                       ConnectorType__r.TokenEndpoint__c, ConnectorType__r.Scope__c, ConnectorType__r.ScopeRequired__c, 
                       ConnectorType__r.RedirectUri__c, ConnectorType__r.Name, ConnectorType__r.Id, 
                       ConnectorType__r.ExtraUrlParameters__c, ConnectorType__r.DeveloperName__c, 
                       ConnectorType__r.ClientSecret__c, ConnectorType__r.ClientId__c, ConnectorType__r.CallbackURL__c, 
                       ConnectorType__r.AuthorizationEndpoint__c FROM Connector__c c];
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();
        ConnectorService csViaId = new ConnectorService(c.Id);
        csViaId.retrieveConnector();
        csViaId.validateConnector();
        ConnectorService csViaRecord = new ConnectorService(c);
        csViaRecord.retrieveConnector();
        csViaRecord.validateConnector();
        csViaRecord.getAccessToken();
        csViaRecord.exchangeCode('a', false);
        csViaRecord.accessTokenExpired();
        
        Test.stopTest();
    }
}