force-app/main/default/objects/Connector__c/Connector__c.object-meta.xml
<CustomObject>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector__c/fields/ConnectorType__c.field-meta.xml
<CustomField>
    <fullName>ConnectorType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connector Type</label>
    <referenceTo>ConnectorType__c</referenceTo>
    <relationshipLabel>Connectors</relationshipLabel>
    <relationshipName>Connectors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/ConnectorType__c.object-meta.xml
<CustomObject>
    <label>Connector Type</label>
    <nameField>
        <label>Connector Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connector Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectorType__c/fields/AuthorizationEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationEndpoint__c</fullName>
    <label>Authorization Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ExtraUrlParameters__c.field-meta.xml
<CustomField>
    <fullName>ExtraUrlParameters__c</fullName>
    <label>Extra Url Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/RedirectUri__c.field-meta.xml
<CustomField>
    <fullName>RedirectUri__c</fullName>
    <label>Redirect URI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ScopeRequired__c.field-meta.xml
<CustomField>
    <fullName>ScopeRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scope Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/TokenEndpoint__c.field-meta.xml
<CustomField>
    <fullName>TokenEndpoint__c</fullName>
    <label>Token Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SchedulableImmobilienFilesTest.cls
@isTest
private class SchedulableImmobilienFilesTest {
  @TestSetup
  static void makeData(){
    ConnectorType__c ct = new ConnectorType__c();
    ct.Name = 'Google Drive';
    ct.AuthorizationEndpoint__c = 'https://accounts.google.com/o/oauth2/auth';
    ct.TokenEndpoint__c = 'https://accounts.google.com/o/oauth2/token';
    ct.ClientId__c = '166550496015-h41c6c5pe3jtu799iefm6gidetre397c.apps.googleusercontent.com';
    ct.ClientSecret__c = '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';
    ct.RedirectUri__c = 'https://carestone.lightning.force.com/apex/connector';
    ct.ScopeRequired__c = true;
    ct.Scope__c = 'https://www.googleapis.com/auth/drive';
    ct.ExtraUrlParameters__c = 'access_type=offline';
    insert ct;

    Connector__c c = new Connector__c();
    c.Name = 'Google Drive';
    c.ConnectorType__c = ct.Id;
    c.TokenType__c = 'Bearer';
    c.AccessToken__c = 'abc';
    insert c;
  }

  @isTest static void test_method_one() {
    new Sandbox();
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Test.startTest();


        // Schedule the test job

        String year = String.valueOf((Date.today().year() + 1));

        String jobId = System.schedule('testBasicScheduledApex',
          '0 0 0 3 9 ? ' + year,
            new SchedulableImmobilienFiles());

      // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

      // Verify the expressions are the same
      System.assertEquals('0 0 0 3 9 ? ' + year,
         ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run
      System.assertEquals(year + '-09-03 00:00:00',
         String.valueOf(ct.NextFireTime));
         
       Test.stopTest();
  }

}