force-app/main/default/objects/Connector__c/Connector__c.object-meta.xml
<CustomObject>
    <label>Connector</label>
    <nameField>
        <label>Connector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connector__c/fields/AccessTokenExpiry__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenExpiry__c</fullName>
    <label>Access Token Expiry</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/AccessTokenRequested__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenRequested__c</fullName>
    <label>Access Token Requested</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>NOT(ISBLANK(AccessToken__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/ConnectorType__c.field-meta.xml
<CustomField>
    <fullName>ConnectorType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Connector Type</label>
    <referenceTo>ConnectorType__c</referenceTo>
    <relationshipLabel>Connectors</relationshipLabel>
    <relationshipName>Connectors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connector__c/fields/RefreshTokenRequested__c.field-meta.xml
<CustomField>
    <fullName>RefreshTokenRequested__c</fullName>
    <label>Refresh Token Requested</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/ConnectorType__c.object-meta.xml
<CustomObject>
    <label>Connector Type</label>
    <nameField>
        <label>Connector Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connector Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnectorType__c/fields/AuthorizationEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AuthorizationEndpoint__c</fullName>
    <label>Authorization Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/CallbackURL__c.field-meta.xml
<CustomField>
    <fullName>CallbackURL__c</fullName>
    <label>Callback URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>Developer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ExtraUrlParameters__c.field-meta.xml
<CustomField>
    <fullName>ExtraUrlParameters__c</fullName>
    <label>Extra Url Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/RedirectUri__c.field-meta.xml
<CustomField>
    <fullName>RedirectUri__c</fullName>
    <label>Redirect URI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/ScopeRequired__c.field-meta.xml
<CustomField>
    <fullName>ScopeRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scope Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConnectorType__c/fields/TokenEndpoint__c.field-meta.xml
<CustomField>
    <fullName>TokenEndpoint__c</fullName>
    <label>Token Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImmobilienBild__c/ImmobilienBild__c.object-meta.xml
<CustomObject>
    <label>Immobilien Bild</label>
    <nameField>
        <label>Immobilien Bild-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien Bilder</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ImmobilienBild__c/fields/BildUrl__c.field-meta.xml
<CustomField>
    <fullName>BildUrl__c</fullName>
    <label>Bild URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ImmobilienBild__c/fields/ImmobilienBilder__c.field-meta.xml
<CustomField>
    <fullName>ImmobilienBilder__c</fullName>
    <label>Immobilien Bilder</label>
    <referenceTo>ImmobilienBilder__c</referenceTo>
    <relationshipLabel>Immobilien Bilder</relationshipLabel>
    <relationshipName>ImmobilienBilder</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ImmobilienBilder__c/ImmobilienBilder__c.object-meta.xml
<CustomObject>
    <label>Immobilien Bilder</label>
    <nameField>
        <label>Immobilien Bilder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien Bilder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImmobilienBilder__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Immobilien Bilder</relationshipLabel>
    <relationshipName>ImmobilienBilder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/ImmobilienDmsDatei__c.object-meta.xml
<CustomObject>
    <label>Immobilien DMS Datei</label>
    <nameField>
        <label>Immobilien DMS Datei Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien DMS Dateien</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/DateiTyp__c.field-meta.xml
<CustomField>
    <fullName>DateiTyp__c</fullName>
    <label>Datei Typ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bilder</fullName>
            </value>
            <value>
                <fullName>Dokumente</fullName>
            </value>
            <value>
                <fullName>Highlights</fullName>
            </value>
            <value>
                <fullName>Grundrisse</fullName>
            </value>
            <value>
                <fullName>Baufortschritt</fullName>
            </value>
            <value>
                <fullName>Musterberechnung</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/DateiUrl__c.field-meta.xml
<CustomField>
    <fullName>DateiUrl__c</fullName>
    <label>Datei Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/FileLastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>FileLastModifiedDate__c</fullName>
    <label>Datei zuletzt geändert am</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/Immobilie__c.field-meta.xml
<CustomField>
    <fullName>Immobilie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Immobilie</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Immobilien DMS Dateien</relationshipLabel>
    <relationshipName>ImmobilienDmsDateien</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/MimeType__c.field-meta.xml
<CustomField>
    <fullName>MimeType__c</fullName>
    <label>Mime Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/ParentOrdner__c.field-meta.xml
<CustomField>
    <fullName>ParentOrdner__c</fullName>
    <label>Parent Ordner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/PreviewUrl__c.field-meta.xml
<CustomField>
    <fullName>PreviewUrl__c</fullName>
    <label>Preview Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ImmobilienDmsDatei__c/fields/ThumbnailUrl__c.field-meta.xml
<CustomField>
    <fullName>ThumbnailUrl__c</fullName>
    <label>Thumbnail Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Immobilie</label>
    <nameField>
        <label>Immobilien Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Immobilien</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Collection_Id__c.field-meta.xml
<CustomField>
    <fullName>Collection_Id__c</fullName>
    <label>Collection Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pflegeapartments</fullName>
            </value>
            <value>
                <fullName>Service-Wohnungen</fullName>
            </value>
            <value>
                <fullName>Wohnimmobilien</fullName>
            </value>
            <value>
                <fullName>Mikroapartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchedulableImmobilienFiles.cls
global class SchedulableImmobilienFiles implements Schedulable, Database.AllowsCallouts {

    public static ConnectorService connectorService;
    public static Boolean validConnector { get; set; }
    public static ffhttp_GoogleDrive client;

    global void execute(SchedulableContext sc){
        List<Property__c> properties = [SELECT Id FROM Property__c WHERE Is_Public__c = true];
        List<Id> propertyIds = new List<Id>();
        for(Property__c property:properties) {
            propertyIds.add(property.Id);
        }
        prepareDocuments(propertyIds);
    }   

    @InvocableMethod(label='Google Drive synchronisieren')
    public static void prepareDocuments(List<Id> propertyIds) {
        // Sorry to whoever sees this
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();
        new ImmobilienBilder__c();

        for(Id propertyId:propertyIds) {
            getDocuments(propertyId);
        }
    }

    @future(callout=true)
    public static void getDocuments(id propertyId) {
        Property__c property = [SELECT Id, Collection_Id__c FROM Property__c WHERE Id = :propertyId];

        if(property.Collection_Id__c == null) {
            return;
        }
        List<ImmobilienDmsDatei__c> immobilienDateien = new List<ImmobilienDmsDatei__c>();

        ffhttp_GoogleDriveFiles files = getGoogleDriveClient().files();
    	ffhttp_GoogleDriveFiles.ListRequest listRequest = files.listRequest();
        listRequest.setFields('items(id,webContentLink,alternateLink,thumbnailLink,title,mimeType,fileExtension,modifiedDate)');
        listRequest.setQ('\'' + property.Collection_Id__c + '\' in parents');

        String thumbnailUrl = 'https://drive.google.com/thumbnail?authuser=0&sz=w320&id=';

        ffhttp_GoogleDriveModelFile.ItemList items = (ffhttp_GoogleDriveModelFile.ItemList)listRequest.execute();
        try{
            for(ffhttp_GoogleDriveModelFile child:(List<ffhttp_GoogleDriveModelFile>)items.getItems()) {

                ffhttp_GoogleDriveFiles.ListRequest innerListRequest = files.listRequest();
                innerListRequest.setFields('items(id,webContentLink,alternateLink,thumbnailLink,title,mimeType,fileExtension,modifiedDate)');
                innerListRequest.setQ('\'' + child.getId() + '\' in parents');
                
                ffhttp_GoogleDriveModelFile.ItemList innerItems = (ffhttp_GoogleDriveModelFile.ItemList)innerListRequest.execute();
                for(ffhttp_GoogleDriveModelFile innerChild:(List<ffhttp_GoogleDriveModelFile>)innerItems.getItems()) {
                    // Datei
                    if(innerChild.getMimeType() != 'application/vnd.google-apps.folder') {
                        ImmobilienDmsDatei__c immobilienDatei = new ImmobilienDmsDatei__c();
                        String fullTitle = innerChild.getTitle();
                        if(fullTitle.length() > 66) {
                            fullTitle = fullTitle.substring(0, 66);
                        }
                        String fileExtension = '.' + innerChild.getFileExtension();
                        if(!fullTitle.endsWith(fileExtension) && !String.isBlank(innerChild.getFileExtension())) {
                            fullTitle = fullTitle + fileExtension;
                        }
                        immobilienDatei.Name = fullTitle;
                        if(child.getTitle() == 'Bilder') {
                            immobilienDatei.DateiTyp__c = 'Bilder';
                        } else {
                            immobilienDatei.DateiTyp__c = 'Highlights';
                        }
                        immobilienDatei.DateiUrl__c = innerChild.getWebContentLink();
                        immobilienDatei.Immobilie__c = propertyId;
                        immobilienDatei.ParentOrdner__c = null;
                        immobilienDatei.PreviewUrl__c = innerChild.getAlternateLink();
                        immobilienDatei.ThumbnailUrl__c = thumbnailUrl + innerChild.getId();
                        immobilienDatei.MimeType__c = innerChild.getMimeType();
                        immobilienDatei.FileLastModifiedDate__c = innerChild.getModifiedDate();
                        immobilienDateien.add(immobilienDatei);
                    } else {
                        // Nur Dokumente haben Unterordner
                        ffhttp_GoogleDriveFiles.ListRequest documentsListRequest = files.listRequest();
                        documentsListRequest.setFields('items(id,webContentLink,alternateLink,thumbnailLink,title,mimeType,fileExtension,modifiedDate)');
                        documentsListRequest.setQ('\'' + innerChild.getId() + '\' in parents');

                        ffhttp_GoogleDriveModelFile.ItemList documentItems = (ffhttp_GoogleDriveModelFile.ItemList)documentsListRequest.execute();
                        for(ffhttp_GoogleDriveModelFile documentChild:(List<ffhttp_GoogleDriveModelFile>)documentItems.getItems()) {
                            ImmobilienDmsDatei__c immobilienDatei = new ImmobilienDmsDatei__c();
                            String fullTitle = documentChild.getTitle();
                            if(fullTitle.length() > 66) {
                                fullTitle = fullTitle.substring(0, 66);
                            }
                            String fileExtension = '.' + documentChild.getFileExtension();
                            if(!fullTitle.endsWith(fileExtension) && !String.isBlank(documentChild.getFileExtension())) {
                                fullTitle = fullTitle + fileExtension;
                            }
                            immobilienDatei.Name = fullTitle;
                            immobilienDatei.DateiTyp__c = 'Dokumente';
                            immobilienDatei.DateiUrl__c = documentChild.getWebContentLink();
                            immobilienDatei.Immobilie__c = propertyId;
                            immobilienDatei.ParentOrdner__c = innerChild.getTitle();
                            immobilienDatei.PreviewUrl__c = documentChild.getAlternateLink();
                            immobilienDatei.ThumbnailUrl__c = thumbnailUrl + documentChild.getId();
                            immobilienDatei.FileLastModifiedDate__c = documentChild.getModifiedDate();
                            immobilienDatei.MimeType__c = documentChild.getMimeType();
                            immobilienDateien.add(immobilienDatei);
                        }
                    }
                }
            }
        } catch(Exception e) { 
            System.debug(e); 
        }

        delete [SELECT Id FROM ImmobilienDmsDatei__c WHERE Immobilie__c = :propertyId];
        insert immobilienDateien;
    }

    public static ConnectorService getConnectorService()
    {
    	if (connectorService == null)
    	{	
    		try
    		{
	    		Connector__c c = 
	    		[
	    			SELECT 
	    				c.TokenType__c, c.RefreshToken__c, c.RefreshTokenRequested__c, c.Name, c.Id, c.AccessToken__c, 
					   	c.AccessTokenRequested__c, c.AccessTokenExpiry__c, c.Active__c, 
					   	ConnectorType__r.TokenEndpoint__c, ConnectorType__r.Scope__c, ConnectorType__r.ScopeRequired__c, 
					   	ConnectorType__r.RedirectUri__c, ConnectorType__r.Name, ConnectorType__r.Id, 
					   	ConnectorType__r.ExtraUrlParameters__c, ConnectorType__r.DeveloperName__c, 
					   	ConnectorType__r.ClientSecret__c, ConnectorType__r.ClientId__c, ConnectorType__r.CallbackURL__c, 
					   	ConnectorType__r.AuthorizationEndpoint__c
	    			FROM Connector__c c
	    			WHERE ConnectorType__r.Name =: 'Google Drive'
	    			LIMIT 1
	    		];
	    		
	    		if (c != null)
	    		{
	    			connectorService = new ConnectorService(c);
	    		}
    		}
    		catch (Exception ex)
    		{
    		}
    	}
    	return connectorService;
    }

    /**
     * Gets the Google Drive client
     */
    public static ffhttp_GoogleDrive getGoogleDriveClient()
    {
        ConnectorService connectorService = getConnectorService();
    	if (client == null)
    	{
            ffhttp_Client.ICredentials credentials = new ffhttp_Client.AccessTokenCredentials(connectorService.connector.TokenType__c,  connectorService.getAccessToken());
            client = new ffhttp_GoogleDrive(credentials);
    	}
    	return client;
    }

    // @future(callout=true)
    // public static void getDocuments(Id propertyId) {
    //     List<ImmobilienBilder__c> propertyImmobilienBilder = [SELECT Id, (SELECT Name FROM ImmobilienBilder__r) FROM ImmobilienBilder__c WHERE Immobilie__c = :propertyId];
    //     List<ContentVersion> bilderCvs = new List<ContentVersion>();
    //     if(propertyImmobilienBilder.size() == 0) {
    //         ImmobilienBilder__c newImmobilienBilder = new ImmobilienBilder__c();
    //         newImmobilienBilder.Name = 'Bilder';
    //         newImmobilienBilder.Immobilie__c = propertyId;
    //         propertyImmobilienBilder.add(newImmobilienBilder);
    //         insert propertyImmobilienBilder;   
    //     }

    //     List<String> imageNames = new List<String>();
    //     for(ImmobilienBild__c immobilienBild:propertyImmobilienBilder[0].ImmobilienBilder__r) {
    //         imageNames.add(immobilienBild.Name);
    //     }

    //     List<String> dmsImageNames = new List<String>();

    //     List<DMSController.OpenTextDocumentMeta> bilder = DMSController.getDocuments(propertyId + '_bilder');
    //     for(DMSController.OpenTextDocumentMeta bild:bilder) {
    //         dmsImageNames.add(bild.documentName);
    //         if(!imageNames.contains(bild.documentName) && bilderCvs.size() == 0) {
    //             DMSController.OpenTextDocument dmsDoc = DMSController.getDocument(bild.docNumber);
    //             ContentVersion cv = getContentVersionFromDmsDoc(dmsDoc);
    //             bilderCvs.add(cv);
    //         } 
    //     }
    //     insert bilderCvs;

    //     List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();
    //     List<ContentVersion> insertedBilderCvs = new List<ContentVersion>();
    //     Map<Id, Id> contentDocumentIdToLinkedEntityId = new Map<Id, Id>();
    //     for(ImmobilienBilder__c newImmobilienBilder:propertyImmobilienBilder) {
    //         Id linkedEntityId = newImmobilienBilder.Id;
    //         List<Id> contentVersionIds = new List<Id>();
    //         for(ContentVersion cv:bilderCvs) {
    //             contentVersionIds.add(cv.Id);
    //         }

    //         insertedBilderCvs = [SELECT ContentDocumentId, Title FROM ContentVersion WHERE Id IN :contentVersionIds];
    //         for(ContentVersion cv:insertedBilderCvs) {
    //             ContentDocumentLink cdl = new ContentDocumentLink();
    //             cdl.ContentDocumentId = cv.ContentDocumentId;
    //             cdl.LinkedEntityId = linkedEntityId;
    //             cdl.Visibility = 'AllUsers';
    //             cdls.add(cdl);
    //             contentDocumentIdToLinkedEntityId.put(cv.ContentDocumentId, linkedEntityId);
    //         }
    //     }
    //     insert cdls;

    //     List<ContentDistribution> cdImgs = new List<ContentDistribution>();
    //     for(ContentVersion cv:insertedBilderCvs) {
    //         ContentDistribution cdImg = new ContentDistribution();
    //         cdImg.Name = cv.Title;
    //         cdImg.ContentVersionId = cv.Id;
    //         cdImg.PreferencesAllowViewInBrowser= true;
    //         cdImg.PreferencesLinkLatestVersion=true;
    //         cdImg.PreferencesNotifyOnVisit=false;
    //         cdImg.PreferencesPasswordRequired=false;
    //         cdImg.PreferencesAllowOriginalDownload= true;
    //         cdImgs.add(cdImg);
    //     }
    //     Database.insert(cdImgs, false);

    //     List<Id> cdImgIds = new List<Id>();
    //     for(ContentDistribution cd:cdImgs) {
    //         cdImgIds.add(cd.Id);
    //     }

    //     List<ContentDistribution> insertedCdImgs = [SELECT ContentDownloadUrl, ContentDocumentId, ContentVersion.Title FROM ContentDistribution WHERE Id IN :cdImgIds];
    //     List<ImmobilienBild__c> singleImmobilienBilder = new List<ImmobilienBild__c>();
    //     for(ContentDistribution insertedCdImg:insertedCdImgs) {
    //         ImmobilienBild__c singleImmobilienBild = new ImmobilienBild__c();
    //         singleImmobilienBild.Name = insertedCdImg.ContentVersion.Title;
    //         singleImmobilienBild.ImmobilienBilder__c = contentDocumentIdToLinkedEntityId.get(insertedCdImg.ContentDocumentId);
    //         singleImmobilienBild.BildUrl__c = insertedCdImg.ContentDownloadUrl;
    //         singleImmobilienBilder.add(singleImmobilienBild);
    //     }
    //     insert singleImmobilienBilder;
    // }

    // public static ContentVersion getContentVersionFromDmsDoc(DMSController.OpenTextDocument dmsDoc) {
    //     ContentVersion cv=new Contentversion();
    //     cv.title = dmsDoc.fileName;
    //     cv.PathOnClient = dmsDoc.fileName + '.' + dmsDoc.fileExtension;
    //     cv.versiondata=EncodingUtil.base64Decode(dmsDoc.fileContent);
    //     return cv;
    // }
}